<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Appropriation Act No. 1, 2021–22</a><ul class="TocIndent"><li><a href="#h-1"><span class="scheduleLabel">SCHEDULE 1.1</span></a>
</li>
<li><a href="#h-2"><span class="scheduleLabel">SCHEDULE 1.2</span></a>
</li>
<li><a href="#h-3"><span class="scheduleLabel">SCHEDULE 1.3</span></a>
</li>
<li><a href="#h-4"><span class="scheduleLabel">SCHEDULE 1.4</span></a>
</li>
<li><a href="#h-5"><span class="scheduleLabel">SCHEDULE 1.5</span></a>
</li>
<li><a href="#h-6"><span class="scheduleLabel">SCHEDULE 1.6</span></a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">SCHEDULE 1.7</span></a>
</li>
<li><a href="#h-8"><span class="scheduleLabel">SCHEDULE 1.8</span></a>
</li>
<li><a href="#h-9"><span class="scheduleLabel">SCHEDULE 2</span></a>
</li></ul>
</li></ul>

</nav>

