<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend certain Acts of Canada, and to enact measures for implementing the Biological and Toxin Weapons Convention, in order to enhance public safety</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AERONAUTICS ACT</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">CANADIAN AIR TRANSPORT SECURITY AUTHORITY ACT</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CANADIAN ENVIRONMENTAL PROTECTION ACT, 1999</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-5"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-6"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">DEPARTMENT OF CITIZENSHIP AND IMMIGRATION ACT</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-7"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">DEPARTMENT OF HEALTH ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-8"><span class="HLabel2">PART 7</span> - <span class="HTitleText2">EXPLOSIVES ACT</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-9"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">EXPORT AND IMPORT PERMITS ACT</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-10"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">FOOD AND DRUGS ACT</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-11"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">HAZARDOUS PRODUCTS ACT</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-12"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">IMMIGRATION AND REFUGEE PROTECTION ACT</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-13"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">MARINE TRANSPORTATION SECURITY ACT</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-14"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">NATIONAL DEFENCE ACT</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-15"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">NATIONAL ENERGY BOARD ACT</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-16"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">NAVIGABLE WATERS PROTECTION ACT</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-17"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">OFFICE OF THE SUPERINTENDENT OF FINANCIAL INSTITUTIONS ACT</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-18"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">PERSONAL INFORMATION PROTECTION AND ELECTRONIC DOCUMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-19"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">PEST CONTROL PRODUCTS ACT</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-20"><span class="HLabel1">PART 19</span> - <span class="HTitleText1">PROCEEDS OF CRIME (MONEY LAUNDERING) AND TERRORIST FINANCING ACT</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-21"><span class="HLabel1">PART 20</span> - <span class="HTitleText1">QUARANTINE ACT</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-22"><span class="HLabel1">PART 21</span> - <span class="HTitleText1">RADIATION EMITTING DEVICES ACT</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-23"><span class="HLabel1">PART 22</span> - <span class="HTitleText1">CANADA SHIPPING ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Shipping Act</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Shipping Act, 2001</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>106 - </span><a href="#h-26"><span class="HLabel1">PART 23</span> - <span class="HTitleText1">BIOLOGICAL AND TOXIN WEAPONS CONVENTION</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-27"><span class="HLabel1">PART 24</span> - <span class="HTitleText1">CONSEQUENTIAL, COORDINATING AND COMMENCEMENT PROVISIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>107 - </span><a href="#h-28"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>107 - </span><a href="#h-29"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-30"><span class="HTitleText3">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-31"><span class="HTitleText3">Repeals</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-32"><span class="HTitleText2">Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-33"><span class="HTitleText3">Transportation Appeal Tribunal of Canada Act</span></a>
</li>
<li><span class='sectionRange'>111.1 - </span><a href="#h-34"><span class="HTitleText3">Pest Control Products Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="#h-35"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-36"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

