<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Tobacco Act and the Non-smokers’ Health Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PART 1</span></span> - <span class="HTitleText1">Tobacco Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Amendments to the Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>71 - </span><a href="page-11.html#h-3"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>71 - </span><a href="page-11.html#h-4"><span class="HTitleText2">Food and Drugs Act</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-11.html#h-5"><span class="HTitleText2">An Act to amend the Tobacco Act</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-11.html#h-6"><span class="HTitleText2">Canada Consumer Product Safety Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 - </span><a href="page-11.html#h-7"><span class="HTitleText1">Terminology</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-11.html#h-8"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-12.html#h-9"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-12.html#h-10"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1">Non-smokers’ Health Act</span></a>
</li>
<li><a href="page-13.html#h-11"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

