<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
COVID-19 Emergency Response Act, No. 2</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText2">Payments out of Consolidated Revenue Fund</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

