<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Public Service Modernization Act</a><ul class="TocIndent"><li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">PUBLIC SERVICE LABOUR RELATIONS ACT</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-2"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE FINANCIAL ADMINISTRATION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-2.html#h-3"><span class="HTitleText2">Responsibilities and Powers</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-3.html#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">PUBLIC SERVICE EMPLOYMENT ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-3.html#h-5"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-4.html#h-6"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Amendments to the Public Service Employment Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="page-5.html#h-7"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">AMENDMENTS TO THE CANADIAN CENTRE FOR MANAGEMENT DEVELOPMENT ACT</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-6.html#h-8"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">TRANSITIONAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="page-6.html#h-9"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Transitional Provisions Arising from the Enactment of the Public Service Labour Relations Act in Part 1</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="page-6.html#h-10"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-7.html#h-11"><span class="HTitleText3">Public Service Staff Relations Board</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-7.html#h-12"><span class="HTitleText3">Bargaining Agents and Bargaining Units</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-7.html#h-13"><span class="HTitleText3">Managerial or Confidential Position</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-7.html#h-14"><span class="HTitleText3">Choice of Process for Dispute Resolution</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-7.html#h-15"><span class="HTitleText3">Collective Agreements and Arbitral Awards</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-7.html#h-16"><span class="HTitleText3">Conciliators and Fact Finders</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-7.html#h-17"><span class="HTitleText3">Alternate Dispute Resolution Process</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-7.html#h-18"><span class="HTitleText3">Arbitration</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-8.html#h-19"><span class="HTitleText3">Designations, Conciliation and Prohibitions</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-8.html#h-20"><span class="HTitleText3">Complaints</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-8.html#h-21"><span class="HTitleText3">Grievances</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-8.html#h-22"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Transitional Provision Arising from the Amendments to the Financial Administration Act in Part 2</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-8.html#h-23"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Transitional Provisions Arising from Part 3</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="page-8.html#h-24"><span class="HLabel3">Subdivision a</span> - <span class="HTitleText3">Transitional Provisions Arising from the Enactment of the Public Service Employment Act in Division 1 of Part 3</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-9.html#h-25"><span class="HLabel3">Subdivision b</span> - <span class="HTitleText3">Transitional Provisions Arising from the Amendments to the Public Service Employment Act in Division 2 of Part 3</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="page-9.html#h-26"><span class="HLabel2">Division 4</span> - <span class="HTitleText2">Transitional Provisions Arising from the Amendments to the Canadian Centre for Management Development Act in Part 4</span></a>
</li></ul>
</li><li><span class='sectionRange'>88 - </span><a href="page-9.html#h-27"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="page-9.html#h-28"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Consequential Amendments Arising from the Enactment of the Public Service Labour Relations Act in Part 1 and the Amendments to the Financial Administration Act in Part 2</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="page-9.html#h-29"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-9.html#h-30"><span class="HTitleText3">Aeronautics Act</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-9.html#h-31"><span class="HTitleText3">Auditor General Act</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-10.html#h-32"><span class="HTitleText3">Bank of Canada Act</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-10.html#h-33"><span class="HTitleText3">Canada Customs and Revenue Agency Act</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-10.html#h-34"><span class="HTitleText3">Canada Elections Act</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-10.html#h-35"><span class="HTitleText3">Canada Evidence Act</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-10.html#h-36"><span class="HTitleText3">Canada Grain Act</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-10.html#h-37"><span class="HTitleText3">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-11.html#h-38"><span class="HTitleText3">Canada Marine Act</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-11.html#h-39"><span class="HTitleText3">Canada Mortgage and Housing Corporation Act</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-11.html#h-40"><span class="HTitleText3">Canada-Newfoundland Atlantic Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-11.html#h-41"><span class="HTitleText3">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-12.html#h-42"><span class="HTitleText3">Canada Oil and Gas Operations Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-12.html#h-43"><span class="HTitleText3">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-12.html#h-44"><span class="HTitleText3">Canada Petroleum Resources Act</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-12.html#h-45"><span class="HTitleText3">Canada School of Public Service Act</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-12.html#h-46"><span class="HTitleText3">Canadian Commercial Corporation Act</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-12.html#h-47"><span class="HTitleText3">Canadian Food Inspection Agency Act</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-12.html#h-48"><span class="HTitleText3">Canadian Forces Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-12.html#h-49"><span class="HTitleText3">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-12.html#h-50"><span class="HTitleText3">Canadian Institutes of Health Research Act</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-13.html#h-51"><span class="HTitleText3">Canadian Payments Act</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-13.html#h-52"><span class="HTitleText3">Canadian Security Intelligence Service Act</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-13.html#h-53"><span class="HTitleText3">Canadian Space Agency Act</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-13.html#h-54"><span class="HTitleText3">Children’s Special Allowances Act</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-13.html#h-55"><span class="HTitleText3">Citizenship Act</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-13.html#h-56"><span class="HTitleText3">Civil Air Navigation Services Commercialization Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-13.html#h-57"><span class="HTitleText3">Cooperative Energy Act</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-13.html#h-58"><span class="HTitleText3">Copyright Act</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-13.html#h-59"><span class="HTitleText3"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-14.html#h-60"><span class="HTitleText3">Courts Administration Service Act</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-14.html#h-61"><span class="HTitleText3">Defence Production Act</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-14.html#h-62"><span class="HTitleText3">Department of Human Resources Development Act</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-14.html#h-63"><span class="HTitleText3">Department of Veterans Affairs Act</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-14.html#h-64"><span class="HTitleText3">Diplomatic Service (Special) Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-14.html#h-65"><span class="HTitleText3">Employment Equity Act</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-14.html#h-66"><span class="HTitleText3">Farm Products Agencies Act</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-14.html#h-67"><span class="HTitleText3">Federal Court Act</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-14.html#h-68"><span class="HTitleText3">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-14.html#h-69"><span class="HTitleText3">Financial Consumer Agency of Canada Act</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-15.html#h-70"><span class="HTitleText3">Hazardous Materials Information Review Act</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-15.html#h-71"><span class="HTitleText3">Immigration and Refugee Protection Act</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-15.html#h-72"><span class="HTitleText3">Inquiries Act</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-15.html#h-73"><span class="HTitleText3">National Film Act</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-15.html#h-74"><span class="HTitleText3">Non-smokers’ Health Act</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="page-15.html#h-75"><span class="HTitleText3">Office of the Superintendent of Financial Institutions Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-15.html#h-76"><span class="HTitleText3">Old Age Security Act</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-15.html#h-77"><span class="HTitleText3">Parks Canada Agency Act</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-15.html#h-78"><span class="HTitleText3">Parliamentary Employment and Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-16.html#h-79"><span class="HTitleText3">Pension Act</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-16.html#h-80"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-16.html#h-81"><span class="HTitleText3">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-16.html#h-82"><span class="HTitleText3">Public Service Employment Act</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="page-17.html#h-83"><span class="HTitleText3">Public Service Rearrangement and Transfer of Duties Act</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="page-17.html#h-84"><span class="HTitleText3">Public Service Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="page-18.html#h-85"><span class="HTitleText3">Publication of Statutes Act</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="page-18.html#h-86"><span class="HTitleText3">Royal Canadian Mounted Police Act</span></a>
</li>
<li><span class='sectionRange'>218 - </span><a href="page-18.html#h-87"><span class="HTitleText3">Royal Canadian Mounted Police Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="page-18.html#h-88"><span class="HTitleText3">Saguenay-St. Lawrence Marine Park Act</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="page-18.html#h-89"><span class="HTitleText3">Status of the Artist Act</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="page-18.html#h-90"><span class="HTitleText3">War Veterans Allowance Act</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="page-18.html#h-91"><span class="HTitleText3">Terminology Changes</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="page-20.html#h-92"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Consequential Amendments Arising from Part 3</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>227 - </span><a href="page-20.html#h-93"><span class="HLabel3">Subdivision a</span> - <span class="HTitleText3">Consequential Amendments Arising from the Enactment of the Public Service Employment Act in Division 1 of Part 3</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>227 - </span><a href="page-20.html#h-94"><span class="HTitleText4">Auditor General Act</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="page-20.html#h-95"><span class="HTitleText4">Canada Customs and Revenue Agency Act</span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-20.html#h-96"><span class="HTitleText4">Canada-Newfoundland Atlantic Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="page-20.html#h-97"><span class="HTitleText4">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-20.html#h-98"><span class="HTitleText4">Canadian Institutes of Health Research Act</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="page-20.html#h-99"><span class="HTitleText4">Canadian Security Intelligence Service Act</span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="page-20.html#h-100"><span class="HTitleText4">Canadian Space Agency Act</span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="page-20.html#h-101"><span class="HTitleText4">Employment Equity Act</span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="page-20.html#h-102"><span class="HTitleText4">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="page-21.html#h-103"><span class="HTitleText4">National Film Act</span></a>
</li>
<li><span class='sectionRange'>241 - </span><a href="page-21.html#h-104"><span class="HTitleText4">Parks Canada Agency Act</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="page-21.html#h-105"><span class="HTitleText4">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</span></a>
</li>
<li><span class='sectionRange'>243 - </span><a href="page-21.html#h-106"><span class="HTitleText4">Public Service Labour Relations Act</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="page-21.html#h-107"><span class="HTitleText4">Referendum Act</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="page-21.html#h-108"><span class="HTitleText4">Veterans Benefit Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>246 - </span><a href="page-21.html#h-109"><span class="HLabel3">Subdivision b</span> - <span class="HTitleText3">Consequential Amendments Arising from the Amendments to the Public Service Employment Act in Division 2 of Part 3</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>246 - </span><a href="page-21.html#h-110"><span class="HTitleText4">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="page-21.html#h-111"><span class="HTitleText4">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="page-21.html#h-112"><span class="HTitleText4">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="page-21.html#h-113"><span class="HTitleText4">Public Service Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="page-21.html#h-114"><span class="HTitleText4">Public Service Superannuation Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>251 - </span><a href="page-21.html#h-115"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Consequential Amendments Arising from the Amendments to the Canadian Centre for Management Development Act in Part 4</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>251 - </span><a href="page-21.html#h-116"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-21.html#h-117"><span class="HTitleText3">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="page-21.html#h-118"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="page-21.html#h-119"><span class="HTitleText3">Public Service Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="page-21.html#h-120"><span class="HTitleText3">Public Service Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="page-21.html#h-121"><span class="HTitleText3">Revolving Funds Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>262 - </span><a href="page-21.html#h-122"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>262 - </span><a href="page-21.html#h-123"><span class="HTitleText2">Public Service Modernization Act</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="page-22.html#h-124"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="page-22.html#h-125"><span class="HTitleText2">Public Service Employment Act</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="page-22.html#h-126"><span class="HTitleText2">Public Service Employment Act</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="page-22.html#h-127"><span class="HTitleText2">Public Service Labour Relations Act</span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="page-23.html#h-128"><span class="HTitleText2">Yukon Act</span></a>
</li>
<li><span class='sectionRange'>277 - </span><a href="page-23.html#h-129"><span class="HTitleText2">Bill C-2</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="page-23.html#h-130"><span class="HTitleText2">Bill C-6</span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="page-23.html#h-131"><span class="HTitleText2">Bill C-12</span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="page-23.html#h-132"><span class="HTitleText2">Bill C-13</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="page-24.html#h-133"><span class="HTitleText2">Bill C-17</span></a>
</li>
<li><span class='sectionRange'>282 - </span><a href="page-24.html#h-134"><span class="HTitleText2">Bill C-18</span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="page-24.html#h-135"><span class="HTitleText2">Bill C-19</span></a>
</li></ul>
</li><li><span class='sectionRange'>284 - </span><a href="page-24.html#h-136"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">REPEALS</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="page-24.html#h-137"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-25.html#h-138"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-26.html#h-139"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

