<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Heritage Lighthouse Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">PURPOSE AND APPLICATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">DESIGNATION OF HERITAGE LIGHTHOUSES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-5"><span class="HTitleText1">PROTECTION OF HERITAGE LIGHTHOUSES</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-6"><span class="HTitleText1">MAINTENANCE OF HERITAGE LIGHTHOUSES</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">RELATED AMENDMENTS TO THE PARKS CANADA AGENCY ACT</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

