<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Canada Marine Act, the Canada Transportation Act, the Pilotage Act and other Acts in consequence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA MARINE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-6.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA TRANSPORTATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-6.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">PILOTAGE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-6.html#h-4"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-6.html#h-5"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="page-6.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Marine Transportation Security Act</cite></span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Transportation Appeal Tribunal of Canada Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="page-6.html#h-8"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

