<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Parliament of Canada Act (Ethics Commissioner and Senate Ethics Officer) and other Acts in consequence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">PARLIAMENT OF CANADA ACT</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-2"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Post Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Federal Court Act</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Garnishment, Attachment and Pension Diversion Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Government Employees Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Lobbyists Registration Act</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Non-smokers' Health Act</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Official Languages Act</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Radiocommunication Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-16"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-17"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

