<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Controlled Drugs and Substances Act and to make related amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Controlled Drugs and Substances Act</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-2"><span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Seized Property Management Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-7"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-8"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-9"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

