<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
First Nations Financial Transparency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">FINANCIAL STATEMENTS AND SCHEDULE OF REMUNERATION AND EXPENSES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Preparation and Independent Audit</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Disclosure</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-1.html#h-7"><span class="HTitleText1">COURT REMEDIES AND ADMINISTRATIVE MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Orders</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Administrative Measures</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

