<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Federal Law–Civil Law Harmonization Act, No. 2</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO CERTAIN ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Animal Pedigree Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Bank of Canada Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-10.html#h-6"><span class="HTitleText2">Canada Council for the Arts Act</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-10.html#h-7"><span class="HTitleText2">Canada Grain Act</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-10.html#h-8"><span class="HTitleText2">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-10.html#h-9"><span class="HTitleText2">Canada Wildlife Act</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-11.html#h-10"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-11.html#h-11"><span class="HTitleText2">Defence Production Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-11.html#h-12"><span class="HTitleText2">Department of Industry Act</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-11.html#h-13"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-12.html#h-14"><span class="HTitleText2">Energy Supplies Emergency Act</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-12.html#h-15"><span class="HTitleText2">Excise Act</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-12.html#h-16"><span class="HTitleText2">Explosives Act</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-12.html#h-17"><span class="HTitleText2">Farm Products Agencies Act</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-12.html#h-18"><span class="HTitleText2">Law Commission of Canada Act</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="page-12.html#h-19"><span class="HTitleText2">An Act to incorporate the Jules and Paul-Émile Léger Foundation</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-12.html#h-20"><span class="HTitleText2">National Arts Centre Act</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-12.html#h-21"><span class="HTitleText2">National Energy Board Act</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="page-13.html#h-22"><span class="HTitleText2">National Research Council Act</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-14.html#h-23"><span class="HTitleText2">Natural Sciences and Engineering Research Council Act</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-14.html#h-24"><span class="HTitleText2">Pesticide Residue Compensation Act</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-14.html#h-25"><span class="HTitleText2">Social Sciences and Humanities Research Council Act</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-14.html#h-26"><span class="HTitleText2">State Immunity Act</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-14.html#h-27"><span class="HTitleText2">Telecommunications Act</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-15.html#h-28"><span class="HTitleText2">Visiting Forces Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>182 - </span><a href="page-15.html#h-29"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>182 - </span><a href="page-15.html#h-30"><span class="HTitleText2">Advance Payments for Crops Act</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="page-15.html#h-31"><span class="HTitleText2">Agricultural Marketing Programs Act</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-15.html#h-32"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-15.html#h-33"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-15.html#h-34"><span class="HTitleText2">Canada Business Corporations Act</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-15.html#h-35"><span class="HTitleText2">Canada Cooperatives Act</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-15.html#h-36"><span class="HTitleText2">Canada Corporations Act</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-15.html#h-37"><span class="HTitleText2">Canada Student Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-15.html#h-38"><span class="HTitleText2">Canadian Payments Act</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="page-15.html#h-39"><span class="HTitleText2">Companies’ Creditors Arrangement Act</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="page-15.html#h-40"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-16.html#h-41"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="page-16.html#h-42"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="page-16.html#h-43"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="page-16.html#h-44"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="page-16.html#h-45"><span class="HTitleText2">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="page-16.html#h-46"><span class="HTitleText2">Prairie Grain Advance Payments Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="page-16.html#h-47"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>205 - </span><a href="page-16.html#h-48"><span class="HTitleText2">Federal Law–Civil Law Harmonization Act, No. 2</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="page-16.html#h-49"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="page-16.html#h-50"><span class="HTitleText2">Canada Grain Act</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="page-16.html#h-51"><span class="HTitleText2">Explosives Act</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

