<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Transportation of Dangerous Goods Act, 1992</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TRANSPORTATION OF DANGEROUS GOODS ACT, 1992</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-2"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

