<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend certain Acts that relate to the environment and to enact provisions respecting the enforcement of certain Acts that relate to the environment</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">ANTARCTIC ENVIRONMENTAL PROTECTION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA NATIONAL MARINE CONSERVATION AREAS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA NATIONAL PARKS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA WILDLIFE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-6"><span class="HTitleText1"><cite class="XRefExternalAct">CANADIAN ENVIRONMENTAL PROTECTION ACT, 1999</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-7"><span class="HTitleText1"><cite class="XRefExternalAct">INTERNATIONAL RIVER IMPROVEMENTS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-8"><span class="HTitleText1"><cite class="XRefExternalAct">MIGRATORY BIRDS CONVENTION ACT, 1994</cite></span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-9"><span class="HTitleText1"><cite class="XRefExternalAct">SAGUENAY-ST. LAWRENCE MARINE PARK ACT</cite></span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-10"><span class="HTitleText1"><cite class="XRefExternalAct">WILD ANIMAL AND PLANT PROTECTION AND REGULATION OF INTERNATIONAL AND INTERPROVINCIAL TRADE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-11"><span class="HTitleText1"><cite class="XRefExternalAct">ENACTMENT OF THE ENVIRONMENTAL VIOLATIONS ADMINISTRATIVE MONETARY PENALTIES ACT</cite></span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-12"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-13"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

