<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Protection of Canada from Terrorists Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CANADIAN SECURITY INTELLIGENCE SERVICE ACT</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-3"><span class="HTitleText1">STRENGTHENING CANADIAN CITIZENSHIP ACT</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-4"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT TO THE ACCESS TO INFORMATION ACT</span></a>
</li></ul>
</li></ul>

</nav>

