<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Criminal Code and the Cultural Property Export and Import Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CULTURAL PROPERTY EXPORT AND IMPORT ACT</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-3"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><a href="page-2.html#h-4"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

