<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada Border Services Agency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">ESTABLISHMENT AND MANDATE OF THE AGENCY</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">MINISTER</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText1">PRESIDENT AND EXECUTIVE VICE-PRESIDENT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-6"><span class="HTitleText1">HUMAN RESOURCES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-7"><span class="HTitleText1">POWERS OF THE AGENCY</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-8"><span class="HTitleText1">EXPENDITURES</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="page-2.html#h-9"><span class="HTitleText1">ANNUAL REPORT</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-10"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-2.html#h-11"><span class="HTitleText2">Definitions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Former Agency</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Canada Customs and Revenue Agency</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Royal Canadian Mint Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="page-3.html#h-15"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Agriculture and Agri-Food Administrative Monetary Penalties Act</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-17"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-18"><span class="HTitleText2">Canada Agricultural Products Act</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Canada Customs and Revenue Agency Act</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-20"><span class="HTitleText2">Canadian Food Inspection Agency Act</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-21"><span class="HTitleText2">Canadian International Trade Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Department of Citizenship and Immigration Act</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Cultural Property Export and Import Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-5.html#h-25"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-7.html#h-26"><span class="HTitleText2">Customs and Excise Offshore Application Act</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-7.html#h-27"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-7.html#h-28"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-7.html#h-29"><span class="HTitleText2">Excise Act</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-7.html#h-30"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-8.html#h-31"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-9.html#h-32"><span class="HTitleText2">Family Orders and Agreements Enforcement Assistance Act</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-9.html#h-33"><span class="HTitleText2">Feeds Act</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-9.html#h-34"><span class="HTitleText2">Fertilizers Act</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-9.html#h-35"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-10.html#h-36"><span class="HTitleText2">Fish Inspection Act</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-10.html#h-37"><span class="HTitleText2">Health of Animals Act</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-10.html#h-38"><span class="HTitleText2">Immigration and Refugee Protection Act</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-10.html#h-39"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-10.html#h-40"><span class="HTitleText2">Meat Inspection Act</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-10.html#h-41"><span class="HTitleText2">Plant Protection Act</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-10.html#h-42"><span class="HTitleText2">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-11.html#h-43"><span class="HTitleText2">Public Service Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-11.html#h-44"><span class="HTitleText2">Royal Canadian Mint Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-11.html#h-45"><span class="HTitleText2">Seeds Act</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-11.html#h-46"><span class="HTitleText2">Special Import Measures Act</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-12.html#h-47"><span class="HTitleText2">Terminology Changes</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="page-13.html#h-48"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-14.html#h-49"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

