<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Bills of Exchange Act, the Interpretation Act and the Canada Labour Code (National Day for Truth and Reconciliation)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Purpose of this Act</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Bills of Exchange Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

