<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Export and Import Permits Act and the Criminal Code (amendments permitting the accession to the Arms Trade Treaty and other amendments)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Export and Import Permits Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-3"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-4"><span class="HTitleText1">Amendment to the <cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-5"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

