<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the National Defence Act and to make related and consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-2"><span class="HTitleText1">Related Amendments to the <cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-3"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Geneva Conventions Act</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Visiting Forces Act</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Sex Offender Information Registration Act</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Prohibiting Cluster Munitions Act</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct"><cite class="XRefExternalAct">Canadian Victims Bill of Rights</cite></cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="#h-11"><span class="HTitleText1">Related and Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-12"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-13"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

