<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Federal Framework on Lyme Disease Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">FEDERAL FRAMEWORK ON LYME DISEASE</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">REVIEW AND REPORT</span></a>
</li></ul>
</li></ul>

</nav>

