<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
International Bridges and Tunnels Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION AND APPLICATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">CONSTRUCTION AND ALTERATION</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-4"><span class="HTitleText1">MAINTENANCE AND REPAIR</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-5"><span class="HTitleText1">OPERATION AND USE</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-6"><span class="HTitleText1">SECURITY AND SAFETY</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-7"><span class="HTitleText1">CHANGE OF OWNERSHIP, OPERATOR OR CONTROL</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-8"><span class="HTitleText1">INCORPORATION BY LETTERS PATENT</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-9"><span class="HTitleText1">SHARES OF A CORPORATION</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-3.html#h-10"><span class="HTitleText1">ENFORCEMENT</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-11"><span class="HTitleText1">ADMINISTRATIVE MONETARY PENALTIES</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-12"><span class="HTitleText1">FIVE-YEAR REVIEW</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-5.html#h-13"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-5.html#h-14"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="page-5.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Transportation Appeal Tribunal of Canada Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="page-5.html#h-16"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-6.html#h-17"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - BRIDGES AND TUNNELS ACTS</span></a>
</li></ul>
</li></ul>

</nav>

