<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Financial Administration Act, the Canada School of Public Service Act and the Official Languages Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">FINANCIAL ADMINISTRATION ACT</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CANADA SCHOOL OF PUBLIC SERVICE ACT</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">OFFICIAL LANGUAGES ACT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">TRANSITIONAL</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

