<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Canadian Forces Superannuation Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CANADIAN FORCES SUPERANNUATION ACT</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-5.html#h-2"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-5.html#h-3"><span class="HTitleText2">Modernization of Benefits and Obligations Act</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-5.html#h-4"><span class="HTitleText2">Public Sector Pension Investment Board Act</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-5"><span class="HTitleText2">Public Service Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-6.html#h-6"><span class="HTitleText2">Royal Canadian Mounted Police Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-7.html#h-7"><span class="HTitleText2">Special Retirement Arrangements Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-7.html#h-8"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-7.html#h-9"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="page-7.html#h-10"><span class="HTitleText2">Bill C-25</span></a>
</li></ul>
</li><li><span class='sectionRange'>71 - </span><a href="page-7.html#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

