<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Federal Law–Civil Law Harmonization Act, No. 3</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO CERTAIN ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Boards of Trade Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Business Development Bank of Canada Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Canada Business Corporations Act</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-6.html#h-6"><span class="HTitleText2">Canada Cooperatives Act</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-9.html#h-7"><span class="HTitleText2">Consumer Packaging and Labelling Act</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-9.html#h-8"><span class="HTitleText2">Electricity and Gas Inspection Act</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-10.html#h-9"><span class="HTitleText2">Expropriation Act</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-14.html#h-10"><span class="HTitleText2">Precious Metals Marking Act</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-14.html#h-11"><span class="HTitleText2">Public Documents Act</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-14.html#h-12"><span class="HTitleText2">Standards Council of Canada Act</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-14.html#h-13"><span class="HTitleText2">Textile Labelling Act</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-14.html#h-14"><span class="HTitleText2">Weights and Measures Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>161 - </span><a href="page-14.html#h-15"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>161 - </span><a href="page-14.html#h-16"><span class="HTitleText2">Dominion Water Power Act</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-14.html#h-17"><span class="HTitleText2">Dry Docks Subsidies Act</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-14.html#h-18"><span class="HTitleText2">Harbour Commissions Act</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-14.html#h-19"><span class="HTitleText2">International Bridges and Tunnels Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="page-14.html#h-20"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><a href="page-15.html#h-21"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-16.html#h-22"><span class="scheduleLabel"><strong>SCHEDULE 2</strong></span> </a>
</li></ul>
</li></ul>

</nav>

