<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Economic Action Plan 2013 Act, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">INCOME TAX ACT</cite>, THE <cite class="XRefExternalAct">TAX COURT OF CANADA ACT</cite> AND THE <cite class="XRefExternalRegulation">INCOME TAX REGULATIONS</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Tax Court of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-6"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="page-4.html#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">MEASURES RELATING TO SALES AND EXCISE TAXES AND EXCISE DUTIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-4.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-6.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="page-6.html#h-10"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-7.html#h-11"><span class="HTitleText3">Application</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="page-7.html#h-12"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">VARIOUS MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="page-7.html#h-13"><span class="HLabel2">Division 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="page-7.html#h-14"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-8.html#h-15"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="page-8.html#h-16"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Financial Institutions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="page-8.html#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-9.html#h-18"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-9.html#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-9.html#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="page-9.html#h-21"><span class="HLabel2">Division 3</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-11.html#h-22"><span class="HLabel2">Division 4</span> - <span class="HTitleText2">Payments to Certain Entities or for Certain Purposes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="page-11.html#h-23"><span class="HTitleText3">Canadian Youth Business Foundation</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-11.html#h-24"><span class="HTitleText3">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-11.html#h-25"><span class="HTitleText3">Nature Conservancy of Canada</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-11.html#h-26"><span class="HTitleText3">Nunavut Housing</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-11.html#h-27"><span class="HTitleText3">Indspire</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-11.html#h-28"><span class="HTitleText3">Pallium Foundation of Canada</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-11.html#h-29"><span class="HTitleText3">Canadian National Institute for the Blind</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="page-11.html#h-30"><span class="HLabel2">Division 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Securities Regulation Regime Transition Office Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="page-11.html#h-31"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-11.html#h-32"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-11.html#h-33"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="page-11.html#h-34"><span class="HLabel2">Division 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="page-11.html#h-35"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-13.html#h-36"><span class="HTitleText3">Related Amendments to the <cite class="XRefExternalAct">Budget Implementation Act, 2009</cite></span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-13.html#h-37"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-13.html#h-38"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>155 - </span><a href="page-13.html#h-39"><span class="HLabel2">Division 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-13.html#h-40"><span class="HLabel2">Division 8</span> - <span class="HTitleText2">Improving Veterans’ Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="page-13.html#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Pension Act</cite></span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-13.html#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">War Veterans Allowance Act</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-14.html#h-43"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-14.html#h-44"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>161 - </span><a href="page-14.html#h-45"><span class="HLabel2">Division 9</span> - <span class="HTitleText2">Immigration and Refugee Protection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>161 - </span><a href="page-14.html#h-46"><span class="HTitleText3"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-14.html#h-47"><span class="HTitleText3">No Appeal to the Refugee Appeal Division</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-14.html#h-48"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>170 - </span><a href="page-14.html#h-49"><span class="HLabel2">Division 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Citizenship Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>170 - </span><a href="page-14.html#h-50"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-14.html#h-51"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>173 - </span><a href="page-14.html#h-52"><span class="HLabel2">Division 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Nuclear Safety and Control Act</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-14.html#h-53"><span class="HLabel2">Division 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Department of Foreign Affairs, Trade and Development Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>174 - </span><a href="page-14.html#h-54"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-15.html#h-55"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>175 - </span><a href="page-15.html#h-56"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-15.html#h-57"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-15.html#h-58"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-15.html#h-59"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-15.html#h-60"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Real Property and Federal Immovables Act</cite></span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-15.html#h-61"><span class="HTitleText4"><cite class="XRefExternalAct">Conflict of Interest Act</cite></span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="page-15.html#h-62"><span class="HTitleText4"><cite class="XRefExternalAct">Official Development Assistance Accountability Act</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-15.html#h-63"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Sustainable Development Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>195 - </span><a href="page-15.html#h-64"><span class="HTitleText3">Terminology</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="page-16.html#h-65"><span class="HTitleText3">Repeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="page-16.html#h-66"><span class="HLabel2">Division 13</span> - <span class="HTitleText2">Ridley Terminals Inc.</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="page-16.html#h-67"><span class="HTitleText3">Reorganization and Divestiture</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="page-17.html#h-68"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Canada Marine Act</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="page-17.html#h-69"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>213 - </span><a href="page-17.html#h-70"><span class="HLabel2">Division 14</span> - <span class="HTitleText2">Transfer of Powers, Duties and Functions to the Minister of Canadian Heritage</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>213 - </span><a href="page-17.html#h-71"><span class="HTitleText3"><cite class="XRefExternalAct">National Capital Act</cite></span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="page-17.html#h-72"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Canadian Heritage Act</cite></span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="page-17.html#h-73"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="page-17.html#h-74"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">National Holocaust Monument Act</cite></span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="page-17.html#h-75"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>225 - </span><a href="page-18.html#h-76"><span class="HLabel2">Division 15</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="page-18.html#h-77"><span class="HTitleText2">Parliamentary Secretaries and Ministers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>225 - </span><a href="page-18.html#h-78"><span class="HTitleText3"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="page-18.html#h-79"><span class="HTitleText3"><cite class="XRefExternalAct">Salaries Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="page-18.html#h-80"><span class="HLabel2">Division 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Department of Public Works and Government Services Act</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-18.html#h-81"><span class="HLabel2">Division 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>228 - </span><a href="page-18.html#h-82"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-18.html#h-83"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>230 - </span><a href="page-18.html#h-84"><span class="HTitleText4"><cite class="XRefExternalAct">Canadian Race Relations Foundation Act</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-18.html#h-85"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Pension Investment Board Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>232 - </span><a href="page-18.html#h-86"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>233 - </span><a href="page-18.html#h-87"><span class="HLabel2">Division 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Keeping Canada’s Economy and Jobs Growing Act</cite></span></a>
</li></ul>
</li><li><a href="page-19.html#h-88"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

