<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Yale First Nation Final Agreement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">APPROPRIATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText1">LANDS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HTitleText1">TAXATION</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-7"><span class="HTitleText1">FISHERIES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-8"><span class="HTitleText1">APPLICATION OF OTHER ACTS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-9"><span class="HTitleText1">APPLICATION OF LAWS OF BRITISH COLUMBIA</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-10"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-11"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-1.html#h-12"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-13"><span class="HTitleText2">Fisheries Act</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-14"><span class="HTitleText2">Payments in Lieu of Taxes Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-15"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-16"><span class="HTitleText2">Specific Claims Tribunal Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="page-2.html#h-17"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

