<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Canada Business Corporations Act, the Canada Cooperatives Act, the Canada Not-for-profit Corporations Act and the Competition Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Corporate Governance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Business Corporations Act</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Cooperatives Act</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-8.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Not-for-profit Corporations Act</cite></span></a>
</li>
<li><span class='sectionRange'>107.1 - </span><a href="page-9.html#h-5"><span class="HTitleText2">Review by Committee</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-9.html#h-6"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="page-9.html#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Application of the <cite class="XRefExternalAct">Competition Act</cite> to Other Entities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>109 - </span><a href="page-9.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

