<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act respecting the registration of information relating to sex offenders, to amend the Criminal Code and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">PURPOSE AND PRINCIPLES</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">OBLIGATIONS OF SEX OFFENDERS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-5"><span class="HTitleText1">RESPONSIBILITIES OF PERSONS WHO COLLECT AND REGISTER INFORMATION</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-6"><span class="HTitleText1">MANAGEMENT OF INFORMATION</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-7"><span class="HTitleText1">PROHIBITIONS</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-3.html#h-8"><span class="HTitleText1">OFFENCES</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-9"><span class="HTitleText1">AUTHORIZATIONS, DESIGNATIONS AND REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-10"><span class="HTitleText1">RELATED AMENDMENTS TO THE CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="page-4.html#h-11"><span class="HTitleText1">REVIEW AND REPORT</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-4.html#h-12"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="page-4.html#h-13"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-4.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Records Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-4.html#h-15"><span class="HTitleText1">COORDINATING PROVISION</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-4.html#h-16"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

