<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Rouge National Urban Park Act, the Parks Canada Agency Act and the Canada National Parks Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Rouge National Urban Park Act</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Parks Canada Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Canada National Parks Act</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

