<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to implement certain provisions of the budget tabled in Parliament on March 23, 2004</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE FEDERALPROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Fiscal Equalization Payments</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Canada Social Transfer</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="page-2.html#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENT TO THE CANADA-NEWFOUNDLAND ATLANTIC ACCORD IMPLEMENTATION ACT</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-6"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">GENERAL — PAYMENTS TO CERTAIN ENTITIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Payments to a Trust</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Payments to Nova Scotia</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-3.html#h-9"><span class="HTitleText2">Payment to Saskatchewan</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Appropriations for Grants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-3.html#h-11"><span class="HTitleText3">Canada Foundation for Sustainable Development Technology</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-3.html#h-12"><span class="HTitleText3">Canada Health Infoway Inc.</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-3.html#h-13"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Canada Foundation for Sustainable Development Technology Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="page-3.html#h-14"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">AMENDMENTS TO THE CANADA PENSION PLAN</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-3.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="page-4.html#h-18"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">AMENDMENTS TO THE EMPLOYMENT INSURANCE ACT</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-4.html#h-19"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">AMENDMENT TO THE FARM CREDIT CANADA ACT</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-4.html#h-20"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">GOODS AND SERVICES TAX AND HARMONIZED SALES TAX REBATE FOR MUNICIPALITIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="page-4.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="page-7.html#h-22"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">LIMITATION PERIODS FOR COLLECTION OF CHARGE DEBTS AND TAX DEBTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-7.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Air Travellers Security Charge Act</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-7.html#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-8.html#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-8.html#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-9.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

