<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Economic Action Plan 2014 Act, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">INCOME TAX ACT</cite> AND TO RELATED LEGISLATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalRegulation">Canada Pension Plan Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalRegulation">Insurable Earnings and Collection of Premiums Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-8"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">EXCISE TAX ACT</cite> (GST/HST MEASURES)</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-9"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">EXCISE ACT, 2001</cite>, THE <cite class="XRefExternalAct">EXCISE TAX ACT</cite> (OTHER THAN GST/HST MEASURES) AND THE <cite class="XRefExternalAct">AIR TRAVELLERS SECURITY CHARGE ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="#h-11"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-12"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Air Travellers Security Charge Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-15"><span class="HLabel1">PART 4</span> - <span class="HTitleText1"><cite class="XRefExternalAct">CUSTOMS TARIFF</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-16"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-17"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-18"><span class="HLabel1">PART 5</span> - <span class="HTitleText1"><cite class="XRefExternalAct">CANADA–UNITED STATES ENHANCED TAX INFORMATION EXCHANGE AGREEMENT IMPLEMENTATION ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-19"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-20"><span class="HTitleText2">Amendments to the <cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>102 - </span><a href="#h-21"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">VARIOUS MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-22"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Payments  —  Veterans Affairs</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-23"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Canada Deposit Insurance Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="#h-24"><span class="HTitleText3"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-25"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-26"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Regulatory Cooperation Council Initiative on Workplace Chemicals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-27"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Hazardous Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-28"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-29"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-30"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-31"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Hazardous Materials Information Review Act</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-32"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-33"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-34"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>163 - </span><a href="#h-35"><span class="HLabel2">Division 4</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Importation of Intoxicating Liquors Act</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-36"><span class="HLabel2">Division 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Judges Act</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-37"><span class="HLabel2">Division 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Members of Parliament Retiring Allowances Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="#h-38"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-39"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="#h-40"><span class="HLabel2">Division 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-41"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-42"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>172 - </span><a href="#h-43"><span class="HLabel2">Division 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-44"><span class="HLabel2">Division 9</span> - <span class="HTitleText2">Atlantic Canada Opportunities Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>175 - </span><a href="#h-45"><span class="HTitleText3"><cite class="XRefExternalAct">Atlantic Canada Opportunities Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-46"><span class="HTitleText3">Dissolution of Board</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="#h-47"><span class="HLabel2">Division 10</span> - <span class="HTitleText2">Enterprise Cape Breton Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-48"><span class="HTitleText3">Dissolution</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-49"><span class="HTitleText3"><cite class="XRefExternalAct">Atlantic Canada Opportunities Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-50"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>188 - </span><a href="#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-53"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="#h-54"><span class="HTitleText3">Repeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>193 - </span><a href="#h-55"><span class="HLabel2">Division 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Museums Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="#h-56"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-57"><span class="HTitleText3">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="#h-58"><span class="HTitleText4">Definitions</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-59"><span class="HTitleText4">Online Works of Reference</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-60"><span class="HTitleText4">Virtual Museum of Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="#h-61"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-62"><span class="HLabel2">Division 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Nordion and Theratronics Divestiture Authorization Act</cite></span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-63"><span class="HLabel2">Division 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-64"><span class="HLabel2">Division 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-65"><span class="HLabel2">Division 15</span> - <span class="HTitleText2">Regulatory Cooperation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>212 - </span><a href="#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Motor Vehicle Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-67"><span class="HTitleText3"><cite class="XRefExternalAct">Railway Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-68"><span class="HTitleText3"><cite class="XRefExternalAct">Transportation of Dangerous Goods Act, 1992</cite></span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-69"><span class="HTitleText3"><cite class="XRefExternalAct">Ensuring Safe Vehicles Imported From Mexico For Canadians Act</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-70"><span class="HTitleText3"><cite class="XRefExternalAct">Safe Food for Canadians Act</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-71"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-72"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>239 - </span><a href="#h-73"><span class="HLabel2">Division 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Telecommunications Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="#h-74"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>241 - </span><a href="#h-75"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>242 - </span><a href="#h-76"><span class="HLabel2">Division 17</span> - <span class="HTitleText2">Sickness Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>242 - </span><a href="#h-77"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-78"><span class="HTitleText3"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="#h-79"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="#h-80"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>252 - </span><a href="#h-81"><span class="HLabel2">Division 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Food Inspection Agency Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>252 - </span><a href="#h-82"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-83"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>254 - </span><a href="#h-84"><span class="HLabel2">Division 19</span> - <span class="HTitleText2">Money Laundering and Terrorist Financing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>254 - </span><a href="#h-85"><span class="HTitleText3"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-86"><span class="HTitleText3"><cite class="XRefExternalAct">Jobs and Economic Growth Act</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-87"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>299 - </span><a href="#h-88"><span class="HLabel2">Division 20</span> - <span class="HTitleText2">Immigration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>299 - </span><a href="#h-89"><span class="HTitleText3"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-90"><span class="HTitleText3"><cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="#h-91"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>308 - </span><a href="#h-92"><span class="HLabel2">Division 21</span> - <span class="HTitleText2">Public Service Labour Relations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>308 - </span><a href="#h-93"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Labour Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="#h-94"><span class="HTitleText3"><cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>310 - </span><a href="#h-95"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>311 - </span><a href="#h-96"><span class="HLabel2">Division 22</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Softwood Lumber Products Export Charge Act, 2006</cite></span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-97"><span class="HLabel2">Division 23</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Budget Implementation Act, 2009</cite></span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="#h-98"><span class="HLabel2">Division 24</span> - <span class="HTitleText2">Securitization of Insured Mortgage or Hypothecary Loans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>314 - </span><a href="#h-99"><span class="HTitleText3"><cite class="XRefExternalAct">Protection of Residential Mortgage or Hypothecary Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="#h-100"><span class="HTitleText3"><cite class="XRefExternalAct">National Housing Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>317 - </span><a href="#h-101"><span class="HLabel2">Division 25</span> - <span class="HTitleText2">Amendments Relating to International Treaties on Trademarks</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>317 - </span><a href="#h-102"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Trade-marks Act</cite></span></a>
</li>
<li><span class='sectionRange'>364 - </span><a href="#h-103"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>364 - </span><a href="#h-104"><span class="HTitleText4"><cite class="XRefExternalAct">Olympic and Paralympic Marks Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>366 - </span><a href="#h-105"><span class="HTitleText3">Terminology</span></a>
</li>
<li><span class='sectionRange'>367 - </span><a href="#h-106"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="#h-107"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>369 - </span><a href="#h-108"><span class="HLabel2">Division 26</span> - <span class="HTitleText2">Reduction of Governor in Council Appointments</span></a>
</li>
<li><span class='sectionRange'>371 - </span><a href="#h-109"><span class="HLabel2">Division 27</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Old Age Security Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>371 - </span><a href="#h-110"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>374 - </span><a href="#h-111"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>375 - </span><a href="#h-112"><span class="HLabel2">Division 28</span> - <span class="HTitleText2"><cite class="XRefExternalAct">New Bridge for the St. Lawrence Act</cite></span></a>
</li>
<li><span class='sectionRange'>376 - </span><a href="#h-113"><span class="HLabel2">Division 29</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Administrative Tribunals Support Service of Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="#h-114"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="#h-115"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>382 - </span><a href="#h-116"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>382 - </span><a href="#h-117"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>389 - </span><a href="#h-118"><span class="HTitleText4"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li>
<li><span class='sectionRange'>390 - </span><a href="#h-119"><span class="HTitleText4"><cite class="XRefExternalAct">Cultural Property Export and Import Act</cite></span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="#h-120"><span class="HTitleText4"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="#h-121"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>414 - </span><a href="#h-122"><span class="HTitleText4"><cite class="XRefExternalAct">Canadian Human Rights Act</cite></span></a>
</li>
<li><span class='sectionRange'>416 - </span><a href="#h-123"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>421 - </span><a href="#h-124"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>428 - </span><a href="#h-125"><span class="HTitleText4"><cite class="XRefExternalAct">Special Import Measures Act</cite></span></a>
</li>
<li><span class='sectionRange'>445 - </span><a href="#h-126"><span class="HTitleText4"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>447 - </span><a href="#h-127"><span class="HTitleText4"><cite class="XRefExternalAct">Competition Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-128"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Agricultural Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="#h-129"><span class="HTitleText4"><cite class="XRefExternalAct">Canadian International Trade Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>458 - </span><a href="#h-130"><span class="HTitleText4"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>459 - </span><a href="#h-131"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>460 - </span><a href="#h-132"><span class="HTitleText4"><cite class="XRefExternalAct">Status of the Artist Act</cite></span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="#h-133"><span class="HTitleText4"><cite class="XRefExternalAct">Employment Equity Act</cite></span></a>
</li>
<li><span class='sectionRange'>464 - </span><a href="#h-134"><span class="HTitleText4"><cite class="XRefExternalAct">Transportation Appeal Tribunal of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>466 - </span><a href="#h-135"><span class="HTitleText4"><cite class="XRefExternalAct">Department of Employment and Social Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="#h-136"><span class="HTitleText4"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>469 - </span><a href="#h-137"><span class="HTitleText4"><cite class="XRefExternalAct">Specific Claims Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>471 - </span><a href="#h-138"><span class="HTitleText4"><cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 2</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>480 - </span><a href="#h-139"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>482 - </span><a href="#h-140"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>483 - </span><a href="#h-141"><span class="HLabel2">Division 30</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Apprentice Loans Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>483 - </span><a href="#h-142"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>484 - </span><a href="#h-143"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>484 - </span><a href="#h-144"><span class="HTitleText4"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>485 - </span><a href="#h-145"><span class="HTitleText4"><cite class="XRefExternalAct">Department of Employment and Social Development Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>486 - </span><a href="#h-146"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-147"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-148"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-149"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-150"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="#h-151"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="#h-152"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li></ul>
</li></ul>

</nav>

