<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Salaries Act and to make a consequential amendment to the Financial Administration Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Salaries Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-2"><span class="HTitleText1">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText1">Consequential Amendment to the Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">Coordinating Amendments</span></a>
</li></ul>
</li></ul>

</nav>

