<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Disability Tax Credit Promoters Restrictions Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PROMOTER’S FEE</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">OFFENCES</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">DISCLOSURE OF INFORMATION</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-7"><span class="HTitleText1">APPLICATION OF INCOME TAX ACT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-8"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Tax Court of Canada Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-1.html#h-10"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

