<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Human Pathogens and Toxins Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">PURPOSE OF THE ACT</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">INTERPRETATION AND APPLICATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">OBLIGATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText1">PROHIBITIONS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText1">SCHEDULES 1 TO 4</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-8"><span class="HTitleText1">SCHEDULE 5</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-9"><span class="HTitleText1">CONSEQUENCES OF ADDING TO SCHEDULES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-10"><span class="HTitleText1">OBLIGATION TO INFORM MINISTER</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-11"><span class="HTitleText1">LICENCES</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-12"><span class="HTitleText1">ACCESS TO FACILITY TO WHICH LICENCE APPLIES</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-13"><span class="HTitleText1">SECURITY CLEARANCES</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-14"><span class="HTitleText1">BIOLOGICAL SAFETY OFFICERS</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-15"><span class="HTitleText1">EXEMPTIONS</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-16"><span class="HTitleText1">INFORMATION</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-17"><span class="HTitleText1">ADMINISTRATION AND ENFORCEMENT</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-18"><span class="HTitleText1">OFFENCES AND PUNISHMENT</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-19"><span class="HTitleText1">DEBTS</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-6.html#h-20"><span class="HTitleText1">REGULATORY POWERS</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-7.html#h-21"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-7.html#h-22"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-8.html#h-23"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - TOXINS</span></a>
</li>
<li><a href="page-9.html#h-24"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - RISK GROUP 2 HUMAN PATHOGENS</span></a>
</li>
<li><a href="page-10.html#h-25"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - RISK GROUP 3 HUMAN PATHOGENS</span></a>
</li>
<li><a href="page-11.html#h-26"><span class="scheduleLabel">SCHEDULE 4</span> <span class="scheduleTitleText"> - RISK GROUP 4 HUMAN PATHOGENS</span></a>
</li>
<li><a href="page-12.html#h-27"><span class="scheduleLabel">SCHEDULE 5</span> <span class="scheduleTitleText"> - PROHIBITED HUMAN PATHOGENS AND TOXINS</span></a>
</li></ul>
</li></ul>

</nav>

