<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Tax Conventions Implementation Act, 2002</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">CANADA–KUWAIT TAX AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">CANADA–MONGOLIA TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CANADA–UNITED ARAB EMIRATES TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">CANADA–MOLDOVA TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CANADA–NORWAY TAX CONVENTIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-1.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Canada–Norway Tax Convention Act, 2002</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Canada–Norway Income Tax Convention Act, 1967</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-2.html#h-9"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">CANADA–BELGIUM TAX CONVENTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="page-2.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">An Act to implement conventions for the avoidance of double taxation with respect to income tax between Canada and France, Canada and Belgium and Canada and Israel</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="page-2.html#h-11"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">CANADA–ITALY TAX CONVENTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-2.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">An Act to implement conventions between Canada and Spain, Canada and the Republic of Austria, Canada and Italy, Canada and the Republic of Korea, Canada and the Socialist Republic of Romania and Canada and the Republic of Indonesia and agreements between Canada and Malaysia, Canada and Jamaica and Canada and Barbados and a convention between Canada and the United Kingdom of Great Britain and Northern Ireland for the avoidance of double taxation with respect to income tax</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-2.html#h-13"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">CANADA–VIETNAM TAX AGREEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Conventions Implementation Act, 1998</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="page-2.html#h-15"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">CANADA–PORTUGAL TAX CONVENTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-2.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Conventions Implementation Act, 1999</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-2.html#h-17"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">CANADA–SENEGAL TAX CONVENTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-2.html#h-18"><span class="HTitleText2">Income Tax Conventions Implementation Act, 2001</span></a>
</li></ul>
</li><li><a href="page-3.html#h-19"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-4.html#h-20"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-5.html#h-21"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-6.html#h-22"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-7.html#h-23"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="page-8.html#h-24"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li>
<li><a href="page-9.html#h-25"><span class="scheduleLabel">SCHEDULE 7</span> </a>
</li></ul>
</li></ul>

</nav>

