<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Assisted Human Reproduction Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">PRINCIPLES</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">INTERPRETATION AND APPLICATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">PROHIBITED ACTIVITIES</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-5"><span class="HTitleText1">CONTROLLED ACTIVITIES</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-6"><span class="HTitleText1">PRIVACY AND ACCESS TO INFORMATION</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-7"><span class="HTitleText1">RESPONSIBILITY OF MINISTER</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-8"><span class="HTitleText1">ASSISTED HUMAN REPRODUCTION AGENCY OF CANADA</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-9"><span class="HTitleText1">ADMINISTRATION</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-10"><span class="HTitleText1">INSPECTION AND ENFORCEMENT</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-6.html#h-11"><span class="HTitleText1">OFFENCES</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-12"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-7.html#h-13"><span class="HTitleText1">EQUIVALENCY AGREEMENTS</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-7.html#h-14"><span class="HTitleText1">PARLIAMENTARY REVIEW</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-7.html#h-15"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-7.html#h-16"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="page-7.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-7.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-7.html#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-7.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-7.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="page-7.html#h-22"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

