<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Main Point of Contact with the Government of Canada in case of Death Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">MANDATE</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">ANNUAL REPORT</span></a>
</li></ul>
</li></ul>

</nav>

