<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Claim Settlements (Alberta and Saskatchewan) Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">CLAIM SETTLEMENTS (ALBERTA AND SASKATCHEWAN) IMPLEMENTATION ACT</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-2"><span class="HTitleText1">RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-3"><span class="HTitleText2">Manitoba Claim Settlements Implementation Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-4"><span class="HTitleText2">Saskatchewan Treaty Land Entitlement Act</span></a>
</li></ul>
</li><li><a href="#h-5"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

