<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Good Samaritan Drug Overdose Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Controlled Drugs and Substances Act</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

