<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Expungement of Historically Unjust Convictions Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Powers, Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Expungement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Effects</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Order</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Destruction and Removal</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Disclosure of Information</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-1.html#h-10"><span class="HTitleText1">Amendment of Schedule</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-11"><span class="HTitleText1">Criteria</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-12"><span class="HTitleText1">Same-Sex Sexual Offences</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-13"><span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Sex Offender Information Registration Act</cite></span></a>
</li></ul>
</li><li><a href="page-3.html#h-16"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

