<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Budget and Economic Statement Implementation Act, 2007</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF THE GOODS AND SERVICES TAX/HARMONIZED SALES TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-1.html#h-4"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENT RELATING TO EXCISE TAX ON RENEWABLE FUELS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS RELATING TO INCOME TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-14.html#h-8"><span class="HTitleText2">Income Tax Application Rules</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-14.html#h-9"><span class="HTitleText2">Income Tax Conventions Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-14.html#h-10"><span class="HTitleText2">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-16.html#h-11"><span class="HTitleText2">Canada Pension Plan Regulations</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-16.html#h-12"><span class="HTitleText2">Insurable Earnings and Collection of Premiums Regulations</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-16.html#h-13"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="page-18.html#h-14"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">DISABILITY SAVINGS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="page-18.html#h-15"><span class="HTitleText2">Amendments Relating to Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="page-18.html#h-16"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-21.html#h-17"><span class="HTitleText3">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-21.html#h-18"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="page-21.html#h-19"><span class="HTitleText4">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-21.html#h-20"><span class="HTitleText4">Old Age Security Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="page-22.html#h-21"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-22.html#h-22"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="page-22.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Disability Savings Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="page-22.html#h-24"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-23.html#h-25"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Children’s Special Allowances Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-23.html#h-26"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>139 - </span><a href="page-23.html#h-27"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">INCENTIVE FOR PROVINCES TO ELIMINATE TAXES ON CAPITAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>139 - </span><a href="page-23.html#h-28"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="page-23.html#h-29"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">BANK FOR INTERNATIONAL SETTLEMENTS (IMMUNITY) ACT</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-24.html#h-30"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">PHASED RETIREMENT — AMENDMENTS OTHER THAN THOSE CONCERNING INCOME TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="page-24.html#h-31"><span class="HTitleText2">Pension Benefits Standards Act, 1985</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-24.html#h-32"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="page-24.html#h-33"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">ADVANCE MARKET COMMITMENT</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-24.html#h-34"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">OIL AND GAS OPERATIONS IN CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>145 - </span><a href="page-24.html#h-35"><span class="HTitleText2">Canada Oil and Gas Operations Act</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-26.html#h-36"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="page-26.html#h-37"><span class="HTitleText3">Canada Petroleum Resources Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-26.html#h-38"><span class="HTitleText3">National Energy Board Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>154 - </span><a href="page-26.html#h-39"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">AMENDMENTS TO THE FARM INCOME PROTECTION ACT</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-26.html#h-40"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>161 - </span><a href="page-26.html#h-41"><span class="HTitleText2">Amendments to the Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-28.html#h-42"><span class="HTitleText2">Amendments to the Budget Implementation Act, 2007</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-28.html#h-43"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Canada-Newfoundland Atlantic Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-28.html#h-44"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-29.html#h-45"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>176 - </span><a href="page-29.html#h-46"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">AMENDMENTS TO THE CANADA EDUCATION SAVINGS ACT</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-29.html#h-47"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">PRIVATE-PUBLIC PARTNERSHIPS</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-29.html#h-48"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">TAX AMENDMENTS TO IMPLEMENT THE 2007 ECONOMIC STATEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="page-29.html#h-49"><span class="HTitleText2">Amendments Relating to Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="page-29.html#h-50"><span class="HTitleText3">Income Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>183 - </span><a href="page-29.html#h-51"><span class="HTitleText2">Amendments to Implement the GST/HST Rate Reduction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="page-29.html#h-52"><span class="HTitleText3">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>196 - </span><a href="page-32.html#h-53"><span class="HTitleText2">Related Amendments as a Result of the GST/HST Rate Reduction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="page-32.html#h-54"><span class="HTitleText3">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-32.html#h-55"><span class="HTitleText3">Excise Act, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="page-32.html#h-56"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="page-33.html#h-57"><span class="HTitleText4">Application</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>

