<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Agricultural Growth Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">PLANT BREEDERS’ RIGHTS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-3"><span class="HTitleText1">FEEDS ACT</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-4"><span class="HTitleText1">FERTILIZERS ACT</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-5"><span class="HTitleText1">SEEDS ACT</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-6"><span class="HTitleText1">HEALTH OF ANIMALS ACT</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-7"><span class="HTitleText1">PLANT PROTECTION ACT</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-8"><span class="HTitleText1">AGRICULTURE AND AGRI-FOOD ADMINISTRATIVE MONETARY PENALTIES ACT</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-9"><span class="HTitleText1"><cite class="XRefExternalAct">AGRICULTURAL MARKETING PROGRAMS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-10"><span class="HTitleText1"><cite class="XRefExternalAct">FARM DEBT MEDIATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-11"><span class="HTitleText1">TRANSITIONAL PROVISIONS — AGRICULTURAL MARKETING PROGRAMS ACT</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-12"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

