<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–Korea Economic Growth and Prosperity Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">CAUSES OF ACTION</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">IMPLEMENTATION OF THE AGREEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Approval</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Panels, Committees, Subcommittees, Working Groups and Other Bodies</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Orders</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText2">Protection of Geographical Indications</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-12"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText2">Crown Liability and Proceedings Act</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-15"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HTitleText2">Commercial Arbitration Act</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-17"><span class="HTitleText2">Canadian International Trade Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-18"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-19"><span class="HTitleText2">Department of Employment and Social Development Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="#h-20"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">COORDINATING AMENDMENTS AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="#h-21"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-22"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-23"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-24"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

