<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–EFTA Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">IMPLEMENTATION OF AGREEMENTS GENERALLY</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Approval of Agreements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText2">Subcommittees and Working Groups</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">RELATED AND CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-12"><span class="HTitleText2">Canadian International Trade Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText2">Customs Tariff</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-15"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-16"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-17"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-18"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-19"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="#h-20"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="#h-21"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">SCHEDULE 7</span> </a>
</li></ul>
</li></ul>

</nav>

