<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Safer Witnesses Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">WITNESS PROTECTION PROGRAM ACT</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT TO THE ACCESS TO INFORMATION ACT</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-4"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-6"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

