<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Multilateral Instrument in Respect of Tax Conventions Act</a><ul class="TocIndent"><li><a href="page-2.html#h-1"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Multilateral Convention to Implement Tax Treaty Related Measures to Prevent Base Erosion and Profit Shifting</span></a>
</li></ul>
</li></ul>

</nav>

