<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Economic Action Plan 2014 Act, No. 2</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">INCOME TAX ACT</cite> AND A RELATED TEXT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-18.html#h-4"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>92 - </span><a href="page-23.html#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">EXCISE TAX ACT</cite> (GST/HST MEASURES) AND A RELATED TEXT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>92 - </span><a href="page-23.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-25.html#h-7"><span class="HTitleText2"><cite class="XRefExternalRegulation">Selected Listed Financial Institutions Attribution Method (GST/HST) Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>100 - </span><a href="page-25.html#h-8"><span class="HLabel1">PART 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">EXCISE ACT, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-25.html#h-9"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">VARIOUS MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="page-25.html#h-10"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Intellectual Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="page-25.html#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Industrial Design Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="page-25.html#h-12"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-26.html#h-13"><span class="HTitleText4">Consequential Amendment to the <cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="page-27.html#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Patent Act</cite></span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-30.html#h-15"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>143 - </span><a href="page-30.html#h-16"><span class="HLabel2">Division 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Aeronautics Act</cite></span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-30.html#h-17"><span class="HLabel2">Division 3</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian High Arctic Research Station Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>145 - </span><a href="page-30.html#h-18"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-31.html#h-19"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-31.html#h-20"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="page-31.html#h-21"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-31.html#h-22"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="page-31.html#h-23"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-31.html#h-24"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>169 - </span><a href="page-31.html#h-25"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-31.html#h-26"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>171 - </span><a href="page-31.html#h-27"><span class="HLabel2">Division 4</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-32.html#h-28"><span class="HLabel2">Division 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-32.html#h-29"><span class="HLabel2">Division 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Radiocommunication Act</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="page-34.html#h-30"><span class="HLabel2">Division 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Revolving Funds Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="page-34.html#h-31"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-34.html#h-32"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="page-34.html#h-33"><span class="HLabel2">Division 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Royal Canadian Mint Act</cite></span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="page-34.html#h-34"><span class="HLabel2">Division 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>186 - </span><a href="page-34.html#h-35"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-34.html#h-36"><span class="HTitleText3">Related Amendments to the <cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-34.html#h-37"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>191 - </span><a href="page-34.html#h-38"><span class="HLabel2">Division 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Broadcasting Act</cite></span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="page-34.html#h-39"><span class="HLabel2">Division 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Telecommunications Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="page-34.html#h-40"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="page-37.html#h-41"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="page-38.html#h-42"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>211 - </span><a href="page-38.html#h-43"><span class="HLabel2">Division 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Business Development Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="page-39.html#h-44"><span class="HLabel2">Division 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Northwest Territories Act</cite></span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="page-39.html#h-45"><span class="HLabel2">Division 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="page-39.html#h-46"><span class="HLabel2">Division 15</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada-Chile Free Trade Agreement Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-39.html#h-47"><span class="HLabel2">Division 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Marine Act</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="page-40.html#h-48"><span class="HLabel2">Division 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">DNA Identification Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>232 - </span><a href="page-40.html#h-49"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="page-41.html#h-50"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="page-41.html#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="page-41.html#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>249 - </span><a href="page-41.html#h-53"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>250 - </span><a href="page-41.html#h-54"><span class="HLabel2">Division 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250 - </span><a href="page-41.html#h-55"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="page-41.html#h-56"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>252 - </span><a href="page-41.html#h-57"><span class="HLabel2">Division 19</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Department of Employment and Social Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-41.html#h-58"><span class="HLabel2">Division 20</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Public Health Agency of Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>253 - </span><a href="page-41.html#h-59"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="page-42.html#h-60"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="page-42.html#h-61"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>261 - </span><a href="page-42.html#h-62"><span class="HLabel2">Division 21</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="page-42.html#h-63"><span class="HLabel2">Division 22</span> - <span class="HTitleText2">Central Cooperative Credit Societies and Federal Credit Unions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>266 - </span><a href="page-42.html#h-64"><span class="HTitleText3"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="page-42.html#h-65"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="page-42.html#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="page-43.html#h-67"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="page-44.html#h-68"><span class="HTitleText3">Termination of Agreements</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="page-44.html#h-69"><span class="HTitleText3">Dissolution</span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="page-44.html#h-70"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>300 - </span><a href="page-44.html#h-71"><span class="HTitleText4"><cite class="XRefExternalAct">Office of the Superintendent of Financial Institutions Act</cite></span></a>
</li>
<li><span class='sectionRange'>301 - </span><a href="page-44.html#h-72"><span class="HTitleText4"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>302 - </span><a href="page-44.html#h-73"><span class="HTitleText4"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>303 - </span><a href="page-44.html#h-74"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>304 - </span><a href="page-44.html#h-75"><span class="HLabel2">Division 23</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>304 - </span><a href="page-44.html#h-76"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="page-45.html#h-77"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>306 - </span><a href="page-45.html#h-78"><span class="HLabel2">Division 24</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>306 - </span><a href="page-45.html#h-79"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="page-45.html#h-80"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>315 - </span><a href="page-45.html#h-81"><span class="HLabel2">Division 25</span> - <span class="HTitleText2">Prothonotaries of the Federal Court</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>315 - </span><a href="page-45.html#h-82"><span class="HTitleText3"><cite class="XRefExternalAct">Judges Act</cite></span></a>
</li>
<li><span class='sectionRange'>328 - </span><a href="page-46.html#h-83"><span class="HTitleText3"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>329 - </span><a href="page-46.html#h-84"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="page-46.html#h-85"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">Garnishment, Attachment and Pension Diversion Act</cite></span></a>
</li>
<li><span class='sectionRange'>333 - </span><a href="page-46.html#h-86"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>334 - </span><a href="page-47.html#h-87"><span class="HLabel2">Division 26</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Payments Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>334 - </span><a href="page-47.html#h-88"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>358 - </span><a href="page-49.html#h-89"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>359 - </span><a href="page-49.html#h-90"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>360 - </span><a href="page-49.html#h-91"><span class="HLabel2">Division 27</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Payment Clearing and Settlement Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>360 - </span><a href="page-49.html#h-92"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>374 - </span><a href="page-51.html#h-93"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>374 - </span><a href="page-51.html#h-94"><span class="HTitleText4"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>375 - </span><a href="page-51.html#h-95"><span class="HTitleText4"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>376 - </span><a href="page-51.html#h-96"><span class="HLabel2">Division 28</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Extractive Sector Transparency Measures Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="page-51.html#h-97"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="page-52.html#h-98"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>378 - </span><a href="page-52.html#h-99"><span class="HLabel2">Division 29</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Jobs and Economic Growth Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>378 - </span><a href="page-52.html#h-100"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>381 - </span><a href="page-52.html#h-101"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>382 - </span><a href="page-52.html#h-102"><span class="HLabel2">Division 30</span> - <span class="HTitleText2">Public Service Labour Relations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>382 - </span><a href="page-52.html#h-103"><span class="HTitleText3"><cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>386 - </span><a href="page-52.html#h-104"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>387 - </span><a href="page-52.html#h-105"><span class="HLabel2">Division 31</span> - <span class="HTitleText2">Royal Canadian Mounted Police Pensions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>387 - </span><a href="page-52.html#h-106"><span class="HTitleText3">Transfer of Pension of Certain Employees</span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="page-53.html#h-107"><span class="HTitleText3"><cite class="XRefExternalAct">Royal Canadian Mounted Police Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>400 - </span><a href="page-53.html#h-108"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>401 - </span><a href="page-53.html#h-109"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>

