<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
First Nations Elections Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">ADDING TO THE SCHEDULE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">ELECTION DATES</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">COUNCIL</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText1">CANDIDATES</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">BALLOTS</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText1">VOTING</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-9"><span class="HTitleText1">POLLING STATIONS</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText1">AWARDING OF POSITIONS</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText1">BY-ELECTIONS</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-12"><span class="HTitleText1">OBSTRUCTION OF ELECTIONS</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-13"><span class="HTitleText1">TERM OF OFFICE</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText1">CONTESTED ELECTIONS</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-15"><span class="HTitleText1">PETITION FOR REMOVAL FROM OFFICE</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-16"><span class="HTitleText1">OFFENCES</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-17"><span class="HTitleText1">PENALTIES</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-18"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-19"><span class="HTitleText1">REMOVAL FROM SCHEDULE</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-20"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT TO THE INDIAN ACT</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-21"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - PARTICIPATING FIRST NATIONS</span></a>
</li></ul>
</li></ul>

</nav>

