<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Economic Recovery Act (stimulus)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS RELATED TO INCOME TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-4"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="page-3.html#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">MISCELLANEOUS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-3.html#h-6"><span class="HTitleText2">Payments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-3.html#h-7"><span class="HTitleText3">Multilateral Debt Relief</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-8"><span class="HTitleText3">Payment to Nova Scotia — Offshore Petroleum Resources</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-3.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Bretton Woods and Related Agreements Act</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Broadcasting Act</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Budget Implementation Act, 2009</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="page-3.html#h-13"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-6.html#h-14"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="page-6.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan Investment Board Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-6.html#h-16"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-7.html#h-17"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-7.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-7.html#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="page-7.html#h-20"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-7.html#h-21"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="page-7.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="page-7.html#h-23"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-8.html#h-24"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="page-8.html#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-8.html#h-26"><span class="HTitleText2">Amendments Related to the <cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="page-8.html#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-8.html#h-28"><span class="HTitleText3">Chapter 36 of the Statutes of Canada, 2007</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-9.html#h-29"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

