<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
National Strategy for Alzheimer’s Disease and Other Dementias Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">National Strategy on Alzheimer’s Disease and other Dementias</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Advisory Board</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Review and Report</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

