<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Miscellaneous Statute Law Amendment Act, 2014</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Aeronautics Act</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Agricultural Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Business Corporations Act</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Corporations Act</cite></span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Marine Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Canada National Parks Act</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Not-for-profit Corporations Act</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Shipping Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Transportation Act</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-2.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Chemical Weapons Convention Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Coasting Trade Act</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Companies’ Creditors Arrangement Act</cite></span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-3.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-3.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Consumer Packaging and Labelling Act</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-3.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-3.html#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-4.html#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-4.html#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-5.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Defence Production Act</cite></span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-5.html#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Veterans Affairs Act</cite></span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-5.html#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Divorce Act</cite></span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-5.html#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Economic Development Agency of Canada for the Regions of Quebec Act</cite></span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-5.html#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Electoral Boundaries Readjustment Act</cite></span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-5.html#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Electricity and Gas Inspection Act</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-5.html#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Explosives Act</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-5.html#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Farm Products Agencies Act</cite></span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-6.html#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-6.html#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Fisheries Act</cite></span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-6.html#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Gender Equity in Indian Registration Act</cite></span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-6.html#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Government Employees Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-6.html#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Health of Animals Act</cite></span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-7.html#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-7.html#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Indian Act</cite></span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-7.html#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-7.html#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">International Bridges and Tunnels Act</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-7.html#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Interpretation Act</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-8.html#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Judges Act</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-8.html#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Legislative Instruments Re-enactment Act</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-8.html#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Library and Archives of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-8.html#h-48"><span class="HTitleText2"><cite class="XRefExternalAct">Meat Inspection Act</cite></span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-8.html#h-49"><span class="HTitleText2"><cite class="XRefExternalAct">Merchant Seamen Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-8.html#h-50"><span class="HTitleText2"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-8.html#h-51"><span class="HTitleText2"><cite class="XRefExternalAct">Newfoundland Additional Financial Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-8.html#h-52"><span class="HTitleText2"><cite class="XRefExternalAct">Nuclear Safety and Control Act</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-8.html#h-53"><span class="HTitleText2"><cite class="XRefExternalAct">Oceans Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-8.html#h-54"><span class="HTitleText2"><cite class="XRefExternalAct">Patent Act</cite></span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-8.html#h-55"><span class="HTitleText2"><cite class="XRefExternalAct">Pension Act</cite></span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-8.html#h-56"><span class="HTitleText2"><cite class="XRefExternalAct">Physical Activity and Sport Act</cite></span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-9.html#h-57"><span class="HTitleText2"><cite class="XRefExternalAct">Plant Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-9.html#h-58"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-9.html#h-59"><span class="HTitleText2"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-9.html#h-60"><span class="HTitleText2"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-9.html#h-61"><span class="HTitleText2"><cite class="XRefExternalAct">Railway Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-9.html#h-62"><span class="HTitleText2"><cite class="XRefExternalAct">Saguenay-St. Lawrence Marine Park Act</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-9.html#h-63"><span class="HTitleText2"><cite class="XRefExternalAct">Seized Property Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="page-9.html#h-64"><span class="HTitleText2"><cite class="XRefExternalAct">Species at Risk Act</cite></span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-9.html#h-65"><span class="HTitleText2"><cite class="XRefExternalAct">Tobacco Act</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-9.html#h-66"><span class="HTitleText2"><cite class="XRefExternalAct">Transportation of Dangerous Goods Act, 1992</cite></span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-9.html#h-67"><span class="HTitleText2"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-9.html#h-68"><span class="HTitleText2"><cite class="XRefExternalAct">Veterans Review and Appeal Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-9.html#h-69"><span class="HTitleText2"><cite class="XRefExternalAct">Visiting Forces Act</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-10.html#h-70"><span class="HTitleText2"><cite class="XRefExternalAct">War Veterans Allowance Act</cite></span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-10.html#h-71"><span class="HTitleText2"><cite class="XRefExternalAct">Winding-up and Restructuring Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>172 - </span><a href="page-10.html#h-72"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">TERMINOLOGY</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-11.html#h-73"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li></ul>
</li></ul>

</nav>

