<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to provide further support in response to COVID-19</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PART 1</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Related Amendments to the <cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Worker Lockdown Benefit Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-8"><span class="HTitleText3"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText3"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-10"><span class="HLabel1">PART 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Recovery Benefits Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-11"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Related Amendment to the <cite class="XRefExternalRegulation">Canada Recovery Benefits Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>19.1 - </span><a href="#h-13"><span class="HLabel1">PART 3.1</span> - <span class="HTitleText1">Review of Acts</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-14"><span class="HLabel1">PART 4</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-15"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText2">Related Amendment to the <cite class="XRefExternalAct">Budget Implementation Act, 2021, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-18"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

