<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
<?Pub Caret?>Abolition of Early Parole Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CORRECTIONS AND CONDITIONAL RELEASE ACT</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-4"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-1.html#h-5"><span class="HTitleText2">An Act to amend the Corrections and Conditional Release Act, the Criminal Code, the Criminal Records Act, the Prisons and Reformatories Act and the Transfer of Offenders Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-6"><span class="HTitleText2">An Act to amend the Criminal Code (high risk offenders), the Corrections and Conditional Release Act, the Criminal Records Act, the Prisons and Reformatories Act and the Department of the Solicitor General Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Anti-terrorism Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-1.html#h-8"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-9"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

