<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Employment Insurance Act and to increase benefits</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">EMPLOYMENT INSURANCE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CLAIMANTS NOT IN CANADA</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-3"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

