<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Immigration and Refugee Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">OBJECTIVES AND APPLICATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">ENABLING AUTHORITY</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">AGREEMENTS</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">IMMIGRATION TO CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-7"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Requirements Before Entering Canada and Selection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText3">Requirements Before Entering Canada</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText3">Selection of Permanent Residents</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText3">Sponsorship of Foreign Nationals</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-12"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Examination</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Entering and Remaining in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-14"><span class="HTitleText3">Entering and Remaining</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-15"><span class="HTitleText3">Status and Authorization to Enter</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-16"><span class="HTitleText3">Rights and Obligations of Permanent and Temporary Residents</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-17"><span class="HTitleText3">Status Document</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-18"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-19"><span class="HLabel2">Division 4</span> - <span class="HTitleText2">Inadmissibility</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-20"><span class="HLabel2">Division 5</span> - <span class="HTitleText2">Loss of Status and Removal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-21"><span class="HTitleText3">Report on Inadmissibility</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-22"><span class="HTitleText3">Admissibility Hearing by the Immigration Division</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-23"><span class="HTitleText3">Loss of Status</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-24"><span class="HTitleText3">Enforcement of Removal Orders</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-25"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-26"><span class="HLabel2">Division 6</span> - <span class="HTitleText2">Detention and Release</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-27"><span class="HLabel2">Division 7</span> - <span class="HTitleText2">Right of Appeal</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-28"><span class="HLabel2">Division 8</span> - <span class="HTitleText2">Judicial Review</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-29"><span class="HLabel2">Division 9</span> - <span class="HTitleText2">Certificates and Protection of Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-30"><span class="HTitleText3">Examination on Request by the Minister and the Solicitor General of Canada</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-31"><span class="HTitleText3">Detention</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-32"><span class="HTitleText3">Consideration During an Admissibility Hearing or an Immigration Appeal</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-33"><span class="HTitleText3">Consideration During Judicial Review</span></a>
</li></ul>
</li><li><span class='sectionRange'>88 - </span><a href="#h-34"><span class="HLabel2">Division 10</span> - <span class="HTitleText2">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="#h-35"><span class="HTitleText3">Loans</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-36"><span class="HTitleText3">Fees</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-37"><span class="HTitleText3">Social Insurance Number Cards</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-38"><span class="HTitleText3">Representation</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-39"><span class="HTitleText3">Material Incorporated in Regulations</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-40"><span class="HTitleText3">Report to Parliament</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-41"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">REFUGEE PROTECTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="#h-42"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Refugee Protection, Convention Refugees and Persons in Need of Protection</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-43"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Convention Refugees and Persons in Need of Protection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-44"><span class="HTitleText3">Claim for Refugee Protection</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-45"><span class="HTitleText3">Examination of Eligibility to Refer Claim</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-46"><span class="HTitleText3">Suspension or Termination of Consideration of Claim</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-47"><span class="HTitleText3">Extradition Procedure</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-48"><span class="HTitleText3">Claimant Without Identification</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-49"><span class="HTitleText3">Decision on Claim for Refugee Protection</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-50"><span class="HTitleText3">Cessation of Refugee Protection</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-51"><span class="HTitleText3">Applications to Vacate</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-52"><span class="HTitleText3">Appeal to Refugee Appeal Division</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="#h-53"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Pre-removal Risk Assessment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-54"><span class="HTitleText3">Protection</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-55"><span class="HTitleText3">Principle of Non-refoulement</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-56"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">ENFORCEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="#h-57"><span class="HTitleText2">Human Smuggling and Trafficking</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-58"><span class="HTitleText2">Offences Related to Documents</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-59"><span class="HTitleText2">General Offences</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-60"><span class="HTitleText2">Proceeds of Crime</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-61"><span class="HTitleText2">Prosecution of Offences</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-62"><span class="HTitleText2">Forfeiture</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-63"><span class="HTitleText2">Officers Authorized to Enforce Act</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-64"><span class="HTitleText2">Peace Officers</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-65"><span class="HTitleText2">Ticketable Offences</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-66"><span class="HTitleText2">Debt Due to Her Majesty</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-67"><span class="HTitleText2">Collection of Debts Due to Her Majesty</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-68"><span class="HTitleText2">Transportation Companies</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="#h-69"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">IMMIGRATION AND REFUGEE BOARD</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-70"><span class="HTitleText2">Composition of Board</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-71"><span class="HTitleText2">Head Office and Staff</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-72"><span class="HTitleText2">Duties of Chairperson</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-73"><span class="HTitleText2">Functioning of Board</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-74"><span class="HTitleText2">Provisions that Apply to All Divisions</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-75"><span class="HTitleText2">Refugee Protection Division</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-76"><span class="HTitleText2">Refugee Appeal Division</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-77"><span class="HTitleText2">Immigration Division</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-78"><span class="HTitleText2">Immigration Appeal Division</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-79"><span class="HTitleText2">Remedial and Disciplinary Measures</span></a>
</li></ul>
</li><li><span class='sectionRange'>187 - </span><a href="#h-80"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">TRANSITIONAL PROVISIONS, CONSEQUENTIAL AND RELATED AMENDMENTS, COORDINATING AMENDMENTS, REPEALS AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>187 - </span><a href="#h-81"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-82"><span class="HTitleText2">Consequential and Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>202 - </span><a href="#h-83"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="#h-84"><span class="HTitleText3">Agricultural Marketing Programs Act</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-85"><span class="HTitleText3">Animal Pedigree Act</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-86"><span class="HTitleText3">Bank Act</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-87"><span class="HTitleText3">Budget Implementation Act, 1998</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-88"><span class="HTitleText3">Business Development Bank of Canada Act</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-89"><span class="HTitleText3">Canada Business Corporations Act</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-90"><span class="HTitleText3">Canada Customs and Revenue Agency Act</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-91"><span class="HTitleText3">Canada Elections Act</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-92"><span class="HTitleText3">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-93"><span class="HTitleText3">Canada Shipping Act</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-94"><span class="HTitleText3">Canada Student Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-95"><span class="HTitleText3">Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-96"><span class="HTitleText3">Canada Transportation Act</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-97"><span class="HTitleText3">Canadian Security Intelligence Service Act</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-98"><span class="HTitleText3">Chemical Weapons Convention Implementation Act</span></a>
</li>
<li><span class='sectionRange'>227.1 - </span><a href="#h-99"><span class="HTitleText3">Citizenship Act</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-100"><span class="HTitleText3">Comprehensive Nuclear Test-Ban Treaty Implementation Act</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-101"><span class="HTitleText3">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="#h-102"><span class="HTitleText3">Copyright Act</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-103"><span class="HTitleText3">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-104"><span class="HTitleText3">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-105"><span class="HTitleText3">Emergencies Act</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="#h-106"><span class="HTitleText3">Extradition Act</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-107"><span class="HTitleText3">Foreign Publishers Advertising Services Act</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-108"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-109"><span class="HTitleText3">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="#h-110"><span class="HTitleText3">International Centre for Human Rights and Democratic Development Act</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="#h-111"><span class="HTitleText3">Investment Canada Act</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="#h-112"><span class="HTitleText3">Labour Adjustment Benefits Act</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-113"><span class="HTitleText3">Mutual Legal Assistance in Criminal Matters Act</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-114"><span class="HTitleText3">National Energy Board Act</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="#h-115"><span class="HTitleText3">Old Age Security Act</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-116"><span class="HTitleText3">Pilotage Act</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="#h-117"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-118"><span class="HTitleText3">Proceeds of Crime (Money Laundering) Act</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-119"><span class="HTitleText3">Trade-marks Act</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-120"><span class="HTitleText3">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="#h-121"><span class="HTitleText3">Terminology</span></a>
</li></ul>
</li><li><span class='sectionRange'>273.1 - </span><a href="#h-122"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>274 - </span><a href="#h-123"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="#h-124"><span class="HTitleText2">Coming Into Force</span></a>
</li></ul>
</li><li><a href="#h-125"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - SECTIONS E AND F OF ARTICLE 1 OF THE UNITED NATIONS CONVENTION RELATING TO THE STATUS OF REFUGEES</span></a>
</li></ul>
</li></ul>

</nav>

