<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Canadian Human Rights Act and the Criminal Code</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Canadian Human Rights Act</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

