<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Sales Tax Amendments Act, 2006</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE EXCISE TAX ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Amendments in Respect of the Goods and Services Tax/Harmonized Sales Tax</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-11.html#h-4"><span class="HTitleText2">Amendments in Respect of Excise Taxes</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-11.html#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF EXCISE DUTY ON ALCOHOL AND TOBACCO PRODUCTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="page-11.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-16.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-16.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-17.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-17.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="page-17.html#h-11"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS TO THE AIR TRAVELLERS SECURITY CHARGE ACT</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-18.html#h-12"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li></ul>
</li></ul>

</nav>

