<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada–Costa Rica Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">IMPLEMENTATION OF AGREEMENT GENERALLY</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Approval of Agreement</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Panels, Committees, Subcommittees and Working Groups</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-11"><span class="HTitleText2">Orders and Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="page-2.html#h-12"><span class="HLabel1">PART II</span> - <span class="HTitleText1">RELATED AND CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Canadian International Trade Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-14"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-16"><span class="HTitleText2">Export and Import Permits Act</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-6.html#h-17"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-6.html#h-18"><span class="HTitleText2">Importation of Intoxicating Liquors Act</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-6.html#h-19"><span class="HTitleText2">National Energy Board Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="page-6.html#h-20"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-7.html#h-21"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-8.html#h-22"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-9.html#h-23"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>

</nav>

