<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Fairness for the Self-Employed Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">EMPLOYMENT INSURANCE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-4"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-3.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-4.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Companies’ Creditors Arrangement Act</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-4.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-4.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Old Age Security Act</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-4.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Tax Court of Canada Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-4.html#h-10"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-5.html#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

