<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Canada Transportation Act (railway transportation)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CANADA TRANSPORTATION ACT</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-2"><span class="HTitleText1">AN ACT TO AMEND THE CANADA TRANSPORTATION ACT AND THE RAILWAY SAFETY ACT AND TO MAKE CONSEQUENTIAL AMENDMENTS TO OTHER ACTS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-3"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li></ul>
</li></ul>

</nav>

