<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal Framework for Suicide Prevention Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">FEDERAL FRAMEWORK FOR SUICIDE PREVENTION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">CONSULTATIONS</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">REPORT</span></a>
</li></ul>
</li></ul>

</nav>

