<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Canada-Israel Free Trade Agreement Implementation Act and to make related amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Canada-Israel Free Trade Agreement Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-2"><span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Crown Liability and Proceedings Act</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Importation of Intoxicating Liquors Act</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Employment and Social Development Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-7"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-8"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

