<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Economic Development Agency of Canada for the Regions of Quebec Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">MINISTER</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">ECONOMIC DEVELOPMENT AGENCY OF CANADA FOR THE REGIONS OF QUEBEC</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText1">OBJECT, POWERS AND DUTIES</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HTitleText1">REPORTS</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Auditor General Act</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText2">Department of Industry Act</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-14"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText2">Public Service Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText2">Salaries Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-18"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

