<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to give effect to the Agreement on Cree Nation Governance between the Crees of Eeyou Istchee and the Government of Canada, to amend the Cree-Naskapi (of Quebec) Act and to make related and consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Cree Nation of Eeyou Istchee Governance Agreement Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Enactment of Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>2 - </span><a href="#h-3"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Cree-Naskapi (of Quebec) Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-4"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-5"><span class="HTitleText2">Terminology</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="#h-6"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Transitional Provisions, Related and Consequential Amendments and Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124 - </span><a href="#h-7"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-8"><span class="HTitleText2">Related Amendment to the <cite class="XRefExternalAct">Modernization of Benefits and Obligations Act</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-9"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Veterans’ Land Act</cite></span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-12"><span class="HTitleText3"><cite class="XRefExternalAct">Expropriation Act</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Lands Surveys Act</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">National Energy Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Specific Claims Tribunal Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>134 - </span><a href="#h-18"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

