<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the National Defence Act, the Criminal Code, the Sex Offender Information Registration Act and the Criminal Records Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">NATIONAL DEFENCE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL CODE</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-5.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">SEX OFFENDER INFORMATION REGISTRATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-8.html#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL RECORDS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-8.html#h-5"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-8.html#h-6"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

