<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Federal Accountability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">CONFLICTS OF INTEREST, ELECTION FINANCING, LOBBYING AND MINISTERS’ STAFF</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Conflict of Interest Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-4"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-5"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-6"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-2.html#h-7"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Post Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-8"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-9"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-10"><span class="HTitleText4"><cite class="XRefExternalAct">First Nations Fiscal and Statistical Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-11"><span class="HTitleText4"><cite class="XRefExternalAct">Garnishment, Attachment and Pension Diversion Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-12"><span class="HTitleText4"><cite class="XRefExternalAct">Government Employees Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-13"><span class="HTitleText4"><cite class="XRefExternalAct">Non-smokers’ Health Act</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-14"><span class="HTitleText4"><cite class="XRefExternalAct">Official Languages Act</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-4.html#h-15"><span class="HTitleText4"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-4.html#h-16"><span class="HTitleText4"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-5.html#h-17"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-5.html#h-18"><span class="HTitleText4"><cite class="XRefExternalAct">Radiocommunication Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-5.html#h-19"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="page-5.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Elections Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="page-5.html#h-21"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-7.html#h-22"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-7.html#h-23"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="page-7.html#h-24"><span class="HTitleText4"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="page-8.html#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Lobbyists Registration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="page-8.html#h-26"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-10.html#h-27"><span class="HTitleText3">Terminology</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-11.html#h-28"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-11.html#h-29"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="page-11.html#h-30"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-11.html#h-31"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-12.html#h-32"><span class="HTitleText4"><cite class="XRefExternalAct">Official Languages Act</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-12.html#h-33"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="page-12.html#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-12.html#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>100 - </span><a href="page-12.html#h-36"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-13.html#h-37"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="page-13.html#h-38"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="page-13.html#h-39"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">SUPPORTING PARLIAMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>109 - </span><a href="page-13.html#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-13.html#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Auditor General Act</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-13.html#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Official Languages Act</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-13.html#h-43"><span class="HTitleText2">Parliament of Canada Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="page-13.html#h-44"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-14.html#h-45"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="page-14.html#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-14.html#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-14.html#h-48"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="page-15.html#h-49"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">OFFICE OF THE DIRECTOR OF PUBLIC PROSECUTIONS, ADMINISTRATIVE TRANSPARENCY AND DISCLOSURE OF WRONGDOING</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="page-15.html#h-50"><span class="HTitleText2"><cite class="XRefExternalAct">Director of Public Prosecutions Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="page-15.html#h-51"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-16.html#h-52"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-16.html#h-53"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="page-16.html#h-54"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-16.html#h-55"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Elections Act</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-17.html#h-56"><span class="HTitleText4"><cite class="XRefExternalAct">Department of Justice Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-17.html#h-57"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-17.html#h-58"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>141 - </span><a href="page-17.html#h-59"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="page-17.html#h-60"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>172.1 - </span><a href="page-19.html#h-61"><span class="HTitleText3">Consequential Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>172.1 - </span><a href="page-19.html#h-62"><span class="HTitleText4">Canadian Wheat Board Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>76.1 - </span><a href="page-19.html#h-63"><span class="HTitleText2">Review by Minister</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-19.html#h-64"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Elections Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="page-19.html#h-65"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-19.html#h-66"><span class="HTitleText3">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="page-20.html#h-67"><span class="HTitleText2"><cite class="XRefExternalAct">Export Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>179.1 - </span><a href="page-20.html#h-68"><span class="HTitleText2"><cite class="XRefExternalAct">Library and Archives of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="page-20.html#h-69"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-21.html#h-70"><span class="HTitleText2"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="page-21.html#h-71"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="page-25.html#h-72"><span class="HTitleText3">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="page-25.html#h-73"><span class="HTitleText2"><cite class="XRefExternalAct">Salaries Act</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-25.html#h-74"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>229 - </span><a href="page-25.html#h-75"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">ADMINISTRATIVE OVERSIGHT AND ACCOUNTABILITY</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>229 - </span><a href="page-25.html#h-76"><span class="HTitleText2"><cite class="XRefExternalAct">Business Development Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-25.html#h-77"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Council for the Arts Act</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-25.html#h-78"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Mortgage And Housing Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="page-26.html#h-79"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Post Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="page-26.html#h-80"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Revenue Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="page-26.html#h-81"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Commercial Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="page-26.html#h-82"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Dairy Commission Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="page-26.html#h-83"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="page-26.html#h-84"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>243 - </span><a href="page-26.html#h-85"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Race Relations Foundation Act</cite></span></a>
</li>
<li><span class='sectionRange'>244.1 - </span><a href="page-26.html#h-86"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Tourism Commission Act</cite></span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="page-26.html#h-87"><span class="HTitleText2"><cite class="XRefExternalAct">Cape Breton Development Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>246 - </span><a href="page-26.html#h-88"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="page-26.html#h-89"><span class="HTitleText2"><cite class="XRefExternalAct">Enterprise Cape Breton Corporation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="page-26.html#h-90"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-27.html#h-91"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>254 - </span><a href="page-27.html#h-92"><span class="HTitleText2"><cite class="XRefExternalAct">Export Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="page-27.html#h-93"><span class="HTitleText2"><cite class="XRefExternalAct">Farm Credit Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="page-27.html#h-94"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>257 - </span><a href="page-27.html#h-95"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="page-28.html#h-96"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>276 - </span><a href="page-29.html#h-97"><span class="HTitleText2"><cite class="XRefExternalAct">Freshwater Fish Marketing Act</cite></span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="page-29.html#h-98"><span class="HTitleText2"><cite class="XRefExternalAct">Museums Act</cite></span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="page-29.html#h-99"><span class="HTitleText2"><cite class="XRefExternalAct">National Arts Centre Act</cite></span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="page-29.html#h-100"><span class="HTitleText2"><cite class="XRefExternalAct">National Capital Act</cite></span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="page-30.html#h-101"><span class="HTitleText2"><cite class="XRefExternalAct">Pilotage Act</cite></span></a>
</li>
<li><span class='sectionRange'>295 - </span><a href="page-30.html#h-102"><span class="HTitleText2"><cite class="XRefExternalAct">Public Sector Pension Investment Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="page-30.html#h-103"><span class="HTitleText2"><cite class="XRefExternalAct">Royal Canadian Mint Act</cite></span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="page-30.html#h-104"><span class="HTitleText2"><cite class="XRefExternalAct">Standards Council of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="page-30.html#h-105"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>301 - </span><a href="page-30.html#h-106"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">PROCUREMENT AND CONTRACTING</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>301 - </span><a href="page-30.html#h-107"><span class="HTitleText2"><cite class="XRefExternalAct">Auditor General Act</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="page-31.html#h-108"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Public Works and Government Services Act</cite></span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="page-31.html#h-109"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>308 - </span><a href="page-31.html#h-110"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="page-32.html#h-111"><span class="HTitleText3">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>314 - </span><a href="page-32.html#h-112"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-33.html#h-113"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

