<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Sustaining Canada’s Economic Recovery Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE INCOME TAX ACT AND RELATED ACTS AND REGULATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-4"><span class="HTitleText2">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-5"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-6"><span class="HTitleText2">Universal Child Care Benefit Act</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-7"><span class="HTitleText2">Income Tax Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-8"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF EXCISE DUTIES AND SALES AND EXCISE TAXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-9"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-10"><span class="HTitleText2">Excise Act</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-11"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-12"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-13"><span class="HTitleText2">Brewery Departmental Regulations</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-14"><span class="HTitleText2">Brewery Regulations</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-15"><span class="HTitleText2">New Harmonized Value-added Tax System Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-16"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS TO THE FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT IN RESPECT OF INCOME TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>144 - </span><a href="#h-17"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>146 - </span><a href="#h-18"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">AMENDMENTS RELATING TO EXTERNAL COMPLAINTS BODIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>146 - </span><a href="#h-19"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-20"><span class="HTitleText2">Financial Consumer Agency of Canada Act</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-21"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-22"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>166 - </span><a href="#h-23"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CANADA DISABILITY SAVINGS ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="#h-24"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-25"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-26"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>172 - </span><a href="#h-27"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">CUSTOMS ACT</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-28"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-29"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">OFFICE OF THE SUPERINTENDENT OF FINANCIAL INSTITUTIONS ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>174 - </span><a href="#h-30"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-31"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="#h-32"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">PENSION BENEFITS STANDARDS ACT, 1985</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-33"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-34"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-35"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-36"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

