<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Budget Implementation Act, 2017, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Income Tax Act</cite> and to Related Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-4.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Budget Implementation Act, 2016, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-4.html#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-6"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-5.html#h-7"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Tax Act</cite> (GST/HST Measures)</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-6.html#h-8"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Act</cite>, the <cite class="XRefExternalAct">Excise Act, 2001</cite> and the <cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-6.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-7.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-9.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-9.html#h-12"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="page-9.html#h-13"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="page-9.html#h-14"><span class="HLabel2">DIVISION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Special Import Measures Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="page-9.html#h-15"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-13.html#h-16"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-13.html#h-17"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="page-13.html#h-18"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Public Debt</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>103 - </span><a href="page-13.html#h-19"><span class="HTitleText3">Enactment of <cite class="XRefExternalAct">Borrowing Authority Act</cite></span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-14.html#h-20"><span class="HTitleText3">Amendment to the <cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-14.html#h-21"><span class="HTitleText3">Amendment to the <cite class="XRefExternalAct">Hibernia Development Project Act</cite></span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-14.html#h-22"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Budget Implementation Act, 2016, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-14.html#h-23"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="page-14.html#h-24"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Financial Sector Stability</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="page-14.html#h-25"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-14.html#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-14.html#h-27"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>113 - </span><a href="page-14.html#h-28"><span class="HLabel2">DIVISION 4</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Shared Services Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-15.html#h-29"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Payment to the Canadian Institute for Advanced Research</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-15.html#h-30"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Financial Assistance for Students</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="page-15.html#h-31"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Student Financial Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-15.html#h-32"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Education Savings Act</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-15.html#h-33"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="page-15.html#h-34"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Parliamentary Budget Officer and Board of Internal Economy</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="page-15.html#h-35"><span class="HTitleText3"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="page-15.html#h-36"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-16.html#h-37"><span class="HTitleText4">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>157 - </span><a href="page-17.html#h-38"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="page-17.html#h-39"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-17.html#h-40"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Post Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-18.html#h-41"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-18.html#h-42"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-18.html#h-43"><span class="HTitleText4"><cite class="XRefExternalAct">Garnishment, Attachment and Pension Diversion Act</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-19.html#h-44"><span class="HTitleText4"><cite class="XRefExternalAct">Government Employees Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-19.html#h-45"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-19.html#h-46"><span class="HTitleText4"><cite class="XRefExternalAct">Radiocommunication Act</cite></span></a>
</li>
<li><span class='sectionRange'>173.1 - </span><a href="page-19.html#h-47"><span class="HTitleText4"><cite class="XRefExternalAct">Royal Canadian Mounted Police Act</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-19.html#h-48"><span class="HTitleText4"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-20.html#h-49"><span class="HTitleText4"><cite class="XRefExternalAct">Non-smokers’ Health Act</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-20.html#h-50"><span class="HTitleText4"><cite class="XRefExternalAct">Official Languages Act</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-20.html#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="page-20.html#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-20.html#h-53"><span class="HTitleText4"><cite class="XRefExternalAct">Conflict of Interest Act</cite></span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-20.html#h-54"><span class="HTitleText4"><cite class="XRefExternalAct">Expenditure Restraint Act</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-20.html#h-55"><span class="HTitleText4"><cite class="XRefExternalAct">Language Skills Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>191 - </span><a href="page-20.html#h-56"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="page-20.html#h-57"><span class="HLabel2">DIVISION 8</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>192 - </span><a href="page-20.html#h-58"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-20.html#h-59"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>195 - </span><a href="page-20.html#h-60"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Funding for Home Care Services and Mental Health Services</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="page-21.html#h-61"><span class="HLabel2">DIVISION 10</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Judges Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="page-21.html#h-62"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="page-23.html#h-63"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-23.html#h-64"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>229 - </span><a href="page-23.html#h-65"><span class="HLabel2">DIVISION 11</span> - <span class="HTitleText2">Support for Families: Benefits and Leaves</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>229 - </span><a href="page-23.html#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>229 - </span><a href="page-23.html#h-67"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="page-28.html#h-68"><span class="HTitleText4">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="page-28.html#h-69"><span class="HTitleText4">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>259 - </span><a href="page-29.html#h-70"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>259 - </span><a href="page-29.html#h-71"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="page-30.html#h-72"><span class="HTitleText4">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>269 - </span><a href="page-31.html#h-73"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>270 - </span><a href="page-31.html#h-74"><span class="HLabel2">DIVISION 12</span> - <span class="HTitleText2">Canadian Forces Members and Veterans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>270 - </span><a href="page-31.html#h-75"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Forces Members and Veterans Re-establishment and Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="page-33.html#h-76"><span class="HTitleText3"><cite class="XRefExternalAct">Pension Act</cite></span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="page-33.html#h-77"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Veterans Affairs Act</cite></span></a>
</li>
<li><span class='sectionRange'>292 - </span><a href="page-33.html#h-78"><span class="HTitleText3">Terminology Changes</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="page-34.html#h-79"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="page-34.html#h-80"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>297 - </span><a href="page-34.html#h-81"><span class="HTitleText4"><cite class="XRefExternalAct">Jobs, Growth and Long-term Prosperity Act</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="page-34.html#h-82"><span class="HTitleText4"><cite class="XRefExternalAct">Budget Implementation Act, 2016, No. 1</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>299 - </span><a href="page-34.html#h-83"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>300 - </span><a href="page-34.html#h-84"><span class="HLabel2">DIVISION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="page-35.html#h-85"><span class="HLabel2">DIVISION 14</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>306 - </span><a href="page-35.html#h-86"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>311 - </span><a href="page-35.html#h-87"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>312 - </span><a href="page-35.html#h-88"><span class="HLabel2">DIVISION 15</span> - <span class="HTitleText2">Agreements — Minister of Transport</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>312 - </span><a href="page-35.html#h-89"><span class="HTitleText3"><cite class="XRefExternalAct">Aeronautics Act</cite></span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="page-35.html#h-90"><span class="HTitleText3"><cite class="XRefExternalAct">Navigation Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="page-35.html#h-91"><span class="HTitleText3"><cite class="XRefExternalAct">Railway Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="page-35.html#h-92"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Shipping Act, 2001</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>317 - </span><a href="page-36.html#h-93"><span class="HLabel2">DIVISION 16</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Food and Drugs Act</cite></span></a>
</li>
<li><span class='sectionRange'>318 - </span><a href="page-36.html#h-94"><span class="HLabel2">DIVISION 17</span> - <span class="HTitleText2">Labour and Employment Laws</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>318 - </span><a href="page-36.html#h-95"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>378 - </span><a href="page-44.html#h-96"><span class="HTitleText3"><cite class="XRefExternalAct">Wage Earner Protection Program Act</cite></span></a>
</li>
<li><span class='sectionRange'>382 - </span><a href="page-44.html#h-97"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="page-45.html#h-98"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>394 - </span><a href="page-45.html#h-99"><span class="HTitleText4"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>395 - </span><a href="page-45.html#h-100"><span class="HTitleText4"><cite class="XRefExternalAct">Hazardous Materials Information Review Act</cite></span></a>
</li>
<li><span class='sectionRange'>396 - </span><a href="page-45.html#h-101"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Labour Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="page-45.html#h-102"><span class="HTitleText4"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>398 - </span><a href="page-45.html#h-103"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>402 - </span><a href="page-45.html#h-104"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>403 - </span><a href="page-46.html#h-105"><span class="HLabel2">DIVISION 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Infrastructure Bank Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>403 - </span><a href="page-46.html#h-106"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>404 - </span><a href="page-47.html#h-107"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>404 - </span><a href="page-47.html#h-108"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>405 - </span><a href="page-47.html#h-109"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>406 - </span><a href="page-47.html#h-110"><span class="HTitleText4"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>407 - </span><a href="page-47.html#h-111"><span class="HLabel2">DIVISION 19</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>407 - </span><a href="page-47.html#h-112"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>436 - </span><a href="page-50.html#h-113"><span class="HTitleText3"><cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>436 - </span><a href="page-50.html#h-114"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>438 - </span><a href="page-50.html#h-115"><span class="HTitleText4">Related Amendment to the <cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>439 - </span><a href="page-50.html#h-116"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="page-51.html#h-117"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>442 - </span><a href="page-51.html#h-118"><span class="HLabel2">DIVISION 20</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Invest in Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>442 - </span><a href="page-51.html#h-119"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>443 - </span><a href="page-52.html#h-120"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>444 - </span><a href="page-52.html#h-121"><span class="HTitleText3">Consequential and Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>444 - </span><a href="page-52.html#h-122"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>445 - </span><a href="page-52.html#h-123"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>448 - </span><a href="page-52.html#h-124"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="page-52.html#h-125"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>450 - </span><a href="page-52.html#h-126"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>451 - </span><a href="page-52.html#h-127"><span class="HLabel2">DIVISION 21</span> - <span class="HTitleText2">Modernization of Service Fees</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>451 - </span><a href="page-52.html#h-128"><span class="HTitleText3">Enactment of <cite class="XRefExternalAct">Service Fees Act</cite></span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="page-53.html#h-129"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>453 - </span><a href="page-53.html#h-130"><span class="HTitleText3">Related Amendment to the <cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>454 - </span><a href="page-53.html#h-131"><span class="HTitleText3">Terminology</span></a>
</li>
<li><span class='sectionRange'>455 - </span><a href="page-53.html#h-132"><span class="HTitleText3">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>456 - </span><a href="page-53.html#h-133"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>457 - </span><a href="page-53.html#h-134"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-54.html#h-135"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-55.html#h-136"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

