<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2008</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS RELATED TO INCOME TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-4"><span class="HTitleText2">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-5"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-6"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-7"><span class="HTitleText2">Conditional Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-8"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF EXCISE DUTY ON TOBACCO PRODUCTS AND ALCOHOL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-9"><span class="HTitleText2">Excise Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-10"><span class="HTitleText2">Excise Act, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="#h-11"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-12"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="#h-13"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="#h-14"><span class="HTitleText3">Customs Tariff</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="#h-15"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF THE GOODS AND SERVICES TAX AND HARMONIZED SALES TAX (GST/HST)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-16"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="#h-17"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">CANADA MILLENNIUM SCHOLARSHIP FOUNDATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>94 - </span><a href="#h-18"><span class="HTitleText2">Dissolution of the Foundation</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-19"><span class="HTitleText2">Amendments to the Budget Implementation Act, 1998</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-20"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="#h-21"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-22"><span class="HTitleText3">Privacy Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>100 - </span><a href="#h-23"><span class="HTitleText2">Coming Into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-24"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">FEDERAL FINANCIAL ASSISTANCE FOR STUDENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-25"><span class="HTitleText2">Amendments to the Canada Student Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-26"><span class="HTitleText2">Amendments to the Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-27"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>116 - </span><a href="#h-28"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">IMMIGRATION AND REFUGEE PROTECTION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="#h-29"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-30"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="#h-31"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">EMPLOYMENT INSURANCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="#h-32"><span class="HTitleText2">Canada Employment Insurance Financing Board Act</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-33"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-34"><span class="HTitleText2">Amendments to the Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-35"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="#h-36"><span class="HTitleText3">Department of Human Resources and Skills Development Act</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-37"><span class="HTitleText3">Financial Administration Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>135 - </span><a href="#h-38"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="#h-39"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">PAYMENTS TO PROVINCES AND TERRITORIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-40"><span class="HTitleText2">Police Officers Recruitment Fund</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-41"><span class="HTitleText2">Public Transit Capital Trust 2008</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-42"><span class="HTitleText2">Payment to Saskatchewan for Carbon Capture and Storage</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-43"><span class="HTitleText2">Payment to Nova Scotia for Carbon Storage</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-44"><span class="HTitleText2">Canada Social Transfer Transition Protection Payment to Saskatchewan</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-45"><span class="HTitleText2">Canada Social Transfer Transition Protection Payment to Nunavut</span></a>
</li></ul>
</li><li><span class='sectionRange'>142 - </span><a href="#h-46"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">PAYMENTS TO CERTAIN ENTITIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>142 - </span><a href="#h-47"><span class="HTitleText2">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-48"><span class="HTitleText2">Mental Health Commission of Canada</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-49"><span class="HTitleText2">The Gairdner Foundation</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-50"><span class="HTitleText2">University of Calgary</span></a>
</li></ul>
</li><li><span class='sectionRange'>146 - </span><a href="#h-51"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">VARIOUS AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>146 - </span><a href="#h-52"><span class="HTitleText2">Bank of Canada Act</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-53"><span class="HTitleText2">Budget Implementation Act, 2006</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-54"><span class="HTitleText2">Canadian Forces Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-55"><span class="HTitleText2">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-56"><span class="HTitleText2">Donkin Coal Block Development Opportunity Act</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-57"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-58"><span class="HTitleText2">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-59"><span class="HTitleText2">Interest Act</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-60"><span class="HTitleText2">Old Age Security Act</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-61"><span class="HTitleText2">Public Service Superannuation act</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-62"><span class="HTitleText2">Royal Canadian Mounted Police Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-63"><span class="HTitleText2">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-64"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

