<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Port of Montreal Operations Act, 2021</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Port of Montreal Operations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Extension of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Mediator-Arbitrator</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-6"><span class="HTitleText1">New Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-7"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-8"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

