<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Species at Risk Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-4"><span class="HTitleText1">PURPOSES</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-5"><span class="HTitleText1">CANADIAN ENDANGERED SPECIES CONSERVATION COUNCIL</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-6"><span class="HTitleText1">ADMINISTRATION OF ACT</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="page-2.html#h-7"><span class="HTitleText1">STEWARDSHIP ACTION PLAN</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-8"><span class="HTitleText1">STEWARDSHIP</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-9"><span class="HTitleText1">WILDLIFE SPECIES LISTING PROCESS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Committee on the Status of Endangered Wildlife in Canada</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Reviews and Reports</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-12"><span class="HTitleText2">List of Wildlife Species at Risk</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="page-4.html#h-13"><span class="HTitleText1">MEASURES TO PROTECT LISTED WILDLIFE SPECIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="page-4.html#h-14"><span class="HTitleText2">General Prohibitions</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-15"><span class="HTitleText2">Recovery of Endangered, Threatened and Extirpated Species</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-4.html#h-16"><span class="HTitleText3">Recovery Strategy</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-17"><span class="HTitleText3">Action Plan</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="page-6.html#h-18"><span class="HTitleText2">Protection of Critical Habitat</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-7.html#h-19"><span class="HTitleText2">Management of Species of Special Concern</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-7.html#h-20"><span class="HTitleText2">Agreements and Permits</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-8.html#h-21"><span class="HTitleText2">Project Review</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-8.html#h-22"><span class="HTitleText2">Emergency Orders</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-8.html#h-23"><span class="HTitleText2">Exceptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="page-9.html#h-24"><span class="HTitleText1">ENFORCEMENT MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="page-9.html#h-25"><span class="HTitleText2">Enforcement Officers</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-9.html#h-26"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-9.html#h-27"><span class="HTitleText2">Disposition of Things Seized</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-9.html#h-28"><span class="HTitleText2">Assistance to Enforcement Officers</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-9.html#h-29"><span class="HTitleText2">Investigations</span></a>
</li></ul>
</li><li><span class='sectionRange'>97 - </span><a href="page-10.html#h-30"><span class="HTitleText1">OFFENCES AND PUNISHMENT</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-11.html#h-31"><span class="HTitleText1">ALTERNATIVE MEASURES</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-12.html#h-32"><span class="HTitleText1">PUBLIC REGISTRY</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-12.html#h-33"><span class="HTitleText1">FEES AND CHARGES</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-12.html#h-34"><span class="HTitleText1">REPORTS AND REVIEW OF ACT</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-13.html#h-35"><span class="HTitleText1">ASSESSMENT OF WILDLIFE SPECIES MENTIONED IN THE SCHEDULES</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-13.html#h-36"><span class="HTitleText1">RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>134 - </span><a href="page-13.html#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Wildlife Act</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-13.html#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Environmental Assessment Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-13.html#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Migratory Birds Convention Act, 1994</cite></span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-13.html#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Wild Animal and Plant Protection and Regulation of International and Interprovincial Trade Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>141.1 - </span><a href="page-13.html#h-41"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-14.html#h-42"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-15.html#h-43"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - LIST OF WILDLIFE SPECIES AT RISK</span></a>
</li>
<li><a href="page-16.html#h-44"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-17.html#h-45"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - SPECIAL CONCERN</span></a>
</li></ul>
</li></ul>

</nav>

