<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to promote the efficiency and adaptability of the Canadian economy by regulating certain activities that discourage reliance on electronic means of carrying out commercial activities, and to amend the Canadian Radio-television and Telecommunications Commission Act, the Competition Act, the Personal Information Protection and Electronic Documents Act and the Telecommunications Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">CONFLICT OF PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">APPLICATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">REQUIREMENTS AND PROHIBITIONS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">ADMINISTRATIVE MONETARY PENALTIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText2">Designation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Preservation Demand</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Notice to Produce</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Warrants</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Undertakings</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText2">Notices of Violation</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText2">Determination of Responsibility</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-16"><span class="HTitleText2">Appeal to Federal Court of Appeal</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-17"><span class="HTitleText2">Recovery of Penalties and Other Amounts</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-18"><span class="HTitleText2">Rules about Violations</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-19"><span class="HTitleText2">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-20"><span class="HTitleText1">INJUNCTION</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-21"><span class="HTitleText1">OFFENCES</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-22"><span class="HTitleText1">PRIVATE RIGHT OF ACTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-23"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-24"><span class="HTitleText2">Hearing</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-25"><span class="HTitleText2">Rules about Contraventions and Reviewable Conduct</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-26"><span class="HTitleText1">CONSULTATION AND DISCLOSURE OF INFORMATION</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-27"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-28"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-29"><span class="HTitleText1">AMENDMENT TO THIS ACT</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-30"><span class="HTitleText1">AMENDMENT TO THE <cite class="XRefExternalAct">CANADIAN RADIO-TELEVISION AND TELECOMMUNICATIONS COMMISSION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-31"><span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">COMPETITION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-32"><span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">PERSONAL INFORMATION PROTECTION AND ELECTRONIC DOCUMENTS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-33"><span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">TELECOMMUNICATIONS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-34"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

