<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend certain Acts and Regulations in relation to firearms</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Firearms Act</cite>, the <cite class="XRefExternalAct">Criminal Code</cite> and the <cite class="XRefExternalRegulation">Regulations Prescribing Certain Firearms and Other Weapons, Components and Parts of Weapons, Accessories, Cartridge Magazines, Ammunition and Projectiles as Prohibited, Restricted or Non-Restricted</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2"><cite class="XRefExternalAct">Firearms Act</cite></span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalRegulation">Regulations Prescribing Certain Firearms and Other Weapons, Components and Parts of Weapons, Accessories, Cartridge Magazines, Ammunition and Projectiles as Prohibited, Restricted or Non-Restricted</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-5"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-6"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Ending the Long-gun Registry Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-7"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-8"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

