<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Ending the Captivity of Whales and Dolphins Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Fisheries Act</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">Wild Animal and Plant Protection and Regulation of International and Interprovincial Trade Act</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Related provision</span></a>
</li></ul>
</li></ul>

</nav>

