<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Budget Implementation Act, 2016, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Income Tax Act</cite> and to Related Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-10.html#h-4"><span class="HTitleText2">Related Amendments to Other Acts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="page-10.html#h-5"><span class="HTitleText3"><cite class="XRefExternalAct">Children’s Special Allowances Act</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-10.html#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Universal Child Care Benefit Act</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-10.html#h-7"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="page-10.html#h-8"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-11.html#h-9"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="page-12.html#h-10"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Tax Act</cite> (GST/HST Measures)</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-13.html#h-11"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Tax Act</cite> (Excise Measures), the <cite class="XRefExternalAct">Excise Act, 2001</cite> and Other Related Texts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="page-13.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-14.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-14.html#h-14"><span class="HTitleText2"><cite class="XRefExternalRegulation">Regulations Respecting Excise Licences and Registrations</cite></span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-14.html#h-15"><span class="HTitleText2"><cite class="XRefExternalRegulation">Stamping and Marking of Tobacco Products Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="page-15.html#h-16"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="page-15.html#h-17"><span class="HLabel2">DIVISION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Federal Balanced Budget Act</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-15.html#h-18"><span class="HLabel2">DIVISION 2</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Forces Members and Veterans Re-establishment and Compensation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 - </span><a href="page-15.html#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Amendments to the Act</cite></span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-16.html#h-20"><span class="HTitleText3">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-16.html#h-21"><span class="HTitleText4">Earnings Loss Benefit</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-16.html#h-22"><span class="HTitleText4">Disability Award and Death Benefit</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="page-16.html#h-23"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="page-16.html#h-24"><span class="HTitleText4"><cite class="XRefExternalAct">Children of Deceased Veterans Education Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-16.html#h-25"><span class="HTitleText4"><cite class="XRefExternalAct">Pension Act</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-17.html#h-26"><span class="HTitleText4"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>115 - </span><a href="page-17.html#h-27"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-17.html#h-28"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="page-17.html#h-29"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Financial Institutions (Sunset Provisions)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="page-17.html#h-30"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-17.html#h-31"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-17.html#h-32"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-17.html#h-33"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>123 - </span><a href="page-18.html#h-34"><span class="HLabel2">DIVISION 4</span></span> - <span class="HTitleText2">Amendments to the <cite class="XRefExternalAct">Bank Act</cite> (Federal Credit Unions)</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-18.html#h-35"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Bank Recapitalization Regime (Bail-in)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="page-18.html#h-36"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-25.html#h-37"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-25.html#h-38"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="page-25.html#h-39"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-25.html#h-40"><span class="HTitleText4"><cite class="XRefExternalAct">Winding-up and Restructuring Act</cite></span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="page-26.html#h-41"><span class="HTitleText4"><cite class="XRefExternalAct">Payment Clearing and Settlement Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="page-26.html#h-42"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>169 - </span><a href="page-26.html#h-43"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Chief Executive Officer of the Canada Deposit Insurance Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>169 - </span><a href="page-26.html#h-44"><span class="HTitleText3"><cite class="XRefExternalAct">Office of the Superintendent of Financial Institutions Act</cite></span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-26.html#h-45"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Payments Act</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-26.html#h-46"><span class="HTitleText3"><cite class="XRefExternalAct">National Housing Act</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-26.html#h-47"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-26.html#h-48"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-26.html#h-49"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="page-26.html#h-50"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-26.html#h-51"><span class="HTitleText3"><cite class="XRefExternalAct">Payment Clearing and Settlement Act</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-26.html#h-52"><span class="HTitleText3"><cite class="XRefExternalAct">Protection of Residential Mortgage or Hypothecary Insurance Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>180 - </span><a href="page-26.html#h-53"><span class="HLabel2">DIVISION 7</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-27.html#h-54"><span class="HLabel2">DIVISION 8</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>182 - </span><a href="page-27.html#h-55"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-27.html#h-56"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>188 - </span><a href="page-27.html#h-57"><span class="HLabel2">DIVISION 9</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Old Age Security Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>188 - </span><a href="page-27.html#h-58"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-27.html#h-59"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="page-27.html#h-60"><span class="HLabel2">DIVISION 10</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Special Import Measures Act</cite></span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="page-29.html#h-61"><span class="HLabel2">DIVISION 11</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Pension Benefits Standards Act, 1985</cite></span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="page-29.html#h-62"><span class="HLabel2">DIVISION 12</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>207 - </span><a href="page-29.html#h-63"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="page-31.html#h-64"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-31.html#h-65"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-31.html#h-66"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Economic Action Plan 2015 Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-32.html#h-67"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>232 - </span><a href="page-32.html#h-68"><span class="HLabel2">DIVISION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Marine Act</cite></span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-32.html#h-69"><span class="HLabel2">DIVISION 14</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Jobs, Growth and Long-term Prosperity Act</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="page-32.html#h-70"><span class="HLabel2">DIVISION 15</span> - <span class="HTitleText2">Canada Foundation for Sustainable Development Technology</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>237 - </span><a href="page-32.html#h-71"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Foundation for Sustainable Development Technology Act</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="page-32.html#h-72"><span class="HTitleText3"><cite class="XRefExternalAct">Budget Implementation Act, 2007</cite></span></a>
</li></ul>
</li></ul>
</li><li><a href="page-33.html#h-73"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-34.html#h-74"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

