<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Budget Implementation Act, 2019, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Income Tax Act</cite> and Other Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-9.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-9.html#h-5"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-9.html#h-6"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="page-9.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Cultural Property Export and Import Act</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-9.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-10.html#h-9"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="page-14.html#h-10"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">GST/HST Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="page-14.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-15.html#h-12"><span class="HTitleText2"><cite class="XRefExternalRegulation">Streamlined Accounting (GST/HST) Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>81 - </span><a href="page-15.html#h-13"><span class="HLabel1">PART 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-16.html#h-14"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-16.html#h-15"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Financial Sector</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-16.html#h-16"><span class="HLabel3">SUBDIVISION A</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-16.html#h-17"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-16.html#h-18"><span class="HTitleText4"><cite class="XRefExternalAct">An Act to amend certain Acts in relation to financial institutions</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-17.html#h-19"><span class="HTitleText4">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>93 - </span><a href="page-17.html#h-20"><span class="HLabel3">SUBDIVISION B</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Canadian Payments Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>93 - </span><a href="page-17.html#h-21"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-17.html#h-22"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="page-17.html#h-23"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Strengthening Anti-Money Laundering and Anti-Terrorist Financing Regime</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-17.html#h-24"><span class="HLabel3">SUBDIVISION A</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Canada Business Corporations Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-17.html#h-25"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-18.html#h-26"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="page-18.html#h-27"><span class="HLabel3">SUBDIVISION B</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-18.html#h-28"><span class="HLabel3">SUBDIVISION C</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-18.html#h-29"><span class="HLabel3">SUBDIVISION D</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Seized Property Management Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="page-18.html#h-30"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-20.html#h-31"><span class="HTitleText4">Consequential Amendments</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="page-20.html#h-32"><span class="HTitleText5"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-20.html#h-33"><span class="HTitleText5"><cite class="XRefExternalAct">Crimes Against Humanity and War Crimes Act</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-20.html#h-34"><span class="HTitleText5"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="page-20.html#h-35"><span class="HLabel2">DIVISION 3</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Equity Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="page-20.html#h-36"><span class="HTitleText3">Amendment to the Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="page-20.html#h-37"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="page-20.html#h-38"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Payments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="page-20.html#h-39"><span class="HTitleText3">Climate Action Support</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-21.html#h-40"><span class="HTitleText3">Payment in Relation to Infrastructure</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-21.html#h-41"><span class="HTitleText3">Federation of Canadian Municipalities</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-21.html#h-42"><span class="HTitleText3">Shock Trauma Air Rescue Service</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="page-21.html#h-43"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Enhancing Retirement Security</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="page-21.html#h-44"><span class="HTitleText3"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-22.html#h-45"><span class="HTitleText3"><cite class="XRefExternalAct">Companies’ Creditors Arrangement Act</cite></span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-22.html#h-46"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Business Corporations Act</cite></span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-23.html#h-47"><span class="HTitleText3"><cite class="XRefExternalAct">Pension Benefits Standards Act, 1985</cite></span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-23.html#h-48"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-23.html#h-49"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-24.html#h-50"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="page-24.html#h-51"><span class="HLabel2">DIVISION 6</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="page-24.html#h-52"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-24.html#h-53"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>156 - </span><a href="page-24.html#h-54"><span class="HLabel2">DIVISION 7</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Old Age Security Act</cite></span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-24.html#h-55"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">Non-permitted Surplus</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="page-24.html#h-56"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Forces Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-24.html#h-57"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-24.html#h-58"><span class="HTitleText3"><cite class="XRefExternalAct">Royal Canadian Mounted Police Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>160 - </span><a href="page-24.html#h-59"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Regulatory Modernization</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>160 - </span><a href="page-24.html#h-60"><span class="HLabel3">SUBDIVISION A</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-24.html#h-61"><span class="HLabel3">SUBDIVISION B</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Electricity and Gas Inspection Act</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-25.html#h-62"><span class="HLabel3">SUBDIVISION C</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Food and Drugs Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="page-25.html#h-63"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-28.html#h-64"><span class="HTitleText4">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-28.html#h-65"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="page-28.html#h-66"><span class="HLabel3">SUBDIVISION D</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Importation of Intoxicating Liquors Act</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-28.html#h-67"><span class="HLabel3">SUBDIVISION E</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Precious Metals Marking Act</cite></span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-29.html#h-68"><span class="HLabel3">SUBDIVISION F</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Textile Labelling Act</cite></span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-29.html#h-69"><span class="HLabel3">SUBDIVISION G</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Weights and Measures Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>192 - </span><a href="page-29.html#h-70"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-29.html#h-71"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>198 - </span><a href="page-29.html#h-72"><span class="HLabel3">SUBDIVISION H</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Hazardous Materials Information Review Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>198 - </span><a href="page-29.html#h-73"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="page-31.html#h-74"><span class="HTitleText4">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="page-31.html#h-75"><span class="HTitleText4">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="page-31.html#h-76"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="page-31.html#h-77"><span class="HLabel3">SUBDIVISION I</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Canada Transportation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="page-31.html#h-78"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="page-32.html#h-79"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>217 - </span><a href="page-32.html#h-80"><span class="HLabel3">SUBDIVISION J</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Pest Control Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="page-32.html#h-81"><span class="HLabel3">SUBDIVISION K</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Quarantine Act</cite></span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="page-32.html#h-82"><span class="HLabel3">SUBDIVISION L</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Human Pathogens and Toxins Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>222 - </span><a href="page-32.html#h-83"><span class="HLabel2">DIVISION 10</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Royal Canadian Mounted Police Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>222 - </span><a href="page-32.html#h-84"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="page-33.html#h-85"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="page-33.html#h-86"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>225 - </span><a href="page-33.html#h-87"><span class="HLabel2">DIVISION 11</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Pilotage Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>225 - </span><a href="page-33.html#h-88"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="page-40.html#h-89"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="page-40.html#h-90"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>266 - </span><a href="page-40.html#h-91"><span class="HTitleText4"><cite class="XRefExternalAct">Arctic Waters Pollution Prevention Act</cite></span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="page-40.html#h-92"><span class="HTitleText4"><cite class="XRefExternalAct">Transportation Appeal Tribunal of Canada Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>268 - </span><a href="page-40.html#h-93"><span class="HTitleText3">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="page-40.html#h-94"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>270 - </span><a href="page-40.html#h-95"><span class="HLabel2">DIVISION 12</span> - <span class="HTitleText2">Security Screening Services Commercialization</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>270 - </span><a href="page-40.html#h-96"><span class="HTitleText3"><cite class="XRefExternalAct">Security Screening Services Commercialization Act</cite></span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="page-41.html#h-97"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>271 - </span><a href="page-41.html#h-98"><span class="HTitleText4"><cite class="XRefExternalAct">Aeronautics Act</cite></span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="page-41.html#h-99"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>277 - </span><a href="page-41.html#h-100"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Transportation Act</cite></span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="page-41.html#h-101"><span class="HTitleText4"><cite class="XRefExternalAct">Secure Air Travel Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>279 - </span><a href="page-41.html#h-102"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>280 - </span><a href="page-41.html#h-103"><span class="HLabel2">DIVISION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Aviation Industry Indemnity Act</cite></span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="page-42.html#h-104"><span class="HLabel2">DIVISION 14</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Transportation Appeal Tribunal of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="page-42.html#h-105"><span class="HLabel2">DIVISION 15</span> - <span class="HTitleText2">Immigration and Citizenship Representation or Advice</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>292 - </span><a href="page-42.html#h-106"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="page-43.html#h-107"><span class="HTitleText3">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>293 - </span><a href="page-43.html#h-108"><span class="HTitleText4"><cite class="XRefExternalAct">Citizenship Act</cite></span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="page-43.html#h-109"><span class="HTitleText4"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>298 - </span><a href="page-43.html#h-110"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>298 - </span><a href="page-43.html#h-111"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="page-43.html#h-112"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>300 - </span><a href="page-43.html#h-113"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>301 - </span><a href="page-44.html#h-114"><span class="HLabel2">DIVISION 16</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>301 - </span><a href="page-44.html#h-115"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="page-45.html#h-116"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>310 - </span><a href="page-45.html#h-117"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>311 - </span><a href="page-45.html#h-118"><span class="HLabel2">DIVISION 17</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="page-45.html#h-119"><span class="HLabel2">DIVISION 18</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">National Housing Act</cite></span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="page-45.html#h-120"><span class="HLabel2">DIVISION 19</span> - <span class="HTitleText2"><cite class="XRefExternalAct">National Housing Strategy Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>313 - </span><a href="page-45.html#h-121"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="page-46.html#h-122"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>315 - </span><a href="page-46.html#h-123"><span class="HLabel2">DIVISION 20</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Poverty Reduction Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>315 - </span><a href="page-46.html#h-124"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="page-46.html#h-125"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>317 - </span><a href="page-46.html#h-126"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>318 - </span><a href="page-47.html#h-127"><span class="HLabel2">DIVISION 21</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Veterans Well-being Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>318 - </span><a href="page-47.html#h-128"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="page-47.html#h-129"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>323 - </span><a href="page-47.html#h-130"><span class="HLabel2">DIVISION 22</span> - <span class="HTitleText2">Student Loans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>323 - </span><a href="page-47.html#h-131"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Student Loans Act</cite></span></a>
</li>
<li><span class='sectionRange'>325 - </span><a href="page-47.html#h-132"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Student Financial Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>327 - </span><a href="page-47.html#h-133"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>328 - </span><a href="page-47.html#h-134"><span class="HLabel2">DIVISION 23</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada National Parks Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>328 - </span><a href="page-47.html#h-135"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>333 - </span><a href="page-49.html#h-136"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>334 - </span><a href="page-49.html#h-137"><span class="HLabel2">DIVISION 24</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Parks Canada Agency Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>334 - </span><a href="page-49.html#h-138"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="page-49.html#h-139"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>336 - </span><a href="page-49.html#h-140"><span class="HLabel2">DIVISION 25</span> - <span class="HTitleText2">Various Measures Related to Indigenous Matters</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>336 - </span><a href="page-49.html#h-141"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3"><cite class="XRefExternalAct">Department of Indigenous Services Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>336 - </span><a href="page-49.html#h-142"><span class="HTitleText4">Enactment of Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>336.1 - </span><a href="page-50.html#h-143"><span class="HTitleText3">Coming into Force</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="page-50.html#h-144"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3"><cite class="XRefExternalAct">Department of Crown-Indigenous Relations and Northern Affairs Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>337 - </span><a href="page-50.html#h-145"><span class="HTitleText4">Enactment of Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>337.1 - </span><a href="page-51.html#h-146"><span class="HTitleText3">Coming into Force</span></a>
</li>
<li><span class='sectionRange'>338 - </span><a href="page-51.html#h-147"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Transitional Provisions, Consequential Amendments, Coordinating Amendments and Repeal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>338 - </span><a href="page-51.html#h-148"><span class="HTitleText4">Transitional Provisions</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>338 - </span><a href="page-51.html#h-149"><span class="HTitleText5">Indigenous Services</span></a>
</li>
<li><span class='sectionRange'>341 - </span><a href="page-51.html#h-150"><span class="HTitleText5">Crown-Indigenous Relations and Northern Affairs</span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="page-51.html#h-151"><span class="HTitleText5">References and Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>347 - </span><a href="page-51.html#h-152"><span class="HTitleText4">Consequential Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>347 - </span><a href="page-51.html#h-153"><span class="HTitleText5"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>350 - </span><a href="page-51.html#h-154"><span class="HTitleText5"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>357 - </span><a href="page-52.html#h-155"><span class="HTitleText5"><cite class="XRefExternalAct">Indian Act</cite></span></a>
</li>
<li><span class='sectionRange'>359 - </span><a href="page-52.html#h-156"><span class="HTitleText5"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>362 - </span><a href="page-52.html#h-157"><span class="HTitleText5"><cite class="XRefExternalAct">Salaries Act</cite></span></a>
</li>
<li><span class='sectionRange'>363 - </span><a href="page-52.html#h-158"><span class="HTitleText5"><cite class="XRefExternalAct">Dominion Water Power Act</cite></span></a>
</li>
<li><span class='sectionRange'>364 - </span><a href="page-52.html#h-159"><span class="HTitleText5"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="page-52.html#h-160"><span class="HTitleText5"><cite class="XRefExternalAct">Yukon First Nations Self-Government Act</cite></span></a>
</li>
<li><span class='sectionRange'>367 - </span><a href="page-52.html#h-161"><span class="HTitleText5"><cite class="XRefExternalAct">Federal Real Property and Federal Immovables Act</cite></span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="page-52.html#h-162"><span class="HTitleText5"><cite class="XRefExternalAct">First Nations Financial Transparency Act</cite></span></a>
</li>
<li><span class='sectionRange'>370 - </span><a href="page-53.html#h-163"><span class="HTitleText5"><cite class="XRefExternalAct">Indian Act Amendment and Replacement Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>371 - </span><a href="page-53.html#h-164"><span class="HTitleText4">Terminology</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="page-54.html#h-165"><span class="HTitleText4">Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>382 - </span><a href="page-55.html#h-166"><span class="HTitleText4">Repeal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>383 - </span><a href="page-55.html#h-167"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>384 - </span><a href="page-55.html#h-168"><span class="HLabel3">SUBDIVISION D</span> - <span class="HTitleText3">Various Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>384 - </span><a href="page-55.html#h-169"><span class="HTitleText4"><cite class="XRefExternalAct">First Nations Land Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>385 - </span><a href="page-55.html#h-170"><span class="HTitleText4"><cite class="XRefExternalAct">First Nations Oil and Gas and Moneys Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>386 - </span><a href="page-55.html#h-171"><span class="HTitleText4"><cite class="XRefExternalAct">Addition of Lands to Reserves and Reserve Creation Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>387 - </span><a href="page-55.html#h-172"><span class="HLabel2">DIVISION 26</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Federal Prompt Payment for Construction Work Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>387 - </span><a href="page-55.html#h-173"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>388 - </span><a href="page-56.html#h-174"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-57.html#h-175"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-58.html#h-176"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-59.html#h-177"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-60.html#h-178"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li></ul>
</li></ul>

</nav>

