<h2 class="Subheading">Naming or Substitution of a Beneficiary</h2>
<p>For the Supplementary Death Benefit Part II of the Public Service Superannuation Act.</p>


<p>INSTRUCTIONS</p>
<ul>
	<li>Complete all unshaded areas. Please print</li>
	<li>Forward copies 1 and 2 to the following address: </li>
	<li>Supply and Services Canada, Superannuation Branch, P.O. Box  5010 Moncton , N.B. E1C 8Z5</li>
	<li>Copy 3 should be sent to your personnel office.  If you are employed in the public service.</li>
	<li>The superannuation Branch will acknowledge receipt of your “Naming or Substitution of a Beneficiary”</li>
	<li>You must be a participant in the SDB Plan to complete this form: otherwise the form will be invalid. You may cancel or change your beneficiary at any time while a participant, whether employed or retired.</li>
	<li>A witness must sign the form.</li>
</ul>

<p>Information required:</p>
<ul>
	<li>Social Insurance Number</li>
	<li>Pension number</li>
	<li>Date of birth: (day,month,year)</li>
	<li>Sex</li>
	<li>Participant’s family name</li>
	<li>Given name</li>
	<li>Marital status – single, married, widow(er), other</li>
	<li>Mailing address – (street, city, province/country, postal code)</li>
</ul>

<h3>Important</h3>

<p>You may designate as your beneficiary</p>
<ul>
	<li>Any person over 18 years of age on the date of naming:</li>
	<li>Any charitable or benevolent organization or institution (print name of institution):</li>
	<li>Any religious or educational organization:</li>
	<li>Your estate (print “Estate” in the space for beneficiary)</li>
</ul>

<p>An ineligible or ambiguous designation will render this form invalid.</p>

<p>I hereby appoint the following beneficiary and revoke any previous designation:</p>
<ul>
	<li>Beneficiary’s family name</li>
	<li>given name</li>
	<li>Relationship to you</li>
	<li>Address (street, city, province/country, postal code).</li>
</ul>

<p>Note: your named beneficiary may become entitled to certain lump sum benefits which are payable under Part I of the Public Service Superannuation Act. A naming takes effect the date it is completed if this form is received by the Superannuation Branch before your death.</p>

<p>Dated at (city), province of,_____This _____day of (month), (year).</p>
<p>Signature - Participant</p>
<p>Signature - Witness (other than beneficiary)</p>