<h2 class="ScheduleLabel">Family Support Orders and Agreements Garnishment Regulations</h2>
<h4>SOR/88-181</h4>
<p><a href="https://laws-lois.justice.gc.ca/eng/acts/F-1.4/"> FAMILY ORDERS AND AGREEMENTS ENFORCEMENT ASSISTANCE ACT</a></p>
<p>Registration 1988-03-17</p>
<p>Regulations Respecting the Garnishment of Federal Moneys to Satisfy Support Orders and Support Provisions</p>
<p>P.C. 1988-473 1988-03-17</p>
<p>Her Excellency the Governor General in Council, on the recommendation of the Minister of Justice, pursuant to section 61 
of the <a href="https://laws-lois.justice.gc.ca/eng/acts/F-1.4/">Family Orders and Agreements Enforcement Assistance Act*</a>
, is pleased hereby to make the annexed <a href="https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-181/"> Regulations respecting the garnishment of federal moneys to satisfy support orders and support provisions</a>
, effective on the day Part II of the said Act comes into force.</p>
<p>*S.C. 1986, c. 5</p>
<h1 class="Section">Short Title</h1>
<p><b>1</b> These Regulations may be cited as the <a href="https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-181/">Family Support Orders and Agreements Garnishment Regulations</a></p>

<h1 class="Section">Interpretation</h1>
<p><b>2</b> In these Regulations, <b>Act</b> means the <a href="https://laws-lois.justice.gc.ca/eng/acts/F-1.4/">Family Orders and Agreements Enforcement Assistance Act</a>. (Loi)</p>
<h2 class="Section">Designation for the Purposes of the Definition “Garnishable Moneys”</h2>
<ul><b>3</b> The following Acts and their provisions and programs are designated for the purposes of the definition <b>garnishable moneys</b> in subsection 23(1) of the Act:
	<li><b>(a)</b> sections 164 and 216 of the Income Tax Act as they relate to the personal return of income of the taxpayer for a particular taxation year, excluding subsection 164(1.4) of that Act when it applies with respect to an amount payable pursuant to provincial income tax legislation that specifically excludes that amount from garnishment for the purposes of the Act;</li>
	<li><b>(a.1)</b> section 253 of the <a href="https://laws-lois.justice.gc.ca/eng/acts/E-15/">Excise Tax Act</a> as it relates to the rebate payable to employees and partners;</li>
	<li><b>(b.1)</b> section 7 of the <a href="https://laws-lois.justice.gc.ca/eng/acts/H-5.7/"> Department of Employment and Social Development Act</a> as it relates to grants and contributions payable under the Skills Link program, the Apprenticeship Incentive Grant program or the Apprenticeship Completion Grant program;</b>
	<li><b>(b.2)</b> the <a href="https://laws-lois.justice.gc.ca/eng/acts/W-0.8/">Wage Earner Protection Program Act</a>, excluding the provisions relating to fees or expenses paid to a trustee or receiver under subsection 22(2) of that Act;
	<li><b>(c)</b> the <a href="https://laws-lois.justice.gc.ca/eng/acts/E-5.6/">Employment Insurance Act</a>, excluding the provisions relating to benefits paid on behalf of a beneficiary to a province or municipality;</li>
	<li><b>(d)</b> the <a href="https://laws-lois.justice.gc.ca/eng/acts/C-8/"> Canada Pension Plan</a>, excluding the provisions relating to a benefit paid to a child of a disabled contributor under paragraph 44(1)(e) of that Act or to an orphan of a deceased contributor under paragraph 44(1)(f) of that Act and the provisions relating to amounts deducted from a benefit and paid to the government of a province in accordance with subsection 65(2) of that Act;</li>
	<li><b>(e)</b> sections 3, 11, 19 and 21 of the <a href="https://laws-lois.justice.gc.ca/eng/acts/O-9/">Old Age Security Act</a>, excluding the provisions relating to amounts deducted from a benefit and paid to the government of a province in accordance with subsection 36(2) of that Act; and</li>
	<li><b>(f)</b> section 7 of the <a href="https://laws-lois.justice.gc.ca/eng/acts/S-11.5">Department of Social Development Act</a> as it relates to grants and contributions payable under the Opportunities Fund for Persons with Disabilities program.</li>
	<li><b>(g)</b> [Repealed, SOR/2011-189, s. 1]</li>
	<li>SOR/89-278, s. 1 SOR/89-417, s. 1 SOR/91-300, s. 1 SOR/93-414, s. 1 SOR/94-725, s. 1 SOR/94-759, s. 1 SOR/96-11, s. 1 SOR/97-179, s. 1 SOR/2002-278, s. 3 SOR/2006-296, s. 1 SOR/2008-74, s. 1 SOR/2011-189, s. 1 2013, c. 40, s. 236 SOR/2014-101, s. 1</li>
	</ul>
	
<text><a href="https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-181/section-3-20140502.html">Previous Version</a></text>

<h1 class="Section">Order of Priority for Garnishment</h1>
<p><b>4 (1)</b> Where two or more garnishable moneys become payable under any Acts, or any provisions thereof or programs thereunder, referred to in any provisions of section 3 on the same day to the same judgment debtor, those moneys shall be garnisheed according to the order in which those provisions are set out in section 3.</p>
<p><b>(2)</b> Subsection (1) does not apply to moneys that are already being garnisheed when additional garnishable moneys become payable to the judgment debtor and the moneys that are already being garnisheed shall continue to be garnisheed in priority to any other garnishable moneys.</p>
<p>SOR/89-417, s. 2</p>

<h1 class="Section">Application Form</h1>
<p><b>5</b> For the purpose of paragraph 28(c) of the Act, an application to garnishee shall be in the form set out in Schedule 1.</p>
<p>SOR/97-179, s. 2 SOR/2013-104, s. 3 SOR/2014-101, s. 2</p>
<p><a href="https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-181/section-5-20130607.html">Previous Version</a></p>
	
<h1 class="Section">Period During Which Her Majesty Is Not Bound</h1>
<p><b>6 (1)</b> Subject to subsection (2), for the purposes of section 29 of the Act, the prescribed period during which a garnishee summons does not bind Her Majesty is the period beginning on the day of service of the documents referred to in section 28 of the Act and ending 35 days after that day.</p>
<p><b>(2)</b> [Repealed, SOR/2014-101, s. 3]</p>
<p>SOR/89-278, s. 2 SOR/2006-296, s. 2 SOR/2014-101, s. 3</p>
<text><a href="https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-181/section-6-20061123.html">Previous Version</a></text>

<h1 class="Section">Service of Documents</h1>
<p><b>7 (1)</b> For the purposes of sections 33 and 34 of the Act, service of documents on the Minister shall be effected, either in accordance with the law of the province of the court that issued the garnishee summons or by registered mail, at</p>
<p>The Department of Justice,</p>

<p>Family Orders and Agreements Enforcement Assistance Unit,</p>

<p>Ottawa, Ontario</p>

<p>K1A 0H8.</p>

<p><b>(2)</b> Service of documents by a provincial enforcement service may also be effected by the means of electronic communication that has been agreed on by it and the Department of Justice.</p>
<p>SOR/89-417, s. 3(E) SOR/97-179, s. 3 SOR/2011-189, s. 2</p>
<text><a href="https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-181/section-7-20060322.html">Previous Version</a></text>

<h1 class="Section">Time Limit for Response to Garnishee Summons</h1>
<p><b>8</b> For the purpose of section 41 of the Act, the prescribed time within which the Minister shall respond to a garnishee summons on behalf of Her Majesty is 20 days after the date of service of the documents referred to in section 28 of the Act.</p>
