<h2 class="Subheading">Flowchart 1: Research and development, contained site-limited intermediate or contained export-only substances</h2>

<P>"Substance" (oval shape) – According to the type of substance, it leads to two different processes: "Chemical / Biochemical (reference to Section 5)" or "Polymer / Biopolymer (Reference to Section 6)":</p>
<ol class="lowerAlpha">
	<li>"Chemical / Biochemical (Reference to Section 5)" (Rectangle shape) – Details the following two requirements that manufacturers and importers must meet, according to the situation:<ol class="lowerRoman">
		<li>"30 days before exceeding 1000 kg per year" (Diamond shape) leads to "Schedule 1" [Footnote 1: Additional information specified in Schedule 2 is also required if the chemical is a biochemical - see subsections 5(2), (3) and (4)] (Rectangle shape) – Manufacturers and importers need to provide the information detailed in Schedule 1, at least 30 days before exceeding 1000 kg per year of the substance.</li>
		<li>"30 days before exceeding 10000 kg per year" (Diamond shape) leads to "Notify minister and update information provided [subsection 5(5)]" (Rectangle shape) – Manufacturers and importers need to notify Minister and provide updated information, at least 30 days before exceeding 10000 kg per year of the substance.</li>
	</ol></li>
	<li>"Polymer / Biopolymer (Reference to Section 6)" (Rectangle shape) – Details the following requirement that manufacturers and importers must meet according to the situation:<ol class="lowerRoman">
		<li>"30 days before exceeding 10000 kg per year" (Diamond shape) leads to "Schedule 3" [Footnote 2: Additional information specified in Schedule 2 is also required if the polymer is a biopolymer - see subsections 6(2), (3) and (4)] (Rectangle shape) – Manufacturers and importers need to provide the information detailed in Schedule 3, at least 30 days before exceeding 10000 kg per year of the substance.</li>
	</ol></li>
</ol>
