<h2 class="ScheduleLabel">T01 Application</h2>
<P class="Section">Release of Information under Part I of the Family Orders and Agreements Enforcement Assistance Act form</p>
<ul class="lowerAlpha">
	<li><h3>Part 1: Application Identification</h3>
	<ul>
		<li>01 Court, peace officer or provincial enforcement service name</li>
		<li>02 Application reference code no.:</li>
		<li>03 Court, peace officer or provincial enforcement service reference No.</li>

</li>
	</ul>
	</li>
	<li><h3> Part 2: Information on person to be located</h3>
	<ul>
	<text>The name of the person to be located must correspond with the name on the affidavit in support of this application.:</text>
		
		<li>04 Surname:</li>
		<li>05 First name:</li>
		<li>06 Second name:</li>
		<li>07 Date of birth: (YYYY-MM-DD)</li>
		<li>08 Sex:</li>
		<li>09 Social Insurance Number :</li> 
		<li>10 Mother's surname at her birth:</li>
	</ul></li>
	<li><h3>Part 3: Reason for Application</h3>
	<li>11 A - Person in default of the support provision</>
	<li>12 B - Person believed to have possession of the child or children in contravention of the custody provision</li>
	<li>13 C - Person charged with an offence under section 282 or 283 of the Criminal Code</li>
	<li>14 D - Missing child</li>
	<li>5 E - Person believed to have possession of a child or children in contravention of the access right</li>
	
	<li><h3>Part 4: Documents</h3>
	<text>All applications must be accompanied by the following documents:</text>
	<p> a) where the application is made by an officer or judge of a court,</p>
	<p>(i)a copy of the family provision to which the application relates,</p>
	<p>(ii) the court's authorization obtained under section 12 of the Act, and </p>
	<p>(iii) a copy of the affidavit submitted in support of the application for the court's authorization;</p>
	<p> b) where the application is made by a provincial enforcement service, an affidavit in support of the application in accordance with subsection 14(4) of the Act; </p>
	<p> c) where the application is made by a peace officer investigating a child abduction pursuant to section 282 or 283 of the Criminal Code,</p>
	<p>(i) a copy of the Criminal Code information, and</p>
	<p>(ii) an affidavit in support of the application in accordance with subsection 14(5) of the Act.</p>
	
	<li><h3>Part 5: Declaration</h3>
	<p>I declare that the information given in this application is true and is for the purpose of applying for the release of information to assist in locating a person in accordance with the Family Orders and Agreements Enforcement Assistance Act.</p>
    <p><b>Name of declarant: (print)</b></p>
	<p><b>Signature of Declarant:</b></p>
	<p><b>Date: (YYYY-MM-DD)</b></p>
	
</text>
</ul>
