<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Settlement of International Investment Disputes Act</a><ul class="TocIndent"><li><a href="page-2.html#h-1"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - CONVENTION ON THE SETTLEMENT OF INVESTMENT DISPUTES BETWEEN STATES AND NATIONALS OF OTHER STATES</span></a>
</li></ul>
</li></ul>

</nav>

