<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Pest Control Products Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">MANDATE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">ADVISORY COUNCIL</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">PROHIBITIONS</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText1">REGISTRATION OF PEST CONTROL PRODUCTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Applications for Registration or Amendment</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Maximum Residue Limits</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText2">Additional Information and Mandatory Reporting</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText2">Re-evaluation and Special Review</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-12"><span class="HTitleText2">Other Grounds for Cancellation or Amendment</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-13"><span class="HTitleText2">Public Consultation</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText2">Offences</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-15"><span class="HTitleText1">EXPORT CONTROLS</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText1">RECONSIDERATION OF DECISIONS</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText1">AUTHORIZATION TO USE UNREGISTERED PRODUCT</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText1">ACCESS TO INFORMATION</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-19"><span class="HTitleText1">ENFORCEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-20"><span class="HTitleText2">Inspectors and Analysts</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-21"><span class="HTitleText2">Voluntary Reports</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-22"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-23"><span class="HTitleText2">Searches</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-24"><span class="HTitleText2">Seizures</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-25"><span class="HTitleText2">Disposition of Things Seized</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-26"><span class="HTitleText2">Enforcement Measures</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-27"><span class="HTitleText2">Disposal and Risk-control Measures</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-28"><span class="HTitleText2">Review of Inspectors’ Requirements</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-29"><span class="HTitleText2">Court Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-30"><span class="HTitleText1">DELIVERY OF DOCUMENTS</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-31"><span class="HTitleText1">FEES, CHARGES AND COSTS</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-32"><span class="HTitleText1">LIMITATION ON LIABILITY</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-33"><span class="HTitleText1">COMPENSATION FOR USE OF INFORMATION</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-34"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-35"><span class="HTitleText1">OFFENCES AND PUNISHMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-36"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-37"><span class="HTitleText2">Related Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="#h-38"><span class="HTitleText1">REPORT TO PARLIAMENT</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-39"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-40"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Agriculture and Agri-Food Administrative Monetary Penalties Act</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Feeds Act</cite></span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Fertilizers Act</cite></span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Hazardous Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Pesticide Residue Compensation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>89 - </span><a href="#h-46"><span class="HTitleText1">REPEAL</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-47"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

