<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Criminal Code and the National Defence Act (criminal organization recruitment)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL CODE</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">NATIONAL DEFENCE ACT</cite></span></a>
</li></ul>
</li></ul>

</nav>

