<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Public Health Agency of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PUBLIC HEALTH AGENCY OF CANADA</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">CHIEF PUBLIC HEALTH OFFICER</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-5"><span class="HTitleText1">GENERAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-6"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-7"><span class="HTitleText1">RELATED AND CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-2.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Health Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Quarantine Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-2.html#h-10"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

