<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Canada Elections Act (political financing)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Canada Elections Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-2"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-3"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

