<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Criminal Code and the Department of Justice Act and to make consequential amendments to another Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Department of Justice Act</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-3"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-4"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Records Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="#h-6"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-7"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

