<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Keeping Canada’s Economy and Jobs Growing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE INCOME TAX ACT AND RELATED REGULATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-15.html#h-4"><span class="HTitleText2">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-18.html#h-5"><span class="HTitleText2">Canada Education Savings Regulations</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-18.html#h-6"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="page-18.html#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">SOFTWOOD LUMBER PRODUCTS EXPORT CHARGE ACT, 2006</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="page-18.html#h-8"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-18.html#h-9"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="page-18.html#h-10"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CUSTOMS TARIFF SIMPLIFICATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="page-18.html#h-11"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-23.html#h-12"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>146 - </span><a href="page-23.html#h-13"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">FACILITATING LOW VALUE IMPORTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>146 - </span><a href="page-23.html#h-14"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-23.html#h-15"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>148 - </span><a href="page-23.html#h-16"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CANADA EDUCATION SAVINGS ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>148 - </span><a href="page-23.html#h-17"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-23.html#h-18"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="page-23.html#h-19"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">CHILDREN’S SPECIAL ALLOWANCES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="page-23.html#h-20"><span class="HTitleText2">Children’s Special Allowances Act</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-23.html#h-21"><span class="HTitleText2">Children’s Special Allowance Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="page-23.html#h-22"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">FEDERAL FINANCIAL ASSISTANCE FOR STUDENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="page-23.html#h-23"><span class="HTitleText2">Canada Student Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-23.html#h-24"><span class="HTitleText2">Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-24.html#h-25"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>160 - </span><a href="page-24.html#h-26"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">EMPLOYMENT INSURANCE ACT</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-24.html#h-27"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">GAS TAX FUND — FINANCING MUNICIPAL INFRASTRUCTURE</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-24.html#h-28"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">CANADIAN SECURITIES REGULATION REGIME TRANSITION OFFICE ACT</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-24.html#h-29"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">WAGE EARNER PROTECTION PROGRAM ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="page-24.html#h-30"><span class="HTitleText2">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-24.html#h-31"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="page-24.html#h-32"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">AMENDMENTS RELATING TO EMPLOYMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="page-24.html#h-33"><span class="HTitleText2">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-24.html#h-34"><span class="HTitleText2">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-24.html#h-35"><span class="HTitleText2">Conflict of Interest Act</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-24.html#h-36"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>170 - </span><a href="page-24.html#h-37"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">JUDGES ACT</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-24.html#h-38"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">NORDION AND THERATRONICS DIVESTITURE AUTHORIZATION ACT</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-24.html#h-39"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">CANADA PENSION PLAN</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>172 - </span><a href="page-24.html#h-40"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-25.html#h-41"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>177 - </span><a href="page-25.html#h-42"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">JOBS AND ECONOMIC GROWTH ACT</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-25.html#h-43"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">DEPARTMENT OF VETERANS AFFAIRS ACT</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="page-25.html#h-44"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">CANADA ELECTIONS ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>181 - </span><a href="page-25.html#h-45"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-25.html#h-46"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>183 - </span><a href="page-25.html#h-47"><span class="HLabel1">PART 19</span> - <span class="HTitleText1">SPECIAL RETIREMENT ARRANGEMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="page-25.html#h-48"><span class="HTitleText2">Special Retirement Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-25.html#h-49"><span class="HTitleText2">An act to amend certain acts in relation to pensions and to enact the Special Retirement Arrangements Act and the Pension Benefits Division Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="page-25.html#h-50"><span class="HLabel1">PART 20</span> - <span class="HTitleText1">MOTOR VEHICLE SAFETY ACT</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-25.html#h-51"><span class="HLabel1">PART 21</span> - <span class="HTitleText1">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-26.html#h-52"><span class="HLabel1">PART 22</span> - <span class="HTitleText1">DEPARTMENT OF HUMAN RESOURCES AND SKILLS DEVELOPMENT ACT</span></a>
</li>
<li><a href="page-27.html#h-53"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - LIST OF COUNTRIES AND APPLICABLE TARIFF TREATMENTS</span></a>
</li>
<li><a href="page-28.html#h-54"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-29.html#h-55"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>

</nav>

