<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Export and Import of Rough Diamonds Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">MINISTERIAL POWERS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HTitleText1">EXPORTING ROUGH DIAMONDS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-5"><span class="HTitleText1">IMPORTING ROUGH DIAMONDS</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-6"><span class="HTitleText1">IN-TRANSIT ROUGH DIAMONDS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-7"><span class="HTitleText1">INSPECTIONS</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText1">INVESTIGATIONS</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-9"><span class="HTitleText1">DISPOSITION OF THINGS SEIZED</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-10"><span class="HTitleText1">FORFEITURE</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-11"><span class="HTitleText1">LIABILITY FOR COSTS</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-12"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-13"><span class="HTitleText1">OFFENCES AND PUNISHMENT</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-14"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-15"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - PARTICIPANTS</span></a>
</li></ul>
</li></ul>

</nav>

