<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act respecting the protection of the Antarctic Environment</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">APPLICATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">PROHIBITIONS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-6"><span class="HTitleText1">PERMITS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-7"><span class="HTitleText2">Issuance</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText2">Environmental Impact Assessments</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText2">Waste Management Plans and Emergency Plans</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HTitleText2">Security</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-12"><span class="HTitleText1">ENFORCEMENT IN CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-13"><span class="HTitleText2">Enforcement Officers and Analysts</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText2">Inspections in Canada</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-15"><span class="HTitleText2">Search and Seizure in Canada</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText2">Detention in Canada</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-17"><span class="HTitleText2">Detention of Canadian Vessels</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-18"><span class="HTitleText2">Assistance to Enforcement Officers and Analysts</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-19"><span class="HTitleText2">Forfeiture in Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-20"><span class="HTitleText1">INSPECTIONS IN THE ANTARCTIC</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-21"><span class="HTitleText1">OBSTRUCTION AND FALSE INFORMATION</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-22"><span class="HTitleText1">OFFENCES AND PUNISHMENT</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-23"><span class="HTitleText1">DISCLOSURE OF INFORMATION</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-24"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

