<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Criminal Code (offences relating to conveyances) and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Offences Relating to Transportation — Drugs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Amendments to the <cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-3.html#h-3"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-3.html#h-4"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Customs Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-3.html#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Offences Relating to Conveyances — Alcohol and Drugs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-3.html#h-6"><span class="HTitleText2">Amendments to the <cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>31.1 - </span><a href="page-5.html#h-7"><span class="HTitleText2">Review and Report</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-5.html#h-8"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-6.html#h-9"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="page-6.html#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Aeronautics Act</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-6.html#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Criminal Records Act</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-6.html#h-12"><span class="HTitleText3"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-6.html#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-6.html#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Railway Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-6.html#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="page-7.html#h-16"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="page-7.html#h-17"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-7.html#h-18"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

