<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Criminal Code and other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-2"><span class="HTitleText1">CANADA EVIDENCE ACT</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-3"><span class="HTitleText1">FINANCIAL ADMINISTRATION ACT</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-4"><span class="HTitleText1">SECURITY OF INFORMATION ACT</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-5"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-6"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

