<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Rouge National Urban Park Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">PARK ESTABLISHED</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">MANAGEMENT OF THE PARK</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">PARK LANDS</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText1">POLLUTION CLEAN-UP</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText1">PROHIBITED ACTIVITIES</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText1">AGRICULTURAL ACTIVITIES</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-10"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-11"><span class="HTitleText1">ENFORCEMENT</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-12"><span class="HTitleText1">OFFENCES AND PENALTIES</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-13"><span class="HTitleText1">NON-APPLICATION OF STATUTORY INSTRUMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-14"><span class="HTitleText1">CLAIM IN RESPECT OF ABORIGINAL RIGHTS</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-15"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-16"><span class="HTitleText2">Canada Lands Surveys Act</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-17"><span class="HTitleText2">Parks Canada Agency Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-18"><span class="HTitleText2">Species at Risk Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-19"><span class="HTitleText2">Environmental Violations Administrative Monetary Penalties Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-20"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-21"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - ROUGE NATIONAL URBAN PARK</span></a>
</li></ul>
</li></ul>

</nav>

