<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Emergency Management Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">MINISTER’S RESPONSIBILITIES</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">MINISTERS’ RESPONSIBILITIES</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText1">ORDERS OR REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HTitleText1">RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="page-1.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Public Safety and Emergency Preparedness Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-2.html#h-9"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-10"><span class="HTitleText1">REPEAL</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

