<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada–Peru Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">CAUSES OF ACTION</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">IMPLEMENTATION OF THE AGREEMENT AND THE RELATED AGREEMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Approval</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Panels, Committees, Subcommittees and Working Groups</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-1.html#h-11"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-12"><span class="HTitleText2">Canadian International Trade Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Commercial Arbitration Act</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-14"><span class="HTitleText2">Crown Liability and Proceedings Act</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Department of Human Resources and Skills Development Act</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-5.html#h-18"><span class="HTitleText2">Export and Import Permits Act</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-5.html#h-19"><span class="HTitleText2">Financial Administration Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="page-5.html#h-20"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">COORDINATING AMENDMENTS AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="page-5.html#h-21"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-22"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-7.html#h-23"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-8.html#h-24"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-9.html#h-25"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-10.html#h-26"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-11.html#h-27"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="page-12.html#h-28"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li>
<li><a href="page-13.html#h-29"><span class="scheduleLabel">SCHEDULE 7</span> </a>
</li></ul>
</li></ul>

</nav>

