<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend certain Acts in relation to DNA identification</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">AMENDMENTS TO THE OTHER ACT</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-3"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-4"><span class="HTitleText1">DNA IDENTIFICATION ACT</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-5"><span class="HTitleText1">NATIONAL DEFENCE ACT</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-6"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

