<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Protecting Air Service Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">TECHNICAL, MAINTENANCE AND OPERATIONAL SUPPORT EMPLOYEES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Air Service Operations</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Extension of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Final Offer Selection</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-8"><span class="HTitleText2">New Collective Agreement</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="page-2.html#h-9"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">PILOTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-11"><span class="HTitleText2">Air Service Operations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Extension of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Final Offer Selection</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-14"><span class="HTitleText2">New Collective Agreement</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="page-2.html#h-15"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">GENERAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="page-2.html#h-16"><span class="HTitleText2">Costs</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-17"><span class="HTitleText2">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="page-3.html#h-18"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

