<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
National Security and Intelligence Committee of Parliamentarians Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Committee and Members</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Mandate of Committee</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText1">Security and Confidentiality</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText1">Access to Information</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">Procedure</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-9"><span class="HTitleText1">Reports</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-10"><span class="HTitleText1">Review Bodies</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText1">Secretariat</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-12"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-13"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-14"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-15"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-16"><span class="HTitleText2">Security of Information Act</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-17"><span class="HTitleText2">Parliament of Canada Act</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-18"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-19"><span class="HTitleText2">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-20"><span class="HTitleText2">Conflict of Interest Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-21"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Oath or Solemn Affirmation</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

