<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Foreign Missions and International Organizations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">FOREIGN MISSIONS AND INTERNATIONAL ORGANIZATIONS ACT</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-2"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><a href="#h-3"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

