<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Criminal Code (criminal liability of organizations)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-2"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-3"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

