<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Enhancing Royal Canadian Mounted Police Accountability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">ROYAL CANADIAN MOUNTED POLICE ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-7.html#h-4"><span class="HTitleText2">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-7.html#h-5"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-7.html#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-7.html#h-7"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-7.html#h-8"><span class="HTitleText3"><cite class="XRefExternalAct">Security of Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-7.html#h-9"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-7.html#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-7.html#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-7.html#h-12"><span class="HTitleText3"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-8.html#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Conflict of Interest Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-8.html#h-14"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-9.html#h-15"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>86 - </span><a href="page-11.html#h-16"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">PERSONS DEEMED TO BE APPOINTED UNDER THE <cite class="XRefExternalAct">PUBLIC SERVICE EMPLOYMENT ACT</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-11.html#h-17"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

