<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Strengthening Military Justice in the Defence of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">NATIONAL DEFENCE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-4"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>115 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-10"><span class="HTitleText2">An Act to amend the <cite class="XRefExternalAct">National Defence Act</cite> and to make consequential amendments to other Acts</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Sex Offender Information Registration Act</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Public Safety Act, 2002</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>132 - </span><a href="#h-13"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-14"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

