<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
National Security Act, 2017</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">National Security and Intelligence Review Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">National Security and Intelligence Review Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-5"><span class="HTitleText2">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-7"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-8"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText3"><cite class="XRefExternalAct">Citizenship Act</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Human Rights Act</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-12"><span class="HTitleText3"><cite class="XRefExternalAct">Security of Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>37.1 - </span><a href="#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Royal Canadian Mounted Police Act</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-18"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>49.1 - </span><a href="#h-19"><span class="HLabel1">PART 1.1</span> - <span class="HTitleText1">Avoiding Complicity in Mistreatment by Foreign Entities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49.1 - </span><a href="#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Avoiding Complicity in Mistreatment by Foreign Entities Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>49.2 - </span><a href="#h-21"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-22"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Intelligence Commissioner</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Intelligence Commissioner Act</cite></span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-24"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-25"><span class="HTitleText2">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-28"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-29"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-30"><span class="HTitleText3"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-31"><span class="HTitleText3"><cite class="XRefExternalAct">Security of Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-32"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-33"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-34"><span class="HTitleText3"><cite class="XRefExternalAct">Security of Canada Information Disclosure Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="#h-35"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>76 - </span><a href="#h-36"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Communications Security Establishment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Communications Security Establishment Act</cite></span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-38"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-40"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-43"><span class="HTitleText3"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-44"><span class="HTitleText3"><cite class="XRefExternalAct">Security of Canada Information Disclosure Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="#h-45"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>92 - </span><a href="#h-46"><span class="HLabel1">PART 4</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>92 - </span><a href="#h-47"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-48"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="#h-49"><span class="HLabel1">PART 5</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Security of Canada Information Sharing Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-50"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-51"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="#h-52"><span class="HTitleText3"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-53"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Fisheries and Oceans Act</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-54"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-55"><span class="HTitleText3"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-56"><span class="HTitleText3"><cite class="XRefExternalAct">Chemical Weapons Convention Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-57"><span class="HTitleText3"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="#h-58"><span class="HLabel1">PART 6</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Secure Air Travel Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-59"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-60"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-61"><span class="HLabel1">PART 7</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="#h-62"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-63"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>157.1 - </span><a href="#h-64"><span class="HTitleText2">Section 83.3 of the <cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-65"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-66"><span class="HLabel1">PART 8</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Youth Criminal Justice Act</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-67"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Review</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-68"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-69"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

