<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Human Resources and Skills Development Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">DEPARTMENT OF HUMAN RESOURCES AND SKILLS DEVELOPMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2">Interdepartmental Services</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Committees</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-9"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">MINISTER OF LABOUR</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-10"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CANADA EMPLOYMENT INSURANCE COMMISSION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText2">Continuation of the Commission</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-12"><span class="HTitleText2">Powers, Duties and Functions of the Commission</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-13"><span class="HTitleText2">Organization and Operation of the Commission</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText2">Audit</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">PROTECTION OF PERSONAL INFORMATION</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-16"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CANADA EDUCATION SAVINGS GRANTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-17"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-18"><span class="HTitleText2">Purpose of Part</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-19"><span class="HTitleText2">Payments</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-20"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-21"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">TRANSITIONAL PROVISIONS, CONSEQUENTIAL AND RELATED AMENDMENTS, COORDINATING AMENDMENTS, REPEAL AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-22"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-23"><span class="HTitleText2">Consequential and Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-24"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-25"><span class="HTitleText3">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-26"><span class="HTitleText3">Canada Student Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-27"><span class="HTitleText3">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-28"><span class="HTitleText3">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-29"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-30"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-31"><span class="HTitleText3">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-32"><span class="HTitleText3">Salaries Act</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-33"><span class="HTitleText3">Canada Student Financial Assistance Regulations</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-34"><span class="HTitleText3">Changes in Terminology</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-35"><span class="HTitleText2">Coordinating amendments</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-36"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-37"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

