<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to implement the Convention on International Interests in Mobile Equipment and the Protocol to the Convention on International Interests in Mobile Equipment on Matters Specific to Aircraft Equipment</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">FORCE OF LAW</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HTitleText1">INCONSISTENT LAWS</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-7"><span class="HTitleText1">COURTS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-8"><span class="HTitleText1">REQUESTS FOR DECLARATIONS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-9"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-10"><span class="HTitleText1">AMENDMENTS TO CERTAIN ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-11"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-12"><span class="HTitleText2">Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Companies’ Creditors Arrangement Act</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-14"><span class="HTitleText2">Winding-up and Restructuring Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="page-2.html#h-15"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-3.html#h-16"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - CONVENTION ON INTERNATIONAL INTERESTS IN MOBILE EQUIPMENT</span></a>
</li>
<li><a href="page-4.html#h-17"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - PROTOCOL TO THE CONVENTION ON INTERNATIONAL INTERESTS IN MOBILE EQUIPMENT ON MATTERS SPECIFIC TO AIRCRAFT EQUIPMENT</span></a>
</li>
<li><a href="page-5.html#h-18"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - CONSOLIDATED TEXT OF THE CONVENTION ON INTERNATIONAL INTERESTS IN MOBILE EQUIPMENT AND THE PROTOCOL TO THE CONVENTION ON INTERNATIONAL INTERESTS IN MOBILE EQUIPMENT ON MATTERS SPECIFIC TO AIRCRAFT EQUIPMENT</span></a>
</li></ul>
</li></ul>

</nav>

