<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Federal Law-Civil Law Harmonization Act, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">FEDERAL LAW AND CIVIL LAW OF THE PROVINCE OF QUEBEC</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Title</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Civil Code of Lower Canada</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Marriage</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE INTERPRETATION ACT</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS TO THE FEDERAL REAL PROPERTY ACT</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-8"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">AMENDMENTS TO THE BANKRUPTCY AND INSOLVENCY ACT</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-9"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">AMENDMENTS TO THE CROWN LIABILITY AND PROCEEDINGS ACT</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-10"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">MISCELLANEOUS AMENDMENTS TO OTHER ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="page-5.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Aeronautics Act</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-5.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Airport Transfer (Miscellaneous Matters) Act</cite></span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Animal Pedigree Act</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-5.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-6.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Bell Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-6.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Agricultural Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Council Act</cite></span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-6.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-6.html#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Centre for Management Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-6.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Space Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-6.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Defence Production Act</cite></span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-6.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Industry Act</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-7.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-7.html#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Energy Supplies Emergency Act</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-7.html#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Explosives Act</cite></span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-7.html#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Family Orders and Agreements Enforcement Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-7.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Farm Products Agencies Act</cite></span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-7.html#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Feeds Act</cite></span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-7.html#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Firearms Act</cite></span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-7.html#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Foreign Extraterritorial Measures Act</cite></span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-7.html#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Grain Act</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-7.html#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Integrated Circuit Topography Act</cite></span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-7.html#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Interest Act</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-8.html#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">An Act to incorporate the Jules and Paul-Émile Léger Foundation</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-8.html#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Labour Adjustment Benefits Act</cite></span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-8.html#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Law Commission of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-8.html#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Meat Inspection Act</cite></span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-8.html#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Motor Vehicle Transport Act, 1987</cite></span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-8.html#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">National Arts Centre Act</cite></span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-8.html#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">National Energy Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-8.html#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">National Film Act</cite></span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-9.html#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">National Research Council Act</cite></span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-9.html#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Natural Sciences and Engineering Research Council Act</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-9.html#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Old Age Security Act</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-9.html#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Pension Fund Societies Act</cite></span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-9.html#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Pesticide Residue Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-9.html#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Seeds Act</cite></span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-9.html#h-48"><span class="HTitleText2"><cite class="XRefExternalAct">Social Sciences and Humanities Research Council Act</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-9.html#h-49"><span class="HTitleText2"><cite class="XRefExternalAct">Special Economic Measures Act</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-9.html#h-50"><span class="HTitleText2"><cite class="XRefExternalAct">State Immunity Act</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-9.html#h-51"><span class="HTitleText2"><cite class="XRefExternalAct">Telecommunications Act</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-9.html#h-52"><span class="HTitleText2"><cite class="XRefExternalAct">Trade Unions Act</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-9.html#h-53"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Veterans Affairs Act</cite></span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-10.html#h-54"><span class="HTitleText2"><cite class="XRefExternalAct">Visiting Forces Act</cite></span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-10.html#h-55"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Wildlife Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="page-10.html#h-56"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="page-10.html#h-57"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Customs and Revenue Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-11.html#h-58"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Marine Act</cite></span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-12.html#h-59"><span class="HTitleText2"><cite class="XRefExternalAct">Canada-Newfoundland Atlantic Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="page-12.html#h-60"><span class="HTitleText2"><cite class="XRefExternalAct">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-13.html#h-61"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Canadian Heritage Act</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-13.html#h-62"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Public Works and Government Services Act</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-13.html#h-63"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-13.html#h-64"><span class="HTitleText2"><cite class="XRefExternalAct">International Boundary Commission Act</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-13.html#h-65"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Oil and Gas Operations Act</cite></span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="page-13.html#h-66"><span class="HTitleText2"><cite class="XRefExternalAct">Manitoba Claim Settlements Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-13.html#h-67"><span class="HTitleText2"><cite class="XRefExternalAct">Parks Canada Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-14.html#h-68"><span class="HTitleText2"><cite class="XRefExternalAct">Revolving Funds Act</cite></span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-14.html#h-69"><span class="HTitleText2"><cite class="XRefExternalAct">Surplus Crown Assets Act</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-14.html#h-70"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Transport Act</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-14.html#h-71"><span class="HTitleText2"><cite class="XRefExternalAct">Visiting Forces Act</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-14.html#h-72"><span class="HTitleText2">Terminology Changes</span></a>
</li></ul>
</li><li><span class='sectionRange'>174 - </span><a href="page-14.html#h-73"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="page-15.html#h-74"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">TRANSITIONAL PROVISION AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="page-15.html#h-75"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-15.html#h-76"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

