<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Citizenship Act and to make consequential amendments to another Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Citizenship Act</cite></span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-2"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-3"><span class="HTitleText1">Prohibition on Taking Oath of Citizenship</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-4"><span class="HTitleText1">Consequential Amendments to the <cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-5"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

