<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act respecting user fees</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">APPLICATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">CONSULTATION REQUIREMENTS</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="page-1.html#h-5"><span class="HTitleText1">COMPLAINTS</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-6"><span class="HTitleText1">COMMITTEE REVIEW</span></a>
</li>
<li><span class='sectionRange'>5.1 - </span><a href="page-1.html#h-7"><span class="HTitleText1">REDUCTION OF USER FEE</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-8"><span class="HTitleText1">RESOLUTION OF THE HOUSE</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-9"><span class="HTitleText1">ANNUAL REPORT BY MINISTER</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-10"><span class="HTitleText1">REVIEW OF ACT</span></a>
</li></ul>
</li></ul>

</nav>

