<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Canada Transportation Act and the Railway Safety Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA TRANSPORTATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">RAILWAY SAFETY ACT</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-4"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Air Canada Public Participation Act</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="#h-8"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-9"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

