<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Financial Consumer Agency of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">ESTABLISHMENT OF AGENCY</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">COMMISSIONER OF AGENCY</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">POWERS, DUTIES AND FUNCTIONS OF THE COMMISSIONER</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">AGREEMENTS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText1">DEPUTY COMMISSIONERS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8"><span class="HTitleText1">EXERCISE OF POWERS, DUTIES AND FUNCTIONS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-9"><span class="HTitleText1">STAFF OF AGENCY</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText1">APPROPRIATION</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText1">CONFLICT OF INTEREST</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText1">CONFIDENTIALITY</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText1">ASSESSMENTS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-14"><span class="HTitleText1">ADMINISTRATIVE MONETARY PENALTIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-15"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-16"><span class="HTitleText2">Proceedings</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-17"><span class="HTitleText2">Determination of Responsibility and Penalty</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-18"><span class="HTitleText2">Appeal to Federal Court</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-19"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-20"><span class="HTitleText2">Rules about Violations</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-21"><span class="HTitleText2">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-22"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-23"><span class="HTitleText1">NO LIABILITY</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-24"><span class="HTitleText1">ANNUAL REPORT</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-25"><span class="HTitleText1">AMENDMENTS TO ACTS IN RELATION TO FINANCIAL INSTITUTIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Payments Association Act</cite></span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li>
<li><span class='sectionRange'>343 - </span><a href="#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Green Shield Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>466 - </span><a href="#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Office of the Superintendent of Financial Institutions Act</cite></span></a>
</li>
<li><span class='sectionRange'>478 - </span><a href="#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>572 - </span><a href="#h-35"><span class="HTitleText1">AMENDMENTS TO OTHER ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>572 - </span><a href="#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>575 - </span><a href="#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Companies’ Creditors Arrangement Act</cite></span></a>
</li>
<li><span class='sectionRange'>578 - </span><a href="#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li>
<li><span class='sectionRange'>581 - </span><a href="#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Depository Bills and Notes Act</cite></span></a>
</li>
<li><span class='sectionRange'>583 - </span><a href="#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Pension Benefits Standards Act, 1985</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>584 - </span><a href="#h-41"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>584 - </span><a href="#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>586 - </span><a href="#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Bills of Exchange Act</cite></span></a>
</li>
<li><span class='sectionRange'>587 - </span><a href="#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Small Business Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>588 - </span><a href="#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>589 - </span><a href="#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>590 - </span><a href="#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>591 - </span><a href="#h-48"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>592 - </span><a href="#h-49"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>593 - </span><a href="#h-50"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-51"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-52"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-53"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>

</nav>

