<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Railway Safety Act and to make consequential amendments to the Canada Transportation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">RAILWAY SAFETY ACT</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-6.html#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS TO THE CANADA TRANSPORTATION ACT</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-7.html#h-4"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-7.html#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

