<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Federal Sustainable Development Act and the Auditor General Act (involvement of Parliament)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">FEDERAL SUSTAINABLE DEVELOPMENT ACT</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-2"><span class="HTitleText1">AUDITOR GENERAL ACT</span></a>
</li></ul>
</li></ul>

</nav>

