<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Canada Pension Plan and the Canada Pension Plan Investment Board Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">CANADA PENSION PLAN</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-2"><span class="HTitleText1">CANADA PENSION PLAN INVESTMENT BOARD ACT</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

