<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act respecting the mandatory reporting of Internet child pornography by persons who provide an Internet service</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DUTIES</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-3"><span class="HTitleText1">OFFENCES AND PUNISHMENT</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-4"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

