<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Tax Conventions Implementation Act, 2004</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">CANADA–GABON TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">CANADA–IRELAND TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CANADA–ARMENIA TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">CANADA–OMAN TAX AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CANADA–AZERBAIJAN TAX CONVENTION</span></a>
</li>
<li><a href="page-2.html#h-7"><span class="scheduleLabel"><strong>SCHEDULE 1</strong></span> </a>
</li>
<li><a href="page-3.html#h-8"><span class="scheduleLabel"><strong>SCHEDULE 2</strong></span> </a>
</li>
<li><a href="page-4.html#h-9"><span class="scheduleLabel"><strong>SCHEDULE 3</strong></span> </a>
</li>
<li><a href="page-5.html#h-10"><span class="scheduleLabel"><strong>SCHEDULE 4</strong></span> </a>
</li>
<li><a href="page-6.html#h-11"><span class="scheduleLabel"><strong>SCHEDULE 5</strong></span> </a>
</li></ul>
</li></ul>

</nav>

