<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Royal Canadian Mounted Police Superannuation Act, to validate certain calculations and to amend other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">ROYAL CANADIAN MOUNTED POLICE SUPERANNUATION ACT</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-2"><span class="HTitleText1">VALIDATION</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-3"><span class="HTitleText1">CONSEQUENTIAL AND RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-4"><span class="HTitleText2">An Act to amend certain Acts in relation to pensions and to enact the Special Retirement Arrangements Act and the Pension Benefits Division Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-5"><span class="HTitleText2">Public Sector Pension Investment Board Act</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText2">An Act to amend the Canadian Forces Superannuation Act and to make consequential amendments to other Acts</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

