<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Fairness at the Pumps Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">ELECTRICITY AND GAS INSPECTION ACT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-3"><span class="HTitleText1">WEIGHTS AND MEASURES ACT</span></a>
</li>
<li><span class='sectionRange'>29.1 - </span><a href="page-5.html#h-4"><span class="HTitleText1">REPORT</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-5.html#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

