<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
First Nations Commercial and Industrial Development Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-4"><span class="HTitleText1">OTHER ACTS</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-5"><span class="HTitleText1">LIMITS ON LIABILITY, DEFENCES AND IMMUNITIES</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-6"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

