<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Physical Activity and Sport Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">POLICIES</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">OBJECTS AND MANDATE</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText1">AGREEMENTS AND ARRANGEMENTS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HTitleText1">SPORT DISPUTE RESOLUTION CENTRE OF CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Establishment of Centre</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Mission and Powers</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Chairperson</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-11"><span class="HTitleText2">Executive Director</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Audit</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-14"><span class="HTitleText2">Arbitrators and Mediators</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-15"><span class="HTitleText2">General Provisions</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Corporate Plan and Annual Report</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-17"><span class="HTitleText2">Dissolution</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="page-3.html#h-18"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-19"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-3.html#h-20"><span class="HTitleText2">Department of Canadian Heritage Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="page-3.html#h-21"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-22"><span class="HTitleText1">REPEAL</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-23"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

