<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Reform Act, 2014</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA ELECTIONS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">PARLIAMENT OF CANADA ACT</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li></ul>
</li></ul>

</nav>

