<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada–Madagascar Tax Convention Act, 2018</a><ul class="TocIndent"><li><a href="page-2.html#h-1"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Convention between Canada and the Republic of Madagascar for the avoidance of double taxation and the prevention of fiscal evasion with respect to taxes on income</span></a>
</li>
<li><a href="page-3.html#h-2"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Protocol</span></a>
</li></ul>
</li></ul>

</nav>

