<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Federal Sustainable Development Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Federal Sustainable Development Act</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="#h-2"><span class="HTitleText1">Consequential Amendments to the Auditor General Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-3"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-4"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-5"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

