<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Federal Sustainable Development Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Federal Sustainable Development Act</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="page-2.html#h-2"><span class="HTitleText1">Consequential Amendments to the Auditor General Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-3.html#h-3"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-3.html#h-4"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-4.html#h-5"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

