<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to give effect to the Westbank First Nation Self Government Agreement</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">EFFECT OF AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">APPLICATION OF OTHER ACTS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-5"><span class="HTitleText1">LEGAL PROCEEDINGS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-6"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-7"><span class="HTitleText1">RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Lobbyists Registration Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Privacy Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-2.html#h-11"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-12"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

