<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Department of Canadian Heritage Act and the Parks Canada Agency Act and to make related amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">RESPONSIBILITY FOR PARKS CANADA AGENCY</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Department of Canadian Heritage Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText2">Parks Canada Agency Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText2">Canada National Marine Conservation Areas Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText2">Canada National Parks Act</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText2">Canada Shipping Act, 2001</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Heritage Railway Stations Protection Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-9"><span class="HTitleText2">Historic Sites and Monuments Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText2">Saguenay-St. Lawrence Marine Park Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText2">Species at Risk Act</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

