<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Miscellaneous Statute Law Amendment Act, 2017</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Aeronautics Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Canada Health Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Competition Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Companies’ Creditors Arrangement Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-8"><span class="HTitleText2">International River Improvements Act</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Motor Vehicle Safety Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-11"><span class="HTitleText2">Employment Equity Act</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Tobacco Act</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Canadian Environmental Protection Act, 1999</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Canada National Parks Act</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Canada Shipping Act, 2001</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Immigration and Refugee Protection Act</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Yukon Act</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Species at Risk Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-4.html#h-19"><span class="HTitleText2">First Nations Fiscal Management Act</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-4.html#h-20"><span class="HTitleText2">Department of Employment and Social Development Act</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-4.html#h-21"><span class="HTitleText2">Wage Earner Protection Program Act</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Jobs, Growth and Long-term Prosperity Act</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Northwest Territories Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Economic Action Plan 2014 Act, No. 2</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="page-5.html#h-25"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Terminology</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-6.html#h-26"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Repeals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="page-6.html#h-27"><span class="HTitleText2">Maintenance of Ports Operations Act, 1986</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-28"><span class="HTitleText2">Postal Services Continuation Act, 1987</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-6.html#h-29"><span class="HTitleText2">Postal Services Continuation Act, 1991</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-6.html#h-30"><span class="HTitleText2">West Coast Ports Operations Act, 1994</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-6.html#h-31"><span class="HTitleText2">West Coast Ports Operations Act, 1995</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-6.html#h-32"><span class="HTitleText2">Maintenance of Railway Operations Act, 1995</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-6.html#h-33"><span class="HTitleText2">Postal Services Continuation Act, 1997</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-6.html#h-34"><span class="HTitleText2">Railway Continuation Act, 2007</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="page-6.html#h-35"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Coordinating Amendments</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

