<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act respecting First Nations, Inuit and Métis children, youth and families</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-2"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HTitleText1">Purpose and Principles</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText1">Best Interests of Indigenous Child</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-6"><span class="HTitleText1">Provision of Child and Family Services</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">Placement of Indigenous Child</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText1">Jurisdiction — Child and Family Services</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-9"><span class="HTitleText1">Laws of Indigenous Groups, Communities or Peoples</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-10"><span class="HTitleText2">Coordination and Application</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText2">Publication and Accessibility</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-12"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-13"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-14"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-15"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

