<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
First Nations Jurisdiction over Education in British Columbia Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">PURPOSE AND EFFECT OF THE ACT</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">EFFECT OF INDIVIDUAL AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-5"><span class="HTitleText1">FIRST NATIONS EDUCATION AUTHORITY</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-6"><span class="HTitleText1">PURPOSE AND POWERS OF THE AUTHORITY</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-7"><span class="HTitleText1">COMMUNITY EDUCATION AUTHORITY</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText1">OTHER ACTS</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText1">LIABILITY</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HTitleText1">MINISTER’S DUTIES AND POWERS</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-12"><span class="HTitleText1">ORDERS AND REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-13"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-14"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-15"><span class="HTitleText2">Privacy Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-17"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - PARTICIPATING FIRST NATIONS</span></a>
</li></ul>
</li></ul>

</nav>

