<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Telefilm Canada Act and another Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TELEFILM CANADA ACT</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-2"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT TO FINANCIAL ADMINISTRATION ACT</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-3"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li></ul>
</li></ul>

</nav>

