<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Freezing Assets of Corrupt Foreign Officials Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">ORDERS AND REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">DUTY TO DETERMINE</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText1">DISCLOSURE</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">OFFENCES</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText1">RIGHTS OF PERSONS WHO ARE SUBJECT TO AN ORDER OR REGULATION</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText1">APPLICATION FOR A CERTIFICATE</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText1">REVIEW AND REPORT</span></a>
</li></ul>
</li></ul>

</nav>

