<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Technical Tax Amendments Act, 2012</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF OFFSHORE INVESTMENT FUND PROPERTY AND NON-RESIDENT TRUSTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-5.html#h-4"><span class="HTitleText2">Income Tax Amendments Act, 2000</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-5.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Conventions Interpretation Act</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-5.html#h-6"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="page-5.html#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF FOREIGN AFFILIATES: SURPLUS RULES AND OTHER TECHNICAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="page-5.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-6.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Budget and Economic Statement Implementation Act, 2007</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-7.html#h-10"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-12.html#h-11"><span class="HTitleText2">Assessments</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="page-12.html#h-12"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF FOREIGN AFFILIATES: REORGANIZATIONS AND DISTRIBUTIONS AND OTHER TECHNICAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="page-12.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-19.html#h-14"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-23.html#h-15"><span class="HTitleText2">Elections and Assessments</span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="page-23.html#h-16"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">INCOME TAX ACT</cite> RELATED TO BIJURALISM</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-32.html#h-17"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">OTHER AMENDMENTS TO THE <cite class="XRefExternalAct">INCOME TAX ACT</cite> AND RELATED LEGISLATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>169 - </span><a href="page-32.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="page-77.html#h-19"><span class="HTitleText2">An Act to amend the <cite class="XRefExternalAct">Income Tax Act</cite> (natural resources)</span></a>
</li>
<li><span class='sectionRange'>369 - </span><a href="page-78.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>370 - </span><a href="page-78.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>371 - </span><a href="page-78.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Amendments Act, 1997</cite></span></a>
</li>
<li><span class='sectionRange'>372 - </span><a href="page-78.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Amendments Act, 2000</cite></span></a>
</li>
<li><span class='sectionRange'>375 - </span><a href="page-78.html#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Keeping Canada’s Economy and Jobs Growing Act</cite></span></a>
</li>
<li><span class='sectionRange'>376 - </span><a href="page-78.html#h-25"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>413 - </span><a href="page-83.html#h-26"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">MEASURES IN RESPECT OF SALES TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>413 - </span><a href="page-83.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>417 - </span><a href="page-84.html#h-28"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF TAX AGREEMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>417 - </span><a href="page-84.html#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>421 - </span><a href="page-84.html#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">First Nations Goods and Services Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>426 - </span><a href="page-85.html#h-31"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><a href="page-86.html#h-32"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

