<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Economic Statement Implementation Act, 2020</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span></span> - <span class="HTitleText1">Income Tax Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText2">Related Amendment to the Children’s Special Allowances Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1">Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HLabel1">PART 3</span></span> - <span class="HTitleText1">Canada Student Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HLabel1">PART 4</span></span> - <span class="HTitleText1">Apprentice Loans Act</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8"><span class="HLabel1">PART 5</span></span> - <span class="HTitleText1">Food and Drugs Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-10"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-11"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Payments</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-12"><span class="HLabel1">PART 7</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Borrowing Authority Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-13"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-14"><span class="HTitleText2">Related Amendment to the <cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li></ul>
</li><li><a href="#h-15"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

