<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Proposals for a Miscellaneous Statute Law Amendment Act, 2014</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">PART 1 - AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Aeronautics Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Canada Agricultural Products Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Canada Business Corporations Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Canada Corporations Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Canada Evidence Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-11"><span class="HTitleText2">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Canada Marine Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Canada National Parks Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Canada Not-for-profit Corporations Act</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Canada Shipping Act, 2001</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Canada Transportation Act</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Canadian Security Intelligence Service Act</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Chemical Weapons Convention Implementation Act</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Coasting Trade Act</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-20"><span class="HTitleText2">Companies’ Creditors Arrangement Act</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-4.html#h-21"><span class="HTitleText2">Competition Act</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-3.141516"><span class="HTitleText2">Consumer Packaging and Labelling Act</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-22"><span class="HTitleText2">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-6.html#h-24"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-25"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-7.html#h-26"><span class="HTitleText2">Defence Production Act</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-7.html#h-27"><span class="HTitleText2">Department of Veterans Affairs Act</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-7.html#h-28"><span class="HTitleText2">Divorce Act</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-7.html#h-29"><span class="HTitleText2">Economic Development Agency of Canada for the Regions of Quebec Act</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-7.html#h-30"><span class="HTitleText2">Electoral Boundaries Readjustment Act</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-7.html#h-31"><span class="HTitleText2">Electricity and Gas Inspection Act</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-7.html#h-32"><span class="HTitleText2">Explosives Act</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-8.html#h-33"><span class="HTitleText2">Farm Products Agencies Act</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-9.html#h-34"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-9.html#h-35"><span class="HTitleText2">Fisheries Act</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-9.html#h-36"><span class="HTitleText2">Gender Equity in Indian Registration Act</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-9.html#h-37"><span class="HTitleText2">Government Employees Compensation Act</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-9.html#h-38"><span class="HTitleText2">Health of Animals Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-10.html#h-39"><span class="HTitleText2">Immigration and Refugee Protection Act</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-10.html#h-40"><span class="HTitleText2">Indian Act</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-11.html#h-41"><span class="HTitleText2">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-11.html#h-42"><span class="HTitleText2">International Bridges and Tunnels Act</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-11.html#h-43"><span class="HTitleText2">Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-11.html#h-44"><span class="HTitleText2">Judges Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-12.html#h-45"><span class="HTitleText2">Legislative Instruments Re-enactment Act</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-12.html#h-46"><span class="HTitleText2">Library and Archives of Canada Act</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-12.html#h-47"><span class="HTitleText2">Meat Inspection Act</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-12.html#h-48"><span class="HTitleText2">Merchant Seamen Compensation Act</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-12.html#h-49"><span class="HTitleText2">National Defence Act</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-12.html#h-50"><span class="HTitleText2">Newfoundland Additional Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-12.html#h-51"><span class="HTitleText2">Nuclear Safety and Control Act</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-12.html#h-52"><span class="HTitleText2">Oceans Act</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-12.html#h-53"><span class="HTitleText2">Patent Act</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-13.html#h-54"><span class="HTitleText2">Pension Act</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-13.html#h-55"><span class="HTitleText2">Physical Activity and Sport Act</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="page-13.html#h-56"><span class="HTitleText2">Plant Protection Act</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-13.html#h-57"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-13.html#h-58"><span class="HTitleText2">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-14.html#h-59"><span class="HTitleText2">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-14.html#h-60"><span class="HTitleText2">Railway Safety Act</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="page-14.html#h-61"><span class="HTitleText2">Saguenay-St. Lawrence Marine Park Act</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-14.html#h-62"><span class="HTitleText2">Seized Property Management Act</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-14.html#h-63"><span class="HTitleText2">Species at Risk Act</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-14.html#h-64"><span class="HTitleText2">Tobacco Act</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-14.html#h-65"><span class="HTitleText2">Transportation of Dangerous Goods Act, 1992</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-14.html#h-66"><span class="HTitleText2">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-14.html#h-67"><span class="HTitleText2">Veterans Review and Appeal Board Act</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-15.html#h-68"><span class="HTitleText2">Visiting Forces Act</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-16.html#h-69"><span class="HTitleText2">War Veterans Allowance Act</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-16.html#h-70"><span class="HTitleText2">Winding-up and Restructuring Act</span></a>
</li>
</ul>
<li><span class='sectionRange'>174 - </span><a href="page-16.html#h-71"><span class="HTitleText1">PART 2 - TERMINOLOGY</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-16.html#h-72"><span class="HTitleText2">PART 3 - COORDINATING AMENDMENTS</span></a>
</li></ul></li></ul>

</nav>

