
<h1 class="Part" id="h-3.141516">
<span class="HTitleText1">TABLE OF PROVISIONS</span>
</h1>
<h1 class="Part" id="h-3.141516">
<span class="HTitleText1">PROPOSALS TO CORRECT CERTAIN ANOMALIES, INCONSISTENCIES AND ERRORS AND TO DEAL WITH OTHER MATTERS OF A NON-CONTROVERSIAL AND UNCOMPLICATED NATURE IN THE STATUTES OF CANADA AND TO REPEAL CERTAIN PROVISIONS THAT HAVE EXPIRED, LAPSED OR OTHERWISE CEASED TO HAVE EFFECT</span>
</h1>
<h1 class="Part" id="h-3.141516">
<span class="HTitleText1">SHORT TITLE</span>
</h1>
<p>1.</p>
<p class="TableOfProvisions">1. <cite class="XRefExternalAct">Proposals for a Miscellaneous Statute Law Amendment Act, 2014</cite>
</p>
<h1 class="Part" id="h-3.141516">
<span class="HLabel1">PART 1</span>
<span class="HTitleText1">AMENDMENTS</span>
</h1>
<p>
<strong>2.</strong>
</p>
<p class="TableOfProvisions">
<strong>2.</strong> <strong>
<cite class="XRefExternalAct">Access to Information Act</cite>
</strong>
</p>
<p>
<strong>3–4.</strong>
</p>
<p class="TableOfProvisions">
<strong>3–4.</strong> <strong>
<cite class="XRefExternalAct">Aeronautics Act</cite>
</strong>
</p>
<p>
<strong>5.</strong>
</p>
<p class="TableOfProvisions">
<strong>5.</strong> <strong>
<cite class="XRefExternalAct">Bank Act</cite>
</strong>
</p>
<p>
<strong>6–10.</strong>
</p>
<p class="TableOfProvisions">
<strong>6–10.</strong> <strong>
<cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite>
</strong>
</p>
<p>
<strong>11.</strong>
</p>
<p class="TableOfProvisions">
<strong>11.</strong> <strong>
<cite class="XRefExternalAct">Canada Agricultural Products Act</cite>
</strong>
</p>
<p>
<strong>12.</strong>
</p>
<p class="TableOfProvisions">
<strong>12.</strong> <strong>
<cite class="XRefExternalAct">Canada Business Corporations Act</cite>
</strong>
</p>
<p>
<strong>13.</strong>
</p>
<p class="TableOfProvisions">
<strong>13.</strong> <strong>
<cite class="XRefExternalAct">Canada Corporations Act</cite>
</strong>
</p>
<p>
<strong>14.</strong>
</p>
<p class="TableOfProvisions">
<strong>14.</strong> <strong>
<cite class="XRefExternalAct">Canada Evidence Act</cite>
</strong>
</p>
<p>
<strong>15.</strong>
</p>
<p class="TableOfProvisions">
<strong>15.</strong> <strong>
<cite class="XRefExternalAct">Canada Labour Code</cite>
</strong>
</p>
<p>
<strong>16–17.</strong>
</p>
<p class="TableOfProvisions">
<strong>16–17.</strong> <strong>
<cite class="XRefExternalAct">Canada Marine Act</cite>
</strong>
</p>
<p>
<strong>18–22.</strong>
</p>
<p class="TableOfProvisions">
<strong>18–22.</strong> <strong>
<cite class="XRefExternalAct">Canada National Parks Act</cite>
</strong>
</p>
<p>
<strong>23.</strong>
</p>
<p class="TableOfProvisions">
<strong>23.</strong> <strong>
<cite class="XRefExternalAct">Canada Not-for-profit Corporations Act</cite>
</strong>
</p>
<p>
<strong>24–29.</strong>
</p>
<p class="TableOfProvisions">
<strong>24–29.</strong> <strong>
<cite class="XRefExternalAct">Canada Shipping Act, 2001</cite>
</strong>
</p>
<p>
<strong>30–34.</strong>
</p>
<p class="TableOfProvisions">
<strong>30–34.</strong> <strong>
<cite class="XRefExternalAct">Canada Transportation Act</cite>
</strong>
</p>
<p>
<strong>35.</strong>
</p>
<p class="TableOfProvisions">
<strong>35.</strong> <strong>
<cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite>
</strong>
</p>
<p>
<strong>36.</strong>
</p>
<p class="TableOfProvisions">
<strong>36.</strong> <strong>
<cite class="XRefExternalAct">Chemical Weapons Convention Implementation Act</cite>
</strong>
</p>
<p>
<strong>37.</strong>
</p>
<p class="TableOfProvisions">
<strong>37.</strong> <strong>
<cite class="XRefExternalAct">Coasting Trade Act</cite>
</strong>
</p>
<p>
<strong>38.</strong>
</p>
<p class="TableOfProvisions">
<strong>38.</strong> <strong>
<cite class="XRefExternalAct">Companies’ Creditors Arrangement Act</cite>
</strong>
</p>
<p>
<strong>39–42.</strong>
</p>
<p class="TableOfProvisions">
<strong>39–42.</strong> <strong>
<cite class="XRefExternalAct">Competition Act</cite>
</strong>
</p>
<p>
<strong>43.</strong>
</p>
<p class="TableOfProvisions">
<strong>43.</strong> <strong>
<cite class="XRefExternalAct">Consumer Packaging and Labelling Act</cite>
</strong>
</p>
<p>
<strong>44.</strong>
</p>
<p class="TableOfProvisions">
<strong>44.</strong> <strong>
<cite class="XRefExternalAct">Cooperative Credit Associations Act</cite>
</strong>
</p>
<p>
<strong>45–60.</strong>
</p>
<p class="TableOfProvisions">
<strong>45–60.</strong> <strong>
<cite class="XRefExternalAct">Criminal Code</cite>
</strong>
</p>
<p>
<strong>61–64.</strong>
</p>
<p class="TableOfProvisions">
<strong>61–64.</strong> <strong>
<cite class="XRefExternalAct">Customs Act</cite>
</strong>
</p>
<p>
<strong>65–75.</strong>
</p>
<p class="TableOfProvisions">
<strong>65–75.</strong> <strong>
<cite class="XRefExternalAct">Customs Tariff</cite>
</strong>
</p>
<p>
<strong>76.</strong>
</p>
<p class="TableOfProvisions">
<strong>76.</strong> <strong>
<cite class="XRefExternalAct">Defence Production Act</cite>
</strong>
</p>
<p>
<strong>77.</strong>
</p>
<p class="TableOfProvisions">
<strong>77.</strong> <strong>
<cite class="XRefExternalAct">Department of Veterans Affairs Act</cite>
</strong>
</p>
<p>
<strong>78.</strong>
</p>
<p class="TableOfProvisions">
<strong>78.</strong> <strong>
<cite class="XRefExternalAct">Divorce Act</cite>
</strong>
</p>
<p>
<strong>79.</strong>
</p>
<p class="TableOfProvisions">
<strong>79.</strong> <strong>
<cite class="XRefExternalAct">Economic Development Agency of Canada for the Regions of Quebec Act</cite>
</strong>
</p>
<p>
<strong>80–82.</strong>
</p>
<p class="TableOfProvisions">
<strong>80–82.</strong> <strong>
<cite class="XRefExternalAct">Electoral Boundaries Readjustment Act</cite>
</strong>
</p>
<p>
<strong>83.</strong>
</p>
<p class="TableOfProvisions">
<strong>83.</strong> <strong>
<cite class="XRefExternalAct">Electricity and Gas Inspection Act</cite>
</strong>
</p>
<p>
<strong>84.</strong>
</p>
<p class="TableOfProvisions">
<strong>84.</strong> <strong>
<cite class="XRefExternalAct">Explosives Act</cite>
</strong>
</p>
<p>
<strong>85–94.</strong>
</p>
<p class="TableOfProvisions">
<strong>85–94.</strong> <strong>
<cite class="XRefExternalAct">Farm Products Agencies Act</cite>
</strong>
</p>
<p>
<strong>95–98.</strong>
</p>
<p class="TableOfProvisions">
<strong>95–98.</strong> <strong>
<cite class="XRefExternalAct">Financial Administration Act</cite>
</strong>
</p>
<p>
<strong>99.</strong>
</p>
<p class="TableOfProvisions">
<strong>99.</strong> <strong>
<cite class="XRefExternalAct">Fisheries Act</cite>
</strong>
</p>
<p>
<strong>100.</strong>
</p>
<p class="TableOfProvisions">
<strong>100.</strong> <strong>
<cite class="XRefExternalAct">Gender Equity in Indian Registration Act</cite>
</strong>
</p>
<p>
<strong>101.</strong>
</p>
<p class="TableOfProvisions">
<strong>101.</strong> <strong>
<cite class="XRefExternalAct">Government Employees Compensation Act</cite>
</strong>
</p>
<p>
<strong>102–109.</strong>
</p>
<p class="TableOfProvisions">
<strong>102–109.</strong> <strong>
<cite class="XRefExternalAct">Health of Animals Act</cite>
</strong>
</p>
<p>
<strong>110–119.</strong>
</p>
<p class="TableOfProvisions">
<strong>110–119.</strong> <strong>
<cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite>
</strong>
</p>
<p>
<strong>120.</strong>
</p>
<p class="TableOfProvisions">
<strong>120.</strong> <strong>
<cite class="XRefExternalAct">Indian Act</cite>
</strong>
</p>
<p>
<strong>121–123.</strong>
</p>
<p class="TableOfProvisions">
<strong>121–123.</strong> <strong>
<cite class="XRefExternalAct">Insurance Companies Act</cite>
</strong>
</p>
<p>
<strong>124–125.</strong>
</p>
<p class="TableOfProvisions">
<strong>124–125.</strong> <strong>
<cite class="XRefExternalAct">International Bridges and Tunnels Act</cite>
</strong>
</p>
<p>
<strong>126.</strong>
</p>
<p class="TableOfProvisions">
<strong>126.</strong> <strong>
<cite class="XRefExternalAct">Interpretation Act</cite>
</strong>
</p>
<p>
<strong>127–130.</strong>
</p>
<p class="TableOfProvisions">
<strong>127–130.</strong> <strong>
<cite class="XRefExternalAct">Judges Act</cite>
</strong>
</p>
<p>
<strong>131.</strong>
</p>
<p class="TableOfProvisions">
<strong>131.</strong> <strong>
<cite class="XRefExternalAct">Legislative Instruments Re-enactment Act</cite>
</strong>
</p>
<p>
<strong>132.</strong>
</p>
<p class="TableOfProvisions">
<strong>132.</strong> <strong>
<cite class="XRefExternalAct">Library and Archives of Canada Act</cite>
</strong>
</p>
<p>
<strong>133.</strong>
</p>
<p class="TableOfProvisions">
<strong>133.</strong> <strong>
<cite class="XRefExternalAct">Meat Inspection Act</cite>
</strong>
</p>
<p>
<strong>134–135.</strong>
</p>
<p class="TableOfProvisions">
<strong>134–135.</strong> <strong>
<cite class="XRefExternalAct">Merchant Seamen Compensation Act</cite>
</strong>
</p>
<p>
<strong>136.</strong>
</p>
<p class="TableOfProvisions">
<strong>136.</strong> <strong>
<cite class="XRefExternalAct">National Defence Act</cite>
</strong>
</p>
<p>
<strong>137.</strong>
</p>
<p class="TableOfProvisions">
<strong>137.</strong> <strong>
<cite class="XRefExternalAct">Newfoundland Additional Financial Assistance Act</cite>
</strong>
</p>
<p>
<strong>138.</strong>
</p>
<p class="TableOfProvisions">
<strong>138.</strong> <strong>
<cite class="XRefExternalAct">Nuclear Safety and Control Act</cite>
</strong>
</p>
<p>
<strong>139.</strong>
</p>
<p class="TableOfProvisions">
<strong>139.</strong> <strong>
<cite class="XRefExternalAct">Oceans Act</cite>
</strong>
</p>
<p>
<strong>140.</strong>
</p>
<p class="TableOfProvisions">
<strong>140.</strong> <strong>
<cite class="XRefExternalAct">Patent Act</cite>
</strong>
</p>
<p>
<strong>141–142.</strong>
</p>
<p class="TableOfProvisions">
<strong>141–142.</strong> <strong>
<cite class="XRefExternalAct">Pension Act</cite>
</strong>
</p>
<p>
<strong>143.</strong>
</p>
<p class="TableOfProvisions">
<strong>143.</strong> <strong>
<cite class="XRefExternalAct">Physical Activity and Sport Act</cite>
</strong>
</p>
<p>
<strong>144–148.</strong>
</p>
<p class="TableOfProvisions">
<strong>144–148.</strong> <strong>
<cite class="XRefExternalAct">Plant Protection Act</cite>
</strong>
</p>
<p>
<strong>149.</strong>
</p>
<p class="TableOfProvisions">
<strong>149.</strong> <strong>
<cite class="XRefExternalAct">Privacy Act</cite>
</strong>
</p>
<p>
<strong>150.</strong>
</p>
<p class="TableOfProvisions">
<strong>150.</strong> <strong>
<cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite>
</strong>
</p>
<p>
<strong>151.</strong>
</p>
<p class="TableOfProvisions">
<strong>151.</strong> <strong>
<cite class="XRefExternalAct">Public Sector Compensation Act</cite>
</strong>
</p>
<p>
<strong>152.</strong>
</p>
<p class="TableOfProvisions">
<strong>152.</strong> <strong>
<cite class="XRefExternalAct">Railway Safety Act</cite>
</strong>
</p>
<p>
<strong>153.</strong>
</p>
<p class="TableOfProvisions">
<strong>153.</strong> <strong>
<cite class="XRefExternalAct">Saguenay-St. Lawrence Marine Park Act</cite>
</strong>
</p>
<p>
<strong>154.</strong>
</p>
<p class="TableOfProvisions">
<strong>154.</strong> <strong>
<cite class="XRefExternalAct">Seized Property Management Act</cite>
</strong>
</p>
<p>
<strong>155.</strong>
</p>
<p class="TableOfProvisions">
<strong>155.</strong> <strong>
<cite class="XRefExternalAct">Species at Risk Act</cite>
</strong>
</p>
<p>
<strong>156–157.</strong>
</p>
<p class="TableOfProvisions">
<strong>156–157.</strong> <strong>
<cite class="XRefExternalAct">Tobacco Act</cite>
</strong>
</p>
<p>
<strong>158.</strong>
</p>
<p class="TableOfProvisions">
<strong>158.</strong> <strong>
<cite class="XRefExternalAct">Transportation of Dangerous Goods Act, 1992</cite>
</strong>
</p>
<p>
<strong>159.</strong>
</p>
<p class="TableOfProvisions">
<strong>159.</strong> <strong>
<cite class="XRefExternalAct">Trust and Loan Companies Act</cite>
</strong>
</p>
<p>
<strong>160–161.</strong>
</p>
<p class="TableOfProvisions">
<strong>160–161.</strong> <strong>
<cite class="XRefExternalAct">Veterans Review and Appeal Board Act</cite>
</strong>
</p>
<p>
<strong>162–168.</strong>
</p>
<p class="TableOfProvisions">
<strong>162–168.</strong> <strong>
<cite class="XRefExternalAct">Visiting Forces Act</cite>
</strong>
</p>
<p>
<strong>169–170.</strong>
</p>
<p class="TableOfProvisions">
<strong>169–170.</strong> <strong>
<cite class="XRefExternalAct">War Veterans Allowance Act</cite>
</strong>
</p>
<p>
<strong>171–173.</strong>
</p>
<p class="TableOfProvisions">
<strong>171–173.</strong> <strong>
<cite class="XRefExternalAct">Winding-up and Restructuring Act</cite>
</strong>
</p>
<h1 class="Part" id="h-3.141516">
<span class="HLabel1">PART 2</span>
<span class="HTitleText1">TERMINOLOGY</span>
</h1>
<p>
<strong>174.</strong>
</p>
<p class="TableOfProvisions">
<strong>174.</strong> <strong>Replacement of “Newfoundland”</strong>
</p>
<h1 class="Part" id="h-3.141516">
<span class="HLabel1">PART 3</span>
<span class="HTitleText1">COORDINATING AMENDMENTS</span>
</h1>
<p>
<strong>175.</strong>
</p>
<p class="TableOfProvisions">
<strong>175.</strong> <strong>2009, c. 23</strong>
</p>
<p>
<strong>176.</strong>
</p>
<p class="TableOfProvisions">
<strong>176.</strong> <strong>2012, c. 24</strong>
</p>
<p>
<strong>177.</strong>
</p>
<p class="TableOfProvisions">
<strong>177.</strong> <strong>Bill C-31</strong>
</p>