<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Preclearance Act, 2016</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Designation of Ministers</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HLabel1">Part 1</span> - <span class="HTitleText1">Preclearance by the United States in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Definitions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Designation of Preclearance Areas and Preclearance Perimeters</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Powers, Duties and Functions in Preclearance Area and Preclearance Perimeter</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText3">Preclearance</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText3">Other Powers and Justification</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Preclearance Area</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText3">Access</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-12"><span class="HTitleText3">Obligations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-13"><span class="HTitleText3">Powers, Duties and Functions</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-14"><span class="HTitleText2">Preclearance Perimeter</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-15"><span class="HTitleText2">Withdrawal</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-16"><span class="HTitleText2">Seizure and Forfeiture</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-17"><span class="HTitleText2">Police Officers and Border Services Officers</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-18"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-19"><span class="HTitleText2">Civil Liability and Immunity</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-20"><span class="HTitleText2">Limitation on Requests for Extradition or Provisional Arrest</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-21"><span class="HTitleText2">Regulations and Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-22"><span class="HLabel1">Part 2</span> - <span class="HTitleText1">Preclearance by Canada in the United States</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-23"><span class="HTitleText2">Definitions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-24"><span class="HTitleText2">Preclearance</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-25"><span class="HTitleText2">Detention and Delivery under Laws of the United States</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-26"><span class="HTitleText2">Exemption from Compliance on Entry into Canada</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-27"><span class="HTitleText2">Withdrawal</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-28"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-29"><span class="HTitleText2">Offences — Acts or Omissions in Preclearance Area or Preclearance Perimeter</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-30"><span class="HTitleText2">Jurisdiction — Offence by Canadian Officer</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="#h-31"><span class="HLabel1">Part 3</span></span> - <span class="HTitleText1">Related Amendments to the <cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>62.1 - </span><a href="#h-32"><span class="HLabel1">Part 3.1</span> - <span class="HTitleText1">Independent Review</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-33"><span class="HLabel1">Part 4</span> - <span class="HTitleText1">Consequential Amendment, Repeal and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-34"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-35"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-36"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-37"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Locations in Canada in which Preclearance Areas and Preclearance Perimeters May Be Designated</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

