<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Federal Sustainable Development Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">BASIC PRINCIPLE</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HTitleText1">COMMITTEE</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-7"><span class="HTitleText1">OFFICE</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-8"><span class="HTitleText1">SUSTAINABLE DEVELOPMENT ADVISORY COUNCIL</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-9"><span class="HTitleText1">FEDERAL SUSTAINABLE DEVELOPMENT STRATEGY</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-10"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-11"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-12"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-1.html#h-13"><span class="HTitleText2">Auditor General Act</span></a>
</li></ul>
</li><li><a href="page-3.html#h-14"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

