<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Youth Criminal Justice Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-3"><span class="HTitleText1">DECLARATION OF PRINCIPLE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">EXTRAJUDICIAL MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Principles and Objectives</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Warnings, Cautions and Referrals</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Extrajudicial Sanctions</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="page-2.html#h-8"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">ORGANIZATION OF YOUTH CRIMINAL JUSTICE SYSTEM</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Youth Justice Court</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Youth Justice Committees</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Conferences</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Justices of the Peace</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-13"><span class="HTitleText2">Clerks of the Court</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-4.html#h-14"><span class="HTitleText2">Provincial Directors</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-4.html#h-15"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">JUDICIAL MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Consent to Prosecute</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Right to Counsel</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Notices to Parents</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-5.html#h-19"><span class="HTitleText2">Detention before Sentencing</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-5.html#h-20"><span class="HTitleText2">Appearance</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-6.html#h-21"><span class="HTitleText2">Release from or Detention in Custody</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-6.html#h-22"><span class="HTitleText2">Medical and Psychological Reports</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-6.html#h-23"><span class="HTitleText2">Referral to Child Welfare Agency</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-6.html#h-24"><span class="HTitleText2">Adjudication</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-7.html#h-25"><span class="HTitleText2">Appeals</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="page-7.html#h-26"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">SENTENCING</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="page-7.html#h-27"><span class="HTitleText2">Purpose and Principles</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-7.html#h-28"><span class="HTitleText2">Pre-sentence Report</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-8.html#h-29"><span class="HTitleText2">Youth Sentences</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-11.html#h-30"><span class="HTitleText2">Adult Sentence and Election</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-14.html#h-31"><span class="HTitleText2">Effect of Termination of Youth Sentence</span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="page-14.html#h-32"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CUSTODY AND SUPERVISION</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-19.html#h-33"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">PUBLICATION, RECORDS AND INFORMATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="page-19.html#h-34"><span class="HTitleText2">Protection of Privacy of Young Persons</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-19.html#h-35"><span class="HTitleText2">Fingerprints and Photographs</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-19.html#h-36"><span class="HTitleText2">Records That May Be Kept</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-20.html#h-37"><span class="HTitleText2">Access to Records</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-21.html#h-38"><span class="HTitleText2">Disclosure of Information in a Record</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-22.html#h-39"><span class="HTitleText2">Disposition or Destruction of Records and Prohibition on Use and Disclosure</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="page-22.html#h-40"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">GENERAL PROVISIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="page-22.html#h-41"><span class="HTitleText2">Disqualification of Judge</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-22.html#h-42"><span class="HTitleText2">Substitution of Judge</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-22.html#h-43"><span class="HTitleText2">Exclusion from Hearing</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-22.html#h-44"><span class="HTitleText2">Transfer of Charges</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-22.html#h-45"><span class="HTitleText2">Forfeiture of Recognizances</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-23.html#h-46"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-23.html#h-47"><span class="HTitleText2">Application of Criminal Code</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-24.html#h-48"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-24.html#h-49"><span class="HTitleText2">Evidence</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-25.html#h-50"><span class="HTitleText2">Forms, Regulations and Rules of Court</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-25.html#h-51"><span class="HTitleText2">Agreements with Provinces</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-25.html#h-52"><span class="HTitleText2">Programs</span></a>
</li></ul>
</li><li><span class='sectionRange'>158 - </span><a href="page-25.html#h-53"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-26.html#h-54"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">CONSEQUENTIAL AMENDMENTS, REPEAL AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="page-26.html#h-55"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="page-26.html#h-56"><span class="HTitleText3">Canada Evidence Act</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-26.html#h-57"><span class="HTitleText3">Contraventions Act</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-26.html#h-58"><span class="HTitleText3">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-26.html#h-59"><span class="HTitleText3">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-27.html#h-60"><span class="HTitleText3">DNA Identification Act</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-28.html#h-61"><span class="HTitleText3">Extradition Act</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="page-28.html#h-62"><span class="HTitleText3">Mutual Legal Assistance in Criminal Matters Act</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="page-28.html#h-63"><span class="HTitleText3">Prisons and Reformatories Act</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="page-29.html#h-64"><span class="HTitleText3">Transfer of Offenders Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>199 - </span><a href="page-29.html#h-65"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="page-29.html#h-66"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-30.html#h-67"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

