<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2005</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF INCOME TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-4"><span class="HTitleText2">Income Tax Application Rules</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF THE AIR TRAVELLERS SECURITY CHARGE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-6"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-7"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-8"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF THE GOODS AND SERVICES TAX AND HARMONIZED SALES TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF EXCISE TAX ON JEWELLERY, ETC.</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-12"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">AMENDMENTS TO THE FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="#h-13"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">NORTHERN STRATEGY</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-16"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">AUDITOR GENERAL OF CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-17"><span class="HTitleText2">Amendments to the Auditor General Act</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-18"><span class="HTitleText2">Amendments to the Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-19"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Broadcasting Act</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-21"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Post Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-22"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Race Relations Foundation Act</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-23"><span class="HTitleText3"><cite class="XRefExternalAct">Public Sector Pension Investment Board Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>50 - </span><a href="#h-24"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-25"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">PAYMENTS TO CERTAIN ENTITIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="#h-26"><span class="HTitleText2">Aboriginal Healing Foundation</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-27"><span class="HTitleText2">Asia-Pacific Foundation of Canada</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-28"><span class="HTitleText2">Canadian Academies of Science</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-29"><span class="HTitleText2">Canadian Cattlemen’s Association</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-30"><span class="HTitleText2">Canadian Youth Business Foundation</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-31"><span class="HTitleText2">Federation of Canadian Municipalities</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-32"><span class="HTitleText2">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-33"><span class="HTitleText2">Precarn Incorporated</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-34"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">ASIA-PACIFIC FOUNDATION OF CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-35"><span class="HTitleText2">Asia-Pacific Foundation of Canada Act</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-36"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-37"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">AMENDMENT TO THE BUDGET IMPLEMENTATION ACT, 1998</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-38"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">PAYMENTS FOR INFRASTRUCTURE</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-39"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">NOVA SCOTIA AND NEWFOUNDLAND AND LABRADOR ADDITIONAL FISCAL EQUALIZATION OFFSET PAYMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="#h-40"><span class="HTitleText2">Nova Scotia and Newfoundland and Labrador Additional Fiscal Equalization Offset Payments Act</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-41"><span class="HTitleText2">Related Amendment to the Budget Implementation Act, 2004</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="#h-42"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">CANADA EMISSION REDUCTION INCENTIVES AGENCY</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="#h-43"><span class="HTitleText2">Canada Emission Reduction Incentives Agency Act</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-44"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="#h-45"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-46"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-47"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-48"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-49"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>93 - </span><a href="#h-50"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-51"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="#h-52"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">GREENHOUSE GAS TECHNOLOGY INVESTMENT FUND</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>96 - </span><a href="#h-53"><span class="HTitleText2"><strong>Greenhouse Gas Technology Investment Fund Act</strong></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-54"><span class="HTitleText2"><strong>Coming into Force</strong></span></a>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="#h-55"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">AMENDMENTS TO THE CANADA DEPOSIT INSURANCE CORPORATION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="#h-56"><span class="HTitleText2">Canada Deposit Insurance Corporation Act</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-57"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-58"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">AMENDMENTS TO THE CANADA STUDENT FINANCIAL ASSISTANCE ACT</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-59"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">AMENDMENTS TO THE CURRENCY ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>113 - </span><a href="#h-60"><span class="HTitleText2">Exchange Fund Account</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-61"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-62"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>120 - </span><a href="#h-63"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">AMENDMENTS TO THE DEPARTMENT OF PUBLIC WORKS AND GOVERNMENT SERVICES ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-64"><span class="HTitleText2">Department of Public Works and Government Services Act</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-65"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="#h-66"><span class="HLabel1">PART 19</span> - <span class="HTitleText1">AMENDMENTS RELATED TO THE PREMIUM RATE PROVIDED FOR UNDER THE EMPLOYMENT INSURANCE ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-67"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-68"><span class="HTitleText2">Department of Human Resources Development Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-69"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-70"><span class="HLabel1">PART 20</span> - <span class="HTitleText1">AMENDMENTS TO THE EMPLOYMENT INSURANCE ACT (PROVINCIAL PLANS)</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-71"><span class="HLabel1">PART 21</span> - <span class="HTitleText1">AMENDMENTS TO THE FINANCIAL ADMINISTRATION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="#h-72"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-73"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="#h-74"><span class="HLabel1">PART 22</span> - <span class="HTitleText1">AMENDMENTS TO THE OLD AGE SECURITY ACT</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-75"><span class="HLabel1">PART 23</span> - <span class="HTitleText1">PAYMENTS TO CERTAIN PROVINCES AND TERRITORIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="#h-76"><span class="HTitleText2">Payment to Quebec</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-77"><span class="HTitleText2">Payment to British Columbia</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-78"><span class="HTitleText2">Payment to Saskatchewan</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-79"><span class="HTitleText2">Payment to Yukon</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-80"><span class="HTitleText2">Payment to the Northwest Territories</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-81"><span class="HTitleText2">Payment to Nunavut</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

