<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Quarantine Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">BINDING ON HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">POWERS OF MINISTER</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-6"><span class="HTitleText1">TRAVELLERS</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-7"><span class="HTitleText1">CONVEYANCES</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-8"><span class="HTitleText1">CADAVERS, BODY PARTS AND OTHER HUMAN REMAINS</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-9"><span class="HTitleText1">GENERAL POWERS</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-10"><span class="HTitleText1">INFORMATION</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-11"><span class="HTitleText1">EMERGENCY ORDERS</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-12"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-13"><span class="HTitleText1">STATUTORY INSTRUMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-14"><span class="HTitleText1">OFFENCES AND PUNISHMENT</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-15"><span class="HTitleText1">RELATED PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-16"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>81 - </span><a href="#h-17"><span class="HTitleText2">Immigration and Refugee Protection Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-18"><span class="HTitleText1">REPEAL</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-19"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-20"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-21"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

