<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Criminal Code and another Act</a><ul class="TocIndent"><li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERNATIONAL TRANSFER OF OFFENDERS ACT</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

