<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Fair Elections Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA ELECTIONS ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-15.html#h-4"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="page-16.html#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">ELECTORAL BOUNDARIES READJUSTMENT ACT</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-16.html#h-6"><span class="HTitleText1">TELECOMMUNICATIONS ACT</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-17.html#h-7"><span class="HTitleText1"><cite class="XRefExternalAct">CONFLICT OF INTEREST ACT</cite></span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-17.html#h-8"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>146 - </span><a href="page-17.html#h-9"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-17.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Electoral Boundaries Readjustment Act</cite></span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-17.html#h-11"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-17.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-17.html#h-13"><span class="HTitleText2">Director of Public Prosecutions Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="page-17.html#h-14"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-18.html#h-15"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-19.html#h-16"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

