<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Oil Tanker Moratorium Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-4"><span class="HTitleText1">Rights of Indigenous Peoples of Canada</span></a>
</li>
<li><span class='sectionRange'>3.2 - </span><a href="#h-5"><span class="HTitleText1">Duty of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-6"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText1">Exemptions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-9"><span class="HTitleText2">Reporting Requirement</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-10"><span class="HTitleText2">Designated Persons</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-11"><span class="HTitleText3">Powers</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-12"><span class="HTitleText3">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-13"><span class="HTitleText2">Detention of Vessels</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-14"><span class="HTitleText2">Sale of Vessels</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-16"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-17"><span class="HTitleText1">Summary Conviction Proceedings</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-18"><span class="HTitleText1">Review and Report</span></a>
</li>
<li><a href="#h-19"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

