<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Patent Act and the Food and Drugs Act (The Jean Chrétien Pledge to Africa)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">PATENT ACT</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">FOOD AND DRUGS ACT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-4"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-5"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-6"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li></ul>
</li></ul>

</nav>

