<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Patent Act and the Food and Drugs Act (The Jean Chrétien Pledge to Africa)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">PATENT ACT</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-2.html#h-2"><span class="HTitleText1">FOOD AND DRUGS ACT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-3"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-3.html#h-4"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-4.html#h-5"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-5.html#h-6"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-6.html#h-7"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li></ul>
</li></ul>

</nav>

