<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Criminal Code, the DNA Identification Act and the National Defence Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-4.html#h-2"><span class="HTitleText1">DNA IDENTIFICATION ACT</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-5.html#h-3"><span class="HTitleText1">NATIONAL DEFENCE ACT</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="page-6.html#h-4"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-6.html#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

