<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Faster Removal of Foreign Criminals Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">IMMIGRATION AND REFUGEE PROTECTION ACT</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-4"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

