<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Protection of Communities and Exploited Persons Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL CODE</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Records Act</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Youth Criminal Justice Act</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">International Transfer of Offenders Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>45.1 - </span><a href="#h-10"><span class="HTitleText1">REVIEW AND REPORT</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-11"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-12"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

