<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Protection of Communities and Exploited Persons Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL CODE</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="page-4.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Records Act</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-5.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-5.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Youth Criminal Justice Act</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-5.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">International Transfer of Offenders Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>45.1 - </span><a href="page-5.html#h-10"><span class="HTitleText1">REVIEW AND REPORT</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-11"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-6.html#h-12"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

