<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Tax Convention and Arrangement Implementation Act, 2016</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Canada–Israel Tax Convention</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Canada and Taiwan Territories Tax Arrangement</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART 3</span></span> - <span class="HTitleText1">Canada–Hong Kong Tax Agreement Act, 2013</span></a>
</li>
<li><a href="#h-5"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-6"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

