<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Criminal Law Amendment Act, 2001</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>696.1 - </span><a href="page-7.html#h-3"><span class="HLabel1">PART XXI.1</span> - <span class="HTitleText1">APPLICATIONS FOR MINISTERIAL REVIEW — MISCARRIAGES OF JUSTICE</span></a>
</li>
<li><span class='sectionRange'>841 - </span><a href="page-9.html#h-4"><span class="HLabel1">PART XXVIII</span> - <span class="HTitleText1">MISCELLANEOUS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>841 - </span><a href="page-9.html#h-5"><span class="HTitleText2">Electronic Documents</span></a>
</li>
<li><span class='sectionRange'>848 - </span><a href="page-9.html#h-6"><span class="HTitleText2">Remote Appearance by Incarcerated Accused</span></a>
</li>
<li><span class='sectionRange'>849 - </span><a href="page-9.html#h-7"><span class="HTitleText2">Forms</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="page-9.html#h-8"><span class="HTitleText1">NATIONAL CAPITAL ACT</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-9.html#h-9"><span class="HTitleText1">NATIONAL DEFENCE ACT</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-10.html#h-10"><span class="HTitleText1">YOUNG OFFENDERS ACT</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-10.html#h-11"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-10.html#h-12"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

