<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Economic Action Plan 2013 Act, No. 2</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">MEASURES RELATING TO INCOME TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Keeping Canada’s Economy and Jobs Growing Act</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-6"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">EXCISE TAX ACT</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-8"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">VARIOUS MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>125 - </span><a href="#h-9"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Employment Insurance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>125 - </span><a href="#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Employment Insurance Financing Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-12"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="#h-13"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Not-for-profit Corporations Act</cite></span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-14"><span class="HTitleText4"><cite class="XRefExternalAct">Jobs, Growth and Long-term Prosperity Act</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-15"><span class="HTitleText4"><cite class="XRefExternalAct">Jobs and Growth Act, 2012</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>157 - </span><a href="#h-16"><span class="HTitleText3"><cite class="XRefExternalRegulation">Employment Insurance (Fishing) Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-17"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-18"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Financial Institutions (Conflicts of Interest)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Office of the Superintendent of Financial Institutions Act</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-21"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-22"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-23"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Consumer Agency of Canada Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>167 - </span><a href="#h-24"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Financial Institutions (Investments)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="#h-25"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-28"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>174 - </span><a href="#h-29"><span class="HLabel2">Division 4</span> - <span class="HTitleText2">Passports</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>174 - </span><a href="#h-30"><span class="HTitleText3"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-31"><span class="HTitleText3">Amendment to the <cite class="XRefExternalAct">Department of Foreign Affairs, Trade and Development Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>176 - </span><a href="#h-32"><span class="HLabel2">Division 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>176 - </span><a href="#h-33"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-34"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-35"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="#h-36"><span class="HTitleText4"><cite class="XRefExternalAct">National Energy Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-37"><span class="HTitleText4"><cite class="XRefExternalAct">Hazardous Materials Information Review Act</cite></span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-38"><span class="HTitleText4"><cite class="XRefExternalAct">Non-smokers’ Health Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>203 - </span><a href="#h-39"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>204 - </span><a href="#h-40"><span class="HLabel2">Division 6</span> - <span class="HTitleText2">Changes to the Canadian Ministry</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>204 - </span><a href="#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Human Resources and Skills Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Salaries Act</cite></span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-43"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-44"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>221 - </span><a href="#h-45"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-46"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-47"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-48"><span class="HTitleText4"><cite class="XRefExternalAct">Family Orders and Agreements Enforcement Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-49"><span class="HTitleText4"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-50"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Student Financial Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>236 - </span><a href="#h-53"><span class="HTitleText3">Terminology</span></a>
</li></ul>
</li><li><span class='sectionRange'>239 - </span><a href="#h-54"><span class="HLabel2">Division 7</span> - <span class="HTitleText2">Dominion Coal Blocks</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-55"><span class="HLabel2">Division 8</span> - <span class="HTitleText2">Reorganization of Certain Crown Corporations (Bridges)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>249 - </span><a href="#h-56"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="#h-57"><span class="HTitleText3">Amalgamation</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-58"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>261 - </span><a href="#h-59"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-60"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Marine Act</cite></span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="#h-61"><span class="HTitleText4"><cite class="XRefExternalAct">International Bridges and Tunnels Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>264 - </span><a href="#h-62"><span class="HTitleText3">Repeals</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="#h-63"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>270 - </span><a href="#h-64"><span class="HLabel2">Division 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-65"><span class="HLabel2">Division 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">National Research Council Act</cite></span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="#h-66"><span class="HLabel2">Division 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Veterans Review and Appeal Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>277 - </span><a href="#h-67"><span class="HLabel2">Division 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan Investment Board Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>277 - </span><a href="#h-68"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-69"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>279 - </span><a href="#h-70"><span class="HLabel2">Division 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>279 - </span><a href="#h-71"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="#h-72"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>282 - </span><a href="#h-73"><span class="HLabel2">Division 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Mackenzie Gas Project Impacts Fund Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>282 - </span><a href="#h-74"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="#h-75"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>283 - </span><a href="#h-76"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>284 - </span><a href="#h-77"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>285 - </span><a href="#h-78"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="#h-79"><span class="HTitleText4"><cite class="XRefExternalAct">Budget Implementation Act, 2006</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>287 - </span><a href="#h-80"><span class="HTitleText3">Repeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>288 - </span><a href="#h-81"><span class="HLabel2">Division 15</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Conflict of Interest Act</cite></span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="#h-82"><span class="HLabel2">Division 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>290 - </span><a href="#h-83"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="#h-84"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>294 - </span><a href="#h-85"><span class="HLabel2">Division 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Public Service Labour Relations</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>294 - </span><a href="#h-86"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Labour Relations Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>294 - </span><a href="#h-87"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>338 - </span><a href="#h-88"><span class="HTitleText4">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>340 - </span><a href="#h-89"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Human Rights Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>340 - </span><a href="#h-90"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>341 - </span><a href="#h-91"><span class="HTitleText4">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>342 - </span><a href="#h-92"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>342 - </span><a href="#h-93"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>360 - </span><a href="#h-94"><span class="HTitleText4">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>361 - </span><a href="#h-95"><span class="HTitleText3"><cite class="XRefExternalAct">Public Sector Equitable Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>363 - </span><a href="#h-96"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>364 - </span><a href="#h-97"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>365 - </span><a href="#h-98"><span class="HLabel2">Division 18</span> - <span class="HTitleText2">Reorganization of Federal Public Service Labour Relations and Employment Boards</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>365 - </span><a href="#h-99"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Labour Relations and Employment Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="#h-100"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Labour Relations Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>366 - </span><a href="#h-101"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>391 - </span><a href="#h-102"><span class="HTitleText4">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>403 - </span><a href="#h-103"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>403 - </span><a href="#h-104"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>415 - </span><a href="#h-105"><span class="HTitleText4">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>425 - </span><a href="#h-106"><span class="HTitleText3"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>425 - </span><a href="#h-107"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>438 - </span><a href="#h-108"><span class="HTitleText4">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>439 - </span><a href="#h-109"><span class="HTitleText3"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>439 - </span><a href="#h-110"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>440 - </span><a href="#h-111"><span class="HTitleText4">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>441 - </span><a href="#h-112"><span class="HTitleText3"><cite class="XRefExternalAct">Public Sector Equitable Compensation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>441 - </span><a href="#h-113"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>445 - </span><a href="#h-114"><span class="HTitleText4">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>446 - </span><a href="#h-115"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>446 - </span><a href="#h-116"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>448 - </span><a href="#h-117"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-118"><span class="HTitleText4"><cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite></span></a>
</li>
<li><span class='sectionRange'>450 - </span><a href="#h-119"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>459 - </span><a href="#h-120"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>461 - </span><a href="#h-121"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>464 - </span><a href="#h-122"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>466 - </span><a href="#h-123"><span class="HTitleText4"><cite class="XRefExternalAct">Status of the Artist Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>467 - </span><a href="#h-124"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>470 - </span><a href="#h-125"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>471 - </span><a href="#h-126"><span class="HLabel2">Division 19</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Supreme Court Act</cite></span></a>
</li></ul>
</li><li><a href="#h-127"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

