<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Marine Liability Act and the Federal Courts Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">MARINE LIABILITY ACT</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-2"><span class="HTitleText1">FEDERAL COURTS ACT</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-4"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-5"><span class="HTitleText2">Arctic Waters Pollution Prevention Act</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-6"><span class="HTitleText2">Nunavut Waters and Nunavut Surface Rights Tribunal Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-8"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

