<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2017, No. 2</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Income Tax Act</cite> and to Related Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-6"><span class="HTitleText2">Regulations Amending the <cite class="XRefExternalRegulation">Income Tax Regulations</cite> (Omnibus, No. 3)</span></a>
</li></ul>
</li><li><span class='sectionRange'>106 - </span><a href="#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Tax Act</cite> and to Related Legislation (GST/HST Measures)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>106 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalRegulation">Public Service Body Rebate (GST/HST) Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalRegulation">Specified Crown Agents (GST/HST) Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-11"><span class="HLabel1">PART 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Excise Act</cite></span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-12"><span class="HLabel1">PART 4</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-13"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>172 - </span><a href="#h-14"><span class="HLabel2">DIVISION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Bretton Woods and Related Agreements Act</cite></span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-15"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Asian Infrastructure Investment Bank Agreement Act</cite></span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-16"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">International Development Financing Agreements</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-17"><span class="HLabel2">DIVISION 4</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>180 - </span><a href="#h-18"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-19"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">Payment Clearing and Settlement Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-20"><span class="HLabel2">DIVISION 5</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>185 - </span><a href="#h-21"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-22"><span class="HTitleText3">Related Amendments to the <cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-23"><span class="HTitleText3">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>188 - </span><a href="#h-24"><span class="HLabel2">DIVISION 6</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Payment Clearing and Settlement Act</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-25"><span class="HLabel2">DIVISION 7</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Northern Pipeline Act</cite></span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-26"><span class="HLabel2">DIVISION 8</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>195 - </span><a href="#h-27"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-28"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-29"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-30"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>217 - </span><a href="#h-31"><span class="HLabel2">DIVISION 9</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Economic Action Plan 2015 Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-32"><span class="HLabel2">DIVISION 10</span> - <span class="HTitleText2">Trade within Canada and Harmonization of Energy Efficiency Requirements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>219 - </span><a href="#h-33"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Free Trade Agreement Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-34"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-35"><span class="HTitleText3">Related Amendments to the <cite class="XRefExternalAct">Energy Efficiency Act</cite></span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-36"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>223 - </span><a href="#h-37"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-38"><span class="HTitleText4"><cite class="XRefExternalAct">Department of Public Works and Government Services Act</cite></span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-39"><span class="HTitleText4"><cite class="XRefExternalRegulation">Procurement Ombudsman Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-40"><span class="HTitleText3">Repeals</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-41"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>230 - </span><a href="#h-42"><span class="HLabel2">DIVISION 11</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Judges Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>230 - </span><a href="#h-43"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-44"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-45"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>255 - </span><a href="#h-46"><span class="HTitleText4"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="#h-47"><span class="HTitleText4"><cite class="XRefExternalAct">Nunavut Act</cite></span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-48"><span class="HTitleText4"><cite class="XRefExternalAct">Yukon Act</cite></span></a>
</li>
<li><span class='sectionRange'>258 - </span><a href="#h-49"><span class="HTitleText4"><cite class="XRefExternalAct">Northwest Territories Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>259 - </span><a href="#h-50"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="#h-51"><span class="HLabel2">DIVISION 12</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Business Development Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-52"><span class="HLabel2">DIVISION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li></ul>
</li><li><a href="#h-53"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

