<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend certain Acts that relate to the environment and to enact provisions respecting the enforcement of certain Acts that relate to the environment</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">ANTARCTIC ENVIRONMENTAL PROTECTION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA NATIONAL MARINE CONSERVATION AREAS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-5.html#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA NATIONAL PARKS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-8.html#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA WILDLIFE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-10.html#h-6"><span class="HTitleText1"><cite class="XRefExternalAct">CANADIAN ENVIRONMENTAL PROTECTION ACT, 1999</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-15.html#h-7"><span class="HTitleText1"><cite class="XRefExternalAct">INTERNATIONAL RIVER IMPROVEMENTS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-16.html#h-8"><span class="HTitleText1"><cite class="XRefExternalAct">MIGRATORY BIRDS CONVENTION ACT, 1994</cite></span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-18.html#h-9"><span class="HTitleText1"><cite class="XRefExternalAct">SAGUENAY-ST. LAWRENCE MARINE PARK ACT</cite></span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-20.html#h-10"><span class="HTitleText1"><cite class="XRefExternalAct">WILD ANIMAL AND PLANT PROTECTION AND REGULATION OF INTERNATIONAL AND INTERPROVINCIAL TRADE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-21.html#h-11"><span class="HTitleText1"><cite class="XRefExternalAct">ENACTMENT OF THE ENVIRONMENTAL VIOLATIONS ADMINISTRATIVE MONETARY PENALTIES ACT</cite></span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-22.html#h-12"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-22.html#h-13"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

