<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Public Safety and Emergency Preparedness Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">ESTABLISHMENT OF THE DEPARTMENT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">POWERS, DUTIES AND FUNCTIONS OF THE MINISTER</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HTitleText2">Canadian Centre on Substance Abuse Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText2">Canadian Peacekeeping Service Medal Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText2">Canadian Security Intelligence Service Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText2">Citizenship Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-11"><span class="HTitleText2">Controlled Drugs and Substances Act</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText2">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText2">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-14"><span class="HTitleText2">DNA Identification Act</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-15"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-16"><span class="HTitleText2">Firearms Act</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-17"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-18"><span class="HTitleText2">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-19"><span class="HTitleText2">Terminology Changes</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-20"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-21"><span class="HTitleText1">REPEAL</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-22"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

