<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Justice for Victims of Corrupt Foreign Officials Act (Sergei Magnitsky Law)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Orders and Regulations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Duty to Determine</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Disclosure</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText1">Rights of Foreign Nationals Who are the Subject of an Order or Regulation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8"><span class="HTitleText1">Application for a Certificate</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-9"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText1">Review and Report</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Special Economic Measures Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>

