<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Excise Act, 2001</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-3"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">APPLICATION AND ADMINISTRATIVE MATTERS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Application to Her Majesty</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Administration and Officers</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Inquiries</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-2.html#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">LICENCES AND REGISTRATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Registrations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Excise Warehouses</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Special Excise Warehouses</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Duty Free Shops</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-13"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="page-3.html#h-14"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">TOBACCO</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Regulation of Tobacco</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Duty on Tobacco</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Excise Warehouses</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-18"><span class="HTitleText2">Special Duties on Tobacco Products</span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="page-5.html#h-19"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">ALCOHOL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="page-5.html#h-20"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-6.html#h-21"><span class="HTitleText2">Bulk Alcohol</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-6.html#h-22"><span class="HTitleText2">Special Containers of Spirits</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-6.html#h-23"><span class="HTitleText2">Special Containers of Wine</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-6.html#h-24"><span class="HTitleText2">Packaged Alcohol</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-7.html#h-25"><span class="HTitleText2">Denatured Alcohol and Specially Denatured Alcohol</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-7.html#h-26"><span class="HTitleText2">Responsibility for Bulk Spirits</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-8.html#h-27"><span class="HTitleText2">Responsibility for Bulk Wine</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-8.html#h-28"><span class="HTitleText2">Imposition and Payment of Duty on Alcohol</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-9.html#h-29"><span class="HTitleText2">Liability of Excise Warehouse Licensees and Licensed Users</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-10.html#h-30"><span class="HTitleText2">Non-dutiable Uses and Removals of Alcohol</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-10.html#h-31"><span class="HTitleText2">Determining Volume of Alcohol</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-10.html#h-32"><span class="HTitleText2">Excise Warehouses</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="page-11.html#h-33"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">GENERAL PROVISIONS CONCERNING DUTY AND OTHER AMOUNTS PAYABLE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="page-11.html#h-34"><span class="HTitleText2">Fiscal Month</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-11.html#h-35"><span class="HTitleText2">Returns and Payment of Duty and Other Amounts</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-11.html#h-36"><span class="HTitleText2">Interest</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-12.html#h-37"><span class="HTitleText2">Refunds</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-13.html#h-38"><span class="HTitleText2">Assessments</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="page-14.html#h-39"><span class="HTitleText2">Objections to Assessment</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-15.html#h-40"><span class="HTitleText2">Appeal</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="page-16.html#h-41"><span class="HTitleText2">Records and Information</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="page-17.html#h-42"><span class="HTitleText2">Bankruptcies and Corporate Reorganizations</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="page-18.html#h-43"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">ENFORCEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="page-18.html#h-44"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-19.html#h-45"><span class="HTitleText2">Proceeds of Crime</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-19.html#h-46"><span class="HTitleText2">Penalties</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="page-20.html#h-47"><span class="HTitleText2">Penalty Imposition</span></a>
</li>
<li><span class='sectionRange'>258 - </span><a href="page-21.html#h-48"><span class="HTitleText2">Search Warrants</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="page-21.html#h-49"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="page-21.html#h-50"><span class="HTitleText2">Return or Disposal of Things Seized</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="page-22.html#h-51"><span class="HTitleText2">Forfeitures</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="page-22.html#h-52"><span class="HTitleText2">Review of Imposed Penalty or Seizure</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="page-23.html#h-53"><span class="HTitleText2">Third Party Claims</span></a>
</li>
<li><span class='sectionRange'>284 - </span><a href="page-23.html#h-54"><span class="HTitleText2">Collection</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="page-26.html#h-55"><span class="HTitleText2">Evidence and Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>304 - </span><a href="page-27.html#h-56"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="page-27.html#h-57"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">TRANSITIONAL PROVISIONS AND CONSEQUENTIAL, RELATED AND COORDINATING AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>305 - </span><a href="page-27.html#h-58"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>321 - </span><a href="page-29.html#h-59"><span class="HTitleText2">Consequential and Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>321 - </span><a href="page-29.html#h-60"><span class="HTitleText3">Budget Implementation Act, 2000</span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="page-29.html#h-61"><span class="HTitleText3">Canada Customs and Revenue Agency Act</span></a>
</li>
<li><span class='sectionRange'>324 - </span><a href="page-29.html#h-62"><span class="HTitleText3">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>328 - </span><a href="page-29.html#h-63"><span class="HTitleText3">Customs Act</span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="page-31.html#h-64"><span class="HTitleText3">Customs and Excise Offshore Application Act</span></a>
</li>
<li><span class='sectionRange'>346 - </span><a href="page-31.html#h-65"><span class="HTitleText3">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>363 - </span><a href="page-32.html#h-66"><span class="HTitleText3">Excise Act</span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="page-32.html#h-67"><span class="HTitleText3">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="page-34.html#h-68"><span class="HTitleText3">Export Act</span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="page-35.html#h-69"><span class="HTitleText3">Importation of Intoxicating Liquors Act</span></a>
</li>
<li><span class='sectionRange'>396 - </span><a href="page-35.html#h-70"><span class="HTitleText3">Special Economic Measures Act</span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="page-35.html#h-71"><span class="HTitleText3">Tax Court of Canada Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>408 - </span><a href="page-36.html#h-72"><span class="HTitleText2">Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>408 - </span><a href="page-36.html#h-73"><span class="HTitleText3">An Act to amend the Customs Act and to make related amendments to other Acts</span></a>
</li>
<li><span class='sectionRange'>409 - </span><a href="page-37.html#h-74"><span class="HTitleText3">Bill C-24</span></a>
</li>
<li><span class='sectionRange'>410 - </span><a href="page-37.html#h-75"><span class="HTitleText3">Bill C-30</span></a>
</li>
<li><span class='sectionRange'>411 - </span><a href="page-37.html#h-76"><span class="HTitleText3">Bill C-32</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>412 - </span><a href="page-38.html#h-77"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">AMENDMENTS RELATED TO EXCISE TAX ON TOBACCO PRODUCTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>412 - </span><a href="page-38.html#h-78"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>413 - </span><a href="page-38.html#h-79"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>422 - </span><a href="page-38.html#h-80"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">AMENDMENTS RELATED TO SHIPS’ STORES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>422 - </span><a href="page-38.html#h-81"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>423 - </span><a href="page-38.html#h-82"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>424 - </span><a href="page-38.html#h-83"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>425 - </span><a href="page-38.html#h-84"><span class="HTitleText2">Excise Act</span></a>
</li>
<li><span class='sectionRange'>426 - </span><a href="page-38.html#h-85"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>427 - </span><a href="page-38.html#h-86"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>430 - </span><a href="page-39.html#h-87"><span class="HTitleText2">Ships’ Stores Regulations</span></a>
</li>
<li><span class='sectionRange'>431 - </span><a href="page-40.html#h-88"><span class="HTitleText2">Ships’ Stores Regulations</span></a>
</li>
<li><span class='sectionRange'>432 - </span><a href="page-40.html#h-89"><span class="HTitleText2">Ships Suppliers Drawback Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>433 - </span><a href="page-40.html#h-90"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-41.html#h-91"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - RATES OF DUTY ON TOBACCO PRODUCTS</span></a>
</li>
<li><a href="page-42.html#h-92"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - ADDITIONAL DUTY ON CIGARS</span></a>
</li>
<li><a href="page-43.html#h-93"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - RATES OF SPECIAL DUTIES ON CERTAIN MANUFACTURED TOBACCO</span></a>
</li>
<li><a href="page-44.html#h-94"><span class="scheduleLabel">SCHEDULE 4</span> <span class="scheduleTitleText"> - RATES OF DUTY ON SPIRITS</span></a>
</li>
<li><a href="page-45.html#h-95"><span class="scheduleLabel">SCHEDULE 5</span> <span class="scheduleTitleText"> - RATE OF SPECIAL DUTY ON SPIRITS</span></a>
</li>
<li><a href="page-46.html#h-96"><span class="scheduleLabel">SCHEDULE 6</span> <span class="scheduleTitleText"> - RATES OF DUTY ON WINE</span></a>
</li></ul>
</li></ul>

</nav>

