<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Budget Implementation Act, 2003</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">DIAGNOSTIC AND MEDICAL EQUIPMENT</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">STUDENT LOANS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-2.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Student Financial Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-3.html#h-6"><span class="HTitleText2">Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-3.html#h-7"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="page-3.html#h-8"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">EMPLOYMENT INSURANCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-3.html#h-9"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-5.html#h-10"><span class="HTitleText2">Employment Insurance (Fishing) Regulations</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-5.html#h-11"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-5.html#h-12"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="page-5.html#h-13"><span class="HTitleText3">Canada Labour Code</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="page-6.html#h-14"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="page-6.html#h-15"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">GENERAL — NON-TAX MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-6.html#h-16"><span class="HTitleText2">Foundations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-6.html#h-17"><span class="HTitleText3">Budget Implementation Act, 1997</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-6.html#h-18"><span class="HTitleText3">Budget Implementation Act, 1998</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-6.html#h-19"><span class="HTitleText3">Canada Foundation for Sustainable Development Technology Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-6.html#h-20"><span class="HTitleText2">Appropriations for Grants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="page-6.html#h-21"><span class="HTitleText3">Canada Foundation for Sustainable Development Technology</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-6.html#h-22"><span class="HTitleText3">Canadian Foundation for Climate and Atmospheric Sciences</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-6.html#h-23"><span class="HTitleText3">Canada Health Infoway Inc.</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-6.html#h-24"><span class="HTitleText3">Canadian Health Services Research Foundation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-6.html#h-25"><span class="HTitleText3">Canadian Institute for Health Information</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-6.html#h-26"><span class="HTitleText3">Canada Foundation for Innovation</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-6.html#h-27"><span class="HTitleText3">Genome Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-6.html#h-28"><span class="HTitleText2">Amendments to the Farm Credit Canada Act</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-6.html#h-29"><span class="HTitleText2">Repeal of Debt Servicing and Reduction Account Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="page-6.html#h-30"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">AMENDMENTS TO THE AIR TRAVELLERS SECURITY CHARGE ACT</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-6.html#h-31"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">AMENDMENTS RELATED TO THE TAXATION OF TOBACCO PRODUCTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-6.html#h-32"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-6.html#h-33"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-7.html#h-34"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-7.html#h-35"><span class="HTitleText2">Coming into Force and Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="page-7.html#h-36"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">AMENDMENTS RELATED TO EXCISE TAX ON FUEL AND TO THE GOODS AND SERVICES TAX/HARMONIZED SALES TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="page-7.html#h-37"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-8.html#h-38"><span class="HTitleText2">Consequential Amendment to Excise Act, 2001</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-8.html#h-39"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">FIRST NATIONS GOODS AND SERVICES TAXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="page-8.html#h-40"><span class="HTitleText2">First Nations Goods and Services Tax Act</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-9.html#h-41"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="page-9.html#h-42"><span class="HTitleText3">Excise Tax Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>69 - </span><a href="page-9.html#h-43"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">AMENDMENTS TO THE INCOME TAX ACT AND ANOTHER ACT AS A CONSEQUENCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="page-9.html#h-44"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-13.html#h-45"><span class="HTitleText2">Children’s Special Allowances Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="page-13.html#h-46"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">AMENDMENTS RELATED TO STANDARDIZED ACCOUNTING</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-13.html#h-47"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-13.html#h-48"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-15.html#h-49"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-16.html#h-50"><span class="HTitleText2">Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="page-16.html#h-51"><span class="HTitleText3">Excise Act, 2001</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-17.html#h-52"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

