<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Jobs and Growth Act, 2012</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">INCOME TAX ACT</cite> AND RELATED REGULATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Canada Disability Savings Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="#h-6"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">MEASURES IN RESPECT OF SALES TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>74 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Jobs and Economic Growth Act</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalRegulation">Input Tax Credit Allocation Methods (GST/HST) Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>97 - </span><a href="#h-10"><span class="HLabel1">PART 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-11"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">VARIOUS MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-12"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Financial Institutions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Trust And Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Jobs and Economic Growth Act</cite></span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-17"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>156 - </span><a href="#h-18"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Shipping</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Shipping Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-20"><span class="HTitleText3">Services Provided by Classification Societies</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-21"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>166 - </span><a href="#h-22"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Preserving the Stability and Strength of Canada’s Financial Sector</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="#h-23"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-24"><span class="HTitleText3"><cite class="XRefExternalAct">Payment Clearing and Settlement Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>173 - </span><a href="#h-25"><span class="HLabel2">Division 4</span> - <span class="HTitleText2">Fisheries</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Fisheries Act</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Jobs, Growth and Long-term Prosperity Act</cite></span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-28"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-29"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="#h-30"><span class="HLabel2">Division 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Bridge To Strengthen Trade Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-31"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-32"><span class="HTitleText3">Related Amendments to the <cite class="XRefExternalAct">International Bridges and Tunnels Act</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-33"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-34"><span class="HLabel2">Division 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Bretton Woods and Related Agreements Act</cite></span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-35"><span class="HLabel2">Division 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="#h-36"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-37"><span class="HTitleText3">Related Amendment to the <cite class="XRefExternalAct">Department of Human Resources and Skills Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-38"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-39"><span class="HLabel2">Division 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Indian Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="#h-40"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-41"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>210 - </span><a href="#h-42"><span class="HLabel2">Division 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Judges Act</cite></span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-43"><span class="HLabel2">Division 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>219 - </span><a href="#h-44"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-45"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-46"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>233 - </span><a href="#h-47"><span class="HLabel2">Division 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Merchant Seamen Compensation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>233 - </span><a href="#h-48"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-49"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-50"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>261 - </span><a href="#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>263 - </span><a href="#h-53"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>264 - </span><a href="#h-54"><span class="HLabel2">Division 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>264 - </span><a href="#h-55"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-56"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>269 - </span><a href="#h-57"><span class="HLabel2">Division 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Hazardous Materials Information Review Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>269 - </span><a href="#h-58"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>285 - </span><a href="#h-59"><span class="HTitleText3">Transfer of Employees and Positions</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="#h-60"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="#h-61"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>290 - </span><a href="#h-62"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="#h-63"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="#h-64"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>295 - </span><a href="#h-65"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="#h-66"><span class="HTitleText4"><cite class="XRefExternalRegulation">Canadian Security Intelligence Service Act Deputy Heads of the Public Service of Canada Order</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>297 - </span><a href="#h-67"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-68"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>299 - </span><a href="#h-69"><span class="HLabel2">Division 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Agreement on Internal Trade Implementation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>299 - </span><a href="#h-70"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="#h-71"><span class="HTitleText3">Related Amendment to the <cite class="XRefExternalAct">Crown Liability and Proceedings Act</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-72"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>307 - </span><a href="#h-73"><span class="HLabel2">Division 15</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="#h-74"><span class="HLabel2">Division 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>308 - </span><a href="#h-75"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-76"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>315 - </span><a href="#h-77"><span class="HLabel2">Division 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Mortgage and Housing Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="#h-78"><span class="HLabel2">Division 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Navigable Waters Protection Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>316 - </span><a href="#h-79"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>332 - </span><a href="#h-80"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="#h-81"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>336 - </span><a href="#h-82"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>336 - </span><a href="#h-83"><span class="HTitleText4"><cite class="XRefExternalAct">Harbour Commissions Act</cite></span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="#h-84"><span class="HTitleText4"><cite class="XRefExternalAct">National Energy Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="#h-85"><span class="HTitleText4"><cite class="XRefExternalAct">Railway Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>342 - </span><a href="#h-86"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Marine Act</cite></span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="#h-87"><span class="HTitleText4"><cite class="XRefExternalAct">Transportation Appeal Tribunal of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>346 - </span><a href="#h-88"><span class="HTitleText4"><cite class="XRefExternalAct">Canada National Marine Conservation Areas Act</cite></span></a>
</li>
<li><span class='sectionRange'>347 - </span><a href="#h-89"><span class="HTitleText4"><cite class="XRefExternalAct">Highway 30 Completion Bridges Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>348 - </span><a href="#h-90"><span class="HTitleText3">Related Amendment to the <cite class="XRefExternalAct">Public Safety Act, 2002</cite></span></a>
</li>
<li><span class='sectionRange'>349 - </span><a href="#h-91"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>350 - </span><a href="#h-92"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>351 - </span><a href="#h-93"><span class="HLabel2">Division 19</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Grain Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>351 - </span><a href="#h-94"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>390 - </span><a href="#h-95"><span class="HTitleText3">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>390 - </span><a href="#h-96"><span class="HTitleText4"><cite class="XRefExternalAct">An Act to amend the <cite class="XRefExternalAct">Canada Grain Act</cite> and the <cite class="XRefExternalAct">Agriculture and Agri-food Administrative Monetary Penalties Act</cite> and to repeal the <cite class="XRefExternalAct">Grain Futures Act</cite></cite></span></a>
</li>
<li><span class='sectionRange'>403 - </span><a href="#h-97"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Law–Civil Law Harmonization Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>404 - </span><a href="#h-98"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Law–Civil Law Harmonization Act, No. 2</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>405 - </span><a href="#h-99"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>410 - </span><a href="#h-100"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>411 - </span><a href="#h-101"><span class="HLabel2">Division 20</span> - <span class="HTitleText2"><cite class="XRefExternalAct">International Interests in Mobile Equipment (aircraft equipment) Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>411 - </span><a href="#h-102"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>414 - </span><a href="#h-103"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>414 - </span><a href="#h-104"><span class="HTitleText4"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>419 - </span><a href="#h-105"><span class="HTitleText4"><cite class="XRefExternalAct">Companies’ Creditors Arrangement Act</cite></span></a>
</li>
<li><span class='sectionRange'>422 - </span><a href="#h-106"><span class="HTitleText4"><cite class="XRefExternalAct">Winding-up and Restructuring Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>424 - </span><a href="#h-107"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>425 - </span><a href="#h-108"><span class="HLabel2">Division 21</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Environmental Assessment Act, 2012</cite></span></a>
</li>
<li><span class='sectionRange'>433 - </span><a href="#h-109"><span class="HLabel2">Division 22</span> - <span class="HTitleText2">Canada Employment Insurance Financing Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>433 - </span><a href="#h-110"><span class="HTitleText3"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="#h-111"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Human Resources and Skills Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>442 - </span><a href="#h-112"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Employment Insurance Financing Board Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>442 - </span><a href="#h-113"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>446 - </span><a href="#h-114"><span class="HTitleText4">Suspension</span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-115"><span class="HTitleText4">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>450 - </span><a href="#h-116"><span class="HTitleText3"><cite class="XRefExternalAct">Jobs, Growth and Long-term Prosperity Act</cite></span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="#h-117"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>461 - </span><a href="#h-118"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>462 - </span><a href="#h-119"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="#h-120"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>464 - </span><a href="#h-121"><span class="HLabel2">Division 23</span> - <span class="HTitleText2">Public Sector Pensions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>464 - </span><a href="#h-122"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Forces Superannuation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>464 - </span><a href="#h-123"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>473 - </span><a href="#h-124"><span class="HTitleText4">Consequential Amendment to the <cite class="XRefExternalAct">Special Retirement Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>474 - </span><a href="#h-125"><span class="HTitleText4">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>475 - </span><a href="#h-126"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>475 - </span><a href="#h-127"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>501 - </span><a href="#h-128"><span class="HTitleText4">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>502 - </span><a href="#h-129"><span class="HTitleText4">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>502 - </span><a href="#h-130"><span class="HTitleText4"><cite class="XRefExternalAct">Garnishment, Attachment and Pension Diversion Act</cite></span></a>
</li>
<li><span class='sectionRange'>503 - </span><a href="#h-131"><span class="HTitleText4"><cite class="XRefExternalAct">Special Retirement Arrangements Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>504 - </span><a href="#h-132"><span class="HTitleText3"><cite class="XRefExternalAct">Royal Canadian Mounted Police Superannuation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>504 - </span><a href="#h-133"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>513 - </span><a href="#h-134"><span class="HTitleText4">Consequential Amendment to the <cite class="XRefExternalAct">Special Retirement Arrangements Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>514 - </span><a href="#h-135"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>515 - </span><a href="#h-136"><span class="HLabel2">Division 24</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Revenue Agency Act</cite></span></a>
</li></ul>
</li><li><a href="#h-137"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-138"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

