<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Judges Act and certain other Acts in relation to courts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">JUDGES ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2"><cite class="XRefExternalAct">Judges Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO OTHER ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Transportation Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Crown Liability and Proceedings Act</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Pesticide Residue Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Railway Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Tax Court of Canada Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

