<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Competition Act and the Competition Tribunal Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">COMPETITION ACT</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-4.html#h-2"><span class="HTitleText1">COMPETITION TRIBUNAL ACT</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-5.html#h-3"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

