<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
First Nations Fiscal and Statistical Management Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">ABORIGINAL RIGHTS</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">FIRST NATIONS FISCAL POWERS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">FIRST NATIONS TAX COMMISSION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText2">Establishment and Organization of Commission</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-8"><span class="HTitleText2">Purposes</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-9"><span class="HTitleText2">Functions and Powers</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-10"><span class="HTitleText2">Standards and Procedures</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-11"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="#h-12"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">FIRST NATIONS FINANCIAL MANAGEMENT BOARD</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="#h-13"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-14"><span class="HTitleText2">Establishment and Organization of Board</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-15"><span class="HTitleText2">Purposes</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-16"><span class="HTitleText2">Functions and Powers</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-17"><span class="HTitleText2">Standards and Procedures</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-18"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>57 - </span><a href="#h-19"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">FIRST NATIONS FINANCE AUTHORITY</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>57 - </span><a href="#h-20"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-21"><span class="HTitleText2">Establishment and Organization of Authority</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-22"><span class="HTitleText2">Purposes</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-23"><span class="HTitleText2">Functions and Powers</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-24"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-25"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="#h-26"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">FIRST NATIONS STATISTICAL INSTITUTE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>90 - </span><a href="#h-27"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-28"><span class="HTitleText2">Establishment and Organization of Institute</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-29"><span class="HTitleText2">Purposes</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-30"><span class="HTitleText2">Powers</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-31"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-32"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-33"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="#h-34"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">FINANCIAL MANAGEMENT AND CONTROL</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-35"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">PROVISIONS OF GENERAL APPLICATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="#h-36"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-37"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>143 - </span><a href="#h-38"><span class="HLabel1"><strong>PART 8</strong></span> - <span class="HTitleText1"><strong>TRANSITIONAL PROVISIONS, CONSEQUENTIAL AMENDMENTS, COORDINATING AMENDMENTS AND COMING INTO FORCE</strong></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>143 - </span><a href="#h-39"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-40"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>147 - </span><a href="#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-43"><span class="HTitleText3"><cite class="XRefExternalAct">Indian Act</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-44"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-45"><span class="HTitleText1"><cite class="XRefExternalAct"><strong><em>Westbank First Nation Self-Government Act</em></strong></cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>154 - </span><a href="#h-46"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-47"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-48"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

