<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Canada Shipping Act, the Canada Shipping Act, 2001, the Canada National Marine Conservation Areas Act and the Oceans Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">CANADA SHIPPING ACT</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-2"><span class="HTitleText1">CANADA SHIPPING ACT, 2001</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-3"><span class="HTitleText1">CANADA NATIONAL MARINE CONSERVATION AREAS ACT</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-4"><span class="HTitleText1">OCEANS ACT</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

