<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Migratory Birds Convention Act, 1994 and the Canadian Environmental Protection Act, 1999</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">MIGRATORY BIRDS CONVENTION ACT, 1994</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-4.html#h-2"><span class="HTitleText1">CANADIAN ENVIRONMENTAL PROTECTION ACT, 1999</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-7.html#h-3"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-8.html#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

