<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Canada Transportation Act and the Railway Safety Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA TRANSPORTATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">RAILWAY SAFETY ACT</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-4"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-5"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-6"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-5.html#h-7"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

