<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend certain Acts and instruments and to repeal the Fisheries Prices Support Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Atlantic Canada Opportunities Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Film Development Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Lieutenant Governors Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">National Capital Act</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">National Film Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Nuclear Safety and Control Act</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Special Retirement Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Telecommunications Act</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Yukon First Nations Self-Government Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HTitleText1">REPEAL OF THE FISHERIES PRICES SUPPORT ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-17"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-18"><span class="HTitleText2">Transitional</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="#h-19"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-20"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

