<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Common Sense Firearms Licensing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">FIREARMS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL CODE</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-4"><span class="HTitleText1">RELATED AMENDMENT TO THE <cite class="XRefExternalAct">CUSTOMS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-5"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT TO THE <cite class="XRefExternalAct">ENDING THE LONG-GUN REGISTRY ACT</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-6"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

