<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Safe Food for Canadians Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">PROHIBITIONS</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-5"><span class="HTitleText1">REGISTRATIONS AND LICENCES</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-6"><span class="HTitleText1">ADMINISTRATION AND ENFORCEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-7"><span class="HTitleText2">Certificate</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-8"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-9"><span class="HTitleText2">Dealing with Seized Things</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-10"><span class="HTitleText2">Other Measures</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-11"><span class="HTitleText2">Forfeiture</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-12"><span class="HTitleText2">Analysis</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-13"><span class="HTitleText2">Offences</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-14"><span class="HTitleText1">GENERAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-15"><span class="HTitleText2">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-16"><span class="HTitleText2">Export Certificates</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-17"><span class="HTitleText2">Samples</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-18"><span class="HTitleText2">Intellectual Property</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-19"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-20"><span class="HTitleText2">Incorporation by Reference</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-21"><span class="HTitleText2">Interim Orders</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-22"><span class="HTitleText2">Costs</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-23"><span class="HTitleText2">Limitation on Liability</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-24"><span class="HTitleText2">Board of Arbitration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-25"><span class="HTitleText3">Composition</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-26"><span class="HTitleText3">Chairperson</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-27"><span class="HTitleText3">Remuneration and Expenses</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-28"><span class="HTitleText3">Staff</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-29"><span class="HTitleText3">Role</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-30"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-31"><span class="HTitleText1">REVIEW</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-32"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-33"><span class="HTitleText1">REPEALS</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-34"><span class="HTitleText1">RELATED AND CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Consumer Packaging and Labelling Act</cite></span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Feeds Act</cite></span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Fertilizers Act</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Seeds Act</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Health of Animals Act</cite></span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Plant Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Contraventions Act</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Agriculture and Agri-Food Administrative Monetary Penalties Act</cite></span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Food Inspection Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Pest Control Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-48"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Border Services Agency Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-49"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-50"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

