<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada National Marine Conservation Areas Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">MARINE CONSERVATION AREAS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-5"><span class="HTitleText1">ADMINISTRATION</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-6"><span class="HTitleText1">PROHIBITIONS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-7"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-8"><span class="HTitleText1">ENFORCEMENT</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-9"><span class="HTitleText1">OFFENCES AND PUNISHMENT</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-4.html#h-10"><span class="HTitleText1">MITIGATION OF ENVIRONMENTAL DAMAGE</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-4.html#h-11"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="page-4.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Canada National Parks Act</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Canadian Heritage Act</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-4.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Parks Canada Agency Act</cite></span></a>
</li></ul>
</li><li><a href="page-6.html#h-15"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - MARINE CONSERVATION AREAS</span></a>
</li>
<li><a href="page-7.html#h-16"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - RESERVES</span></a>
</li></ul>
</li></ul>

</nav>

