<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Donkin Coal Block Development Opportunity Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">APPLICATION</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HTitleText1">DELEGATION</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText1">ROYALTIES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-8"><span class="HTitleText1">AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-9"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-10"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT TO THE CANADA-NOVA SCOTIA OFFSHORE PETROLEUM RESOURCES ACCORD IMPLEMENTATION ACT</span></a>
</li>
<li><a href="page-2.html#h-11"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - AREA OF THE DONKIN COAL BLOCK</span></a>
</li></ul>
</li></ul>

</nav>

