<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the statute law in respect of benefits for veterans and the children of deceased veterans</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CHILDREN OF DECEASED VETERANS EDUCATION ASSISTANCE ACT</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-2"><span class="HTitleText1">PENSION ACT</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-3"><span class="HTitleText1">ROYAL CANADIAN MOUNTED POLICE SUPERANNUATION ACT</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-4"><span class="HTitleText1">WAR VETERANS ALLOWANCE ACT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-5"><span class="HTitleText1">AN ACT TO AMEND THE STATUTE LAW IN RELATION TO VETERANS’ BENEFITS</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-6"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

