<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Elections Modernization Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Canada Elections Act</span></a>
</li>
<li><span class='sectionRange'>378 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>379 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
</li>
<li><span class='sectionRange'>380 - </span><a href="#h-5"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>391 - </span><a href="#h-6"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>391 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>392 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Electoral Boundaries Readjustment Act</cite></span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>395 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Director of Public Prosecutions Act</cite></span></a>
</li>
<li><span class='sectionRange'>398 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalRegulation">Special Voting Rules</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>399 - </span><a href="#h-12"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>401 - </span><a href="#h-13"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-14"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

