<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Cracking Down on Tobacco Marketing Aimed at Youth Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">ALTERNATIVE TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">TOBACCO ACT</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-3"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-3.html#h-4"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

