<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Pension Act and the Royal Canadian Mounted Police Superannuation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">PENSION ACT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-2"><span class="HTitleText1">ROYAL CANADIAN MOUNTED POLICE SUPERANNUATION ACT</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li></ul>
</li></ul>

</nav>

