<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Nuclear Fuel Waste Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PURPOSE OF ACT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">APPLICATION OF ACT</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">WASTE MANAGEMENT ORGANIZATION</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HTitleText1">FINANCING</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-7"><span class="HTitleText1">STUDY BY WASTE MANAGEMENT ORGANIZATION</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-8"><span class="HTitleText1">REPORTS BY WASTE MANAGEMENT ORGANIZATION</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-9"><span class="HTitleText1">CHANGE IN APPROACH</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-10"><span class="HTitleText1">WITHDRAWAL BY BENEFICIARY</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-11"><span class="HTitleText1">RECORDS, BOOKS AND FINANCIAL STATEMENTS</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-12"><span class="HTitleText1">DOCUMENTS TO BE MADE PUBLIC</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-13"><span class="HTitleText1">INSPECTION OF RECORDS AND BOOKS</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-14"><span class="HTitleText1">OFFENCES AND PUNISHMENT</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-15"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

