<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Postal Services Resumption and Continuation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Postal Services</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">Extension of Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Mediator-Arbitrator</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-6"><span class="HTitleText1">New Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

