<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Cree-Naskapi (of Quebec) Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CREE-NASKAPI (OF QUEBEC) ACT</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-2"><span class="HTitleText1">PUBLICATION</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-3"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

