<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Wrecked, Abandoned or Hazardous Vessels Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HTitleText1">Powers, Duties and Functions of Ministers</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-7"><span class="HTitleText1">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-8"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Removal of Wrecks</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Hazards</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Liability</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Insurance or Other Financial Security</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="page-3.html#h-13"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Vessels and Wrecks of Concern</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Measures</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Disposition of Vessel, Wreck or Contents</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-5.html#h-19"><span class="HTitleText2">Compensation and Liability</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-20"><span class="HTitleText2">Miscellaneous</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="page-5.html#h-21"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Salvage</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Salvage Convention</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-5.html#h-25"><span class="HTitleText2">Salvage by Crown Vessels</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-6.html#h-26"><span class="HTitleText2">Limitation or Prescription Period for Salvage Proceedings</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-6.html#h-27"><span class="HTitleText2">Aircraft</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-6.html#h-28"><span class="HTitleText2">Rights of Salvors</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="page-6.html#h-29"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Receiver of Wreck</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="page-6.html#h-30"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-31"><span class="HTitleText2">Designation of Receivers of Wreck</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-6.html#h-32"><span class="HTitleText2">Finding or Bringing Wreck into Canada</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-6.html#h-33"><span class="HTitleText2">Disposition of Wrecks</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-7.html#h-34"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-7.html#h-35"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="page-7.html#h-36"><span class="HTitleText2">Measures Relating to Hazards</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-7.html#h-37"><span class="HTitleText2">Designation of Enforcement Officers</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-7.html#h-38"><span class="HTitleText2">Compliance Measures</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-9.html#h-39"><span class="HTitleText2">Provisions Related to Entry</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-9.html#h-40"><span class="HTitleText2">Obstruction</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-9.html#h-41"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="page-9.html#h-42"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-9.html#h-43"><span class="HTitleText3">Assurances of Compliance and Notices of Violation</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-11.html#h-44"><span class="HTitleText3">Recovery of Debts</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-11.html#h-45"><span class="HTitleText3">General</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-11.html#h-46"><span class="HTitleText3">Public Record</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-11.html#h-47"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="page-12.html#h-48"><span class="HTitleText2">Offences and Punishment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="page-12.html#h-49"><span class="HTitleText3">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-13.html#h-50"><span class="HTitleText3">Forfeiture, Retention or Disposition</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-13.html#h-51"><span class="HTitleText3">Jurisdiction</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="page-13.html#h-52"><span class="HTitleText2">Reporting of Alleged Contraventions</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-13.html#h-53"><span class="HTitleText2">Injunction</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="page-13.html#h-54"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-13.html#h-55"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-14.html#h-56"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Transitional Provision and Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="page-14.html#h-57"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-14.html#h-58"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="page-14.html#h-59"><span class="HTitleText3"><cite class="XRefExternalAct">Oceans Act</cite></span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-14.html#h-60"><span class="HTitleText3"><cite class="XRefExternalAct">Canada National Marine Conservation Areas Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>135 - </span><a href="page-14.html#h-61"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>135 - </span><a href="page-14.html#h-62"><span class="HTitleText3"><cite class="XRefExternalAct">Crown Liability and Proceedings Act</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-14.html#h-63"><span class="HTitleText3"><cite class="XRefExternalAct">Navigation Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-14.html#h-64"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-14.html#h-65"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Shipping Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-15.html#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Transportation Appeal Tribunal of Canada Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="page-15.html#h-67"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Review</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-15.html#h-68"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-16.html#h-69"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Nairobi International Convention on the Removal of Wrecks, 2007</span></a>
</li>
<li><a href="page-17.html#h-70"><span class="scheduleLabel">ANNEX</span> - <span class="scheduleTitleText"> - Certificate of Insurance or Other Financial Security in Respect of Liability for the Removal of Wrecks</span></a>
</li>
<li><a href="page-18.html#h-71"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Salvage</span></a>
</li></ul>
</li></ul>

</nav>

