<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Tlicho Land Claims and Self-Government</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">OTHER LAWS</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">APPROPRIATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">TAXATION</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText1">WEKEEZHII RENEWABLE RESOURCES BOARD</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText1">AMENDMENTS TO THE MACKENZIE VALLEY RESOURCE MANAGEMENT ACT</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-10"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-11"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>97 - </span><a href="#h-12"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-13"><span class="HTitleText2">Canada Lands Surveys Act</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-14"><span class="HTitleText2">Canadian Environmental Assessment Act</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-15"><span class="HTitleText2">Lobbyists Registration Act</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-16"><span class="HTitleText2">Northwest Territories Act</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-17"><span class="HTitleText2">Northwest Territories Waters Act</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-18"><span class="HTitleText2">Payments in Lieu of Taxes Act</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-19"><span class="HTitleText2">Privacy Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>107 - </span><a href="#h-20"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>107 - </span><a href="#h-21"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-22"><span class="HTitleText2">Lobbyists Registration Act</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-23"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-24"><span class="HTitleText2">Other Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-25"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

