<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Not-for-profit Corporations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">INTERPRETATION AND APPLICATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Designation of Minister</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">INCORPORATION</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CAPACITY AND POWERS</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-9"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">REGISTERED OFFICE AND RECORDS</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-10"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CORPORATE FINANCE</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-11"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">DEBT OBLIGATIONS, CERTIFICATES, REGISTERS AND TRANSFERS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="#h-12"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-13"><span class="HTitleText2">Debt Obligation Certificates</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-14"><span class="HTitleText2">Registers</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-15"><span class="HTitleText2">Proceedings</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-16"><span class="HTitleText2">Delivery</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-17"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-18"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">TRUST INDENTURES</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-19"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">RECEIVERS, RECEIVER-MANAGERS AND SEQUESTRATORS</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-20"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">DIRECTORS AND OFFICERS</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-21"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">BY-LAWS AND MEMBERS</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-22"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">FINANCIAL DISCLOSURE</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-23"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">PUBLIC ACCOUNTANT</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-24"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">FUNDAMENTAL CHANGES</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-25"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">LIQUIDATION AND DISSOLUTION</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-26"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">INVESTIGATION</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="#h-27"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">REMEDIES, OFFENCES AND PUNISHMENT</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="#h-28"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">DOCUMENTS IN ELECTRONIC OR OTHER FORM</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-29"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">GENERAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>272 - </span><a href="#h-30"><span class="HTitleText2">Notice, Certificates and Other Documents</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="#h-31"><span class="HTitleText2">Director</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="#h-32"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>294 - </span><a href="#h-33"><span class="HLabel1">PART 19</span> - <span class="HTitleText1">SPECIAL ACT BODIES CORPORATE WITHOUT SHARE CAPITAL</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-34"><span class="HLabel1">PART 20</span> - <span class="HTitleText1">TRANSITIONAL PROVISIONS, CONSEQUENTIAL AMENDMENTS, COORDINATING AMENDMENTS, REPEALS AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>297 - </span><a href="#h-35"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="#h-36"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>300 - </span><a href="#h-37"><span class="HTitleText3">An Act to incorporate St. Mary’s River Bridge Company</span></a>
</li>
<li><span class='sectionRange'>303 - </span><a href="#h-38"><span class="HTitleText3">An Act to incorporate the Jules and Paul-Émile Léger Foundation</span></a>
</li>
<li><span class='sectionRange'>304 - </span><a href="#h-39"><span class="HTitleText3">An Act to incorporate the Pickering Harbour Company (Limited) and to authorize it to collect tolls</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="#h-40"><span class="HTitleText3">An Act to provide for the creation by amalgamation of The Wesleyan Church of Canada</span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-41"><span class="HTitleText3">Bank Act</span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="#h-42"><span class="HTitleText3">Budget Implementation Act, 1997</span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="#h-43"><span class="HTitleText3">Budget Implementation Act, 1998</span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="#h-44"><span class="HTitleText3">Canada Business Corporations Act</span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="#h-45"><span class="HTitleText3">Canada Cooperatives Act</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-46"><span class="HTitleText3">Canada Corporations Act</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="#h-47"><span class="HTitleText3">Canada Employment Insurance Financing Board Act</span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="#h-48"><span class="HTitleText3">Canada Foundation for Sustainable Development Technology Act</span></a>
</li>
<li><span class='sectionRange'>317 - </span><a href="#h-49"><span class="HTitleText3">Canada Pension Plan Investment Board Act</span></a>
</li>
<li><span class='sectionRange'>318 - </span><a href="#h-50"><span class="HTitleText3">Canadian Food Inspection Agency Act</span></a>
</li>
<li><span class='sectionRange'>319 - </span><a href="#h-51"><span class="HTitleText3">Canadian Institutes of Health Research Act</span></a>
</li>
<li><span class='sectionRange'>320 - </span><a href="#h-52"><span class="HTitleText3">Canadian Payments Act</span></a>
</li>
<li><span class='sectionRange'>321 - </span><a href="#h-53"><span class="HTitleText3">Cooperative Energy Act</span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="#h-54"><span class="HTitleText3">Cree-Naskapi (of Quebec) Act</span></a>
</li>
<li><span class='sectionRange'>323 - </span><a href="#h-55"><span class="HTitleText3">Evangelical Lutheran Church in Canada Act</span></a>
</li>
<li><span class='sectionRange'>324 - </span><a href="#h-56"><span class="HTitleText3">Evangelical Missionary Church (Canada West District) Act</span></a>
</li>
<li><span class='sectionRange'>327 - </span><a href="#h-57"><span class="HTitleText3">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>328 - </span><a href="#h-58"><span class="HTitleText3">First Nations Fiscal and Statistical Management Act</span></a>
</li>
<li><span class='sectionRange'>329 - </span><a href="#h-59"><span class="HTitleText3">Green Shield Canada Act</span></a>
</li>
<li><span class='sectionRange'>330 - </span><a href="#h-60"><span class="HTitleText3">Gwich’in Land Claim Settlement Act</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="#h-61"><span class="HTitleText3">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>332 - </span><a href="#h-62"><span class="HTitleText3">Mackenzie Gas Project Impacts Act</span></a>
</li>
<li><span class='sectionRange'>333 - </span><a href="#h-63"><span class="HTitleText3">Mi’kmaq Education Act</span></a>
</li>
<li><span class='sectionRange'>334 - </span><a href="#h-64"><span class="HTitleText3">Physical Activity and Sport Act</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="#h-65"><span class="HTitleText3">Pilotage Act</span></a>
</li>
<li><span class='sectionRange'>336 - </span><a href="#h-66"><span class="HTitleText3">Public Sector Pension Investment Board Act</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="#h-67"><span class="HTitleText3">Sahtu Dene and Metis Land Claim Settlement Act</span></a>
</li>
<li><span class='sectionRange'>338 - </span><a href="#h-68"><span class="HTitleText3">United Grain Growers Act</span></a>
</li>
<li><span class='sectionRange'>339 - </span><a href="#h-69"><span class="HTitleText3">Yukon First Nations Land Claims Settlement Act</span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="#h-70"><span class="HTitleText3">Other Acts</span></a>
</li></ul>
</li><li><span class='sectionRange'>341 - </span><a href="#h-71"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="#h-72"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>372 - </span><a href="#h-73"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

