<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Mackenzie Valley Resource Management Act and the Canada Petroleum Resources Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PART 1</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Mackenzie Valley Resource Management Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-6.html#h-3"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-6.html#h-4"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-6.html#h-5"><span class="HTitleText3"><cite class="XRefExternalAct">Northwest Territories Devolution Act</cite></span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-6.html#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Tlicho Land Claims and Self-Government Act</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-6.html#h-7"><span class="HTitleText3"><cite class="XRefExternalAct">Déline Final Self-Government Agreement Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="page-6.html#h-8"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-7.html#h-9"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="page-7.html#h-10"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Petroleum Resources Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="page-7.html#h-11"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-7.html#h-12"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

