<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Transboundary Waters Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERNATIONAL BOUNDARY WATERS TREATY ACT</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-3.html#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT TO THE INTERNATIONAL RIVER IMPROVEMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-3.html#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-4.html#h-5"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

