<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Geneva Conventions Act, An Act to incorporate the Canadian Red Cross Society and the Trade-marks Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">GENEVA CONVENTIONS ACT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-2"><span class="HTitleText1">AN ACT TO INCORPORATE THE CANADIAN RED CROSS SOCIETY</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">TRADE-MARKS ACT</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-2.html#h-5"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

