<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Respect for Communities Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CONTROLLED DRUGS AND SUBSTANCES ACT</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-3"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

