<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Protecting Canada’s Immigration System Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">IMMIGRATION AND REFUGEE PROTECTION ACT</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-3"><span class="HTitleText1">BALANCED REFUGEE REFORM ACT</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-4"><span class="HTitleText1">MARINE TRANSPORTATION SECURITY ACT</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-5"><span class="HTitleText1">DEPARTMENT OF CITIZENSHIP AND IMMIGRATION ACT</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-6"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-7"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-8"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

