<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Safeguarding Canada’s Seas and Skies Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">AVIATION INDUSTRY INDEMNITY ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText3">Marine and Aviation War Risks Act</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText3">References</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">AERONAUTICS ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-9"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-12"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Transportation Accident Investigation and Safety Board Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-13"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-14"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-15"><span class="HLabel1">PART 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">CANADA MARINE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-16"><span class="HLabel1">PART 4</span> - <span class="HTitleText1"><cite class="XRefExternalAct">MARINE LIABILITY ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-17"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-18"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="#h-19"><span class="HLabel1">PART 5</span> - <span class="HTitleText1"><cite class="XRefExternalAct">CANADA SHIPPING ACT, 2001</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-20"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-21"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Coasting Trade Act</cite></span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-22"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-23"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

