<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Framework for Diabetes Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">National Framework for Diabetes</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Reports to Parliament</span></a>
</li></ul>
</li></ul>

</nav>

