<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Servants Disclosure Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">AMENDING THE SCHEDULES</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">PROMOTING ETHICAL PRACTICES</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">CODE OF CONDUCT</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText1">WRONGDOINGS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">DISCLOSURE OF WRONGDOINGS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-8"><span class="HTitleText1">PROTECTION OF PERSONS MAKING DISCLOSURES</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText1">DUTIES OF THE COMMISSIONER</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-10"><span class="HTitleText1">INVESTIGATIONS</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-11"><span class="HTitleText1">REPORTS</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-12"><span class="HTitleText1">OFFICE OF THE PUBLIC SECTOR INTEGRITY COMMISSIONER</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-13"><span class="HTitleText2">Public Sector Integrity Commissioner</span></a>
</li>
<li><span class='sectionRange'>39.3 - </span><a href="#h-14"><span class="HTitleText2">Staff</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-15"><span class="HTitleText1">PROHIBITIONS</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-16"><span class="HTitleText1">CONFIDENTIALITY</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-17"><span class="HTitleText1">PROTECTION</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-18"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-19"><span class="HTitleText1">EXCLUDED ORGANIZATIONS</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-20"><span class="HTitleText1">FIVE-YEAR REVIEW</span></a>
</li>
<li><span class='sectionRange'>54.1 - </span><a href="#h-21"><span class="HTitleText1">TRANSITIONAL</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-22"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-23"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-24"><span class="HTitleText2">Canada Evidence Act</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-25"><span class="HTitleText2">Personal Information Protection and Electronic Documents Act</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-26"><span class="HTitleText2">Privacy Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="#h-27"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-28"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-29"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-30"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-31"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>

</nav>

