<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Criminal Code (trafficking in persons)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-2"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li></ul>
</li></ul>

</nav>

