<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to change the names of certain electoral districts and to amend the Electoral Boundaries Readjustment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">ELECTORAL DISTRICTS IN QUEBEC, ONTARIO, SASKATCHEWAN, ALBERTA AND BRITISH COLUMBIA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Quebec</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-4"><span class="HTitleText2">Ontario</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-5"><span class="HTitleText2">Saskatchewan</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-6"><span class="HTitleText2">Alberta</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-7"><span class="HTitleText2">British Columbia</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-8"><span class="HTitleText1">AMENDMENT TO THE <cite class="XRefExternalAct">ELECTORAL BOUNDARIES READJUSTMENT ACT</cite></span></a>
</li></ul>
</li></ul>

</nav>

