<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada Consumer Product Safety Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">APPLICATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">PROHIBITIONS</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-6"><span class="HTitleText1">TESTS, STUDIES AND COMPILATION OF INFORMATION</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-7"><span class="HTitleText1">PREPARING AND MAINTAINING DOCUMENTS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-8"><span class="HTitleText1">DUTIES IN THE EVENT OF AN INCIDENT</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-9"><span class="HTitleText1">DISCLOSURE OF INFORMATION BY THE MINISTER</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-10"><span class="HTitleText1">INSPECTORS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-11"><span class="HTitleText1">INSPECTION</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-12"><span class="HTitleText1">PROCEDURES FOLLOWING SEIZURE</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-13"><span class="HTitleText1">ANALYSIS</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-14"><span class="HTitleText1">ORDERS FOR RECALLS AND TAKING MEASURES</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-3.html#h-15"><span class="HTitleText1">REVIEW OF ORDERS FOR RECALLS AND TAKING MEASURES</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-16"><span class="HTitleText1">INJUNCTION</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-17"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-18"><span class="HTitleText1">INTERIM ORDERS</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-19"><span class="HTitleText1">OFFENCES</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-5.html#h-20"><span class="HTitleText1">ADMINISTRATIVE MONETARY PENALTIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="page-5.html#h-21"><span class="HTitleText2">Violation</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Powers of the Governor in Council and Minister</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Proceedings</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Penalties</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-25"><span class="HTitleText2">Compliance Agreements</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-6.html#h-26"><span class="HTitleText2">Review by the Minister</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-27"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-6.html#h-28"><span class="HTitleText2">Rules of Law About Violations</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-29"><span class="HTitleText2">Other Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-6.html#h-30"><span class="HTitleText1">GENERAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-6.html#h-31"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS TO THE HAZARDOUS PRODUCTS ACT</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-7.html#h-32"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-8.html#h-33"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-9.html#h-34"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

