<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Kyoto Protocol Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">CLIMATE CHANGE PLAN</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText1">EXPECTED REDUCTIONS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-8"><span class="HTitleText1">REPORT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-9"><span class="HTitleText1">OFFENCES AND PENALTIES</span></a>
</li></ul>
</li></ul>

</nav>

