<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Kanesatake Interim Land Base Governance Act</a><ul class="TocIndent"><li><span class='sectionRange'>24 - </span><a href="page-2.html#h-1"><span class="HTitleText1">AMENDMENT TO CANADA LANDS SURVEYS ACT</span></a>
</li>
<li><a href="page-3.html#h-2"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - KANESATAKE MOHAWK INTERIM LAND BASE</span></a>
</li></ul>
</li></ul>

</nav>

