<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Miscellaneous Statute Law Amendment Act, 2001</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Anti-Personnel Mines Convention Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Arctic Waters Pollution Prevention Act</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Atlantic Canada Opportunities Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">An Act to amend the Bank Act, the Winding-up and Restructuring Act and other Acts relating to financial institutions and to make consequential amendments to other Acts</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Budget Implementation Act, 1997</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Business Development Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Council Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Canada National Parks Act</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Shipping Act</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Environmental Protection Act, 1999</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Radio-television and Telecommunications Commission Act</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Companies’ Creditors Arrangement Act</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Copyright Act</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Crimes Against Humanity and War Crimes Act</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Cultural Property Export and Import Act</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Electricity and Gas Inspection Act</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Employment Equity Act</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-3.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-3.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Energy Monitoring Act</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-3.html#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-3.html#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Hazardous Materials Information Review Act</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-3.html#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Industrial Design Act</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-3.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Migratory Birds Convention Act, 1994</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-3.html#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">National Arts Centre Act</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-3.html#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Nuclear Safety and Control Act</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-4.html#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Patent Act</cite></span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-4.html#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Pension Benefits Division Act</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-4.html#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Pension Benefits Standards Act, 1985</cite></span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-5.html#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-5.html#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-5.html#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Weights and Measures Act</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-5.html#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Yukon Placer Mining Act</cite></span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-5.html#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Yukon Quartz Mining Act</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

