<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
First Nations Oil and Gas and Moneys Management Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION AND APPLICATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">REQUESTS FOR TRANSFER</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-4"><span class="HTitleText1">REQUIREMENTS FOR TRANSFER</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-5"><span class="HTitleText1">APPROVAL PROCEDURE</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-6"><span class="HTitleText1">TRANSFERS TO FIRST NATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-7"><span class="HTitleText2">Oil and Gas</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-8"><span class="HTitleText2">Moneys</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="#h-9"><span class="HTitleText1">POWERS RELATING TO OIL AND GAS</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-10"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-11"><span class="HTitleText1">APPLICATION OF OTHER LAWS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-12"><span class="HTitleText2">Oil and Gas</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-13"><span class="HTitleText2">Moneys</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-14"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-15"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-16"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-17"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

