<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Sir John A. Macdonald Day and the Sir Wilfrid Laurier Day Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">SIR JOHN A. MACDONALD DAY</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">SIR WILFRID LAURIER DAY</span></a>
</li></ul>
</li></ul>

</nav>

