<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Transportation Modernization Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Canada Transportation Act</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">CN Commercialization Act</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">Railway Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">Canadian Transportation Accident Investigation and Safety Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-6"><span class="HTitleText1"><cite class="XRefExternalAct">Canadian Air Transport Security Authority Act</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-7"><span class="HTitleText1"><cite class="XRefExternalAct">Coasting Trade Act</cite></span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-8"><span class="HTitleText1"><cite class="XRefExternalAct">Canada Marine Act</cite></span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-9"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-10"><span class="HTitleText1">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Companies’ Creditors Arrangement Act</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Air Canada Public Participation Act</cite></span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Budget Implementation Act, 2009</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Fair Rail for Grain Farmers Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-17"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-18"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

