<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Specific Claims Resolution Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">CANADIAN CENTRE FOR THE INDEPENDENT RESOLUTION OF FIRST NATIONS SPECIFIC CLAIMS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Establishment, Composition and Functions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText2">Chief Executive Officer</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Personnel Management</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText2">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-9"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">COMMISSION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-10"><span class="HTitleText2">Composition and Role</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText3">Composition</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-12"><span class="HTitleText3">Remuneration</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-13"><span class="HTitleText3">Management</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-14"><span class="HTitleText3">Functions, Powers and Duties</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText3">Restriction</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText2">Process Relating to Specific Claims</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-17"><span class="HTitleText3">Filing of Claims</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-18"><span class="HTitleText3">Preparatory Meetings</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-19"><span class="HTitleText3">Validity of Claims</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-20"><span class="HTitleText3">Compensation</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-21"><span class="HTitleText3">General</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-22"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">TRIBUNAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-23"><span class="HTitleText2">Composition and Role</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-24"><span class="HTitleText3">Composition</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-25"><span class="HTitleText3">Remuneration</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-26"><span class="HTitleText3">Management</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-27"><span class="HTitleText3">Functions, Powers and Duties</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-28"><span class="HTitleText2">Panels, Hearings and Decisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="#h-29"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>77.1 - </span><a href="#h-30"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">TRANSITIONAL PROVISION, CONSEQUENTIAL AMENDMENTS, COORDINATING AMENDMENT AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77.1 - </span><a href="#h-31"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-32"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="#h-33"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-34"><span class="HTitleText3">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-35"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-36"><span class="HTitleText3">Public Service Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-37"><span class="HTitleText3">Public Service Superannuation Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>84 - </span><a href="#h-38"><span class="HTitleText2">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-39"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-40"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

