<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Criminal Code (medical assistance in dying)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-2"><span class="HTitleText1">Independent Review</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Review</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

