<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Canada Pension Plan, the Canada Pension Plan Investment Board Act and the Income Tax Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the Canada Pension Plan and the Canada Pension Plan Investment Board Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-3"><span class="HTitleText2">Canada Pension Plan Investment Board Act</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-4"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-5"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="#h-6"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1">Related Amendments to the Income Tax Act</span></a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

