<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Conveyance Presentation and Reporting Requirements Modernization Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Coordinating Amendment</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

