<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Ensuring Safe Vehicles Imported from Mexico for Canadians</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">MOTOR VEHICLE SAFETY ACT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">CANADIAN ENVIRONMENTAL PROTECTION ACT, 1999</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

