<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Tougher Penalties for Child Predators Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL CODE</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA EVIDENCE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">SEX OFFENDER INFORMATION REGISTRATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">HIGH RISK CHILD SEX OFFENDER DATABASE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-6"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="page-3.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="page-4.html#h-9"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-10"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

