<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Supporting Vulnerable Seniors and Strengthening Canada’s Economy Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE INCOME TAX ACT, A RELATED ACT AND A RELATED REGULATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Canada Disability Savings Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Canada Disability Savings Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="page-2.html#h-6"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">MEASURES RELATING TO EXCISE DUTIES AND SALES AND EXCISE TAXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="page-2.html#h-9"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">OLD AGE SECURITY ACT</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-3.html#h-10"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">PAYMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Canadian Youth Business Foundation</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="page-3.html#h-13"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">AUDITOR GENERAL ACT</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-14"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">CANADA STUDENT FINANCIAL ASSISTANCE ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-3.html#h-17"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">MORTGAGE OR HYPOTHECARY INSURANCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-3.html#h-18"><span class="HTitleText2">Enactment of Protection of Residential Mortgage or Hypothecary Insurance Act</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-4.html#h-20"><span class="HTitleText3">Budget Implementation Act, 2006</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-4.html#h-21"><span class="HTitleText3">National Housing Act</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-4.html#h-22"><span class="HTitleText3">Office of the Superintendent of Financial Institutions Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="page-4.html#h-23"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="page-4.html#h-24"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-4.html#h-25"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">INSURANCE COMPANIES ACT</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-26"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">ASSESSMENT OF FINANCIAL INSTITUTIONS REGULATIONS, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="page-4.html#h-27"><span class="HTitleText2">Amendment to the Regulations</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-4.html#h-28"><span class="HTitleText2">Validation</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-4.html#h-29"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">FINANCIAL ADMINISTRATION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="page-4.html#h-30"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-5.html#h-31"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="page-5.html#h-32"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">CANADA SHIPPING ACT, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-5.html#h-33"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-6.html#h-34"><span class="HTitleText2">Consequential Amendment to the Coasting Trade Act</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

