<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Prohibiting Cluster Munitions Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION AND APPLICATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PURPOSE OF ACT</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">DESIGNATION OF MINISTER</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">PROHIBITIONS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-6"><span class="HTitleText1">DETENTION IN A SAFE PLACE</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-7"><span class="HTitleText1">DELEGATION</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-8"><span class="HTitleText1">AMENDMENTS TO THE CONVENTION</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-9"><span class="HTitleText1">ENFORCEMENT</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-10"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-3.html#h-12"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - CONVENTION ON CLUSTER MUNITIONS</span></a>
</li></ul>
</li></ul>

</nav>

