<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Comprehensive and Progressive Agreement for Trans-Pacific Partnership Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Causes of Action</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Implementation of the Agreement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Approval and Representation on the Commission</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Panels and Labour Council</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Expenses</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-1.html#h-11"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Related Amendments and Transitional Provision</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-1.html#h-12"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-1.html#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Export and Import Permits Act</cite></span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Trade-marks Act</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-18"><span class="HTitleText3"><cite class="XRefExternalAct">Commercial Arbitration Act</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian International Trade Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="page-6.html#h-21"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="page-6.html#h-22"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="page-6.html#h-23"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-6.html#h-24"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-7.html#h-25"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-8.html#h-26"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-9.html#h-27"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-10.html#h-28"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-11.html#h-29"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="page-12.html#h-30"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li>
<li><a href="page-13.html#h-31"><span class="scheduleLabel">SCHEDULE 7</span> </a>
</li>
<li><a href="page-14.html#h-32"><span class="scheduleLabel">SCHEDULE 8</span> </a>
</li>
<li><a href="page-15.html#h-33"><span class="scheduleLabel">SCHEDULE 9</span> </a>
</li>
<li><a href="page-16.html#h-34"><span class="scheduleLabel">SCHEDULE 10</span> </a>
</li>
<li><a href="page-17.html#h-35"><span class="scheduleLabel">SCHEDULE 11</span> </a>
</li>
<li><a href="page-18.html#h-36"><span class="scheduleLabel">SCHEDULE 12</span> </a>
</li>
<li><a href="page-19.html#h-37"><span class="scheduleLabel">SCHEDULE 13</span> </a>
</li></ul>
</li></ul>

</nav>

