<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Pooled Registered Pension Plans Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PURPOSE OF ACT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">APPLICATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">AGREEMENTS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-6"><span class="HTitleText1">POWERS OF SUPERINTENDENT</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-7"><span class="HTitleText1">REGISTRATION</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-8"><span class="HTitleText1">ADMINISTRATION OF POOLED REGISTERED PENSION PLANS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Administrator</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Employer</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-3.html#h-11"><span class="HTitleText1">DIRECTIONS OF COMPLIANCE</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-12"><span class="HTitleText1">OBJECTIONS AND APPEALS</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-13"><span class="HTitleText1">GENERAL REQUIREMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Membership</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-4.html#h-15"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Locking-in</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Variable Payments</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Death of Member</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Divorce, Annulment, Separation or Breakdown of Common-law Partnership</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-20"><span class="HTitleText2">Transfer of Funds and Purchase of Life Annuities</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-21"><span class="HTitleText2">Sex Discrimination Prohibited</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Rights to Information</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Duty to Provide Information</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="page-5.html#h-24"><span class="HTitleText1">TERMINATION AND WINDING-UP</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-5.html#h-25"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-6.html#h-26"><span class="HTitleText1">OFFENCES AND PUNISHMENT</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-7.html#h-27"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-7.html#h-28"><span class="HTitleText1">ANNUAL REPORT</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-7.html#h-29"><span class="HTitleText1">RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="page-7.html#h-30"><span class="HTitleText2">Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-7.html#h-31"><span class="HTitleText2">Companies’ Creditors Arrangement Act</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-7.html#h-32"><span class="HTitleText2">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-7.html#h-33"><span class="HTitleText2">Pension Benefits Standards Act, 1985</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-8.html#h-34"><span class="HTitleText2">Office of the Superintendent of Financial Institutions Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="page-8.html#h-35"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-8.html#h-36"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

