<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2018, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Income Tax Act</cite> and to Related Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-4"><span class="HTitleText2">Deemed Coming into Force</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-5"><span class="HTitleText2">An Act to amend the <cite class="XRefExternalAct">Canada Pension Plan</cite>, the <cite class="XRefExternalAct">Canada Pension Plan Investment Board Act</cite> and the <cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Budget Implementation Act, 2017, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-8"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Act, 2001</cite> (Tobacco Taxation) and to Related Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Budget Implementation Act, 2017, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-13"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-14"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Act, 2001</cite> (Cannabis Taxation), the <cite class="XRefExternalAct">Excise Tax Act</cite> and Other Related Texts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-15"><span class="HTitleText2">Coordination with the <cite class="XRefExternalAct">Cannabis Act</cite></span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-18"><span class="HTitleText2">Amendments to Various Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-19"><span class="HTitleText3"><cite class="XRefExternalRegulation">Postal Imports Remission Order</cite></span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-20"><span class="HTitleText3"><cite class="XRefExternalRegulation">Courier Imports Remission Order</cite></span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-21"><span class="HTitleText3"><cite class="XRefExternalRegulation">Public Service Body Rebate (GST/HST) Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-22"><span class="HTitleText3"><cite class="XRefExternalRegulation">Regulations Respecting Excise Licences and Registrations</cite></span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-23"><span class="HTitleText3"><cite class="XRefExternalRegulation">Regulations Respecting the Possession of Tobacco Products That Are Not Stamped</cite></span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-24"><span class="HTitleText3"><cite class="XRefExternalRegulation">Stamping and Marking of Tobacco Products Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-25"><span class="HTitleText3"><cite class="XRefExternalRegulation">Tobacco Products Labelling Regulations (Cigarettes and Little Cigars)</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="#h-26"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>114 - </span><a href="#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-28"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-29"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-30"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-31"><span class="HTitleText2">Amendment to the <cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>120 - </span><a href="#h-32"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Canadian Forces Members and Veterans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Pension Act</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Veterans Well-being Act</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-35"><span class="HTitleText2">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>162 - </span><a href="#h-36"><span class="HTitleText3">Definitions</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-37"><span class="HTitleText3">Rehabilitation Services and Vocational Assistance</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-38"><span class="HTitleText3">Canadian Forces Income Support Benefit</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-39"><span class="HTitleText3">Pain and Suffering Compensation</span></a>
</li></ul>
</li><li><span class='sectionRange'>178 - </span><a href="#h-40"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>178 - </span><a href="#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Children of Deceased Veterans Education Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Veterans Affairs Act</cite></span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-43"><span class="HTitleText3"><cite class="XRefExternalAct">Veterans Review and Appeal Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-44"><span class="HTitleText3"><cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-45"><span class="HTitleText3"><cite class="XRefExternalAct">Budget Implementation Act, 2016, No. 1</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-46"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>186 - </span><a href="#h-47"><span class="HLabel1">PART 5</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Greenhouse Gas Pollution Pricing Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>186 - </span><a href="#h-48"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-49"><span class="HTitleText2">Making of Regulations</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-50"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>188 - </span><a href="#h-51"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-52"><span class="HTitleText3"><cite class="XRefExternalAct">Tax Court of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-53"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Revenue Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-54"><span class="HTitleText3"><cite class="XRefExternalAct">Environmental Violations Administrative Monetary Penalties Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>198 - </span><a href="#h-55"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>199 - </span><a href="#h-56"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>199 - </span><a href="#h-57"><span class="HLabel2">DIVISION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-58"><span class="HLabel2">DIVISION 2</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>202 - </span><a href="#h-59"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-60"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-61"><span class="HLabel2">DIVISION 3</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-62"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Securities Issued or Guaranteed by Foreign Governments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="#h-63"><span class="HTitleText3"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-64"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>222 - </span><a href="#h-65"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Exchange Fund Account</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>222 - </span><a href="#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Currency Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>225 - </span><a href="#h-67"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Bank Notes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>225 - </span><a href="#h-68"><span class="HTitleText3"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-69"><span class="HTitleText3"><cite class="XRefExternalAct">Currency Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>231 - </span><a href="#h-70"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Payment Clearing and Settlement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>231 - </span><a href="#h-71"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Resolution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>231 - </span><a href="#h-72"><span class="HTitleText4">Amendments to the <cite class="XRefExternalAct">Payment Clearing and Settlement Act</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-73"><span class="HTitleText4">Consequential Amendment to the <cite class="XRefExternalAct">Canadian Payments Act</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-74"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>240 - </span><a href="#h-75"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Oversight Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>240 - </span><a href="#h-76"><span class="HTitleText4">Amendments to the <cite class="XRefExternalAct">Payment Clearing and Settlement Act</cite></span></a>
</li>
<li><span class='sectionRange'>243 - </span><a href="#h-77"><span class="HTitleText4">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-78"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>245 - </span><a href="#h-79"><span class="HLabel2">DIVISION 8</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian International Trade Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-80"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Canadian High Arctic Research Station and Application of an Order in Nunavut</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="#h-81"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian High Arctic Research Station Act</cite></span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-82"><span class="HTitleText3">Application of an Order in Nunavut</span></a>
</li></ul>
</li><li><span class='sectionRange'>250 - </span><a href="#h-83"><span class="HLabel2">DIVISION 10</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Institutes of Health Research Act</cite></span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-84"><span class="HLabel2">DIVISION 11</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Red Tape Reduction Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>257 - </span><a href="#h-85"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="#h-86"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>265 - </span><a href="#h-87"><span class="HLabel2">DIVISION 12</span> - <span class="HTitleText2">Communications Security Establishment</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-88"><span class="HLabel2">DIVISION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Department of Employment and Social Development Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>268 - </span><a href="#h-89"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="#h-90"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>284 - </span><a href="#h-91"><span class="HLabel2">DIVISION 14</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>284 - </span><a href="#h-92"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>292 - </span><a href="#h-93"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="#h-94"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>297 - </span><a href="#h-95"><span class="HLabel2">DIVISION 15</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Judges Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>297 - </span><a href="#h-96"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>304 - </span><a href="#h-97"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="#h-98"><span class="HTitleText3">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="#h-99"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>310 - </span><a href="#h-100"><span class="HLabel2">DIVISION 16</span> - <span class="HTitleText2">Financial Sector Legislative Renewal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>310 - </span><a href="#h-101"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Financial Technology Activities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>310 - </span><a href="#h-102"><span class="HTitleText4"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="#h-103"><span class="HTitleText4"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>329 - </span><a href="#h-104"><span class="HTitleText4"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="#h-105"><span class="HTitleText4"><cite class="XRefExternalAct">Green Shield Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>341 - </span><a href="#h-106"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>342 - </span><a href="#h-107"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Life Insurance Companies (Infrastructure Investment)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>342 - </span><a href="#h-108"><span class="HTitleText4"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>349 - </span><a href="#h-109"><span class="HTitleText4">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>350 - </span><a href="#h-110"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>351 - </span><a href="#h-111"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Bank Terminology</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>351 - </span><a href="#h-112"><span class="HTitleText4"><cite class="XRefExternalAct">Office of the Superintendent of Financial Institutions Act</cite></span></a>
</li>
<li><span class='sectionRange'>352 - </span><a href="#h-113"><span class="HTitleText4"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>354 - </span><a href="#h-114"><span class="HLabel3">SUBDIVISION D</span> - <span class="HTitleText3">Sunset Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>354 - </span><a href="#h-115"><span class="HTitleText4"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>355 - </span><a href="#h-116"><span class="HTitleText4"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>357 - </span><a href="#h-117"><span class="HTitleText4"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>359 - </span><a href="#h-118"><span class="HLabel2">DIVISION 17</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Western Economic Diversification Act</cite></span></a>
</li>
<li><span class='sectionRange'>360 - </span><a href="#h-119"><span class="HLabel2">DIVISION 18</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="#h-120"><span class="HLabel2">DIVISION 19</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>361 - </span><a href="#h-121"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>402 - </span><a href="#h-122"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>403 - </span><a href="#h-123"><span class="HLabel2">DIVISION 20</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>403 - </span><a href="#h-124"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>406 - </span><a href="#h-125"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>407 - </span><a href="#h-126"><span class="HTitleText3">Related Amendments to the <cite class="XRefExternalAct">Seized Property Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>409 - </span><a href="#h-127"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-128"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-129"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-130"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-131"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="#h-132"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="#h-133"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li></ul>
</li></ul>

</nav>

