<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Sioux Valley Dakota Nation Governance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">SIOUX VALLEY DAKOTA NATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText1">APPLICATION OF OTHER ACTS</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-6"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-7"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-8"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-2.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-2.html#h-11"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-12"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

