<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to enact the Impact Assessment Act and the Canadian Energy Regulator Act, to amend the Navigation Protection Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Impact Assessment Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Amendments to the <cite class="XRefExternalAct">Impact Assessment Act</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-4"><span class="HTitleText2">Repeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canadian Energy Regulator Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-8"><span class="HTitleText2">Repeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-9"><span class="HLabel1">PART 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Navigation Protection Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-10"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-11"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>81 - </span><a href="#h-12"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Consequential and Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>81 - </span><a href="#h-13"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>81 - </span><a href="#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Energy Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Energy Supplies Emergency Act</cite></span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-18"><span class="HTitleText3"><cite class="XRefExternalAct">Export Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-21"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-22"><span class="HTitleText3"><cite class="XRefExternalAct">Northern Pipeline Act</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-23"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Oil and Gas Operations Act</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-24"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-25"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Petroleum Resources Act</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-28"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Transportation Accident Investigation and Safety Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-29"><span class="HTitleText3"><cite class="XRefExternalAct">Hibernia Development Project Act</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-30"><span class="HTitleText3"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-31"><span class="HTitleText3"><cite class="XRefExternalAct">Transportation of Dangerous Goods Act, 1992</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-32"><span class="HTitleText3"><cite class="XRefExternalAct">Yukon Surface Rights Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-33"><span class="HTitleText3"><cite class="XRefExternalAct">Mackenzie Valley Resource Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-34"><span class="HTitleText3"><cite class="XRefExternalAct">Yukon Act</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-35"><span class="HTitleText3"><cite class="XRefExternalAct">Nunavut Waters and Nunavut Surface Rights Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-36"><span class="HTitleText3"><cite class="XRefExternalAct">Species at Risk Act</cite></span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-37"><span class="HTitleText3"><cite class="XRefExternalAct">Yukon Environmental and Socio-economic Assessment Act</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-38"><span class="HTitleText3"><cite class="XRefExternalAct">First Nations Oil and Gas and Moneys Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-39"><span class="HTitleText3"><cite class="XRefExternalAct">Environmental Violations Administrative Monetary Penalties Act</cite></span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-40"><span class="HTitleText3"><cite class="XRefExternalAct">Bridge To Strengthen Trade Act</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Nunavut Planning and Project Assessment Act</cite></span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Northwest Territories Devolution Act</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-43"><span class="HTitleText3"><cite class="XRefExternalAct">Northwest Territories Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>186 - </span><a href="#h-44"><span class="HTitleText2">Terminology</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-45"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-46"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-47"><span class="scheduleLabel">Schedule</span> </a>
</li></ul>
</li></ul>

</nav>

