<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Export Development Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">EXPORT DEVELOPMENT ACT</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-2"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-2.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Bretton Woods and Related Agreements Act</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Other Federal Acts</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-11"><span class="HTitleText2">Regulations and Other Instruments</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="page-2.html#h-12"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

