<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend certain Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CANADA CUSTOMS AND REVENUE AGENCY ACT</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">CUSTOMS ACT</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">FINANCIAL ADMINISTRATION ACT</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-5"><span class="HTitleText1">IMPORTATION OF INTOXICATING LIQUORS ACT</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-6"><span class="HTitleText1">LIEUTENANT GOVERNORS SUPERANNUATION ACT</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-7"><span class="HTitleText1">MODERNIZATION OF BENEFITS AND OBLIGATIONS ACT</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-8"><span class="HTitleText1">NATIONAL ROUND TABLE ON THE ENVIRONMENT AND THE ECONOMY ACT</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="page-3.html#h-9"><span class="HTitleText1">PARLIAMENT OF CANADA ACT</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-10"><span class="HTitleText1">SALARIES ACT</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-11"><span class="HTitleText1">SUPPLEMENTARY RETIREMENT BENEFITS ACT</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-12"><span class="HTitleText1">CONSULAR FEES (SPECIALIZED SERVICES) REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-13"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Lieutenant Governors Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Bill C-25</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="page-4.html#h-16"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

