<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Victims Bill of Rights Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CANADIAN VICTIMS BILL OF RIGHTS</cite></span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">PARLIAMENTARY REVIEW</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL CODE</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-6"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-7"><span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">CORRECTIONS AND CONDITIONAL RELEASE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-8"><span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">CANADA EVIDENCE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-9"><span class="HTitleText1">AMENDMENT TO THE <cite class="XRefExternalAct">EMPLOYMENT INSURANCE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-10"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

