<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Railway Continuation Act, 2007</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">RAILWAY OPERATIONS</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">OBLIGATIONS</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">EXTENSION OF EACH COLLECTIVE AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HTitleText1">FINAL OFFER SELECTION</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-7"><span class="HTitleText1">NEW COLLECTIVE AGREEMENTS</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-8"><span class="HTitleText1">COSTS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-9"><span class="HTitleText1">AMENDMENT OF NEW COLLECTIVE AGREEMENTS</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-10"><span class="HTitleText1">ENFORCEMENT</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

