<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Anishinabek Nation Education Agreement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-4"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-5"><span class="HTitleText1">Regulations and Orders</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText1">Amendment of Schedule</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-9"><span class="HTitleText2">Privacy Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-10"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-12"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Participating First Nations</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

