<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Canada Labour Code (harassment and violence), the Parliamentary Employment and Staff Relations Act and the Budget Implementation Act, 2017, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>0.1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PART 1</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>0.1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-3"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-4"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-5"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="page-3.html#h-6"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-3.html#h-7"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-4.html#h-8"><span class="HTitleText2">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-4.html#h-9"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-4.html#h-10"><span class="HLabel1">PART 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Budget Implementation Act, 2017, No. 1</cite></span></a>
</li></ul>
</li></ul>

</nav>

