<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Fair Rail for Grain Farmers Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA GRAIN ACT</cite></span></a>
</li>
<li><span class='sectionRange'>5.1 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA TRANSPORTATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalRegulation">ORDER IMPOSING MEASURES TO ADDRESS THE EXTRAORDINARY DISRUPTION TO THE NATIONAL TRANSPORTATION SYSTEM IN RELATION TO GRAIN MOVEMENT</cite></span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-5"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-6"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

