<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Remote Sensing Space Systems Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">DESIGNATION OF MINISTER</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">APPLICATION OF ACT</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">OPERATION OF REMOTE SENSING SPACE SYSTEMS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Requirement for Licence</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Applications, Licences and Related Matters</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Amendment, Suspension and Cancellation of Licences</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Interruptions of Service</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Priority Access</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Transfer of Remote Sensing Satellites</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="page-3.html#h-12"><span class="HTitleText1">INSPECTION</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-13"><span class="HTitleText1">REQUESTS FOR INFORMATION</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-14"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-15"><span class="HTitleText1">DELEGATION</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-16"><span class="HTitleText1">NO LIABILITY</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-4.html#h-17"><span class="HTitleText1">ADMINISTRATIVE MONETARY PENALTIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Enforcement Officers</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-4.html#h-20"><span class="HTitleText2">Notices of Violation</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-4.html#h-21"><span class="HTitleText2">Determination of Responsibility and Penalty</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="page-4.html#h-22"><span class="HTitleText3">Payment of Penalty</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-4.html#h-23"><span class="HTitleText3">Making Representations</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-4.html#h-24"><span class="HTitleText3">Responsibility</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="page-4.html#h-25"><span class="HTitleText2">Appeal to Minister</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-4.html#h-26"><span class="HTitleText2">Rules about Violations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-27"><span class="HTitleText2">Recovery of Penalties and Amounts</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="page-4.html#h-28"><span class="HTitleText1">OFFENCES</span></a>
</li>
<li><span class='sectionRange'>45.1 - </span><a href="page-5.html#h-29"><span class="HTitleText1">REVIEW AND REPORT</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-30"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-31"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

