<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Food and Drugs Act, the Hazardous Products Act, the Radiation Emitting Devices Act, the Canadian Environmental Protection Act, 1999, the Pest Control Products Act and the Canada Consumer Product Safety Act and to make related amendments to another Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Food and Drugs Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-2"><span class="HTitleText1">Hazardous Products Act</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-3"><span class="HTitleText1">Radiation Emitting Devices Act</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-4"><span class="HTitleText1">Canadian Environmental Protection Act, 1999</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-5"><span class="HTitleText1">Pest Control Products Act</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-6"><span class="HTitleText1">Canada Consumer Product Safety Act</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-7"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-8"><span class="HTitleText1">Related Amendments to the Agriculture and Agri-Food Administrative Monetary Penalties Act</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-9"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-10"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

