<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Tackling Violent Crime Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL CODE</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-8.html#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="page-8.html#h-4"><span class="HTitleText2">Aeronautics Act</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-8.html#h-5"><span class="HTitleText2">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-8.html#h-6"><span class="HTitleText2">Criminal Records Act</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-8.html#h-7"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-8.html#h-8"><span class="HTitleText2">Railway Safety Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="page-8.html#h-9"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-9.html#h-10"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

