<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Criminal Code, the Youth Criminal Justice Act and other Acts and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Criminal Code</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>354 - </span><a href="#h-3"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>361 - </span><a href="#h-4"><span class="HTitleText1">Youth Criminal Justice Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>361 - </span><a href="#h-5"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>384 - </span><a href="#h-6"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>385 - </span><a href="#h-7"><span class="HTitleText1">Controlled Drugs and Substances Act</span></a>
</li>
<li><span class='sectionRange'>386 - </span><a href="#h-8"><span class="HTitleText1">An Act to amend the Criminal Code (exploitation and trafficking in persons)</span></a>
</li>
<li><span class='sectionRange'>387 - </span><a href="#h-9"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>387 - </span><a href="#h-10"><span class="HTitleText2">Competition Act</span></a>
</li>
<li><span class='sectionRange'>388 - </span><a href="#h-11"><span class="HTitleText2">Identification of Criminals Act</span></a>
</li>
<li><span class='sectionRange'>389 - </span><a href="#h-12"><span class="HTitleText2">Parliament of Canada Act</span></a>
</li>
<li><span class='sectionRange'>391 - </span><a href="#h-13"><span class="HTitleText2">Supreme Court Act</span></a>
</li>
<li><span class='sectionRange'>392 - </span><a href="#h-14"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="#h-15"><span class="HTitleText2">Mutual Legal Assistance in Criminal Matters Act</span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="#h-16"><span class="HTitleText2">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>396 - </span><a href="#h-17"><span class="HTitleText2">Contraventions Act</span></a>
</li>
<li><span class='sectionRange'>399 - </span><a href="#h-18"><span class="HTitleText2">Crimes Against Humanity and War Crimes Act</span></a>
</li>
<li><span class='sectionRange'>400 - </span><a href="#h-19"><span class="HTitleText2">Species at Risk Act</span></a>
</li>
<li><span class='sectionRange'>400.1 - </span><a href="#h-20"><span class="HTitleText2">Cannabis Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>401 - </span><a href="#h-21"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>405 - </span><a href="#h-22"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

