<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Softwood Lumber Products Export Charge Act, 2006</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-4"><span class="HTitleText1">APPLICATION</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-5"><span class="HTitleText1">SOFTWOOD LUMBER PRODUCTS EXPORT CHARGE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Export Charge</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-7"><span class="HTitleText2">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="page-3.html#h-8"><span class="HTitleText1">CHARGE ON REFUNDS OF DUTY DEPOSITS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-9"><span class="HTitleText1">GENERAL PROVISIONS CONCERNING CHARGES AND OTHER AMOUNTS PAYABLE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Administration, Enforcement and Officers</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Registration and Certification</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-4.html#h-12"><span class="HTitleText2">Returns and Payment of Charges</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-13"><span class="HTitleText2">Interest</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-5.html#h-14"><span class="HTitleText2">Administrative Charge under the <cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-5.html#h-15"><span class="HTitleText2">Refunds</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-16"><span class="HTitleText2">Bankruptcies and Corporate Reorganizations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-6.html#h-17"><span class="HTitleText2">Partnerships</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-6.html#h-18"><span class="HTitleText2">Records and Information</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-6.html#h-19"><span class="HTitleText2">Assessments</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-7.html#h-20"><span class="HTitleText2">Objections to Assessment</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-7.html#h-21"><span class="HTitleText2">Appeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="page-8.html#h-22"><span class="HTitleText1">ADMINISTRATION AND ENFORCEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="page-8.html#h-23"><span class="HTitleText2">Penalties</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-9.html#h-24"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-9.html#h-25"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-10.html#h-26"><span class="HTitleText2">Investigation</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-10.html#h-27"><span class="HTitleText2">Confidentiality of Information</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-11.html#h-28"><span class="HTitleText2">Collection</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-13.html#h-29"><span class="HTitleText2">Evidence and Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="page-14.html#h-30"><span class="HTitleText1">PAYMENTS TO PROVINCES</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-14.html#h-31"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-14.html#h-32"><span class="HTitleText1">EXPIRY</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-14.html#h-33"><span class="HTitleText1">PAYMENT TO ACCOUNTS</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-14.html#h-34"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-15.html#h-35"><span class="HTitleText1">AMENDMENTS TO THE EXPORT AND IMPORT PERMITS ACT</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-16.html#h-36"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>118 - </span><a href="page-16.html#h-37"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-16.html#h-38"><span class="HTitleText2">Canada Revenue Agency Act</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-16.html#h-39"><span class="HTitleText2">Tax Court of Canada Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>125 - </span><a href="page-16.html#h-40"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-17.html#h-41"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-18.html#h-42"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - EXEMPT PERSONS</span></a>
</li></ul>
</li></ul>

</nav>

