<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2006</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS RELATING TO THE GST/HST RATE REDUCTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Amendments Relating to the GST/HST</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-4"><span class="HTitleText3"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-5"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-6"><span class="HTitleText3">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-7"><span class="HTitleText3">Amendments Relating to the Taxation of Tobacco Products</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-8"><span class="HTitleText4"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-9"><span class="HTitleText4">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-10"><span class="HTitleText3">Amendments Relating to Alcohol Products</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-11"><span class="HTitleText4"><cite class="XRefExternalAct">Excise Act</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-12"><span class="HTitleText4">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-13"><span class="HTitleText4">Application</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-14"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE INCOME TAX ACT</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-15"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS RELATING TO EXCISE TAX ON JEWELLERY, ETC.</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-16"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-17"><span class="HTitleText2">Budget Implementation Act, 2005</span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-18"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">AMENDMENTS RELATING TO ABORIGINAL TAX POWERS AND ABORIGINAL TAX TREATMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-19"><span class="HTitleText2">First Nations Goods and Services Tax Act</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-20"><span class="HTitleText2">Yukon First Nations Self-Government Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-21"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">OTHER TAX-RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-22"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-23"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-24"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-25"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-26"><span class="HTitleText2">Conditional Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="#h-27"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">UNIVERSAL CHILD CARE BENEFIT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-28"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-29"><span class="HTitleText2">Consequential And Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>169 - </span><a href="#h-30"><span class="HTitleText3">Children’s Special Allowances Act</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-31"><span class="HTitleText3">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-32"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-33"><span class="HTitleText3">Old Age Security Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>181 - </span><a href="#h-34"><span class="HTitleText2">Coming Into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>182 - </span><a href="#h-35"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">AMENDMENTS TO THE FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-36"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">PAYMENTS TO PROVINCES AND TERRITORIES</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-37"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">MORTGAGE INSURANCE</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-38"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">AMENDMENTS RELATING TO FINANCIAL INSTITUTIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>199 - </span><a href="#h-39"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-40"><span class="HTitleText2">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-41"><span class="HTitleText2">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-42"><span class="HTitleText2">Trust and Loan Companies Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>203 - </span><a href="#h-43"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">AMENDMENTS RELATING TO PENSIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>203 - </span><a href="#h-44"><span class="HTitleText2">Canadian Forces Superannuation act</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-45"><span class="HTitleText2">Public Service Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-46"><span class="HTitleText2">Royal Canadian Mounted Police Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-47"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>208 - </span><a href="#h-48"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">MACKENZIE GAS PROJECT IMPACTS ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>208 - </span><a href="#h-49"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-50"><span class="HTitleText2">Payments</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-51"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>210 - </span><a href="#h-52"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-53"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-54"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>213 - </span><a href="#h-55"><span class="HTitleText2">Coming Into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-56"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">MISCELLANEOUS AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-57"><span class="HTitleText2"><cite class="XRefExternalAct">European Bank for Reconstruction and Development Agreement Act</cite></span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-58"><span class="HTitleText2">Freshwater Fish Marketing Act</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-59"><span class="HTitleText2">Public Sector Pension Investment Board Act</span></a>
</li></ul>
</li><li><a href="#h-60"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-61"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

