<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Family Homes on Reserves and Matrimonial Interests or Rights Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">PURPOSE AND APPLICATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">ENACTMENT OF FIRST NATION LAWS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText2">Power of First Nations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText2">Community Approval</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText1">PROVISIONAL FEDERAL RULES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-11"><span class="HTitleText2">Family Home</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-12"><span class="HTitleText3">Occupation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-13"><span class="HTitleText3">Emergency Protection Order</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-14"><span class="HTitleText3">Exclusive Occupation Order</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-15"><span class="HTitleText3">Other Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-16"><span class="HTitleText2">Division of the Value of Matrimonial Interests or Rights</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-17"><span class="HTitleText3">Breakdown of a Conjugal Relationship</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-18"><span class="HTitleText3">Death of a Spouse or Common-Law Partner</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-19"><span class="HTitleText2">Notice to Council and Views of Council</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-20"><span class="HTitleText2">Jurisdiction of Courts</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-21"><span class="HTitleText2">Rules of Practice and Procedure</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-22"><span class="HTitleText2">Other Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 - </span><a href="#h-23"><span class="HTitleText1">REGULATIONS</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-24"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-25"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

