<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
CONSTITUTION ACT, 1867</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">I. Preliminary</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-2"><span class="HTitleText1">II. Union</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-3"><span class="HTitleText1">III. Executive Power</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-4"><span class="HTitleText1">IV. Legislative Power</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-1.html#h-5"><span class="HTitleText2">The Senate</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-1.html#h-6"><span class="HTitleText2">The House of Commons</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Money Votes; Royal Assent</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="page-2.html#h-8"><span class="HTitleText1">V. Provincial Constitutions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Executive Power</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Legislative Power</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="page-2.html#h-11"><span class="HTitleText3">1. Ontario</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-2.html#h-12"><span class="HTitleText3">2. Quebec</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-2.html#h-13"><span class="HTitleText3">3. Ontario and Quebec</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-2.html#h-14"><span class="HTitleText3">4. Nova Scotia and New Brunswick</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-2.html#h-15"><span class="HTitleText3">5. Ontario, Quebec, and Nova Scotia</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-2.html#h-16"><span class="HTitleText3">6. The Four Provinces</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="page-3.html#h-17"><span class="HTitleText1">VI. Distribution of Legislative Powers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-3.html#h-18"><span class="HTitleText2">Powers of the Parliament</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-3.html#h-19"><span class="HTitleText2">Exclusive Powers of Provincial Legislatures</span></a>
</li>
<li><span class='sectionRange'>92A - </span><a href="page-3.html#h-20"><span class="HTitleText2">Non-Renewable Natural Resources, Forestry Resources and Electrical Energy</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-3.html#h-21"><span class="HTitleText2">Education</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-3.html#h-22"><span class="HTitleText2">Uniformity of Laws in Ontario, Nova Scotia, and New Brunswick</span></a>
</li>
<li><span class='sectionRange'>94A - </span><a href="page-3.html#h-23"><span class="HTitleText2">Old Age Pensions</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-3.html#h-24"><span class="HTitleText2">Agriculture and Immigration</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="page-3.html#h-25"><span class="HTitleText1">VII. Judicature</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-3.html#h-26"><span class="HTitleText1">VIII. Revenues; Debts; Assets; Taxation</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-4.html#h-27"><span class="HTitleText1">IX. Miscellaneous Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="page-4.html#h-28"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-4.html#h-29"><span class="HTitleText2">Ontario and Quebec</span></a>
</li></ul>
</li><li><span class='sectionRange'>145 - </span><a href="page-4.html#h-30"><span class="HTitleText1">X. Intercolonial Railway</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-4.html#h-31"><span class="HTitleText1">XI. Admission of Other Colonies</span></a>
</li>
<li><a href="page-5.html#h-32"><span class="scheduleLabel">THE FIRST SCHEDULE</span> - <span class="scheduleTitleText"> - Electoral Districts of Ontario</span></a>
</li>
<li><a href="page-6.html#h-33"><span class="scheduleLabel">THE SECOND SCHEDULE</span> - <span class="scheduleTitleText"> - Electoral Districts of Quebec specially fixed</span></a>
</li>
<li><a href="page-7.html#h-34"><span class="scheduleLabel">THE THIRD SCHEDULE</span> - <span class="scheduleTitleText"> - Provincial Public Works and Property to be the Property of Canada</span></a>
</li>
<li><a href="page-8.html#h-35"><span class="scheduleLabel">THE FOURTH SCHEDULE</span> - <span class="scheduleTitleText"> - Assets to be the Property of Ontario and Quebec conjointly</span></a>
</li>
<li><a href="page-9.html#h-36"><span class="scheduleLabel">THE FIFTH SCHEDULE</span></a>
</li>
<li><a href="page-10.html#h-37"><span class="scheduleLabel">THE SIXTH SCHEDULE</span> - <span class="scheduleTitleText"> - Primary Production from Non-Renewable Natural Resources and Forestry Resources</span></a>
</li></ul>
</li><li><span class='sectionRange'>1 - </span><a href="page-11.html#h-38">CANADA ACT 1982</a>
</li>
<li><span class='sectionRange'>1 - </span><a href="page-12.html#h-39">CONSTITUTION ACT, 1982</a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-12.html#h-40"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Canadian Charter of Rights and Freedoms</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-12.html#h-41"><span class="HTitleText2">Guarantee of Rights and Freedoms</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-12.html#h-42"><span class="HTitleText2">Fundamental Freedoms</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-12.html#h-43"><span class="HTitleText2">Democratic Rights</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-12.html#h-44"><span class="HTitleText2">Mobility Rights</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-12.html#h-45"><span class="HTitleText2">Legal Rights</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-12.html#h-46"><span class="HTitleText2">Equality Rights</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-12.html#h-47"><span class="HTitleText2">Official Languages of Canada</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-12.html#h-48"><span class="HTitleText2">Minority Language Educational Rights</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-12.html#h-49"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-12.html#h-50"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-12.html#h-51"><span class="HTitleText2">Application of Charter</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-12.html#h-52"><span class="HTitleText2">Citation</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-13.html#h-53"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Rights of the Aboriginal Peoples of Canada</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-13.html#h-54"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Equalization and Regional Disparities</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-13.html#h-55"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Constitutional Conference</span></a>
</li>
<li><span class='sectionRange'>37.1 - </span><a href="page-13.html#h-56"><span class="HLabel1">PART IV.I</span> - <span class="HTitleText1">Constitutional Conferences</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-13.html#h-57"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Procedure for Amending Constitution of Canada<span class="wb-invisible">End note </span><sup>(102)</sup></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-13.html#h-58"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Amendment to the <cite class="XRefExternalAct">Constitution Act, 1867</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-13.html#h-59"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">General</span></a>
</li>
<li><a href="page-14.html#h-60"><span class="scheduleTitleText">Schedule to the Constitution Act, 1982</span> </a>
</li></ul>
</li>
<li><a href="endNotes.html"><span class="scheduleTitleText">Endnotes</span> </a>
</li></ul>

</nav>

