<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act respecting further COVID-19 measures</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Income Tax Act</cite> and <cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-3"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="page-2.html#h-4"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">One-time Payment to Persons with Disabilities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-2.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Pension Act</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Veterans Affairs Act</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Children’s Special Allowances Act</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Veterans Well-being Act</cite></span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Payment out of Consolidated Revenue Fund</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="page-2.html#h-11"><span class="HLabel1">PART 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Time Limits and Other Periods Act (COVID-19)</cite></span></a>
</li>
<li><a href="page-3.html#h-12"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

