<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Offshore Health and Safety Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA-NEWFOUNDLAND ATLANTIC ACCORD IMPLEMENTATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA-NOVA SCOTIA OFFSHORE PETROLEUM RESOURCES ACCORD IMPLEMENTATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-5"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-6"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA LABOUR CODE</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-7"><span class="HTitleText1"><cite class="XRefExternalAct">ACCESS TO INFORMATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-8"><span class="HTitleText1"><cite class="XRefExternalAct">EXCISE TAX ACT</cite></span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-9"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA OIL AND GAS OPERATIONS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-10"><span class="HTitleText1"><cite class="XRefExternalAct">PRIVACY ACT</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-11"><span class="HTitleText1"><cite class="XRefExternalAct">HAZARDOUS MATERIALS INFORMATION REVIEW ACT</cite></span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-12"><span class="HTitleText1"><cite class="XRefExternalAct">HIBERNIA DEVELOPMENT PROJECT ACT</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-13"><span class="HTitleText1"><cite class="XRefExternalRegulation">FEDERAL AUTHORITIES REGULATIONS</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-14"><span class="HTitleText1">TERMINOLOGY</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-15"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-16"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

