<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Judges Act and the Criminal Code</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Judges Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Criminal Code</span></a>
</li></ul>
</li></ul>

</nav>

