<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act respecting equalization and authorizing the Minister of Finance to make certain payments related to health</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-2"><span class="HTitleText1">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS REGULATIONS, 1999</span></a>
</li></ul>
</li></ul>

</nav>

