<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Gender Equity in Indian Registration Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INDIAN ACT</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-3"><span class="HTitleText1">REPORT TO PARLIAMENT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">RELATED PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

