<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Fair Representation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CONSTITUTION ACT, 1867</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">ELECTORAL BOUNDARIES READJUSTMENT ACT</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA ELECTIONS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-5"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-6"><span class="HTitleText1">INTERPRETATION</span></a>
</li></ul>
</li></ul>

</nav>

