<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Pipeline Safety Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">NATIONAL ENERGY BOARD ACT</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-5.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA OIL AND GAS OPERATIONS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-6.html#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

