<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend certain Acts as a result of the accession of the People’s Republic of China to the Agreement Establishing the World Trade Organization</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CANADIAN INTERNATIONAL TRADE TRIBUNAL ACT</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-2"><span class="HTitleText1">CUSTOMS TARIFF</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-3.html#h-3"><span class="HTitleText1">EXPORT AND IMPORT PERMITS ACT</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-4.html#h-4"><span class="HTitleText1">SPECIAL IMPORT MEASURES ACT</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-4.html#h-5"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-4.html#h-6"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-5.html#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

