<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Helping Families in Need Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternal">CANADA LABOUR CODE</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-3"><span class="HTitleText1">EMPLOYMENT INSURANCE ACT</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-5.html#h-4"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="page-5.html#h-5"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-5.html#h-6"><span class="HTitleText2">Income Tax Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="page-5.html#h-7"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-5.html#h-8"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-6.html#h-9"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

