<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Northern Jobs and Growth Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">NUNAVUT PLANNING AND PROJECT ASSESSMENT ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-2.html#h-5"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-7"><span class="HTitleText3"><cite class="XRefExternalAct">Nunavut Waters and Nunavut Surface Rights Tribunal Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="page-2.html#h-9"><span class="HLabel1">PART 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">NORTHWEST TERRITORIES SURFACE RIGHTS BOARD ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Related Amendments to the <cite class="XRefExternalAct">Yukon Surface Rights Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="page-3.html#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Oil and Gas Operations Act</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-4.html#h-17"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

