<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Anti-terrorism Act, 2015</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">SECURITY OF CANADA INFORMATION SHARING ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText3"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Fisheries and Oceans Act</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-7"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-8"><span class="HTitleText3"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-9"><span class="HTitleText3"><cite class="XRefExternalAct">Chemical Weapons Convention Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-11"><span class="HTitleText2">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-12"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-13"><span class="HLabel1">PART 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">SECURE AIR TRAVEL ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-14"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-15"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Aeronautics Act</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-18"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-19"><span class="HLabel1">PART 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL CODE</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-20"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-21"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-22"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-23"><span class="HTitleText3"><cite class="XRefExternalAct">Prisons and Reformatories Act</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-24"><span class="HTitleText3"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-25"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Youth Criminal Justice Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="#h-27"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-28"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-29"><span class="HLabel1">PART 4</span> - <span class="HTitleText1"><cite class="XRefExternalAct">CANADIAN SECURITY INTELLIGENCE SERVICE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-30"><span class="HLabel1">PART 5</span> - <span class="HTitleText1"><cite class="XRefExternalAct">IMMIGRATION AND REFUGEE PROTECTION ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="#h-31"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-32"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-33"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-34"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

