<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Energy Safety and Security Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">MODERNIZING CANADA’S OFFSHORE OIL AND GAS OPERATIONS REGIME</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Oil and Gas Operations Act</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-6.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Petroleum Resources Act</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-7.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Canada-Newfoundland Atlantic Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-13.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-19.html#h-7"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="page-19.html#h-8"><span class="HTitleText3"><cite class="XRefExternalAct">Nova Scotia and Newfoundland and Labrador Additional Fiscal Equalization Offset Payments Act</cite></span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-19.html#h-9"><span class="HTitleText3"><cite class="XRefExternalAct">Budget and Economic Statement Implementation Act, 2007</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="page-19.html#h-10"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-20.html#h-11"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>120 - </span><a href="page-20.html#h-12"><span class="HLabel1">PART 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">NUCLEAR LIABILITY AND COMPENSATION ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="page-20.html#h-13"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-21.html#h-14"><span class="HTitleText2">Amendments to the <cite class="XRefExternalAct">Nuclear Liability and Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-21.html#h-15"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="page-21.html#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Transportation of Dangerous Goods Act, 1992</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-21.html#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Nuclear Safety and Control Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="page-21.html#h-18"><span class="HTitleText2">Terminology</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-21.html#h-19"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-21.html#h-20"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-22.html#h-21"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-23.html#h-22"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-24.html#h-23"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-25.html#h-24"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li></ul>
</li></ul>

</nav>

