<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Criminal Code (organized crime and law enforcement) and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-8.html#h-2"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="page-8.html#h-3"><span class="HTitleText2">Controlled Drugs and Substances Act</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-9.html#h-4"><span class="HTitleText2">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-9.html#h-5"><span class="HTitleText2">Corruption of Foreign Public Officials Act</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-9.html#h-6"><span class="HTitleText2">Crimes Against Humanity and War Crimes Act</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-9.html#h-7"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-9.html#h-8"><span class="HTitleText2">Excise Act</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-10.html#h-9"><span class="HTitleText2">Mutual Legal Assistance in Criminal Matters Act</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-10.html#h-10"><span class="HTitleText2">National Defence Act</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-11.html#h-11"><span class="HTitleText2">Proceeds of Crime (money laundering) Act</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-11.html#h-12"><span class="HTitleText2">Proceeds of Crime (Money Laundering) Act</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-11.html#h-13"><span class="HTitleText2">Seized Property Management Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="page-12.html#h-14"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-13.html#h-15"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

