<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
COVID-19 Emergency Response Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Income Tax Act</cite> and <cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Emergency Response Benefit Act</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PART 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Public Health Events of National Concern Payments Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-9"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-10"><span class="HLabel1">PART 4</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-11"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-12"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-13"><span class="HLabel1">PART 5</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Mortgage and Housing Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-14"><span class="HLabel1">PART 6</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Export Development Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-15"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-16"><span class="HTitleText2">Suspension of Certain Provisions of the <cite class="XRefExternalRegulation">Export Development Canada Exercise of Certain Powers Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-17"><span class="HLabel1">PART 7</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-18"><span class="HLabel1">PART 8</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-19"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-20"><span class="HTitleText2">Related Amendments to the <cite class="XRefExternalAct">Borrowing Authority Act</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-21"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-22"><span class="HLabel1">PART 9</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Food and Drugs Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-23"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-24"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-25"><span class="HLabel1">PART 10</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="#h-26"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-27"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Budget Implementation Act, 2018, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-28"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-29"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-30"><span class="HLabel1">PART 11</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">National Housing Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-31"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-32"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-33"><span class="HLabel1">PART 12</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Patent Act</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-34"><span class="HLabel1">PART 13</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Student Loans Act</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-35"><span class="HLabel1">PART 14</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Farm Credit Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-36"><span class="HLabel1">PART 15</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Student Financial Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-37"><span class="HLabel1">PART 16</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Business Development Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-38"><span class="HLabel1">PART 17</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Apprentice Loans Act</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-39"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">Employment Insurance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>57 - </span><a href="#h-40"><span class="HLabel2">DIVISION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-41"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Medical Certificates</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

