<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal Framework on Post-Traumatic Stress Disorder Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Federal Framework on Post-Traumatic Stress Disorder</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Review and Report</span></a>
</li></ul>
</li></ul>

</nav>

