<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Criminal Code (mental disorder) and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-2"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-3"><span class="HTitleText2">An Act to amend the Criminal Code (mental disorder) and to amend the National Defence Act and the Young Offenders Act in consequence thereof</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-4"><span class="HTitleText2">An Act to amend the Criminal Code (sentencing) and other Acts in consequence thereof</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-5"><span class="HTitleText2">An Act to amend the Criminal Code, the Controlled Drugs and Substances Act and the Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-6"><span class="HTitleText2">An Act to amend the Criminal Code (victims of crime) and another Act in consequence</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-7"><span class="HTitleText2">National Defence Act</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-8"><span class="HTitleText2">Nuclear Safety and Control Act</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-9"><span class="HTitleText2">Youth Criminal Justice Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="#h-10"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

