<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Copyright Act (access to copyrighted works or other subject-matter for persons with perceptual disabilities)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Copyright Act</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

