<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Jobs and Economic Growth Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE INCOME TAX ACT AND RELATED ACTS AND REGULATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-4"><span class="HTitleText2">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-5"><span class="HTitleText2">Canada Disability Savings Act</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-4.html#h-6"><span class="HTitleText2">Canada Disability Savings Regulations</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-4.html#h-7"><span class="HTitleText2">Canada Education Savings Act</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-8"><span class="HTitleText2">Canada Education Savings Regulations</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-9"><span class="HTitleText2">Canada Pension Plan Regulations</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-10"><span class="HTitleText2">Insurable Earnings and Collection of Premiums Regulations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-11"><span class="HTitleText2">Regulations Excluding Certain Indictable Offences from the Definition of “Designated Offence”</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="page-4.html#h-12"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF EXCISE DUTIES AND SALES AND EXCISE TAXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-4.html#h-13"><span class="HTitleText2">Excise Act</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-14"><span class="HTitleText2">Amendments in Respect of the Excise Act, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="page-4.html#h-15"><span class="HTitleText3">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-16"><span class="HTitleText3">Customs Act</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-6.html#h-17"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="page-6.html#h-18"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-16.html#h-19"><span class="HTitleText2">Health Care Services (GST/HST) Regulations</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-17.html#h-20"><span class="HTitleText2">Input Tax Credit Allocation Methods (GST/HST) Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-17.html#h-21"><span class="HTitleText3">Making of Regulations</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-17.html#h-22"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>93 - </span><a href="page-17.html#h-23"><span class="HTitleText2">Interest Rates (Excise Act, 2001) Regulations</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-17.html#h-24"><span class="HTitleText2">Interest Rates (Excise Tax Act) Regulations</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-17.html#h-25"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="page-18.html#h-26"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF THE AIR TRAVELLERS SECURITY CHARGE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>96 - </span><a href="page-18.html#h-27"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-18.html#h-28"><span class="HTitleText2">Interest Rates (Air Travellers Security Charge Act) Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="page-18.html#h-29"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">SOFTWOOD LUMBER PRODUCTS EXPORT CHARGE ACT, 2006</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-18.html#h-30"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-18.html#h-31"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="page-18.html#h-32"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CUSTOMS TARIFF</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="page-18.html#h-33"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1645 - </span><a href="page-72.html#h-34"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1646 - </span><a href="page-72.html#h-35"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>1649 - </span><a href="page-72.html#h-36"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">EXPENDITURE RESTRAINT ACT</span></a>
</li>
<li><span class='sectionRange'>1650 - </span><a href="page-73.html#h-37"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">AMENDMENTS RELATING TO CERTAIN GOVERNMENTAL BODIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1650 - </span><a href="page-73.html#h-38"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Amendments Relating to Certain Governor in Council Appointments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1650 - </span><a href="page-73.html#h-39"><span class="HTitleText3">Alberta-British Columbia Boundary Act, 1974</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1650 - </span><a href="page-73.html#h-40"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1653 - </span><a href="page-73.html#h-41"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1654 - </span><a href="page-73.html#h-42"><span class="HTitleText3">Asia-Pacific Foundation of Canada Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1654 - </span><a href="page-73.html#h-43"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1655 - </span><a href="page-73.html#h-44"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1656 - </span><a href="page-73.html#h-45"><span class="HTitleText3">Assisted Human Reproduction Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1656 - </span><a href="page-73.html#h-46"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1657 - </span><a href="page-73.html#h-47"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1658 - </span><a href="page-73.html#h-48"><span class="HTitleText3">Budget Implementation Act, 1997</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1658 - </span><a href="page-73.html#h-49"><span class="HTitleText4">Amendment to the Act (Canada Foundation for Innovation)</span></a>
</li>
<li><span class='sectionRange'>1659 - </span><a href="page-73.html#h-50"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1660 - </span><a href="page-73.html#h-51"><span class="HTitleText3">Business Development Bank of Canada Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1660 - </span><a href="page-73.html#h-52"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1661 - </span><a href="page-73.html#h-53"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1662 - </span><a href="page-73.html#h-54"><span class="HTitleText3">Canada Grain Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1662 - </span><a href="page-73.html#h-55"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1664 - </span><a href="page-73.html#h-56"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1665 - </span><a href="page-73.html#h-57"><span class="HTitleText3">Canada Mortgage and Housing Corporation Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1665 - </span><a href="page-73.html#h-58"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1667 - </span><a href="page-73.html#h-59"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1668 - </span><a href="page-73.html#h-60"><span class="HTitleText3">Canada Pension Plan</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1668 - </span><a href="page-73.html#h-61"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1670 - </span><a href="page-73.html#h-62"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1671 - </span><a href="page-73.html#h-63"><span class="HTitleText3">Canada School of Public Service Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1671 - </span><a href="page-73.html#h-64"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1674 - </span><a href="page-74.html#h-65"><span class="HTitleText4">Related Amendment to the Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>1675 - </span><a href="page-74.html#h-66"><span class="HTitleText4">Related Amendments to the Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>1676 - </span><a href="page-74.html#h-67"><span class="HTitleText4">Related Amendment to the Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>1677 - </span><a href="page-74.html#h-68"><span class="HTitleText4">Related Amendment to the Privacy Act</span></a>
</li>
<li><span class='sectionRange'>1678 - </span><a href="page-74.html#h-69"><span class="HTitleText4">Related Amendments to the Public Servants Disclosure Protection Act</span></a>
</li>
<li><span class='sectionRange'>1683 - </span><a href="page-74.html#h-70"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1684 - </span><a href="page-74.html#h-71"><span class="HTitleText3">Canadian Centre for Occupational Health and Safety Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1684 - </span><a href="page-74.html#h-72"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1686 - </span><a href="page-74.html#h-73"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1687 - </span><a href="page-74.html#h-74"><span class="HTitleText3">Canadian Centre on Substance Abuse Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1687 - </span><a href="page-74.html#h-75"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1692 - </span><a href="page-75.html#h-76"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1693 - </span><a href="page-75.html#h-77"><span class="HTitleText3">Canadian Institutes of Health Research Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1693 - </span><a href="page-75.html#h-78"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1694 - </span><a href="page-75.html#h-79"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1695 - </span><a href="page-75.html#h-80"><span class="HTitleText3">Canadian International Trade Tribunal Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1695 - </span><a href="page-75.html#h-81"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1696 - </span><a href="page-75.html#h-82"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1697 - </span><a href="page-75.html#h-83"><span class="HTitleText3">Canadian Race Relations Foundation Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1697 - </span><a href="page-75.html#h-84"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1699 - </span><a href="page-75.html#h-85"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1700 - </span><a href="page-75.html#h-86"><span class="HTitleText3">Canadian Radio-television and Telecommunications Commission Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1700 - </span><a href="page-75.html#h-87"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1710 - </span><a href="page-75.html#h-88"><span class="HTitleText4">Consequential Amendment to the Broadcasting Act</span></a>
</li>
<li><span class='sectionRange'>1711 - </span><a href="page-75.html#h-89"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1712 - </span><a href="page-76.html#h-90"><span class="HTitleText3">Canadian Space Agency Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1712 - </span><a href="page-76.html#h-91"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1716 - </span><a href="page-76.html#h-92"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1717 - </span><a href="page-76.html#h-93"><span class="HTitleText3">Canadian Tourism Commission Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1717 - </span><a href="page-76.html#h-94"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1722 - </span><a href="page-76.html#h-95"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1723 - </span><a href="page-76.html#h-96"><span class="HTitleText3">Department of Human Resources and Skills Development Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1723 - </span><a href="page-76.html#h-97"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1724 - </span><a href="page-76.html#h-98"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1725 - </span><a href="page-76.html#h-99"><span class="HTitleText3">Energy Supplies Emergency Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1725 - </span><a href="page-76.html#h-100"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1728 - </span><a href="page-76.html#h-101"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1729 - </span><a href="page-76.html#h-102"><span class="HTitleText3">Export Development Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1729 - </span><a href="page-76.html#h-103"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1730 - </span><a href="page-76.html#h-104"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1731 - </span><a href="page-76.html#h-105"><span class="HTitleText3">Farm Products Agencies Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1731 - </span><a href="page-76.html#h-106"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1732 - </span><a href="page-76.html#h-107"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1733 - </span><a href="page-76.html#h-108"><span class="HTitleText3">First Nations Fiscal and Statistical Management Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1733 - </span><a href="page-76.html#h-109"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1737 - </span><a href="page-77.html#h-110"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1738 - </span><a href="page-77.html#h-111"><span class="HTitleText3">Freshwater Fish Marketing Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1738 - </span><a href="page-77.html#h-112"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1739 - </span><a href="page-77.html#h-113"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1740 - </span><a href="page-77.html#h-114"><span class="HTitleText3">Historic Sites and Monuments Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1740 - </span><a href="page-77.html#h-115"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1742 - </span><a href="page-77.html#h-116"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1743 - </span><a href="page-77.html#h-117"><span class="HTitleText3">International Boundary Commission Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1743 - </span><a href="page-77.html#h-118"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1745 - </span><a href="page-77.html#h-119"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1746 - </span><a href="page-77.html#h-120"><span class="HTitleText3">International Development Research Centre Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1746 - </span><a href="page-77.html#h-121"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1754 - </span><a href="page-77.html#h-122"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1755 - </span><a href="page-77.html#h-123"><span class="HTitleText3">National Defence Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1755 - </span><a href="page-77.html#h-124"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1756 - </span><a href="page-77.html#h-125"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1757 - </span><a href="page-77.html#h-126"><span class="HTitleText3">National Research Council Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1757 - </span><a href="page-77.html#h-127"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1758 - </span><a href="page-77.html#h-128"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1759 - </span><a href="page-77.html#h-129"><span class="HTitleText3">National Round Table on the Environment and the Economy Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1759 - </span><a href="page-77.html#h-130"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1760 - </span><a href="page-78.html#h-131"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1761 - </span><a href="page-78.html#h-132"><span class="HTitleText3">Natural Sciences and Engineering Research Council Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1761 - </span><a href="page-78.html#h-133"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1762 - </span><a href="page-78.html#h-134"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1763 - </span><a href="page-78.html#h-135"><span class="HTitleText3">Public Sector Pension Investment Board Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1763 - </span><a href="page-78.html#h-136"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1764 - </span><a href="page-78.html#h-137"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1765 - </span><a href="page-78.html#h-138"><span class="HTitleText3">Roosevelt Campobello International Park Commission Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1765 - </span><a href="page-78.html#h-139"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1766 - </span><a href="page-78.html#h-140"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1767 - </span><a href="page-78.html#h-141"><span class="HTitleText3">Social Sciences and Humanities Research Council Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1767 - </span><a href="page-78.html#h-142"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1768 - </span><a href="page-78.html#h-143"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1769 - </span><a href="page-78.html#h-144"><span class="HTitleText3">Standards Council of Canada Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1769 - </span><a href="page-78.html#h-145"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1773 - </span><a href="page-78.html#h-146"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1774 - </span><a href="page-78.html#h-147"><span class="HTitleText3">Status of the Artist Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1774 - </span><a href="page-78.html#h-148"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1775 - </span><a href="page-78.html#h-149"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1776 - </span><a href="page-78.html#h-150"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">North American Free Trade Agreement Implementation Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1776 - </span><a href="page-78.html#h-151"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1778 - </span><a href="page-78.html#h-152"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>1779 - </span><a href="page-79.html#h-153"><span class="HTitleText3">Consequential Amendments to the Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>1782 - </span><a href="page-79.html#h-154"><span class="HTitleText3">Consequential Amendment to the Special Import Measures Act</span></a>
</li>
<li><span class='sectionRange'>1783 - </span><a href="page-79.html#h-155"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1784 - </span><a href="page-79.html#h-156"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">The Intercolonial and Prince Edward Island Railways Employees’ Provident Fund Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1784 - </span><a href="page-79.html#h-157"><span class="HTitleText3">Repeal of the Act</span></a>
</li>
<li><span class='sectionRange'>1785 - </span><a href="page-79.html#h-158"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1786 - </span><a href="page-79.html#h-159"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">PENSION BENEFITS STANDARDS ACT, 1985</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1786 - </span><a href="page-79.html#h-160"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1826 - </span><a href="page-86.html#h-161"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>1827 - </span><a href="page-86.html#h-162"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1828 - </span><a href="page-86.html#h-163"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">AGREEMENT ON SOCIAL SECURITY BETWEEN CANADA AND THE REPUBLIC OF POLAND — RETROACTIVE COMING INTO FORCE</span></a>
</li>
<li><span class='sectionRange'>1831 - </span><a href="page-86.html#h-164"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">EXPORT DEVELOPMENT ACT</span></a>
</li>
<li><span class='sectionRange'>1834 - </span><a href="page-86.html#h-165"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">PAYMENT CARD NETWORKS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1834 - </span><a href="page-86.html#h-166"><span class="HTitleText2">Enactment of Payment Card Networks Act</span></a>
</li>
<li><span class='sectionRange'>1835 - </span><a href="page-87.html#h-167"><span class="HTitleText2">Related Amendments to the Financial Consumer Agency of Canada Act</span></a>
</li>
<li><span class='sectionRange'>1850 - </span><a href="page-88.html#h-168"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1851 - </span><a href="page-88.html#h-169"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">FINANCIAL CONSUMER AGENCY OF CANADA ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1851 - </span><a href="page-88.html#h-170"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1858 - </span><a href="page-88.html#h-171"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1858 - </span><a href="page-88.html#h-172"><span class="HTitleText3">Bank Act</span></a>
</li>
<li><span class='sectionRange'>1859 - </span><a href="page-88.html#h-173"><span class="HTitleText3">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>1860 - </span><a href="page-88.html#h-174"><span class="HTitleText3">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>1861 - </span><a href="page-89.html#h-175"><span class="HTitleText3">Trust and Loan Companies Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1862 - </span><a href="page-89.html#h-176"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">PROCEEDS OF CRIME (MONEY LAUNDERING) AND TERRORIST FINANCING ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1862 - </span><a href="page-89.html#h-177"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1883 - </span><a href="page-91.html#h-178"><span class="HTitleText2">Consequential Amendment to the Office of the Superintendent of Financial Institutions act</span></a>
</li>
<li><span class='sectionRange'>1884 - </span><a href="page-91.html#h-179"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1885 - </span><a href="page-91.html#h-180"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">CANADA POST CORPORATION ACT</span></a>
</li>
<li><span class='sectionRange'>1886 - </span><a href="page-91.html#h-181"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">CANADA DEPOSIT INSURANCE CORPORATION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1886 - </span><a href="page-91.html#h-182"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1893 - </span><a href="page-91.html#h-183"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1894 - </span><a href="page-91.html#h-184"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">FEDERAL CREDIT UNIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1894 - </span><a href="page-91.html#h-185"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>2094 - </span><a href="page-111.html#h-186"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>2108 - </span><a href="page-112.html#h-187"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>2110 - </span><a href="page-112.html#h-188"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2110 - </span><a href="page-112.html#h-189"><span class="HTitleText3"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>2113 - </span><a href="page-112.html#h-190"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Cooperatives Act</cite></span></a>
</li>
<li><span class='sectionRange'>2114 - </span><a href="page-112.html#h-191"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li>
<li><span class='sectionRange'>2116 - </span><a href="page-112.html#h-192"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Consumer Agency of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>2117 - </span><a href="page-112.html#h-193"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>2122 - </span><a href="page-113.html#h-194"><span class="HTitleText3"><cite class="XRefExternalAct">Office of the Superintendent of Financial Institutions Act</cite></span></a>
</li>
<li><span class='sectionRange'>2123 - </span><a href="page-113.html#h-195"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>2126 - </span><a href="page-113.html#h-196"><span class="HTitleText3"><cite class="XRefExternalAct">Winding-up and Restructuring Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>2135 - </span><a href="page-114.html#h-197"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>2136 - </span><a href="page-114.html#h-198"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>2137 - </span><a href="page-114.html#h-199"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">ATOMIC ENERGY OF CANADA LIMITED</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2137 - </span><a href="page-114.html#h-200"><span class="HTitleText2">Reorganization and Divestiture</span></a>
</li>
<li><span class='sectionRange'>2147 - </span><a href="page-115.html#h-201"><span class="HTitleText2">Nuclear Energy Act</span></a>
</li>
<li><span class='sectionRange'>2148 - </span><a href="page-115.html#h-202"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>2149 - </span><a href="page-115.html#h-203"><span class="HLabel1">PART 19</span> - <span class="HTitleText1">PARTICIPANT FUNDING PROGRAMS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2149 - </span><a href="page-115.html#h-204"><span class="HTitleText2">National Energy Board Act</span></a>
</li>
<li><span class='sectionRange'>2150 - </span><a href="page-115.html#h-205"><span class="HTitleText2">Nuclear Safety and Control Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>2152 - </span><a href="page-115.html#h-206"><span class="HLabel1">PART 20</span> - <span class="HTitleText1">ENVIRONMENTAL ASSESSMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2152 - </span><a href="page-115.html#h-207"><span class="HTitleText2">Canadian Environmental Assessment Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2152 - </span><a href="page-115.html#h-208"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>2162 - </span><a href="page-116.html#h-209"><span class="HTitleText3">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>2164 - </span><a href="page-116.html#h-210"><span class="HTitleText2">Exclusion List Regulations, 2007</span></a>
</li>
<li><span class='sectionRange'>2167 - </span><a href="page-116.html#h-211"><span class="HTitleText2">Regulations Amending the Exclusion List Regulations, 2007</span></a>
</li>
<li><span class='sectionRange'>2171 - </span><a href="page-116.html#h-212"><span class="HTitleText2">Infrastructure Projects Environmental Assessment Adaptation Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>2172 - </span><a href="page-116.html#h-213"><span class="HLabel1">PART 21</span> - <span class="HTitleText1">CANADA LABOUR CODE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2172 - </span><a href="page-116.html#h-214"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>2178 - </span><a href="page-117.html#h-215"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>2179 - </span><a href="page-117.html#h-216"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>2180 - </span><a href="page-117.html#h-217"><span class="HLabel1">PART 22</span> - <span class="HTitleText1">PAYMENTS TO CERTAIN ENTITIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2180 - </span><a href="page-117.html#h-218"><span class="HTitleText2">Canadian Youth Business Foundation</span></a>
</li>
<li><span class='sectionRange'>2181 - </span><a href="page-117.html#h-219"><span class="HTitleText2">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>2182 - </span><a href="page-117.html#h-220"><span class="HTitleText2">Pathways to Education Canada</span></a>
</li>
<li><span class='sectionRange'>2183 - </span><a href="page-117.html#h-221"><span class="HTitleText2">Rick Hansen Foundation</span></a>
</li></ul>
</li><li><span class='sectionRange'>2184 - </span><a href="page-117.html#h-222"><span class="HLabel1">PART 23</span> - <span class="HTitleText1">TELECOMMUNICATIONS ACT</span></a>
</li>
<li><span class='sectionRange'>2185 - </span><a href="page-117.html#h-223"><span class="HLabel1">PART 24</span> - <span class="HTitleText1">EMPLOYMENT INSURANCE FINANCING</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2185 - </span><a href="page-117.html#h-224"><span class="HTitleText2">Employment Insurance Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2185 - </span><a href="page-117.html#h-225"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>2195 - </span><a href="page-117.html#h-226"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>2201 - </span><a href="page-118.html#h-227"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2201 - </span><a href="page-118.html#h-228"><span class="HTitleText4"><cite class="XRefExternalAct">Department of Human Resources and Skills Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>2202 - </span><a href="page-118.html#h-229"><span class="HTitleText4"><cite class="XRefExternalRegulation">Employment Insurance Regulations</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>2204 - </span><a href="page-118.html#h-230"><span class="HTitleText2">Budget Implementation Act, 2008</span></a>
</li>
<li><span class='sectionRange'>2207 - </span><a href="page-119.html#h-231"><span class="HTitleText2">Canada Employment Insurance Financing Board Act</span></a>
</li>
<li><span class='sectionRange'>2208 - </span><a href="page-119.html#h-232"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-120.html#h-233"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-121.html#h-234"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-122.html#h-235"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>

</nav>

