<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Divorce Act, the Family Orders and Agreements Enforcement Assistance Act and the Garnishment, Attachment and Pension Diversion Act and to make consequential amendments to another Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Divorce Act</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-2"><span class="HTitleText1">Family Orders and Agreements Enforcement Assistance Act</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-3"><span class="HTitleText1">Garnishment, Attachment and Pension Diversion Act</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-4"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-5"><span class="HTitleText1">Consequential Amendments to the Criminal Code</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-6"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-7"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-8"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-9"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

