<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Déline Final Self-Government Agreement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">DÉLINE AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-4"><span class="HTitleText1">DÉLINE GOT’INE GOVERNMENT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-5"><span class="HTitleText1">APPLICATION OF OTHER ACTS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-6"><span class="HTitleText1">TAXATION</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-7"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-8"><span class="HTitleText1">CONSEQUENTIAL AND RELATED AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-2.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Mackenzie Valley Resource Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-3.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">First Nations Goods and Services Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="page-3.html#h-12"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-13"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

