<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Protecting Canadians from Online Crime Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CRIMINAL CODE</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-6.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA EVIDENCE ACT</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-6.html#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">COMPETITION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-6.html#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">MUTUAL LEGAL ASSISTANCE IN CRIMINAL MATTERS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-7.html#h-6"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-8.html#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

