<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Indigenous Languages Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Purposes of Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Rights Related to Indigenous Languages</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Powers, Duties and Functions of Minister</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="page-1.html#h-6"><span class="HTitleText1">Federal Institutions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-7"><span class="HTitleText1">Office of Commissioner of Indigenous Languages</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Mandate and Powers, Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Financial Management</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-11"><span class="HTitleText2">Annual Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="page-4.html#h-12"><span class="HTitleText1">Regulations and Rules</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-4.html#h-13"><span class="HTitleText1">Independent Review</span></a>
</li>
<li><span class='sectionRange'>49.1 - </span><a href="page-5.html#h-14"><span class="HTitleText1">Parliamentary Review</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-5.html#h-15"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

