<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Income Tax Conventions Implementation Act, 2001</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">CANADA–SLOVENIA INCOME TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">CANADA–ECUADOR INCOME TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CANADA–VENEZUELA INCOME TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-5"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">CANADA–PERU INCOME TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-6"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CANADA–SENEGAL INCOME TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-7"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">CANADA–CZECH REPUBLIC INCOME TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-8"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">CANADA–SLOVAK REPUBLIC INCOME TAX AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-9"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">CANADA–GERMANY INCOME TAX AGREEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-10"><span class="HTitleText2">Canada–Germany Tax Agreement Act, 1982</span></a>
</li></ul>
</li><li><a href="#h-11"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - CONVENTION BETWEEN THE GOVERNMENT OF CANADA AND THE GOVERNMENT OF THE REPUBLIC OF SLOVENIA FOR THE AVOIDANCE OF DOUBLE TAXATION AND THE PREVENTION OF FISCAL EVASION WITH RESPECT TO TAXES ON INCOME AND ON CAPITAL</span></a>
</li>
<li><a href="#h-12"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-13"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-14"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="#h-15"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="#h-16"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li>
<li><a href="#h-17"><span class="scheduleLabel">SCHEDULE 7</span> </a>
</li>
<li><a href="#h-18"><span class="scheduleLabel">SCHEDULE 8</span> </a>
</li></ul>
</li></ul>

</nav>

