<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Nunavik Inuit Land Claims Agreement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">APPROPRIATION</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-7"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS TO THE <cite class="XRefExternalAct">CANADA NATIONAL PARKS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-8"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

