<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Fisheries Act and other Acts in consequence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Fisheries Act</cite></span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-11.html#h-2"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-11.html#h-3"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="page-11.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-11.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Oil and Gas Operations Act</cite></span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-11.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Canada–Newfoundland and Labrador Atlantic Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-11.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-11.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Bridge To Strengthen Trade Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>58.1 - </span><a href="page-11.html#h-9"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-12.html#h-10"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

