<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Education Savings Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">PURPOSE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">DESIGNATION OF MINISTER</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">PAYMENTS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Children’s Special Allowances Act</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Department of Human Resources Development Act</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Income Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

