<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Criminal Code (proceeds of crime) and the Controlled Drugs and Substances Act and to make consequential amendments to another Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-2"><span class="HTitleText1">CONTROLLED DRUGS AND SUBSTANCES ACT</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-4"><span class="HTitleText2">Seized Property Management Act</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

