<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Canadian Environmental Assessment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CANADIAN ENVIRONMENTAL ASSESSMENT ACT</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-7.html#h-2"><span class="HTitleText1">REVIEW AND REPORT</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-7.html#h-3"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-7.html#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

