<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Oceans Act and the Canada Petroleum Resources Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Oceans Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-3"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">Canada Petroleum Resources Act</cite></span></a>
</li></ul>
</li></ul>

</nav>

