<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the National Defence Act (court martial) and to make a consequential amendment to another Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">NATIONAL DEFENCE ACT</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-2"><span class="HTitleText1">REVIEW AND REPORT</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-3"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-4"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-5"><span class="HTitleText2">Geneva Conventions Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-6"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

