<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Protecting Victims From Sex Offenders Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-4.html#h-3"><span class="HTitleText1">SEX OFFENDER INFORMATION REGISTRATION ACT</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-6.html#h-4"><span class="HTitleText1">NATIONAL DEFENCE ACT</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-7.html#h-5"><span class="HTitleText1">INTERNATIONAL TRANSFER OF OFFENDERS ACT</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-8.html#h-6"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT TO THE CRIMINAL RECORDS ACT</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-8.html#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-9.html#h-8"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

