<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Museums Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">MUSEUMS ACT</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Payments in Lieu of Taxes Act</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Public Service Superannuation Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-1.html#h-9"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

