<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Employment Insurance Act (additional regular benefits), the Canada Recovery Benefits Act (restriction on eligibility) and another Act in response to COVID-19</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Canada Recovery Benefits Act</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-4"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

