<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Anti-terrorism Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">CRIMINAL CODE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23.1 - </span><a href="#h-3"><span class="HTitleText2">Consequential Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23.1 - </span><a href="#h-4"><span class="HTitleText3">Identification of Criminals Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">OFFICIAL SECRETS ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-6"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-7"><span class="HTitleText3">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-8"><span class="HTitleText3">Identification of Criminals Act</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-9"><span class="HTitleText3">Patent Act</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-10"><span class="HTitleText3">Visiting Forces Act</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-11"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-12"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CANADA EVIDENCE ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-13"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-14"><span class="HTitleText3">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-15"><span class="HTitleText3">Immigration Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-16"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">PROCEEDS OF CRIME (MONEY LAUNDERING) ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-17"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-18"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-19"><span class="HTitleText3">Canada Post Corporation Act</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-20"><span class="HTitleText3">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-21"><span class="HTitleText3">Personal Information Protection and Electronic Documents Act</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-22"><span class="HTitleText3">Seized Property Management Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="#h-23"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">AMENDMENTS TO OTHER ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="#h-24"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-25"><span class="HTitleText2">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-26"><span class="HTitleText2">Canadian Security Intelligence Service Act</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-27"><span class="HTitleText2">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-28"><span class="HTitleText2">Federal Court Act</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-29"><span class="HTitleText2">Firearms Act</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-30"><span class="HTitleText2">National Defence Act</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-31"><span class="HTitleText2">Personal Information Protection and Electronic Documents Act</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-32"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-33"><span class="HTitleText2">Seized Property Management Act</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-34"><span class="HTitleText2">United Nations Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>113 - </span><a href="#h-35"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">REGISTRATION OF CHARITIES — SECURITY INFORMATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>114 - </span><a href="#h-36"><span class="HTitleText2">Amendments to the Income Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>119 - </span><a href="#h-37"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">COORDINATING, REVIEW AND COMMENCEMENT PROVISIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119 - </span><a href="#h-38"><span class="HTitleText2">Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119 - </span><a href="#h-39"><span class="HTitleText3">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-40"><span class="HTitleText3">Bill S-23</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-41"><span class="HTitleText3">Bill C-11</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-42"><span class="HTitleText3">Bill C-15B</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-43"><span class="HTitleText3">Bill C-24</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-44"><span class="HTitleText3">Bill C-30</span></a>
</li></ul>
</li><li><span class='sectionRange'>145 - </span><a href="#h-45"><span class="HTitleText2">Review and Report</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-46"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-47"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-48"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

