<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the <?Pub Caret?>Federal-Provincial Fiscal Arrangements Act and to make consequential amendments to other Acts (fiscal equalization payments to the provinces and funding to the territories)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-2"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-2.html#h-3"><span class="HTitleText2">Appropriation Act No. 1, 2004-2005</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-3.html#h-4"><span class="HTitleText2">Budget Implementation Act, 2004</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

