<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Canada Elections Act and the Income Tax Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CANADA ELECTIONS ACT</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-2"><span class="HTitleText1">INCOME TAX ACT</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

