<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Digital Privacy Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">PERSONAL INFORMATION PROTECTION AND ELECTRONIC DOCUMENTS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-5"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-6"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

