<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Social Development Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">DEPARTMENT OF SOCIAL DEVELOPMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2">Interdepartmental Services</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Committees</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">National Council of Welfare</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText2">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-10"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">PROTECTION OF PERSONAL INFORMATION</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-11"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">TRANSITIONAL PROVISIONS, CONSEQUENTIAL AND RELATED AMENDMENTS, COORDINATING AMENDMENT, REPEAL AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-12"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-13"><span class="HTitleText2">Consequential and Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-14"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-15"><span class="HTitleText3">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-16"><span class="HTitleText3">Family Orders and Agreements Enforcement Assistance Act</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-17"><span class="HTitleText3">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-18"><span class="HTitleText3">Old Age Security Act</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-19"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-20"><span class="HTitleText3">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-21"><span class="HTitleText3">Salaries Act</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-22"><span class="HTitleText3">Changes in Terminology</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-23"><span class="HTitleText2">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-24"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-25"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

