<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
United Nations Declaration on the Rights of Indigenous Peoples Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Purposes of Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Measures for Consistency of Laws and Achieving the Objectives of the Declaration</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><a href="page-2.html#h-7"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - United Nations Declaration on the Rights of Indigenous Peoples</span></a>
</li></ul>
</li></ul>

</nav>

