<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Nunavut Waters and Nunavut Surface Rights Tribunal Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PRECEDENCE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">NUNAVUT WATERS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Scope and Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Delegation and Agreements</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Compensation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-11"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Nunavut Water Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-12"><span class="HTitleText3">Establishment and Organization of Board</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-13"><span class="HTitleText3">Languages</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-14"><span class="HTitleText3">Head Office and Meetings</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-15"><span class="HTitleText3">Status and General Powers</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-16"><span class="HTitleText3">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-17"><span class="HTitleText3">Rules and By-laws</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-18"><span class="HTitleText3">Objects of Board and Its Relationship with Other Bodies</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="page-4.html#h-19"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Licences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-4.html#h-20"><span class="HTitleText3">General Rules</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-21"><span class="HTitleText3">Applications in Relation to Licences</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-4.html#h-22"><span class="HTitleText3">Procedure</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-23"><span class="HTitleText3">Conditions of Issuance</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-5.html#h-24"><span class="HTitleText3">Inuit-owned Land</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-6.html#h-25"><span class="HTitleText3">Mackenzie Valley</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-6.html#h-26"><span class="HTitleText3">Conditions of Licences</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-6.html#h-27"><span class="HTitleText3">Security</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-6.html#h-28"><span class="HTitleText3">Expropriation</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-7.html#h-29"><span class="HTitleText3">Public Register</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-7.html#h-30"><span class="HTitleText3">Decisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="page-7.html#h-31"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="page-7.html#h-32"><span class="HTitleText3">Regulations and Orders</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-7.html#h-33"><span class="HTitleText3">Enforcement</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-8.html#h-34"><span class="HTitleText3">Offences and Punishment</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="page-8.html#h-35"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">NUNAVUT SURFACE RIGHTS TRIBUNAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="page-8.html#h-36"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-8.html#h-37"><span class="HTitleText2">General Provisions</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-8.html#h-38"><span class="HTitleText2">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-8.html#h-39"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Establishment and Organization of Tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="page-8.html#h-40"><span class="HTitleText3">Tribunal Established</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-9.html#h-41"><span class="HTitleText3">Languages</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-9.html#h-42"><span class="HTitleText3">Head Office and Meetings</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-9.html#h-43"><span class="HTitleText3">By-laws</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-9.html#h-44"><span class="HTitleText3">General Powers</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-9.html#h-45"><span class="HTitleText3">Status</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-9.html#h-46"><span class="HTitleText3">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-9.html#h-47"><span class="HTitleText3">Annual Report</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-9.html#h-48"><span class="HTitleText3">Jurisdiction of Tribunal</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-9.html#h-49"><span class="HTitleText3">Applications and Hearings</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-10.html#h-50"><span class="HTitleText3">Records</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-10.html#h-51"><span class="HTitleText3">Rules</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="page-10.html#h-52"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Entry Orders for Inuit-Owned Lands</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="page-10.html#h-53"><span class="HTitleText3">Exercise of Mineral Rights</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-10.html#h-54"><span class="HTitleText3">Other Commercial Purposes</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-11.html#h-55"><span class="HTitleText3">Construction Materials</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-11.html#h-56"><span class="HTitleText3">General Rules for Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>143 - </span><a href="page-11.html#h-57"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Entry Orders for non-Inuit-owned Land</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>143 - </span><a href="page-11.html#h-58"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="page-11.html#h-59"><span class="HTitleText3">Exercise of Mineral Rights</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-11.html#h-60"><span class="HTitleText3">General Rules for Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="page-12.html#h-61"><span class="HLabel2">Division 4</span> - <span class="HTitleText2">Mineral Rights and Carving Stone</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="page-12.html#h-62"><span class="HTitleText3">Specified Substances on Inuit-owned Land</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-12.html#h-63"><span class="HTitleText3">Carving Stone on Crown Lands</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="page-12.html#h-64"><span class="HLabel2">Division 5</span> - <span class="HTitleText2">Wildlife Compensation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="page-12.html#h-65"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="page-12.html#h-66"><span class="HTitleText3">Liability of Developers</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-12.html#h-67"><span class="HTitleText3">Applications to Tribunal</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-12.html#h-68"><span class="HTitleText3">Other Remedies</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="page-12.html#h-69"><span class="HLabel2">Division 6</span> - <span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="page-12.html#h-70"><span class="HTitleText3">Decisions of the Tribunal</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-13.html#h-71"><span class="HTitleText3">Review of Orders</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-13.html#h-72"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>171 - </span><a href="page-13.html#h-73"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">TRANSITIONAL PROVISIONS, CONSEQUENTIAL AND COORDINATING AMENDMENTS AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>171 - </span><a href="page-13.html#h-74"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-14.html#h-75"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>176 - </span><a href="page-14.html#h-76"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="page-14.html#h-77"><span class="HTitleText3">Arctic Waters Pollution Prevention Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-14.html#h-78"><span class="HTitleText3">Mackenzie Valley Resource Management Act</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-14.html#h-79"><span class="HTitleText3">Northern Canada Power Commission (Share Issuance and Sale Authorization) Act</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-14.html#h-80"><span class="HTitleText3">Northwest Territories Waters Act</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-15.html#h-81"><span class="HTitleText3">Canada Oil and Gas Operations Act</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-15.html#h-82"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-15.html#h-83"><span class="HTitleText3">Yukon Surface Rights Board Act</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="page-15.html#h-84"><span class="HTitleText3">Yukon Waters Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="page-15.html#h-85"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="page-16.html#h-86"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-17.html#h-87"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-18.html#h-88"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

