<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Budget Implementation Act, 2006, No. 2</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE INCOME TAX ACT</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-8.html#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE INCOME TAX ACT (DIVIDEND TAXATION)</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-11.html#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS RELATING TO THE EXCISE DUTIES ON CANADIAN WINE AND BEER</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="page-11.html#h-5"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-11.html#h-6"><span class="HTitleText2">Excise Act</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

