<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Jobs, Growth and Long-term Prosperity Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">INCOME TAX ACT</cite>, A RELATED ACT AND THE <cite class="XRefExternalRegulation">INCOME TAX REGULATIONS</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Governor General’s Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-6"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">MEASURES RELATING TO SALES AND EXCISE TAXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Air Travellers Security Charge Act</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalRegulation">Value of Imported Goods (GST/HST) Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalRegulation">Non-Taxable Imported Goods (GST/HST) Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalRegulation">New Harmonized Value-added Tax System Regulations, No. 2</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-13"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">RESPONSIBLE RESOURCE DEVELOPMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="#h-14"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Environmental Assessment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="#h-15"><span class="HTitleText3">Enactment of the <cite class="XRefExternalAct">Canadian Environmental Assessment Act, 2012</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-16"><span class="HTitleText3">Related Amendments to the <cite class="XRefExternalAct">Environmental Violations Administrative Monetary Penalties Act</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-17"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-18"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-19"><span class="HTitleText4"><cite class="XRefExternalAct">Export Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-20"><span class="HTitleText4"><cite class="XRefExternalAct">First Nations Land Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-21"><span class="HTitleText4"><cite class="XRefExternalAct">Species at Risk Act</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-22"><span class="HTitleText4"><cite class="XRefExternalAct">Antarctic Environmental Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-23"><span class="HTitleText4"><cite class="XRefExternalAct">First Nations Oil and Gas and Moneys Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-24"><span class="HTitleText4"><cite class="XRefExternalAct">First Nations Commercial and Industrial Development Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="#h-25"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-26"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-27"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-28"><span class="HLabel2">Division 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">National Energy Board Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-29"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-30"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-31"><span class="HTitleText3">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-32"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-33"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-34"><span class="HTitleText4"><cite class="XRefExternalAct">Northern Pipeline Act</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-35"><span class="HTitleText4"><cite class="XRefExternalAct">An Act to amend the National Energy Board Act and to repeal certain enactments in consequence thereof</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>115 - </span><a href="#h-36"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>116 - </span><a href="#h-37"><span class="HLabel2">Division 3</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Oil and Gas Operations Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="#h-38"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-39"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="#h-40"><span class="HLabel2">Division 4</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Nuclear Safety and Control Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="#h-41"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-42"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>132 - </span><a href="#h-43"><span class="HLabel2">Division 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Fisheries Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="#h-44"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-45"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>157 - </span><a href="#h-46"><span class="HLabel2">Division 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Environmental Protection Act, 1999</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-47"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-48"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>163 - </span><a href="#h-49"><span class="HLabel2">Division 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Species at Risk Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>170 - </span><a href="#h-50"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">VARIOUS MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>170 - </span><a href="#h-51"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Measures with Respect to the Auditor General of Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>170 - </span><a href="#h-52"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Centre for Occupational Health and Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-53"><span class="HTitleText3"><cite class="XRefExternalAct">Currency Act</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-54"><span class="HTitleText3"><cite class="XRefExternalAct">Natural Sciences and Engineering Research Council Act</cite></span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-55"><span class="HTitleText3"><cite class="XRefExternalAct">Northern Pipeline Act</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-56"><span class="HTitleText3"><cite class="XRefExternalAct">Social Sciences and Humanities Research Council Act</cite></span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-57"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Transportation Accident Investigation and Safety Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-58"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Polar Commission Act</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-59"><span class="HTitleText3"><cite class="XRefExternalAct">National Round Table on the Environment and the Economy Act</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-60"><span class="HTitleText3"><cite class="XRefExternalAct">Yukon Surface Rights Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-61"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Food Inspection Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-62"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Revenue Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-63"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Institutes of Health Research Act</cite></span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-64"><span class="HTitleText3">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="#h-65"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Life Annuity-like Products</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>205 - </span><a href="#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-67"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-68"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>209 - </span><a href="#h-69"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">PPP Canada Inc.</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-70"><span class="HLabel2">Division 4</span> - <span class="HTitleText2">Territorial Borrowing Limits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-71"><span class="HTitleText3"><cite class="XRefExternalAct">Northwest Territories Act</cite></span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-72"><span class="HTitleText3"><cite class="XRefExternalAct">Nunavut Act</cite></span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-73"><span class="HTitleText3"><cite class="XRefExternalAct">Yukon Act</cite></span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-74"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>218 - </span><a href="#h-75"><span class="HLabel2">Division 5</span> - <span class="HTitleText2">Reporting Requirements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>218 - </span><a href="#h-76"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-77"><span class="HTitleText3"><cite class="XRefExternalAct">Alternative Fuels Act</cite></span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-78"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>223 - </span><a href="#h-79"><span class="HLabel2">Division 6</span> - <span class="HTitleText2">Social Security Tribunal and Service Delivery</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>223 - </span><a href="#h-80"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Human Resources and Skills Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-81"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="#h-82"><span class="HTitleText3"><cite class="XRefExternalAct">Old Age Security Act</cite></span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="#h-83"><span class="HTitleText3"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="#h-84"><span class="HTitleText3">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>251 - </span><a href="#h-85"><span class="HTitleText4">Interpretation and General</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-86"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="#h-87"><span class="HTitleText4"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>271 - </span><a href="#h-88"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>271 - </span><a href="#h-89"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-90"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="#h-91"><span class="HTitleText4"><cite class="XRefExternalAct">Labour Adjustment Benefits Act</cite></span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="#h-92"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>277 - </span><a href="#h-93"><span class="HTitleText4"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="#h-94"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>281 - </span><a href="#h-95"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>282 - </span><a href="#h-96"><span class="HLabel2">Division 7</span> - <span class="HTitleText2">Consolidation of Privacy Codes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>282 - </span><a href="#h-97"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Human Resources and Skills Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>292 - </span><a href="#h-98"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="#h-99"><span class="HTitleText3"><cite class="XRefExternalAct">Old Age Security Act</cite></span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="#h-100"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>300 - </span><a href="#h-101"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>302 - </span><a href="#h-102"><span class="HTitleText4"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>303 - </span><a href="#h-103"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>304 - </span><a href="#h-104"><span class="HLabel2">Division 8</span> - <span class="HTitleText2">Social Insurance Number Cards</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>304 - </span><a href="#h-105"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Human Resources and Skills Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="#h-106"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="#h-107"><span class="HTitleText3"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="#h-108"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>309 - </span><a href="#h-109"><span class="HTitleText4"><cite class="XRefExternalAct">Canadian Wheat Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>310 - </span><a href="#h-110"><span class="HTitleText4"><cite class="XRefExternalAct">Farm Income Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>311 - </span><a href="#h-111"><span class="HTitleText4"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="#h-112"><span class="HTitleText4"><cite class="XRefExternalAct">Wage Earner Protection Program Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>313 - </span><a href="#h-113"><span class="HTitleText3">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="#h-114"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>315 - </span><a href="#h-115"><span class="HLabel2">Division 9</span> - <span class="HTitleText2">Amendments Relating to the Parks Canada Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>315 - </span><a href="#h-116"><span class="HTitleText3"><cite class="XRefExternalAct">Parks Canada Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>324 - </span><a href="#h-117"><span class="HTitleText3"><cite class="XRefExternalAct">Canada National Parks Act</cite></span></a>
</li>
<li><span class='sectionRange'>325 - </span><a href="#h-118"><span class="HTitleText3"><cite class="XRefExternalAct">Canada National Marine Conservation Areas Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>326 - </span><a href="#h-119"><span class="HLabel2">Division 10</span> - <span class="HTitleText2">Financial Institutions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>326 - </span><a href="#h-120"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>330 - </span><a href="#h-121"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>339 - </span><a href="#h-122"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>348 - </span><a href="#h-123"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>350 - </span><a href="#h-124"><span class="HLabel2">Division 11</span> - <span class="HTitleText2">Canada Mortgage and Housing Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>350 - </span><a href="#h-125"><span class="HTitleText3"><cite class="XRefExternalAct">National Housing Act</cite></span></a>
</li>
<li><span class='sectionRange'>357 - </span><a href="#h-126"><span class="HTitleText3"><cite class="XRefExternalAct">Supporting Vulnerable Seniors and Strengthening Canada’s Economy Act</cite></span></a>
</li>
<li><span class='sectionRange'>360 - </span><a href="#h-127"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Mortgage and Housing Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="#h-128"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>362 - </span><a href="#h-129"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>363 - </span><a href="#h-130"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>364 - </span><a href="#h-131"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li>
<li><span class='sectionRange'>365 - </span><a href="#h-132"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="#h-133"><span class="HTitleText3">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>367 - </span><a href="#h-134"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>368 - </span><a href="#h-135"><span class="HLabel2">Division 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Integrated Cross-border Law Enforcement Operations Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>368 - </span><a href="#h-136"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>369 - </span><a href="#h-137"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Royal Canadian Mounted Police Act</cite></span></a>
</li>
<li><span class='sectionRange'>371 - </span><a href="#h-138"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>371 - </span><a href="#h-139"><span class="HTitleText4"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>372 - </span><a href="#h-140"><span class="HTitleText4"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>374 - </span><a href="#h-141"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>375 - </span><a href="#h-142"><span class="HLabel2">Division 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Bretton Woods and Related Agreements Act</cite></span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="#h-143"><span class="HLabel2">Division 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Health Act</cite></span></a>
</li>
<li><span class='sectionRange'>378 - </span><a href="#h-144"><span class="HLabel2">Division 15</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>378 - </span><a href="#h-145"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>385 - </span><a href="#h-146"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>385 - </span><a href="#h-147"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>386 - </span><a href="#h-148"><span class="HTitleText4"><cite class="XRefExternalAct">Security of Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>387 - </span><a href="#h-149"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>388 - </span><a href="#h-150"><span class="HLabel2">Division 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Currency Act</cite></span></a>
</li>
<li><span class='sectionRange'>390 - </span><a href="#h-151"><span class="HLabel2">Division 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>390 - </span><a href="#h-152"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>407 - </span><a href="#h-153"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">Canada Health Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>411 - </span><a href="#h-154"><span class="HLabel2">Division 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Fisheries Act</cite></span></a>
</li>
<li><span class='sectionRange'>412 - </span><a href="#h-155"><span class="HLabel2">Division 19</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Food and Drugs Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>412 - </span><a href="#h-156"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>417 - </span><a href="#h-157"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>418 - </span><a href="#h-158"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>419 - </span><a href="#h-159"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>420 - </span><a href="#h-160"><span class="HLabel2">Division 20</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Government Employees Compensation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>420 - </span><a href="#h-161"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>425 - </span><a href="#h-162"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>426 - </span><a href="#h-163"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>427 - </span><a href="#h-164"><span class="HLabel2">Division 21</span> - <span class="HTitleText2"><cite class="XRefExternalAct">International Development Research Centre Act</cite></span></a>
</li>
<li><span class='sectionRange'>432 - </span><a href="#h-165"><span class="HLabel2">Division 22</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>432 - </span><a href="#h-166"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>438 - </span><a href="#h-167"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>440 - </span><a href="#h-168"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>441 - </span><a href="#h-169"><span class="HLabel2">Division 23</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Fair Wages and Hours of Labour Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>441 - </span><a href="#h-170"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>442 - </span><a href="#h-171"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>443 - </span><a href="#h-172"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Campobello-Lubec Bridge Act</cite></span></a>
</li>
<li><span class='sectionRange'>444 - </span><a href="#h-173"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>445 - </span><a href="#h-174"><span class="HLabel2">Division 24</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Old Age Security Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>445 - </span><a href="#h-175"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>467 - </span><a href="#h-176"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>468 - </span><a href="#h-177"><span class="HLabel2">Division 25</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Salaries Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>468 - </span><a href="#h-178"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>469 - </span><a href="#h-179"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>469 - </span><a href="#h-180"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>470 - </span><a href="#h-181"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>472 - </span><a href="#h-182"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>473 - </span><a href="#h-183"><span class="HLabel2">Division 26</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Seeds Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>473 - </span><a href="#h-184"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>475 - </span><a href="#h-185"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>476 - </span><a href="#h-186"><span class="HLabel2">Division 27</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Statutory Instruments Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>476 - </span><a href="#h-187"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>478 - </span><a href="#h-188"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>479 - </span><a href="#h-189"><span class="HLabel2">Division 28</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>481 - </span><a href="#h-190"><span class="HLabel2">Division 29</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>483 - </span><a href="#h-191"><span class="HLabel2">Division 30</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Pension Benefits Standards Act, 1985</cite></span></a>
</li>
<li><span class='sectionRange'>484 - </span><a href="#h-192"><span class="HLabel2">Division 31</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Railway Safety Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>484 - </span><a href="#h-193"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>486 - </span><a href="#h-194"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>487 - </span><a href="#h-195"><span class="HLabel2">Division 32</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian International Trade Tribunal Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>487 - </span><a href="#h-196"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>489 - </span><a href="#h-197"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>490 - </span><a href="#h-198"><span class="HLabel2">Division 33</span> - <span class="HTitleText2"><cite class="XRefExternalAct">International Centre for Human Rights and Democratic Development Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>490 - </span><a href="#h-199"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>491 - </span><a href="#h-200"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>492 - </span><a href="#h-201"><span class="HTitleText3">Closing Out of Affairs</span></a>
</li>
<li><span class='sectionRange'>496 - </span><a href="#h-202"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>501 - </span><a href="#h-203"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>501 - </span><a href="#h-204"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>502 - </span><a href="#h-205"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>503 - </span><a href="#h-206"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>504 - </span><a href="#h-207"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>505 - </span><a href="#h-208"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>506 - </span><a href="#h-209"><span class="HLabel2">Division 34</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Health of Animals Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>506 - </span><a href="#h-210"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>515 - </span><a href="#h-211"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>516 - </span><a href="#h-212"><span class="HLabel2">Division 35</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada School of Public Service Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>516 - </span><a href="#h-213"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>523 - </span><a href="#h-214"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>525 - </span><a href="#h-215"><span class="HLabel2">Division 36</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>526 - </span><a href="#h-216"><span class="HLabel2">Division 37</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>526 - </span><a href="#h-217"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>528 - </span><a href="#h-218"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>529 - </span><a href="#h-219"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>530 - </span><a href="#h-220"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>531 - </span><a href="#h-221"><span class="HLabel2">Division 38</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Coasting Trade Act</cite></span></a>
</li>
<li><span class='sectionRange'>532 - </span><a href="#h-222"><span class="HLabel2">Division 39</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Status of the Artist Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>532 - </span><a href="#h-223"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>564 - </span><a href="#h-224"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>571 - </span><a href="#h-225"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>571 - </span><a href="#h-226"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>572 - </span><a href="#h-227"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>573 - </span><a href="#h-228"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>576 - </span><a href="#h-229"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>577 - </span><a href="#h-230"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>578 - </span><a href="#h-231"><span class="HLabel2">Division 40</span> - <span class="HTitleText2"><cite class="XRefExternalAct">National Round Table on the Environment and the Economy Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>578 - </span><a href="#h-232"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>579 - </span><a href="#h-233"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>586 - </span><a href="#h-234"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>586 - </span><a href="#h-235"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>587 - </span><a href="#h-236"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>590 - </span><a href="#h-237"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>591 - </span><a href="#h-238"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>592 - </span><a href="#h-239"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>593 - </span><a href="#h-240"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>594 - </span><a href="#h-241"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>595 - </span><a href="#h-242"><span class="HLabel2">Division 41</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Telecommunications Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>595 - </span><a href="#h-243"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>601 - </span><a href="#h-244"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>602 - </span><a href="#h-245"><span class="HLabel2">Division 42</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Equity Act</cite></span></a>
</li>
<li><span class='sectionRange'>603 - </span><a href="#h-246"><span class="HLabel2">Division 43</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>603 - </span><a href="#h-247"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>616 - </span><a href="#h-248"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>617 - </span><a href="#h-249"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">Canada Employment Insurance Financing Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>619 - </span><a href="#h-250"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>620 - </span><a href="#h-251"><span class="HLabel2">Division 44</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>620 - </span><a href="#h-252"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>625 - </span><a href="#h-253"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>626 - </span><a href="#h-254"><span class="HLabel2">Division 45</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Marine Act</cite></span></a>
</li>
<li><span class='sectionRange'>627 - </span><a href="#h-255"><span class="HLabel2">Division 46</span> - <span class="HTitleText2"><cite class="XRefExternalAct">First Nations Land Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>653 - </span><a href="#h-256"><span class="HLabel2">Division 47</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Travelling Exhibitions Indemnification Act</cite></span></a>
</li>
<li><span class='sectionRange'>654 - </span><a href="#h-257"><span class="HLabel2">Division 48</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Air Transport Security Authority Act</cite></span></a>
</li>
<li><span class='sectionRange'>656 - </span><a href="#h-258"><span class="HLabel2">Division 49</span> - <span class="HTitleText2"><cite class="XRefExternalAct">First Nations Fiscal and Statistical Management Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>656 - </span><a href="#h-259"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>667 - </span><a href="#h-260"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>674 - </span><a href="#h-261"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>674 - </span><a href="#h-262"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>676 - </span><a href="#h-263"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>677 - </span><a href="#h-264"><span class="HTitleText4"><cite class="XRefExternalAct">Indian Act</cite></span></a>
</li>
<li><span class='sectionRange'>679 - </span><a href="#h-265"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>680 - </span><a href="#h-266"><span class="HTitleText4"><cite class="XRefExternalAct">Westbank First Nation Self-Government Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>681 - </span><a href="#h-267"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>682 - </span><a href="#h-268"><span class="HLabel2">Division 50</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Forces Members and Veterans Re-establishment and Compensation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>682 - </span><a href="#h-269"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>684 - </span><a href="#h-270"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>685 - </span><a href="#h-271"><span class="HLabel2">Division 51</span> - <span class="HTitleText2">Repeal of the <cite class="XRefExternalAct">Department Of Social Development Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>685 - </span><a href="#h-272"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>686 - </span><a href="#h-273"><span class="HTitleText3">National Council of Welfare</span></a>
</li>
<li><span class='sectionRange'>687 - </span><a href="#h-274"><span class="HTitleText3">Related Amendment to the <cite class="XRefExternalAct">Department of Human Resources and Skills Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>688 - </span><a href="#h-275"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>688 - </span><a href="#h-276"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>690 - </span><a href="#h-277"><span class="HTitleText4"><cite class="XRefExternalAct">Salaries Act</cite></span></a>
</li>
<li><span class='sectionRange'>692 - </span><a href="#h-278"><span class="HTitleText4"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>693 - </span><a href="#h-279"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>694 - </span><a href="#h-280"><span class="HTitleText4">Terminology Changes</span></a>
</li></ul>
</li><li><span class='sectionRange'>696 - </span><a href="#h-281"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>697 - </span><a href="#h-282"><span class="HLabel2">Division 52</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Wage Earner Protection Program Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>697 - </span><a href="#h-283"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>698 - </span><a href="#h-284"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>699 - </span><a href="#h-285"><span class="HLabel2">Division 53</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Kyoto Protocol Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>700 - </span><a href="#h-286"><span class="HLabel2">Division 54</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>700 - </span><a href="#h-287"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>709 - </span><a href="#h-288"><span class="HTitleText3">Amendment to the <cite class="XRefExternalAct">Budget Implementation Act, 2008</cite></span></a>
</li>
<li><span class='sectionRange'>710 - </span><a href="#h-289"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>711 - </span><a href="#h-290"><span class="HLabel2">Division 55</span> - <span class="HTitleText2">Shared Services Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>711 - </span><a href="#h-291"><span class="HTitleText3"><cite class="XRefExternalAct">Shared Services Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>712 - </span><a href="#h-292"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Department of Public Works and Government Services Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>713 - </span><a href="#h-293"><span class="HLabel2">Division 56</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Assisted Human Reproduction Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>713 - </span><a href="#h-294"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>740 - </span><a href="#h-295"><span class="HTitleText3">Coming into Force of a Provision of the <cite class="XRefExternalAct">Assisted Human Reproduction Act</cite></span></a>
</li>
<li><span class='sectionRange'>741 - </span><a href="#h-296"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>746 - </span><a href="#h-297"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>746 - </span><a href="#h-298"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>748 - </span><a href="#h-299"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>749 - </span><a href="#h-300"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>750 - </span><a href="#h-301"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>751 - </span><a href="#h-302"><span class="HTitleText4"><cite class="XRefExternalAct">Library and Archives of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>752 - </span><a href="#h-303"><span class="HTitleText4"><cite class="XRefExternalAct">Human Pathogens and Toxins Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>753 - </span><a href="#h-304"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-305"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

