<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
COVID-19 Response Measures Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Recovery Benefits Act</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-3"><span class="HLabel1">PART 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-2.html#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">COVID-19 Emergency Response Act</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-7"><span class="HTitleText3"><cite class="XRefExternalRegulation">Canada Labour Standards Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-8"><span class="HTitleText3"><cite class="XRefExternalRegulation">Regulations Amending the Canada Labour Standards Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-3.html#h-11"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Public Health Events of National Concern Payments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-3.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Public Health Events of National Concern Payments Act</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-3.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">COVID-19 Emergency Response Act</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-4.html#h-16"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

