<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Bankruptcy and Insolvency Act, the Companies’ Creditors Arrangement Act, the Wage Earner Protection Program Act and chapter 47 of the Statutes of Canada, 2005</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">BANKRUPTCY AND INSOLVENCY ACT</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-2"><span class="HTitleText1">COMPANIES’ CREDITORS ARRANGEMENT ACT</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-3"><span class="HTitleText1">WAGE EARNER PROTECTION PROGRAM ACT</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-4"><span class="HTitleText1">CHAPTER 47 OF THE STATUTES OF CANADA, 2005</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-5"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-6"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

