<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Access to Information Act and the Privacy Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-3"><span class="HTitleText2">Terminological Changes</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-4"><span class="HTitleText2">Transitional Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-6"><span class="HTitleText1">Validation of Orders in Council</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-9"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Personal Information Protection and Electronic Documents Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-12"><span class="HTitleText1">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-13"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

