<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Strengthening Motor Vehicle Safety for Canadians Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Motor Vehicle Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-3"><span class="HTitleText1">Consequential Amendment to the <cite class="XRefExternalAct">Transportation Appeal Tribunal of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-4"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

