<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
National Strategy for Safe and Environmentally Sound Disposal of Lamps Containing Mercury Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">National Strategy</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Review and Report</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

