<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2007</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS RELATED TO INCOME TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-4"><span class="HTitleText2">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-5"><span class="HTitleText2">Canada Education Savings Act</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-6"><span class="HTitleText2">Canada Education Savings Regulations</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-7"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-8"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE EXCISE TAX ACT (OTHER THAN WITH RESPECT TO THE GOODS AND SERVICES TAX/HARMONIZED SALES TAX)</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-9"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF THE GOODS AND SERVICES TAX/HARMONIZED SALES TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-10"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-11"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-12"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">OTHER MEASURES RELATING TO TAXATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-13"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-14"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-15"><span class="HTitleText2">Payments to Ontario</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-16"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">TAX-BACK GUARANTEE ACT</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-17"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="#h-18"><span class="HTitleText2">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-19"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-20"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="#h-21"><span class="HTitleText3">Canada-Newfoundland Atlantic Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-22"><span class="HTitleText3">Nova Scotia and Newfoundland and Labrador Additional Fiscal Equalization Offset Payments Act</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-23"><span class="HTitleText3">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>84 - </span><a href="#h-24"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="#h-25"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">AMENDMENTS TO THE FINANCIAL ADMINISTRATION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="#h-26"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-27"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="#h-28"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">AMENDMENTS TO THE CANADA MORTGAGE AND HOUSING CORPORATION ACT</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-29"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">AMENDMENTS RELATING TO ELIGIBLE FINANCIAL CONTRACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-30"><span class="HTitleText2">Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-31"><span class="HTitleText2">Canada Deposit Insurance Corporation Act</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-32"><span class="HTitleText2">Companies’ Creditors Arrangement Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-33"><span class="HTitleText2">Payment Clearing and Settlement Act</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-34"><span class="HTitleText2">Winding-up and Restructuring Act</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-35"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-36"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-37"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="#h-38"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">PAYMENTS TO PROVINCES AND TERRITORIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124 - </span><a href="#h-39"><span class="HTitleText2">Payment to British Columbia</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-40"><span class="HTitleText2">Clean Air and Climate Change Trust Fund </span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-41"><span class="HTitleText2">Transitional Payments</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-42"><span class="HTitleText2">Human Papillomavirus Immunization</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-43"><span class="HTitleText2">Patient Wait Times Guarantee</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-44"><span class="HTitleText2">Child Care Spaces</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-45"><span class="HTitleText2">Payment to Yukon</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-46"><span class="HTitleText2">Payment to Northwest Territories</span></a>
</li></ul>
</li><li><span class='sectionRange'>132 - </span><a href="#h-47"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">PAYMENTS TO CERTAIN ENTITIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="#h-48"><span class="HTitleText2">Nature Conservancy of Canada</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-49"><span class="HTitleText2">Canada Health Infoway Inc.</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-50"><span class="HTitleText2">CANARIE Inc.</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-51"><span class="HTitleText2">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-52"><span class="HTitleText2">Aid to Afghanistan</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-53"><span class="HTitleText2">Rick Hansen Man in Motion Foundation</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-54"><span class="HTitleText2">The Perimeter Institute for Theoretical Physics</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-55"><span class="HTitleText2">Canada Foundation for Sustainable Development Technology</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-56"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">AMENDMENTS RELATING TO FINANCIAL INSTITUTIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>144 - </span><a href="#h-57"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-58"><span class="HTitleText2">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-59"><span class="HTitleText2">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-60"><span class="HTitleText2">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-61"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="#h-62"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">AMENDMENTS TO THE DEPARTMENT OF PUBLIC WORKS AND GOVERNMENT SERVICES ACT</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-63"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">AMENDMENT TO THE FINANCIAL CONSUMER AGENCY OF CANADA ACT</span></a>
</li></ul>
</li></ul>

</nav>

