<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2004, No. 2</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE AIR TRAVELLERS SECURITY CHARGE ACT</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE FIRST NATIONS GOODS AND SERVICES TAX ACT</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS TO THE INCOME TAX ACT AND CERTAIN OTHER ACTS AS A CONSEQUENCE AND A COORDINATING AMENDMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-6"><span class="HTitleText2">Budget Implementation Act, 2003</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-7"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-8"><span class="HTitleText2">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-9"><span class="HTitleText2">Income Tax Conventions Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-10"><span class="HTitleText2">Tax Court of Canada Act</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-11"><span class="HTitleText2">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-12"><span class="HTitleText2">Co-ordinating Amendment</span></a>
</li></ul>
</li><li><a href="#h-13"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

