<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Combating Terrorism Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-3"><span class="HTitleText1">CANADA EVIDENCE ACT</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-4"><span class="HTitleText1">SECURITY OF INFORMATION ACT</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

