<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–Ukraine Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Causes of Action</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Implementation of the Agreement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Approval</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Panels, Committees, Subcommittees, Working Groups, Expert Groups and Other Bodies</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Crown Liability and Proceedings Act</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Importation of Intoxicating Liquors Act</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian International Trade Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Employment and Social Development Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-19"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-20"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-21"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-22"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-23"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-24"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

