<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Civil Marriage Act</a><ul class="TocIndent"><li><span class='sectionRange'>5 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Canada Business Corporations Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Canada Cooperatives Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Civilian War-related Benefits Act</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Divorce Act</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Federal Law and Civil Law of the Province of Quebec Act</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Marriage (Prohibited Degrees) Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Modernization of Benefits and Obligations Act</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

