<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Public Service Labour Relations Act, the Public Service Labour Relations and Employment Board Act and other Acts and to provide for certain other measures</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Public Service Labour Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Public Service Labour Relations and Employment Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Royal Canadian Mounted Police Act</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-4"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-4.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-4.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-4.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-4.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Status of the Artist Act</cite></span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-4.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-5.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Public Sector Equitable Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-14"><span class="HTitleText2"><cite class="XRefExternalRegulation">Public Service Labour Relations Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="page-5.html#h-15"><span class="HTitleText1">Terminology</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-7.html#h-16"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-7.html#h-17"><span class="HTitleText1">Coordinating Amendments</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

