<h2>FORM B</h2>

<p>Document issued as evidence that the person named herein is an elective participant under part ii of the public service superannuation act</p>

<p>This document is issued to: Name (referred to herein as "the participant")</p>

<p>Address</p>

<p>As evidence that the person named herein, a participant under Part II of the Public Service Superannuation Act, ceased to be employed in the public service on the _____ day of (month), (year) and is entitled to all the benefits and subject to all the obligations applicable in the participant's case under the Public Service Superannuation Act</p>

<ol>
	<li>Benefits<br />The benefits payable on the death of the participant is $(amount), subject to the following deductions:<ol class="upperAlpha">
		<li>On April 1 or October 1 next following each birthday of the participant commencing with the 61st birthday the benefit will be reduced by 10%.</li>
		<li>The participant may elect to reduce benefits to $500.00 such election is irrevocable (inquiries should be directed to Department of Supply and Services, Superannuation Branch, P.O. Box 5010 Moncton N.B. E1C 8Z5).</li>
		<li>The Benefit will never be less than $500.00 if the participant pays contributions up to the 31st of March or the 30th of September whichever date immediately follows the participant's 65th birthday.</li>
	</ol></li>

	<li>Contributions:<ol class="upperAlpha">
		<li>The payment of the benefit on the death of the participant is subject to the payment of a contribution of $(amount) per month that is subject to a reduction of 10% for each year following the 60th birthday of the participant. Such reduction will be made the first day of April or the first day of October, whichever date immediately follows each anniversary of the birthdate of the participant commencing with the 61st birthday.</li>
		<li>An additional reduction of 20 cents per month will be made on the first day of April or the first day of October whichever date immediately follows the anniversary of the participant's 65th birthday.</li>
		<li>If the participant elects to reduce the benefit to $500.00 the contribution will be 20 cents per month until the date calculated in B) and no contribution is payable thereafter.</li>
		<li>Contributions are deducted in equal instalments from the annuity payable to the participant under Part 1 of the Public Service Superannuation Act.</li>
	</ol></li>

	<li>Date of Birth<br />Proof that the date of birth of the participant is the (day) of (month), (year) has been accepted.</li>

	<li>Re-Employment or Re-Appointment<br />
	This document ceases to have any effect and the benefit described herein is no longer payable on and after the day when the participant ceases to be an elective participant and becomes a participant other than an elective participant under Part II of the Public Service Superannuation Act.</li>
</ol>

<h3>General</h3>

<ol class="upperAlpha">
	<li>if the participant dies and has designated a beneficiary pursuant to section 26 of the Supplementary Death Benefit Regulations, the benefit is payable to the beneficiary in all other cases the benefit is payable in accordance with Part II of the Public Service Superannuation Act. </li>

	<li>The payment of the benefit referred to in section A) is subject to proof of death of the participant and entitlement of the claimant.</li>

	<li>Part II of the Public Service Superannuation Act and the Regulations made thereunder apply to this document.</li>
</ol>

<p>Issued this ___day of (month), (year)</p>

<p>Director Superannuation Branch, Department of Supply and Services.</p>

