<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Immigration and Refugee Protection Act (certificate and special advocate) and to make a consequential amendment to another Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">IMMIGRATION AND REFUGEE PROTECTION ACT</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-2"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT TO THE CANADA EVIDENCE ACT</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

