<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Specific Claims Tribunal Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">PURPOSE AND APPLICATION OF ACT</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">SPECIFIC CLAIMS TRIBUNAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Administration of the Tribunal</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Functions, Powers and Duties</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Specific Claims</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Hearings and Decisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="page-3.html#h-10"><span class="HTitleText1">GENERAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Annual Report</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-3.html#h-13"><span class="HTitleText2">Review and Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="page-4.html#h-14"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-15"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Federal Courts Act</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-4.html#h-20"><span class="HTitleText2">Public Service Superannuation Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="page-4.html#h-21"><span class="HTitleText1">REPEAL</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-4.html#h-22"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="page-5.html#h-23"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

