<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canadian Net-Zero Emissions Accountability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Definitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HTitleText1">Targets and Plans</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-7"><span class="HTitleText1">Reports</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-8"><span class="HTitleText1">Tabling and Publication</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-9"><span class="HTitleText1">Advisory Body</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-10"><span class="HTitleText1">Minister of Finance</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-11"><span class="HTitleText1">Commissioner of the Environment and Sustainable Development</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-12"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-13"><span class="HTitleText1">Consequential Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Auditor General Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="page-2.html#h-15"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

