<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
<?Pub Caret1?>Northwest Territories Devolution Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">NORTHWEST TERRITORIES ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Amendments to Other Acts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-6"><span class="HTitleText3">Arctic Waters Pollution Prevention Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-7"><span class="HTitleText3">Canada Evidence Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-8"><span class="HTitleText3">Canada Water Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-9"><span class="HTitleText3">Crown Liability and Proceedings Act</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-10"><span class="HTitleText3">Electoral Boundaries Readjustment Act</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-11"><span class="HTitleText3">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-12"><span class="HTitleText3">Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-13"><span class="HTitleText3">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-14"><span class="HTitleText3">Importation of Intoxicating Liquors Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-15"><span class="HTitleText3">Department of Indian Affairs and Northern Development Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-16"><span class="HTitleText3">Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-17"><span class="HTitleText3">Canada Lands Surveys Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-18"><span class="HTitleText3">National Energy Board Act</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-19"><span class="HTitleText3">Northern Pipeline Act</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-20"><span class="HTitleText3">Canada Oil and Gas Operations Act</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-21"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-22"><span class="HTitleText3">Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-23"><span class="HTitleText3">Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-24"><span class="HTitleText3">Territorial Lands Act</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-25"><span class="HTitleText3">Dominion Water Power Act</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-26"><span class="HTitleText3">Divorce Act</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-27"><span class="HTitleText3">Canada Petroleum Resources Act</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-28"><span class="HTitleText3">Canadian Multiculturalism Act</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-29"><span class="HTitleText3">Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-30"><span class="HTitleText3">Hibernia Development Project Act</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-31"><span class="HTitleText3">Federal Real Property and Federal Immovables Act</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-32"><span class="HTitleText3">Nunavut Act</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-33"><span class="HTitleText3">Land Titles Repeal Act</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-34"><span class="HTitleText3">Oceans Act</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-35"><span class="HTitleText3">Canadian Environmental Protection Act, 1999</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-36"><span class="HTitleText3">Canada Elections Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-37"><span class="HTitleText3">Canada National Parks Act</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-38"><span class="HTitleText3">Youth Criminal Justice Act</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-39"><span class="HTitleText3">Nunavut Waters and Nunavut Surface Rights Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-40"><span class="HTitleText3">Public Service Labour Relations Act</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-41"><span class="HTitleText3">Public Service Employment Act</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-42"><span class="HTitleText3">Tlicho Land Claims and Self-Government Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="#h-43"><span class="HTitleText2">Amendments to the Oaths of Allegiance and Office and Seat of Government Order (N.W.T.)</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-44"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-45"><span class="HTitleText2">Repeals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="#h-46"><span class="HTitleText3">Acts</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-47"><span class="HTitleText3">Orders and Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-48"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="#h-49"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE TERRITORIAL LANDS ACT</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-50"><span class="HLabel1">PART 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">NORTHWEST TERRITORIES WATERS ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="#h-51"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-52"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-53"><span class="HTitleText2">Consequential Amendment to the Mackenzie Valley Resource Management Act</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-54"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="#h-55"><span class="HLabel1">PART 4</span> - <span class="HTitleText1"><cite class="XRefExternalAct">MACKENZIE VALLEY RESOURCE MANAGEMENT ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-56"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-57"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>238 - </span><a href="#h-58"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-59"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="#h-60"><span class="HTitleText3"><cite class="XRefExternalAct">Tlicho Land Claims and Self-Government Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>241 - </span><a href="#h-61"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-62"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

