<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Transportation Appeal Tribunal of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">TRANSPORTATION APPEAL TRIBUNAL OF CANADA</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-4"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Aeronautics Act</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-6"><span class="HTitleText2">Canada Shipping Act</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-5.html#h-7"><span class="HTitleText2">Canada Transportation Act</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-8"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-5.html#h-9"><span class="HTitleText2">Marine Transportation Security Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-7.html#h-10"><span class="HTitleText2">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-7.html#h-11"><span class="HTitleText2">Public Service Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-7.html#h-12"><span class="HTitleText2">Railway Safety Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>71 - </span><a href="page-8.html#h-13"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>71 - </span><a href="page-8.html#h-14"><span class="HTitleText2">Amendment to This Act</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-8.html#h-15"><span class="HTitleText2">Bill C-14</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="page-9.html#h-16"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

