<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Marketing Freedom for Grain Farmers Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">OPERATIONS OF THE CANADIAN WHEAT BOARD DURING PRELIMINARY PERIOD</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Amendments to the Canadian Wheat Board Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-4"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">VOLUNTARY POOLING</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-6"><span class="HTitleText2">Enactment of Canadian Wheat Board (Interim Operations) Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HTitleText2">Consequential and Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText3">Advance Payments for Crops Act</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText3">Agricultural Marketing Programs Act</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-10"><span class="HTitleText3">Agricultural Products Cooperative Marketing Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-11"><span class="HTitleText3">An Act to amend the Canada Grain Act and the Agriculture and Agri-Food Administrative Monetary Penalties Act and to repeal the Grain Futures Act</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-12"><span class="HTitleText3">Canada Grain Act</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-13"><span class="HTitleText3">Farm Products Agencies Act</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-14"><span class="HTitleText3">Livestock Feed Assistance Act</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-15"><span class="HTitleText3">Prairie Grain Advance Payments Act</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-16"><span class="HTitleText3">Seeds Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-17"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-18"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-19"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">COMMERCIALIZATION OF THE CANADIAN WHEAT BOARD</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-20"><span class="HTitleText2">Continuance</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-21"><span class="HTitleText2">Coming into Force</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-22"><span class="HTitleText2">Ceasing to Have Effect</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-23"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">DISSOLUTION OF THE CANADIAN WHEAT BOARD</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-24"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-25"><span class="HTitleText2">Final Pool Period</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-26"><span class="HTitleText2">Distribution of Assets</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-27"><span class="HTitleText2">Appointment of Liquidator</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-28"><span class="HTitleText2">Dissolution Date</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-29"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">REPEAL OF THE CANADIAN WHEAT BOARD (INTERIM OPERATIONS) ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="#h-30"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-31"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-32"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-33"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-34"><span class="HTitleText3">Canada Grain Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-35"><span class="HTitleText3">Canada Transportation Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-36"><span class="HTitleText3">Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-37"><span class="HTitleText3">Payments in Lieu of Taxes Act</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-38"><span class="HTitleText3">Privacy Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="#h-39"><span class="HTitleText2">Repeal</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

