<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Restoring Rail Service Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">RAIL SERVICE OPERATIONS</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">EXTENSION OF COLLECTIVE AGREEMENTS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">ARBITRATION</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-6"><span class="HTitleText1">NEW COLLECTIVE AGREEMENTS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText1">COSTS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText1">ENFORCEMENT</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-9"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

