<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–United States–Mexico Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Causes of Action</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Implementation of Agreement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Approval, Designation of Minister and Representation on Commission</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText2">Secretariat</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText2">Panels and Committees</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Labour Council</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText2">Expenses</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Copyright Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-17"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-18"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Export and Import Permits Act</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Fertilizers Act</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Food and Drugs Act</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Grain Act</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Importation of Intoxicating Liquors Act</cite></span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Special Import Measures Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-28"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-29"><span class="HTitleText3">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Trademarks Act</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Commercial Arbitration Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian International Trade Tribunal Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="#h-35"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-36"><span class="HTitleText3">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Broadcasting Act</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Pest Control Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Energy Regulator Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>213 - </span><a href="#h-44"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-45"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-46"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-47"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-48"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="#h-49"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li></ul>
</li></ul>

</nav>

