<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Judges Act and to amend another Act in consequence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">JUDGES ACT</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-2"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Supplementary Retirement Benefits Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

