<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2018, No. 2</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Income Tax Act</cite> and to Other Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Mutual Legal Assistance in Criminal Matters Act</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-6"><span class="HTitleText2">An Act to amend the <cite class="XRefExternalAct">Canada Pension Plan</cite>, the <cite class="XRefExternalAct">Canada Pension Plan Investment Board Act</cite> and the <cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-8"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-9"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Tax Act</cite> (GST/HST Measures) and to Related Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalRegulation">Financial Services and Financial Institutions (GST/HST) Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalRegulation">Selected Listed Financial Institutions Attribution Method (GST/HST) Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-13"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="#h-14"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Tax Act</cite> (Excise Measures), the <cite class="XRefExternalAct">Air Travellers Security Charge Act</cite> and the <cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Air Travellers Security Charge Act</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>69 - </span><a href="#h-18"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="#h-19"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Customs Tariff Simplification</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="#h-20"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-21"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-22"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="#h-23"><span class="HLabel2">DIVISION 2</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-24"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-25"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-26"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Financial Sector</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="#h-27"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Financial Institutions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="#h-28"><span class="HTitleText4">Materiality Threshold</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-29"><span class="HTitleText5"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-30"><span class="HTitleText5"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-31"><span class="HTitleText5"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>135 - </span><a href="#h-32"><span class="HTitleText4">Business Growth Fund</span></a>
</li></ul>
</li><li><span class='sectionRange'>135 - </span><a href="#h-33"><span class="HTitleText5"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-34"><span class="HTitleText5"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-35"><span class="HTitleText5"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="#h-36"><span class="HTitleText4">Electronic Consent</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="#h-37"><span class="HTitleText5"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-38"><span class="HTitleText5"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-39"><span class="HTitleText5"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>155 - </span><a href="#h-40"><span class="HTitleText4">Technical Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>155 - </span><a href="#h-41"><span class="HTitleText5"><cite class="XRefExternalAct">Budget Implementation Act, 2018, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-42"><span class="HTitleText5">Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-43"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Amendments related to <cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-44"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="#h-45"><span class="HTitleText4"><cite class="XRefExternalAct">Financial System Review Act</cite></span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-46"><span class="HTitleText5">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-47"><span class="HTitleText5">Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="#h-48"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Privileged information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="#h-49"><span class="HTitleText4"><cite class="XRefExternalAct">Office of the Superintendent of Financial Institutions Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-50"><span class="HTitleText4"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>169 - </span><a href="#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>174 - </span><a href="#h-53"><span class="HLabel2">DIVISION 4</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-54"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Greenhouse Gas Emissions Pricing and Other Topics Relating to Offshore Area</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>176 - </span><a href="#h-55"><span class="HTitleText3"><cite class="XRefExternalAct">Canada–Newfoundland and Labrador Atlantic Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-56"><span class="HTitleText3"><cite class="XRefExternalAct">Greenhouse Gas Pollution Pricing Act</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-57"><span class="HTitleText3"><cite class="XRefExternalAct">Offshore Health and Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-58"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>182 - </span><a href="#h-59"><span class="HLabel2">DIVISION 6</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Business Corporations Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>182 - </span><a href="#h-60"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-61"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>187 - </span><a href="#h-62"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Intellectual Property Strategy</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>187 - </span><a href="#h-63"><span class="HLabel3">SUBDIVISION A</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Patent Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>187 - </span><a href="#h-64"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-65"><span class="HTitleText4">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-66"><span class="HTitleText4">Related Amendments to the <cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-67"><span class="HTitleText4">Consequential Amendment to the <cite class="XRefExternalAct">Canada–European Union Comprehensive Economic and Trade Agreement Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-68"><span class="HTitleText4">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-69"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-70"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Trade-marks</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-71"><span class="HTitleText4"><cite class="XRefExternalAct">Trade-marks Act</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-72"><span class="HTitleText4"><cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="#h-73"><span class="HTitleText4"><cite class="XRefExternalAct">Combating Counterfeit Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-74"><span class="HTitleText4">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-75"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>243 - </span><a href="#h-76"><span class="HLabel3">SUBDIVISION C</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Copyright Act</cite> (notices of claimed infringement)</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-77"><span class="HLabel3">SUBDIVISION D</span> - <span class="HTitleText3"><cite class="XRefExternalAct">College of Patent Agents and Trade-mark Agents Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="#h-78"><span class="HTitleText4">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-79"><span class="HTitleText4">Consequential Amendments</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>248 - </span><a href="#h-80"><span class="HTitleText5"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-81"><span class="HTitleText5"><cite class="XRefExternalAct">Patent Act</cite></span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-82"><span class="HTitleText5"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-83"><span class="HTitleText5"><cite class="XRefExternalAct">Trade-marks Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>259 - </span><a href="#h-84"><span class="HTitleText4">Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>264 - </span><a href="#h-85"><span class="HTitleText4">Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>265 - </span><a href="#h-86"><span class="HLabel3">SUBDIVISION E</span> - <span class="HTitleText3">Amendments relating to preservation of usage rights</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>265 - </span><a href="#h-87"><span class="HTitleText4"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="#h-88"><span class="HTitleText4"><cite class="XRefExternalAct">Companies’ Creditors Arrangement Act</cite></span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-89"><span class="HTitleText4">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-90"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>273 - </span><a href="#h-91"><span class="HLabel3">SUBDIVISION F</span> - <span class="HTitleText3">Privileged Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>273 - </span><a href="#h-92"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>274 - </span><a href="#h-93"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="#h-94"><span class="HTitleText4">Related Amendment to the <cite class="XRefExternalAct">Pest Control Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="#h-95"><span class="HTitleText4">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>278 - </span><a href="#h-96"><span class="HLabel3">SUBDIVISION G</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">National Research Council Act</cite></span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="#h-97"><span class="HLabel3">SUBDIVISION H</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Copyright Act</cite> (Copyright Board Reform)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>280 - </span><a href="#h-98"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-99"><span class="HTitleText4">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="#h-100"><span class="HTitleText4">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>302 - </span><a href="#h-101"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>303 - </span><a href="#h-102"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">Parental Benefits and Related Leave</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>303 - </span><a href="#h-103"><span class="HTitleText3"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>303 - </span><a href="#h-104"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="#h-105"><span class="HTitleText4">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="#h-106"><span class="HTitleText4">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>310 - </span><a href="#h-107"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>310 - </span><a href="#h-108"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="#h-109"><span class="HTitleText4">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>313 - </span><a href="#h-110"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>314 - </span><a href="#h-111"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Gender Budgeting Act</cite></span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="#h-112"><span class="HLabel2">DIVISION 10</span> - <span class="HTitleText2">Financial Consumer Protection Framework</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>315 - </span><a href="#h-113"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>315 - </span><a href="#h-114"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="#h-115"><span class="HTitleText4">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>336 - </span><a href="#h-116"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Consumer Agency of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>351 - </span><a href="#h-117"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>352 - </span><a href="#h-118"><span class="HLabel2">DIVISION 11</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">First Nations Land Management Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>352 - </span><a href="#h-119"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>384 - </span><a href="#h-120"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Family Homes on Reserves and Matrimonial Interests or Rights Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>385 - </span><a href="#h-121"><span class="HLabel2">DIVISION 12</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">First Nations Fiscal Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>415 - </span><a href="#h-122"><span class="HLabel2">DIVISION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Export and Import Permits Act</cite></span></a>
</li>
<li><span class='sectionRange'>416 - </span><a href="#h-123"><span class="HLabel2">DIVISION 14</span> - <span class="HTitleText2">Pay Equity</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>416 - </span><a href="#h-124"><span class="HTitleText3"><cite class="XRefExternalAct">Pay Equity Act</cite></span></a>
</li>
<li><span class='sectionRange'>417 - </span><a href="#h-125"><span class="HTitleText3">Amendment to <cite class="XRefExternalAct">Pay Equity Act</cite></span></a>
</li>
<li><span class='sectionRange'>418 - </span><a href="#h-126"><span class="HTitleText3">Federal Contractors Program</span></a>
</li>
<li><span class='sectionRange'>419 - </span><a href="#h-127"><span class="HTitleText3">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>419 - </span><a href="#h-128"><span class="HTitleText4"><cite class="XRefExternalAct">Canadian Human Rights Act</cite></span></a>
</li>
<li><span class='sectionRange'>427 - </span><a href="#h-129"><span class="HTitleText4"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>428 - </span><a href="#h-130"><span class="HTitleText3">Transitional Provisions, Consequential Amendments, Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>428 - </span><a href="#h-131"><span class="HTitleText4">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>429 - </span><a href="#h-132"><span class="HTitleText4">Consequential Amendments</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>429 - </span><a href="#h-133"><span class="HTitleText5"><cite class="XRefExternalAct">Budget Implementation Act, 2009</cite></span></a>
</li>
<li><span class='sectionRange'>435 - </span><a href="#h-134"><span class="HTitleText5"><cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 2</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>439 - </span><a href="#h-135"><span class="HTitleText4">Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>440 - </span><a href="#h-136"><span class="HTitleText4">Coming into Force</span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="#h-137"><span class="HLabel2">DIVISION 15</span> - <span class="HTitleText2">Modernization of the <cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>441 - </span><a href="#h-138"><span class="HLabel3">SUBDIVISION A</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>441 - </span><a href="#h-139"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>506 - </span><a href="#h-140"><span class="HTitleText4"><cite class="XRefExternalAct">Budget Implementation Act, 2017, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>511 - </span><a href="#h-141"><span class="HTitleText4"><cite class="XRefExternalAct">Budget Implementation Act, 2017, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>517 - </span><a href="#h-142"><span class="HTitleText4">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>529 - </span><a href="#h-143"><span class="HTitleText4">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>534 - </span><a href="#h-144"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>535 - </span><a href="#h-145"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Head of Compliance and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>535 - </span><a href="#h-146"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>622 - </span><a href="#h-147"><span class="HTitleText4">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>625 - </span><a href="#h-148"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>626 - </span><a href="#h-149"><span class="HLabel2">DIVISION 16</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Wage Earner Protection Program Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>626 - </span><a href="#h-150"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>649 - </span><a href="#h-151"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>651 - </span><a href="#h-152"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>653 - </span><a href="#h-153"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>654 - </span><a href="#h-154"><span class="HLabel2">DIVISION 17</span> - <span class="HTitleText2">International Financial Assistance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>654 - </span><a href="#h-155"><span class="HTitleText3">Amendments to Certain Acts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>654 - </span><a href="#h-156"><span class="HTitleText4"><cite class="XRefExternalAct">Bretton Woods and Related Agreements Act</cite></span></a>
</li>
<li><span class='sectionRange'>655 - </span><a href="#h-157"><span class="HTitleText4"><cite class="XRefExternalAct">European Bank for Reconstruction and Development Agreement Act</cite></span></a>
</li>
<li><span class='sectionRange'>656 - </span><a href="#h-158"><span class="HTitleText4"><cite class="XRefExternalAct">Official Development Assistance Accountability Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>659 - </span><a href="#h-159"><span class="HTitleText3"><cite class="XRefExternalAct">International Financial Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>660 - </span><a href="#h-160"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>661 - </span><a href="#h-161"><span class="HLabel2">DIVISION 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Department for Women and Gender Equality Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>661 - </span><a href="#h-162"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>662 - </span><a href="#h-163"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>662 - </span><a href="#h-164"><span class="HTitleText4"><cite class="XRefExternalAct">Appropriation Act No. 3, 1976</cite></span></a>
</li>
<li><span class='sectionRange'>663 - </span><a href="#h-165"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>665 - </span><a href="#h-166"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>670 - </span><a href="#h-167"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>672 - </span><a href="#h-168"><span class="HTitleText4"><cite class="XRefExternalAct">Salaries Act</cite></span></a>
</li>
<li><span class='sectionRange'>673 - </span><a href="#h-169"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>675 - </span><a href="#h-170"><span class="HLabel2">DIVISION 19</span> - <span class="HTitleText2">Addition of Lands to Reserves and Reserve Creation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>675 - </span><a href="#h-171"><span class="HTitleText3"><cite class="XRefExternalAct">Addition of Lands to Reserves and Reserve Creation Act</cite></span></a>
</li>
<li><span class='sectionRange'>676 - </span><a href="#h-172"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>679 - </span><a href="#h-173"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>679 - </span><a href="#h-174"><span class="HTitleText4"><cite class="XRefExternalAct">Saskatchewan Treaty Land Entitlement Act</cite></span></a>
</li>
<li><span class='sectionRange'>680 - </span><a href="#h-175"><span class="HTitleText4"><cite class="XRefExternalAct">Manitoba Claim Settlements Implementation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>684 - </span><a href="#h-176"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>685 - </span><a href="#h-177"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>686 - </span><a href="#h-178"><span class="HLabel2">DIVISION 20</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>687 - </span><a href="#h-179"><span class="HLabel2">DIVISION 21</span> - <span class="HTitleText2">Poverty Reduction Measures, Phase 1</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>687 - </span><a href="#h-180"><span class="HTitleText3"><cite class="XRefExternalAct">Poverty Reduction Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>688 - </span><a href="#h-181"><span class="HLabel2">DIVISION 22</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Shipping Act, 2001</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>688 - </span><a href="#h-182"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>711 - </span><a href="#h-183"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>712 - </span><a href="#h-184"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>713 - </span><a href="#h-185"><span class="HLabel2">DIVISION 23</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Marine Liability Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>713 - </span><a href="#h-186"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>746 - </span><a href="#h-187"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>747 - </span><a href="#h-188"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-189"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-190"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

