<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to establish the Library and Archives of Canada, to amend the Copyright Act and to amend certain Acts in consequence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION AND APPLICATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">ESTABLISHMENT AND ORGANIZATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">OBJECTS AND POWERS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText1">LEGAL DEPOSIT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-6"><span class="HTitleText1">OBTAINING ARCHIVAL QUALITY RECORDINGS FOR PRESERVATION PURPOSES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-7"><span class="HTitleText1">GOVERNMENT AND MINISTERIAL RECORDS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText1">SURPLUS CROWN ASSETS ACT</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-9"><span class="HTitleText1">FINANCIAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-10"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText1">OFFENCES AND PENALTIES</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-12"><span class="HTitleText1">AMENDMENTS TO THE COPYRIGHT ACT</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-13"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText2">Copyright Act</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-16"><span class="HTitleText2">Department of Veterans Affairs Act</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-17"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-18"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-19"><span class="HTitleText2">Historic Sites and Monuments Act</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-20"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-21"><span class="HTitleText2">Injured Military Members Compensation Act</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-22"><span class="HTitleText2">Nunavut Land Claims Agreement Act</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-23"><span class="HTitleText2">Parliament of Canada Act</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-24"><span class="HTitleText2">Pension Act</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-25"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-26"><span class="HTitleText2">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-27"><span class="HTitleText2">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-28"><span class="HTitleText2">Public Service Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-29"><span class="HTitleText2">War Veterans Allowance Act</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-30"><span class="HTitleText2">Youth Criminal Justice Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-31"><span class="HTitleText2">Yukon First Nations Land Claims Settlement Act</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-32"><span class="HTitleText2">Yukon First Nations Self-Government Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-33"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-34"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-35"><span class="HTitleText1">REPEALS</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-36"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

