<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Corrections and Conditional Release Act and another Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Criminal Records Act</cite></span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-3"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="page-5.html#h-4"><span class="HTitleText1">Review and Report</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-5.html#h-5"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

