<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Tax Conventions Implementation Act, 2013</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">CANADA–NAMIBIA TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">CANADA–SERBIA TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CANADA–POLAND TAX CONVENTION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">CANADA–HONG KONG TAX AGREEMENT</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CANADA–LUXEMBOURG TAX CONVENTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Conventions Implementation Act, 1999</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8"><span class="HTitleText2">Canada–Luxembourg 2012 Protocol and Agreement</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">CANADA–SWITZERLAND TAX CONVENTION</span></a>
</li>
<li><a href="#h-10"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-11"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-12"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-13"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="#h-14"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="#h-15"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li></ul>
</li></ul>

</nav>

