<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2016, No. 2</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Income Tax Act</cite> and to Related Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Application Rules</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-6"><span class="HTitleText2">Consequential Amendments to the <cite class="XRefExternalRegulation">Canada Pension Plan Regulations</cite> Arising from Subsection 27(1), Chapter 7 of the Statutes of Canada, 2016</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-7"><span class="HTitleText2">Terminology Changes Arising from Subsection 27(1), Chapter 7 of the Statutes of Canada, 2016</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>86 - </span><a href="#h-8"><span class="HTitleText3">References in the <cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-9"><span class="HTitleText3">References in Regulations</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-10"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>89 - </span><a href="#h-11"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Tax Act</cite> (GST/HST Measures) and Other Related Texts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-13"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-14"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalRegulation">Closely Related Corporations (GST/HST) Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalRegulation">Streamlined Accounting (GST/HST) Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>100 - </span><a href="#h-17"><span class="HLabel1">PART 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-18"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-19"><span class="HLabel2">DIVISION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-20"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-21"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-22"><span class="HLabel2">DIVISION 2</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Old Age Security Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-23"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-24"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>107 - </span><a href="#h-25"><span class="HLabel2">DIVISION 3</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Education Savings Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>107 - </span><a href="#h-26"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-27"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="#h-28"><span class="HLabel2">DIVISION 4</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Disability Savings Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>114 - </span><a href="#h-29"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-30"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-31"><span class="HLabel2">Division 5</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Royal Canadian Mint Act</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-32"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Funds Management</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="#h-33"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-34"><span class="HTitleText3"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-35"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Mortgage and Housing Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-36"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>

