<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Preventing Persons from Concealing Their Identity during Riots and Unlawful Assemblies Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">ALTERNATIVE TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">CRIMINAL CODE</span></a>
</li></ul>
</li></ul>

</nav>

