<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Indian Act in response to the Superior Court of Quebec decision in Descheneaux c. Canada (Procureur général)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Indian Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-2"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-3"><span class="HTitleText1">Related Provisions</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-4"><span class="HTitleText1">Consultations and Reports</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-5"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

