<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Creating Canada’s New National Museum of Immigration at Pier 21 Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">MUSEUMS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Expenditure Restraint Act</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="page-1.html#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

