<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Safe Streets and Communities Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">JUSTICE FOR VICTIMS OF TERRORISM ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Amendments to the State Immunity Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-2.html#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">SENTENCING</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-4.html#h-7"><span class="HTitleText2">Controlled Drugs and Substances Act</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-8"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="page-5.html#h-9"><span class="HTitleText3">An Act to amend the Criminal Code (firearms) and the Firearms Act</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-10"><span class="HTitleText3">National Defence Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="page-6.html#h-11"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="page-6.html#h-12"><span class="HTitleText3">Criminal Records Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-6.html#h-13"><span class="HTitleText3">National Defence Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="page-6.html#h-14"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="page-6.html#h-15"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">POST-SENTENCING</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="page-6.html#h-16"><span class="HTitleText2">Corrections And Conditional Release Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="page-6.html#h-17"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-12.html#h-18"><span class="HTitleText3">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="page-12.html#h-19"><span class="HTitleText2">Criminal Records Act</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-14.html#h-20"><span class="HTitleText2">International Transfer of Offenders Act</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-14.html#h-21"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>137 - </span><a href="page-14.html#h-22"><span class="HTitleText3">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-14.html#h-23"><span class="HTitleText3">Contraventions Act</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-15.html#h-24"><span class="HTitleText3">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-15.html#h-25"><span class="HTitleText3">DNA Identification Act</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-15.html#h-26"><span class="HTitleText3">Immigration and Refugee Protection Act</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-15.html#h-27"><span class="HTitleText3">Limiting Pardons for Serious Crimes Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-15.html#h-28"><span class="HTitleText3">National Defence Act</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-16.html#h-29"><span class="HTitleText3">Youth Criminal Justice Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>160 - </span><a href="page-16.html#h-30"><span class="HTitleText2">Terminology Changes</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-16.html#h-31"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-17.html#h-32"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>167 - </span><a href="page-17.html#h-33"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">YOUTH CRIMINAL JUSTICE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="page-17.html#h-34"><span class="HTitleText2">Youth Criminal Justice Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="page-17.html#h-35"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="page-18.html#h-36"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>196 - </span><a href="page-19.html#h-37"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="page-19.html#h-38"><span class="HTitleText3">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="page-19.html#h-39"><span class="HTitleText3">Prisons and Reformatories Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="page-19.html#h-40"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="page-19.html#h-41"><span class="HTitleText3">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="page-19.html#h-42"><span class="HTitleText3">DNA Identification Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>204 - </span><a href="page-19.html#h-43"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="page-19.html#h-44"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">IMMIGRATION AND REFUGEE PROTECTION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>205 - </span><a href="page-19.html#h-45"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="page-20.html#h-46"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-21.html#h-47"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

