<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Yukon Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">GOVERNMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText2">Executive Power</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText2">Legislative Power</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText3">Legislative Assembly</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText3">Legislature</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText3">Legislative Powers</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-9"><span class="HTitleText2">Yukon Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-10"><span class="HTitleText2">Yukon Public Accounts</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-11"><span class="HTitleText1">ADMINISTRATION OF JUSTICE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-12"><span class="HTitleText2">Judicature</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-13"><span class="HTitleText2">Supreme Court of Yukon</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-14"><span class="HTitleText2">Court of Appeal of Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-15"><span class="HTitleText1">REAL PROPERTY, WATER, OIL AND GAS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-16"><span class="HTitleText2">Administration and Control</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-17"><span class="HTitleText2">Restrictions</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-18"><span class="HTitleText1">EXERCISE OF FEDERAL POWERS</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-19"><span class="HTitleText1">LEGISLATIVE AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-20"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-21"><span class="HTitleText1">AMENDMENTS TO THIS ACT</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-22"><span class="HTitleText1">AMENDMENTS TO OTHER ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 - </span><a href="#h-23"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-24"><span class="HTitleText2">Aeronautics Act</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-25"><span class="HTitleText2">Arctic Waters Pollution Prevention Act</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-26"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-27"><span class="HTitleText2">Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-28"><span class="HTitleText2">Boards of Trade Act</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-29"><span class="HTitleText2">Canada Business Corporations Act</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-30"><span class="HTitleText2">Canada Corporations Act</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-31"><span class="HTitleText2">Canada Elections Act</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-32"><span class="HTitleText2">Canada Evidence Act</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-33"><span class="HTitleText2">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-34"><span class="HTitleText2">Canada Lands Surveys Act</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-35"><span class="HTitleText2">Canada Marine Act</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-36"><span class="HTitleText2">Canada National Parks Act</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-37"><span class="HTitleText2">Canada-Newfoundland Atlantic Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-38"><span class="HTitleText2">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-39"><span class="HTitleText2">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-40"><span class="HTitleText2">Canada Pension Plan Investment Board Act</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-41"><span class="HTitleText2">Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-42"><span class="HTitleText2">Canada Transportation Act</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-43"><span class="HTitleText2">Canada Water Act</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-44"><span class="HTitleText2">Canada-Yukon Oil and Gas Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-45"><span class="HTitleText2">Canadian Centre for Occupational Health and Safety Act</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-46"><span class="HTitleText2">Canadian Environmental Assessment Act</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-47"><span class="HTitleText2">Canadian Environmental Protection Act, 1999</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-48"><span class="HTitleText2">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-49"><span class="HTitleText2">Canadian Multiculturalism Act</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-50"><span class="HTitleText2">Canadian Transportation Accident Investigation and Safety Board Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-51"><span class="HTitleText2">Citizenship Act</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-52"><span class="HTitleText2">Coasting Trade Act</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-53"><span class="HTitleText2">Companies’ Creditors Arrangement Act</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-54"><span class="HTitleText2">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-55"><span class="HTitleText2">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-56"><span class="HTitleText2">Crown Liability and Proceedings Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-57"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-58"><span class="HTitleText2">Department of Indian Affairs and Northern Development Act</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-59"><span class="HTitleText2">Department of Public Works and Government Services Act</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-60"><span class="HTitleText2">Divorce Act</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-61"><span class="HTitleText2">Dominion Water Power Act</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-62"><span class="HTitleText2">Employment Equity Act</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-63"><span class="HTitleText2">Energy Administration Act</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-64"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-65"><span class="HTitleText2">Expropriation Act</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-66"><span class="HTitleText2">Extradition Act</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-67"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-68"><span class="HTitleText2">Federal Real Property and Federal Immovables Act</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-69"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-70"><span class="HTitleText2">Fisheries Act</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-71"><span class="HTitleText2">Government Employees Compensation Act</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-72"><span class="HTitleText2">Gwich’in Land Claim Settlement Act</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-73"><span class="HTitleText2">Hazardous Materials Information Review Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-74"><span class="HTitleText2">Hibernia Development Project Act</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-75"><span class="HTitleText2">Historic Sites and Monuments Act</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-76"><span class="HTitleText2">Immigration Act</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-77"><span class="HTitleText2">Importation of Intoxicating Liquors Act</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-78"><span class="HTitleText2">Indian Act</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-79"><span class="HTitleText2">Industrial and Regional Development Act</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-80"><span class="HTitleText2">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-81"><span class="HTitleText2">Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-82"><span class="HTitleText2">Judges Act</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-83"><span class="HTitleText2">Land Titles Repeal Act</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-84"><span class="HTitleText2">Livestock Feed Assistance Act</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-85"><span class="HTitleText2">Mackenzie Valley Resource Management Act</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-86"><span class="HTitleText2">Motor Vehicle Fuel Consumption Standards Act</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-87"><span class="HTitleText2">Mutual Legal Assistance in Criminal Matters Act</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-88"><span class="HTitleText2">National Energy Board Act</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-89"><span class="HTitleText2">Northern Pipeline Act</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-90"><span class="HTitleText2">Northwest Territories Act</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-91"><span class="HTitleText2">Nuclear Energy Act</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-92"><span class="HTitleText2">Nunavut Act</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-93"><span class="HTitleText2">Oceans Act</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-94"><span class="HTitleText2">Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-95"><span class="HTitleText2">Pension Benefits Standards Act, 1985</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-96"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-97"><span class="HTitleText2">Public Service Employment Act</span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-98"><span class="HTitleText2">Public Service Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-99"><span class="HTitleText2">Public Service Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-100"><span class="HTitleText2">Radiocommunication Act</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-101"><span class="HTitleText2">Railway Safety Act</span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="#h-102"><span class="HTitleText2">Royal Canadian Mounted Police Act</span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="#h-103"><span class="HTitleText2">Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-104"><span class="HTitleText2">Supreme Court Act</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-105"><span class="HTitleText2">Territorial Lands Act</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-106"><span class="HTitleText2">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-107"><span class="HTitleText2">Western Arctic (Inuvialuit) Claims Settlement Act</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="#h-108"><span class="HTitleText2">Winding-up and Restructuring Act</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="#h-109"><span class="HTitleText2">Young Offenders Act</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-110"><span class="HTitleText2">Yukon First Nations Land Claims Settlement Act</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="#h-111"><span class="HTitleText2">Yukon First Nations Self-Government Act</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-112"><span class="HTitleText2">Yukon Surface Rights Board Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>272 - </span><a href="#h-113"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="#h-114"><span class="HTitleText1">REPEALS</span></a>
</li>
<li><span class='sectionRange'>285 - </span><a href="#h-115"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-116"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - DESCRIPTION OF YUKON</span></a>
</li>
<li><a href="#h-117"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - NORTHERN LIMIT OF ADJOINING AREA</span></a>
</li></ul>
</li></ul>

</nav>

