<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Cannabis Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-3"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-4"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-5"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Prohibitions, Obligations and Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="page-2.html#h-7"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Criminal Activities</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-4.html#h-8"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Other Prohibitions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-4.html#h-9"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Promotion</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-5.html#h-10"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Packaging and Labelling</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-5.html#h-11"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Display</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-5.html#h-12"><span class="HLabel3">SUBDIVISION D</span> - <span class="HTitleText3">Selling and Distributing</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-6.html#h-13"><span class="HLabel3">SUBDIVISION E</span> - <span class="HTitleText3">Other Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="page-6.html#h-14"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-6.html#h-15"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Miscellaneous</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="page-6.html#h-16"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Ticketable Offences</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-8.html#h-17"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Licences and Permits</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-9.html#h-18"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">General Authorizations</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-9.html#h-19"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Ministerial Orders</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-10.html#h-20"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Cannabis Tracking System</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-11.html#h-21"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Inspections</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-12.html#h-22"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Search Warrant</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-12.html#h-23"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Disposition of Seized Things</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="page-12.html#h-24"><span class="HTitleText2">Report to Minister</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-12.html#h-25"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-12.html#h-26"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Non-chemical Offence-related Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-12.html#h-27"><span class="HTitleText3">Restraint Orders</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-13.html#h-28"><span class="HTitleText3">Management Orders</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-13.html#h-29"><span class="HTitleText3">Forfeiture</span></a>
</li></ul>
</li><li><span class='sectionRange'>102 - </span><a href="page-15.html#h-30"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Cannabis and Chemical Property</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="page-15.html#h-31"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="page-15.html#h-32"><span class="HTitleText2">Powers of Minister</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-15.html#h-33"><span class="HTitleText2">Violation</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-16.html#h-34"><span class="HTitleText2">Proceedings</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-16.html#h-35"><span class="HTitleText2">Penalties</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-16.html#h-36"><span class="HTitleText2">Compliance Agreements</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-16.html#h-37"><span class="HTitleText2">Review by Minister</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-17.html#h-38"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-17.html#h-39"><span class="HTitleText2">Rules About Violations</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-17.html#h-40"><span class="HTitleText2">Other Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>128 - </span><a href="page-17.html#h-41"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="page-17.html#h-42"><span class="HTitleText2">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-17.html#h-43"><span class="HTitleText2">Analysis</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-17.html#h-44"><span class="HTitleText2">Trademarks</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-17.html#h-45"><span class="HTitleText2">Evidence and Procedure</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-18.html#h-46"><span class="HTitleText2">Regulations and Exemptions</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-19.html#h-47"><span class="HTitleText2">Fees</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-19.html#h-48"><span class="HTitleText2">Costs</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-19.html#h-49"><span class="HTitleText2">Technical Assistance</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-19.html#h-50"><span class="HTitleText2">Amendments to Schedules</span></a>
</li>
<li><span class='sectionRange'>151.1 - </span><a href="page-19.html#h-51"><span class="HTitleText2">Review and Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="page-19.html#h-52"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Transitional Provisions and Related, Consequential and Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="page-19.html#h-53"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-22.html#h-54"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>162 - </span><a href="page-22.html#h-55"><span class="HTitleText3"><cite class="XRefExternalAct">Non-smokers’ Health Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="page-22.html#h-56"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="page-22.html#h-57"><span class="HTitleText3"><cite class="XRefExternalAct">Criminal Records Act</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-22.html#h-58"><span class="HTitleText3"><cite class="XRefExternalAct">Identification of Criminals Act</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-22.html#h-59"><span class="HTitleText3"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-22.html#h-60"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-22.html#h-61"><span class="HTitleText3"><cite class="XRefExternalAct">Mutual Legal Assistance in Criminal Matters Act</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-23.html#h-62"><span class="HTitleText3"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-23.html#h-63"><span class="HTitleText3"><cite class="XRefExternalAct">Seized Property Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-24.html#h-64"><span class="HTitleText3"><cite class="XRefExternalAct">Firearms Act</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="page-24.html#h-65"><span class="HTitleText3"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-24.html#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Youth Criminal Justice Act</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-24.html#h-67"><span class="HTitleText3">International Interests in Mobile Equipment (aircraft equipment) Act</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="page-24.html#h-68"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Consumer Product Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-24.html#h-69"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Victims Bill of Rights</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>188 - </span><a href="page-24.html#h-70"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>193.1 - </span><a href="page-25.html#h-71"><span class="HLabel1">PART 12.1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Cannabis Act</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-25.html#h-72"><span class="HLabel1">PART 13</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Controlled Drugs and Substances Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="page-25.html#h-73"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="page-26.html#h-74"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>207 - </span><a href="page-26.html#h-75"><span class="HLabel1">PART 14</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>207 - </span><a href="page-26.html#h-76"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="page-27.html#h-77"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>226 - </span><a href="page-28.html#h-78"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-29.html#h-79"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-30.html#h-80"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-31.html#h-81"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-32.html#h-82"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-33.html#h-83"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="page-34.html#h-84"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li></ul>
</li></ul>

</nav>

