<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Proceeds of Crime (Money Laundering) and Terrorist Financing Act and the Income Tax Act and to make a consequential amendment to another Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">AMENDMENTS TO THE PROCEEDS OF CRIME (MONEY LAUNDERING) AND TERRORIST FINANCING ACT</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-2"><span class="HTitleText1">AMENDMENTS TO THE INCOME TAX ACT</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Border Services Agency Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

