<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Yukon and Nunavut Regulatory Improvement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">YUKON ENVIRONMENTAL AND SOCIO-ECONOMIC ASSESSMENT ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-4"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">NUNAVUT WATERS AND NUNAVUT SURFACE RIGHTS TRIBUNAL ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-6"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-7"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-8"><span class="HTitleText2">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-9"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

