<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Lobbyists Registration Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOBBYISTS REGISTRATION ACT</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-2"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-3"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-4"><span class="HTitleText2">Filings by Consultant Lobbyists</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-5"><span class="HTitleText2">Filings by In-house Lobbyists (Corporations)</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-6"><span class="HTitleText2">Filings by In-house Lobbyists (Organizations)</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

