<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Safe and Regulated Sports Betting Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

