<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to increase the availability of agricultural loans and to repeal the Farm Improvement Loans Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">FARM IMPROVEMENT AND MARKETING COOPERATIVES LOANS ACT</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-2"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS TO THE BANK ACT</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-3"><span class="HTitleText1">REPEAL</span></a>
</li></ul>
</li></ul>

</nav>

