<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Criminal Code and to make related amendments to other Acts (medical assistance in dying)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-2"><span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-2.html#h-3"><span class="HTitleText2">Pension Act</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Canadian Forces Members and Veterans Re-establishment and Compensation Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>9.1 - </span><a href="page-2.html#h-6"><span class="HTitleText1">Independent Review</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-3.html#h-7"><span class="HTitleText1">Review of Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-3.html#h-8"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

