<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Canada Pension Plan and the Old Age Security Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">CANADA PENSION PLAN</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-2"><span class="HTitleText1">OLD AGE SECURITY ACT</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-3"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-4"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

