<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Zero Tolerance for Barbaric Cultural Practices Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">IMMIGRATION AND REFUGEE PROTECTION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">CIVIL MARRIAGE ACT</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CRIMINAL CODE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText3">Prisons and Reformatories Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText3">Youth Criminal Justice Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

