<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2021, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the Income Tax Act and Other Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-4"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-5"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-6"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-7"><span class="HTitleText2">Greenhouse Gas Pollution Pricing Act</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-8"><span class="HTitleText2">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-9"><span class="HTitleText2">Canada Disability Savings Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>100 - </span><a href="#h-10"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">GST/HST Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>100 - </span><a href="#h-11"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-12"><span class="HTitleText2">New Harmonized Value-added Tax System Regulations, No. 2</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-13"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments to the Excise Act, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="#h-14"><span class="HTitleText2">Excise Act, 2001</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="#h-15"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-16"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Stability and Efficiency of the Financial Sector</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-17"><span class="HTitleText3">Canada Deposit Insurance Corporation Act</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-18"><span class="HTitleText3">Payment Clearing and Settlement Act</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-19"><span class="HTitleText3">Budget Implementation Act, 2018, No. 1</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-20"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-21"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Unclaimed Amounts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="#h-22"><span class="HTitleText3">Bank of Canada Act</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-23"><span class="HTitleText3">Pension Benefits Standards Act, 1985</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-24"><span class="HTitleText3">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-25"><span class="HTitleText3">Bank Act</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-26"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-27"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="#h-28"><span class="HLabel2">DIVISION 3</span></span> - <span class="HTitleText2">Budget Implementation Act, 2018, No. 2</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-29"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-30"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-31"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Sunset Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="#h-32"><span class="HTitleText3">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-33"><span class="HTitleText3">Bank Act</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-34"><span class="HTitleText3">Insurance Companies Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>158 - </span><a href="#h-35"><span class="HLabel2">DIVISION 5</span></span> - <span class="HTitleText2">Justice for Victims of Corrupt Foreign Officials Act (Sergei Magnitsky Law)</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-36"><span class="HLabel2">DIVISION 6</span></span> - <span class="HTitleText2">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-37"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-38"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>177 - </span><a href="#h-39"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Retail Payment Activities Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="#h-40"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-41"><span class="HTitleText3">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>178 - </span><a href="#h-42"><span class="HTitleText4">Canada Deposit Insurance Corporation Act</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-43"><span class="HTitleText4">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-44"><span class="HTitleText4">Financial Consumer Agency of Canada Act</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-45"><span class="HTitleText4">Payment Card Networks Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-46"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-47"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>188 - </span><a href="#h-48"><span class="HLabel2">DIVISION 8</span></span> - <span class="HTitleText2">Pension Benefits Standards Act, 1985</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>188 - </span><a href="#h-49"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-50"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="#h-51"><span class="HLabel2">DIVISION 9</span></span> - <span class="HTitleText2">First Nations Fiscal Management Act</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-52"><span class="HLabel2">DIVISION 10</span></span> - <span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act (Fiscal Stabilization Payments)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="#h-53"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-54"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>196 - </span><a href="#h-55"><span class="HLabel2">DIVISION 11</span></span> - <span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act (Additional Health Payments)</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-56"><span class="HLabel2">DIVISION 12</span> - <span class="HTitleText2">Canada’s COVID-19 Immunization Plan</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-57"><span class="HLabel2">DIVISION 13</span> - <span class="HTitleText2">Canada Community-Building Fund</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>198 - </span><a href="#h-58"><span class="HTitleText3">Additional Payments</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-59"><span class="HTitleText3">Keeping Canada’s Economy and Jobs Growing Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="#h-60"><span class="HLabel2">DIVISION 14</span> - <span class="HTitleText2">Hibernia Dividend Backed Annuity Agreement</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-61"><span class="HLabel2">DIVISION 15</span></span> - <span class="HTitleText2">Nova Scotia and Newfoundland and Labrador Additional Fiscal Equalization Offset Payments Act</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-62"><span class="HLabel2">DIVISION 16</span></span> - <span class="HTitleText2">Telecommunications Act</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-63"><span class="HLabel2">DIVISION 17</span></span> - <span class="HTitleText2">Canada Small Business Financing Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>204 - </span><a href="#h-64"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-65"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>209 - </span><a href="#h-66"><span class="HLabel2">DIVISION 18</span></span> - <span class="HTitleText2">Customs Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>209 - </span><a href="#h-67"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>218 - </span><a href="#h-68"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>219 - </span><a href="#h-69"><span class="HLabel2">DIVISION 19</span></span> - <span class="HTitleText2">Canada–United States–Mexico Agreement Implementation Act</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-70"><span class="HLabel2">DIVISION 20</span> - <span class="HTitleText2">Social Security Tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="#h-71"><span class="HTitleText3">Department of Employment and Social Development Act</span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-72"><span class="HTitleText3">Consequential Amendment to the Federal Courts Act</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-73"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-74"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>245 - </span><a href="#h-75"><span class="HLabel2">DIVISION 21</span></span> - <span class="HTitleText2">Canada Labour Code (Equal Remuneration Protection)</span></a>
</li>
<li><span class='sectionRange'>246 - </span><a href="#h-76"><span class="HLabel2">DIVISION 22</span></span> - <span class="HTitleText2">Canada Labour Code (Federal Minimum Wage)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>246 - </span><a href="#h-77"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-78"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>249 - </span><a href="#h-79"><span class="HLabel2">DIVISION 23</span></span> - <span class="HTitleText2">Canada Labour Code (Leave Related to the Death or Disappearance of a Child)</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="#h-80"><span class="HLabel2">DIVISION 24</span> - <span class="HTitleText2">Payment to Quebec</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="#h-81"><span class="HLabel2">DIVISION 25</span></span> - <span class="HTitleText2">Judges Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>252 - </span><a href="#h-82"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-83"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>254 - </span><a href="#h-84"><span class="HLabel2">DIVISION 26</span> - <span class="HTitleText2">New Judicial Resources</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>254 - </span><a href="#h-85"><span class="HTitleText3">Federal Courts Act</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-86"><span class="HTitleText3">Judges Act</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="#h-87"><span class="HTitleText3">Tax Court of Canada Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="#h-88"><span class="HLabel2">DIVISION 27</span></span> - <span class="HTitleText2">National Research Council Act</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-89"><span class="HLabel2">DIVISION 28</span></span> - <span class="HTitleText2">Department of Employment and Social Development Act</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="#h-90"><span class="HLabel2">DIVISION 29</span> - <span class="HTitleText2">Student Loans and Apprentice Loans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>263 - </span><a href="#h-91"><span class="HTitleText3">Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="#h-92"><span class="HTitleText3">Canada Student Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="#h-93"><span class="HTitleText3">Apprentice Loans Act</span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="#h-94"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>267 - </span><a href="#h-95"><span class="HLabel2">DIVISION 30</span> - <span class="HTitleText2">First Nations Elections</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-96"><span class="HLabel2">DIVISION 31</span> - <span class="HTitleText2">Increase to Old Age Security Pension and Payment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>268 - </span><a href="#h-97"><span class="HTitleText3">Old Age Security Act</span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="#h-98"><span class="HTitleText3">Payment</span></a>
</li></ul>
</li><li><span class='sectionRange'>276 - </span><a href="#h-99"><span class="HLabel2">DIVISION 32</span></span> - <span class="HTitleText2">Public Service Employment Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>276 - </span><a href="#h-100"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>282 - </span><a href="#h-101"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="#h-102"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>287 - </span><a href="#h-103"><span class="HLabel2">DIVISION 33</span> - <span class="HTitleText2">Early Learning and Child Care</span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="#h-104"><span class="HLabel2">DIVISION 34</span> - <span class="HTitleText2">Benefits and Leave</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>288 - </span><a href="#h-105"><span class="HTitleText3">Canada Recovery Benefits Act</span></a>
</li>
<li><span class='sectionRange'>295 - </span><a href="#h-106"><span class="HTitleText3">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="#h-107"><span class="HTitleText3">COVID-19 Response Measures Act</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-108"><span class="HTitleText3">Canada Recovery Benefits Regulations</span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="#h-109"><span class="HTitleText3">Canada Labour Standards Regulations</span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="#h-110"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>301 - </span><a href="#h-111"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>302 - </span><a href="#h-112"><span class="HLabel2">DIVISION 35</span> - <span class="HTitleText2">Benefits and Leave Related to Employment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>302 - </span><a href="#h-113"><span class="HTitleText3">Employment Insurance Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>302 - </span><a href="#h-114"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="#h-115"><span class="HTitleText4">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="#h-116"><span class="HTitleText4">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>339 - </span><a href="#h-117"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>340 - </span><a href="#h-118"><span class="HTitleText3">Canada Labour Code</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>340 - </span><a href="#h-119"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="#h-120"><span class="HTitleText4">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>346 - </span><a href="#h-121"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>347 - </span><a href="#h-122"><span class="HTitleText3">Employment Insurance Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>347 - </span><a href="#h-123"><span class="HTitleText4">Amendments to the Regulations</span></a>
</li>
<li><span class='sectionRange'>351 - </span><a href="#h-124"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>352 - </span><a href="#h-125"><span class="HTitleText3">Employment Insurance (Fishing) Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>352 - </span><a href="#h-126"><span class="HTitleText4">Amendments to the Regulations</span></a>
</li>
<li><span class='sectionRange'>359 - </span><a href="#h-127"><span class="HTitleText4">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>360 - </span><a href="#h-128"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>361 - </span><a href="#h-129"><span class="HLabel2">DIVISION 36</span></span> - <span class="HTitleText2">Canada Elections Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>361 - </span><a href="#h-130"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>362 - </span><a href="#h-131"><span class="HTitleText3">Application of Amendments</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-132"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-133"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-134"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-135"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li></ul>
</li></ul>

</nav>

