<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to provide no-cost, expedited record suspensions for simple possession of cannabis</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Criminal Records Act</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-2"><span class="HTitleText1">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-3"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-3.html#h-4"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

