<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Budget Implementation Act, 2009</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF INCOME TAX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-19.html#h-4"><span class="HTitleText2">Budget Implementation Act, 2008</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-19.html#h-5"><span class="HTitleText2">Income Tax Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>119 - </span><a href="page-24.html#h-6"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS IN RESPECT OF SALES AND EXCISE TAXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119 - </span><a href="page-24.html#h-7"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-24.html#h-8"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="page-25.html#h-9"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS TO THE CUSTOMS TARIFF</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="page-25.html#h-10"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="page-28.html#h-11"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>222 - </span><a href="page-28.html#h-12"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">EMPLOYMENT INSURANCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>222 - </span><a href="page-28.html#h-13"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="page-28.html#h-14"><span class="HTitleText2">Claimants Not in Canada</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="page-28.html#h-15"><span class="HTitleText2">Pilot Project Relating To Extended Benefits</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="page-28.html#h-16"><span class="HTitleText2">Premium Rates Provided for Under the Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="page-28.html#h-17"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-28.html#h-18"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-28.html#h-19"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>232 - </span><a href="page-28.html#h-20"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">STABILITY AND EFFICIENCY OF THE FINANCIAL SYSTEM</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>232 - </span><a href="page-28.html#h-21"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-29.html#h-22"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Canada Deposit Insurance Corporation Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>233 - </span><a href="page-29.html#h-23"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="page-32.html#h-24"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>255 - </span><a href="page-32.html#h-25"><span class="HTitleText4">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="page-32.html#h-26"><span class="HTitleText4">Canadian Payments Act</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="page-32.html#h-27"><span class="HTitleText4">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>258 - </span><a href="page-32.html#h-28"><span class="HTitleText4">Winding-up and Restructuring Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>259 - </span><a href="page-32.html#h-29"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="page-32.html#h-30"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Export Development Act</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="page-33.html#h-31"><span class="HLabel2">Division 4</span> - <span class="HTitleText2">Business Development Bank of Canada Act</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="page-33.html#h-32"><span class="HLabel2">Division 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Small Business Financing Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>265 - </span><a href="page-33.html#h-33"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="page-33.html#h-34"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>269 - </span><a href="page-33.html#h-35"><span class="HLabel2">Division 6</span> - <span class="HTitleText2">Legislation Governing Financial Institutions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>269 - </span><a href="page-33.html#h-36"><span class="HTitleText3">Bank Act</span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="page-34.html#h-37"><span class="HTitleText3">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="page-35.html#h-38"><span class="HTitleText3">Financial Consumer Agency of Canada Act</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="page-35.html#h-39"><span class="HTitleText3">Green Shield Canada Act</span></a>
</li>
<li><span class='sectionRange'>282 - </span><a href="page-35.html#h-40"><span class="HTitleText3">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="page-37.html#h-41"><span class="HTitleText3">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="page-38.html#h-42"><span class="HTitleText3">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="page-38.html#h-43"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>295 - </span><a href="page-38.html#h-44"><span class="HLabel2">Division 7</span> - <span class="HTitleText2">Securities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>295 - </span><a href="page-38.html#h-45"><span class="HTitleText3">Securities Regulation</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="page-38.html#h-46"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Securities Regulation Regime Transition Office Act</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="page-39.html#h-47"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="page-39.html#h-48"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>300 - </span><a href="page-39.html#h-49"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">PAYMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>300 - </span><a href="page-39.html#h-50"><span class="HTitleText2">Infrastructure Stimulus Fund</span></a>
</li>
<li><span class='sectionRange'>301 - </span><a href="page-39.html#h-51"><span class="HTitleText2">Provincial-Territorial Infrastructure Base Funding Program</span></a>
</li>
<li><span class='sectionRange'>302 - </span><a href="page-39.html#h-52"><span class="HTitleText2">Communities Component of the Building Canada Fund</span></a>
</li>
<li><span class='sectionRange'>303 - </span><a href="page-39.html#h-53"><span class="HTitleText2">Green Infrastructure Fund</span></a>
</li>
<li><span class='sectionRange'>304 - </span><a href="page-39.html#h-54"><span class="HTitleText2">Community Adjustment Fund</span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="page-39.html#h-55"><span class="HTitleText2">Improving Infrastructure at Universities and Colleges</span></a>
</li>
<li><span class='sectionRange'>310 - </span><a href="page-39.html#h-56"><span class="HTitleText2">First Nations Housing</span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="page-39.html#h-57"><span class="HTitleText2">Renovation and Retrofit of Social Housing</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="page-39.html#h-58"><span class="HTitleText2">Housing for Low-income Seniors</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="page-39.html#h-59"><span class="HTitleText2">Housing for Persons with Disabilities</span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="page-39.html#h-60"><span class="HTitleText2">Northern Housing</span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="page-39.html#h-61"><span class="HTitleText2">Canada Health Infoway Inc.</span></a>
</li></ul>
</li><li><span class='sectionRange'>317 - </span><a href="page-39.html#h-62"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">NAVIGABLE WATERS PROTECTION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>317 - </span><a href="page-39.html#h-63"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>341 - </span><a href="page-42.html#h-64"><span class="HTitleText2">Consequential Amendment to the International Bridges and Tunnels Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>342 - </span><a href="page-42.html#h-65"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">MISCELLANEOUS PROVISIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>342 - </span><a href="page-42.html#h-66"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Wage Earner Protection Program</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>342 - </span><a href="page-42.html#h-67"><span class="HTitleText3">Wage Earner Protection Program Act</span></a>
</li>
<li><span class='sectionRange'>348 - </span><a href="page-42.html#h-68"><span class="HTitleText3"><cite class="XRefExternalRegulation">Wage Earner Protection Program Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>355 - </span><a href="page-42.html#h-69"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>357 - </span><a href="page-43.html#h-70"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>358 - </span><a href="page-43.html#h-71"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Federal Financial Assistance for Students</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>358 - </span><a href="page-43.html#h-72"><span class="HTitleText3">Canada Student Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>365 - </span><a href="page-43.html#h-73"><span class="HTitleText3">Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="page-44.html#h-74"><span class="HTitleText3">Consequential Amendment to the Budget Implementation Act, 2008</span></a>
</li></ul>
</li><li><span class='sectionRange'>369 - </span><a href="page-44.html#h-75"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Crown Corporations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>369 - </span><a href="page-44.html#h-76"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>376 - </span><a href="page-45.html#h-77"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="page-45.html#h-78"><span class="HTitleText4">Canada Council for the Arts Act</span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="page-45.html#h-79"><span class="HTitleText4">Canada Employment Insurance Financing Board Act</span></a>
</li>
<li><span class='sectionRange'>378 - </span><a href="page-45.html#h-80"><span class="HTitleText4">Canada Post Corporation Act</span></a>
</li>
<li><span class='sectionRange'>379 - </span><a href="page-45.html#h-81"><span class="HTitleText4">Canadian Dairy Commission Act</span></a>
</li>
<li><span class='sectionRange'>380 - </span><a href="page-45.html#h-82"><span class="HTitleText4">Canadian Race Relations Foundation Act</span></a>
</li>
<li><span class='sectionRange'>381 - </span><a href="page-45.html#h-83"><span class="HTitleText4">Public Sector Pension Investment Board Act</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>383 - </span><a href="page-45.html#h-84"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">PAYMENTS TO PROVINCES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>383 - </span><a href="page-45.html#h-85"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>392 - </span><a href="page-47.html#h-86"><span class="HTitleText2">Payment to Nova Scotia</span></a>
</li></ul>
</li><li><span class='sectionRange'>393 - </span><a href="page-47.html#h-87"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">EXPENDITURE RESTRAINT ACT</span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="page-48.html#h-88"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">EQUITABLE COMPENSATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>394 - </span><a href="page-48.html#h-89"><span class="HTitleText2">Public Sector Equitable Compensation Act</span></a>
</li>
<li><span class='sectionRange'>395 - </span><a href="page-49.html#h-90"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>399 - </span><a href="page-49.html#h-91"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>399 - </span><a href="page-49.html#h-92"><span class="HTitleText3">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>400 - </span><a href="page-49.html#h-93"><span class="HTitleText3">Public Service Labour Relations Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>406 - </span><a href="page-49.html#h-94"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>407 - </span><a href="page-49.html#h-95"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">COMPETITION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>407 - </span><a href="page-49.html#h-96"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>440 - </span><a href="page-54.html#h-97"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="page-54.html#h-98"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>441 - </span><a href="page-54.html#h-99"><span class="HTitleText3"><cite class="XRefExternalAct">Competition Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>442 - </span><a href="page-54.html#h-100"><span class="HTitleText3"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>443 - </span><a href="page-54.html#h-101"><span class="HTitleText3"><cite class="XRefExternalAct">Shipping Conferences Exemption Act, 1987</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>444 - </span><a href="page-54.html#h-102"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>445 - </span><a href="page-54.html#h-103"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">INVESTMENT CANADA ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>445 - </span><a href="page-54.html#h-104"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="page-58.html#h-105"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>465 - </span><a href="page-58.html#h-106"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>466 - </span><a href="page-58.html#h-107"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">CANADA TRANSPORTATION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>466 - </span><a href="page-58.html#h-108"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="page-58.html#h-109"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>469 - </span><a href="page-58.html#h-110"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">AIR CANADA PUBLIC PARTICIPATION ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>469 - </span><a href="page-58.html#h-111"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>470 - </span><a href="page-58.html#h-112"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>471 - </span><a href="page-58.html#h-113"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-59.html#h-114"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-60.html#h-115"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-61.html#h-116"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-62.html#h-117"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-63.html#h-118"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="page-64.html#h-119"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li>
<li><a href="page-65.html#h-120"><span class="scheduleLabel">SCHEDULE 7</span> </a>
</li>
<li><a href="page-66.html#h-121"><span class="scheduleLabel">SCHEDULE 8</span> </a>
</li>
<li><a href="page-67.html#h-122"><span class="scheduleLabel">SCHEDULE 9</span> </a>
</li>
<li><a href="page-68.html#h-123"><span class="scheduleLabel">SCHEDULE 10</span> </a>
</li>
<li><a href="page-69.html#h-124"><span class="scheduleLabel">SCHEDULE 11</span> </a>
</li></ul>
</li></ul>

</nav>

