<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Yukon Environmental and Socio-economic Assessment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText1">GENERAL</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">YUKON ENVIRONMENTAL AND SOCIO-ECONOMIC ASSESSMENT BOARD AND DESIGNATED OFFICES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText2">Yukon Environmental and Socio-economic Assessment Board</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-6"><span class="HTitleText2">Assessment Districts and Designated Offices</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-7"><span class="HTitleText2">Budgets and Reporting</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-8"><span class="HTitleText2">Rules and By-Laws</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-9"><span class="HTitleText2">General Requirement</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-10"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">ASSESSMENT PROCESS AND DECISION DOCUMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-11"><span class="HTitleText2">Assessments — General</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-12"><span class="HTitleText2">Proposed Activities Subject to Assessment</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-13"><span class="HTitleText2">Proposals for Projects</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-14"><span class="HTitleText2">Evaluation of Projects by Designated Offices</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-15"><span class="HTitleText2">Screening of Projects by Executive Committee</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-16"><span class="HTitleText2">Request for Review</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-17"><span class="HTitleText2">Powers of Minister of Environment</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-18"><span class="HTitleText2">Panels of the Board</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-19"><span class="HTitleText2">Agreements for Joint Panels</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-20"><span class="HTitleText2">Reviews of Projects by Panels</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-21"><span class="HTitleText2">Consideration of Recommendations and Issuance of Decision Documents</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-22"><span class="HTitleText2">Implementation of Decision Documents</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-23"><span class="HTitleText2">Projects on Yukon North Slope</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-24"><span class="HTitleText2">Collaboration and External Activities</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-25"><span class="HTitleText2">Existing Projects</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-26"><span class="HTitleText2">Plans</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-27"><span class="HTitleText2">Audits and Effects Monitoring</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-28"><span class="HTitleText2">Studies and Research</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-29"><span class="HTitleText2">Violation of Decision Document</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-30"><span class="HTitleText2">Court Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-31"><span class="HTitleText2">Maintenance of Records and Public Access</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-32"><span class="HTitleText2">Regulations and Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="#h-33"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">TRANSITIONAL PROVISIONS, CONSEQUENTIAL AND COORDINATING AMENDMENTS AND COMMENCEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124 - </span><a href="#h-34"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-35"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-36"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-37"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-38"><span class="HTitleText3">Yukon First Nations Self-Government Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-39"><span class="HTitleText3">Yukon Surface Rights Board Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>132 - </span><a href="#h-40"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-41"><span class="HTitleText2">Coming Into Force</span></a>
</li></ul>
</li><li><a href="#h-42"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

