<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Financial System Review Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">BANK ACT</cite></span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">COOPERATIVE CREDIT ASSOCIATIONS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">INSURANCE COMPANIES ACT</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-5"><span class="HLabel1">PART 4</span> - <span class="HTitleText1"><cite class="XRefExternalAct">TRUST AND LOAN COMPANIES ACT</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-6"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">AMENDMENTS TO OTHER ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Payments Act</cite></span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Winding-up and Restructuring Act</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Office of the Superintendent of Financial Institutions Act</cite></span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Payment Clearing and Settlement Act</cite></span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Consumer Agency of Canada Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>222 - </span><a href="#h-14"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">COORDINATING AMENDMENTS AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>222 - </span><a href="#h-15"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-16"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

