<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend certain Acts in relation to financial institutions</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">BANK ACT</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-2"><span class="HTitleText1">COOPERATIVE CREDIT ASSOCIATIONS ACT</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-3"><span class="HTitleText1">GREEN SHIELD CANADA ACT</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-4"><span class="HTitleText1">INSURANCE COMPANIES ACT</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="#h-5"><span class="HTitleText1">TRUST AND LOAN COMPANIES ACT</span></a>
</li>
<li><span class='sectionRange'>453 - </span><a href="#h-6"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

