<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the law governing financial institutions and to provide for related and consequential matters</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">BANK ACT</cite></span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-2"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">COOPERATIVE CREDIT ASSOCIATIONS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-3"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">INSURANCE COMPANIES ACT</cite></span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="#h-4"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">TRUST AND LOAN COMPANIES ACT</cite></span></a>
</li>
<li><span class='sectionRange'>386 - </span><a href="#h-5"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">AMENDMENTS TO OTHER ACTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>386 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">An Act to amend certain Acts in relation to financial institutions</cite></span></a>
</li>
<li><span class='sectionRange'>392 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>398 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Bills of Exchange Act</cite></span></a>
</li>
<li><span class='sectionRange'>399 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Business Corporations Act</cite></span></a>
</li>
<li><span class='sectionRange'>402 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>422 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Payments Act</cite></span></a>
</li>
<li><span class='sectionRange'>435 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Consumer Agency of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>438 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Green Shield Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>439 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>440 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">National Housing Act</cite></span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Payment Clearing and Settlement Act</cite></span></a>
</li>
<li><span class='sectionRange'>443 - </span><a href="#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Winding-up and Restructuring Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>450 - </span><a href="#h-18"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">COORDINATING AMENDMENTS AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>450 - </span><a href="#h-19"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="#h-20"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

