<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Criminal Code (conversion therapy)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-2"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

