<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to implement treaties and administrative arrangements on the international transfer of persons found guilty of criminal offences</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">PURPOSE AND PRINCIPLES</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">MINISTER</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">CONSENT</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">CONTINUED ENFORCEMENT AND ADAPTATION</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">PROBATION</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">YOUNG PERSONS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-9"><span class="HTitleText1">SENTENCE CALCULATION</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-10"><span class="HTitleText1">COMPASSIONATE MEASURES</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-11"><span class="HTitleText1">ADMINISTRATIVE ARRANGEMENTS</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-12"><span class="HTitleText1">GENERAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-13"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-14"><span class="HTitleText1">CONSEQUENTIAL AMENDMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-16"><span class="HTitleText1">REFERENCES</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText1">REPEAL</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-19"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

