<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Enhanced New Veterans Charter Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CANADIAN FORCES MEMBERS AND VETERANS RE-ESTABLISHMENT AND COMPENSATION ACT</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-3"><span class="HTitleText1">PENSION ACT</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="page-2.html#h-4"><span class="HTitleText1">REVIEW</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

