<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada–European Union Comprehensive Economic and Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Causes of Action</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Implementation of the Agreement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Approval and Representation on the CETA Joint Committee</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Tribunals, Arbitration Panels and Panels of Experts</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Expenses</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="page-1.html#h-11"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-1.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Export and Import Permits Act</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Food and Drugs Act</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Importation of Intoxicating Liquors Act</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Patent Act</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-7.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Trade-marks Act</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-12.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-13.html#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-13.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Commercial Arbitration Act</cite></span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-13.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Coasting Trade Act</cite></span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-14.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-17.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Pest Control Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-17.html#h-24"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="page-18.html#h-25"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>118 - </span><a href="page-18.html#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Corporations Act</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-18.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Nuclear Energy Act</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-18.html#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-18.html#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-18.html#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Defence Production Act</cite></span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-19.html#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-19.html#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Public Servants Inventions Act</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-19.html#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Olympic and Paralympic Marks Act</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-19.html#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Canada–Korea Economic Growth and Prosperity Act</cite></span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-19.html#h-35"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="page-19.html#h-36"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="page-19.html#h-37"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-20.html#h-38"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-21.html#h-39"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-22.html#h-40"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-23.html#h-41"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-24.html#h-42"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-25.html#h-43"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="page-26.html#h-44"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

