<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Budget Implementation Act, 2001</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AIR TRANSPORT SECURITY</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Canadian Air Transport Security Authority Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Consequential Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-2.html#h-5"><span class="HTitleText3">Financial Administration Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>4 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="page-2.html#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">AIR SECURITY CHARGES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-3.html#h-9"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-3.html#h-10"><span class="HTitleText3">Tax Court of Canada Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-4.html#h-12"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-4.html#h-13"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">EMPLOYMENT INSURANCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-4.html#h-14"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-4.html#h-15"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Employment Insurance (Fishing) Regulations</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="page-4.html#h-18"><span class="HTitleText3">Canada Labour Code</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-4.html#h-20"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">INCOME TAX ACT</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-8.html#h-21"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">CANADA FUND FOR AFRICA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-8.html#h-22"><span class="HTitleText2">Canada Fund for Africa Act</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-9.html#h-23"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-9.html#h-24"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">CANADA STRATEGIC INFRASTRUCTURE FUND</span></a>
</li></ul>
</li></ul>

</nav>

