<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Nááts’ihch’oh National Park Reserve Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CANADA NATIONAL PARKS ACT</cite></span></a>
</li></ul>
</li></ul>

</nav>

