<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Tax Conventions Implementation Act, 2010</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">CANADA–COLOMBIA TAX CONVENTION ACT, 2010</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">CANADA–GREECE TAX CONVENTION ACT, 2010</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">CANADA–TURKEY TAX CONVENTION ACT, 2010</span></a>
</li>
<li><a href="#h-5"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-6"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>

</nav>

