<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Energy Costs Assistance Measures Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">ENERGY COST BENEFIT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText3">Old Age Security Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">REDUCTION OF HOUSING ENERGY CONSUMPTION</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-7"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">PUBLIC TRANSIT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-8"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li></ul>
</li></ul>

</nav>

