<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Protecting Canadians from Unsafe Drugs Act (Vanessa’s Law)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">ALTERNATIVE TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">FOOD AND DRUGS ACT</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-3"><span class="HTitleText1">TRANSITIONAL PROVISION</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-4"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-5"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

