<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to establish the Wage Earner Protection Program Act, to amend the Bankruptcy and Insolvency Act and the Companies’ Creditors Arrangement Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">WAGE EARNER PROTECTION PROGRAM ACT</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">AMENDMENTS TO THE BANKRUPTCY AND INSOLVENCY ACT</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-3"><span class="HTitleText1">AMENDMENTS TO THE COMPANIES’ CREDITORS ARRANGEMENT ACT</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-4"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-5"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-6"><span class="HTitleText2">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-7"><span class="HTitleText2">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-8"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-9"><span class="HTitleText2">Income Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-10"><span class="HTitleText1">COORDINATING AMENDMENT</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-11"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

