<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Federal-Provincial Fiscal Arrangements Act and to enact An Act respecting the provision of funding for diagnostic and medical equipment</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">FEDERAL-PROVINCIAL FISCAL ARRANGEMENTS ACT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25.91 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Communiqués</span></a>
</li></ul>
</li><li><span class='sectionRange'>7 - </span><a href="page-1.html#h-3"><span class="HTitleText1">AN ACT RESPECTING THE PROVISION OF FUNDING FOR DIAGNOSTIC AND MEDICAL EQUIPMENT</span></a>
</li></ul>
</li></ul>

</nav>

