<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Parliament of Canada Act and the Salaries Act and to make consequential amendments to other Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">PARLIAMENT OF CANADA ACT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-2"><span class="HTitleText1">SALARIES ACT</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-3"><span class="HTitleText1">CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Members of Parliament Retiring Allowances Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Referendum Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-2.html#h-6"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-7"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li></ul>
</li></ul>

</nav>

