<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Marine Liability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRETATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">HER MAJESTY</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">PERSONAL INJURIES AND FATALITIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Liability to Dependants</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">APPORTIONMENT OF LIABILITY</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText2">Limitation of Time</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">LIMITATION OF LIABILITY FOR MARITIME CLAIMS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-12"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-13"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText2">Liability of Owners of Docks, Canals and Ports</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-15"><span class="HTitleText2">Amendment of Maximum Liability</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HTitleText2">Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-17"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">LIABILITY FOR CARRIAGE OF PASSENGERS BY WATER</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-18"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-19"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-20"><span class="HTitleText2">Regulations and Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-21"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">LIABILITY FOR CARRIAGE OF GOODS BY WATER</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-22"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-23"><span class="HTitleText2">Hague-Visby Rules</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-24"><span class="HTitleText2">Hamburg Rules</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-25"><span class="HTitleText2">Institution of Proceedings in Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-26"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">LIABILITY AND COMPENSATION FOR POLLUTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-27"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-28"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-29"><span class="HLabel2">Division 1</span> - <span class="HTitleText2">Civil Liability for Pollution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="#h-30"><span class="HTitleText3">Owners of Ships</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-31"><span class="HTitleText3">Special Rules — Convention Ships</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-32"><span class="HTitleText3">Registration of Foreign Judgments</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="#h-33"><span class="HLabel2">Division 2</span> - <span class="HTitleText2">Compensation for Pollution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-34"><span class="HTitleText3">International Oil Pollution Compensation Fund</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-35"><span class="HTitleText3">Ship-source Oil Pollution Fund</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-36"><span class="HTitleText3">Administrator and Deputy Administrator</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-37"><span class="HTitleText3">Liability of Ship-source Oil Pollution Fund</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-38"><span class="HTitleText3">Claims Arising under Section 51</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-39"><span class="HTitleText3">Claims for Loss of Income</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-40"><span class="HTitleText3">Proceedings against Shipowner</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-41"><span class="HTitleText3">Limit of Liability of Ship-source Oil Pollution Fund</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-42"><span class="HTitleText3">Application to Court for Directions</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-43"><span class="HTitleText3">Payments into the Ship-source Oil Pollution Fund</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-44"><span class="HTitleText3">Annual Report</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-45"><span class="HTitleText3">Interest on Claims</span></a>
</li></ul>
</li><li><span class='sectionRange'>102 - </span><a href="#h-46"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-47"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>106 - </span><a href="#h-48"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">VALIDATION OF CERTAIN BY-LAWS AND REGULATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>106 - </span><a href="#h-49"><span class="HTitleText2">By-laws under the Canada Ports Corporation Act</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-50"><span class="HTitleText2">Regulations under the <cite class="XRefExternalAct">Pilotage Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="#h-51"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">TRANSITIONAL, CONSEQUENTIAL AMENDMENTS, CONDITIONAL AMENDMENT, REPEAL AND COMING INTO FORCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="#h-52"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-53"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>109 - </span><a href="#h-54"><span class="HTitleText3">Arctic Waters Pollution Prevention Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-55"><span class="HTitleText3">Canada-Newfoundland Atlantic Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-56"><span class="HTitleText3">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-57"><span class="HTitleText3">Canadian Environmental Protection Act, 1999</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-58"><span class="HTitleText3">Crown Liability and Proceedings Act</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-59"><span class="HTitleText3">Federal Court Act</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-60"><span class="HTitleText3">Merchant Seamen Compensation Act</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-61"><span class="HTitleText3">Canada Oil and Gas Operations Act</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-62"><span class="HTitleText3">Canada Shipping Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="#h-63"><span class="HTitleText2">Conditional Amendment</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-64"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-65"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-66"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-67"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-68"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - HAGUE-VISBY RULES</span></a>
</li>
<li><a href="#h-69"><span class="scheduleLabel">SCHEDULE 4</span> <span class="scheduleTitleText"> - HAMBURG RULES</span></a>
</li></ul>
</li></ul>

</nav>

