<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
<?Pub Caret?>Expansion and Conservation of Canada’s National Parks Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">SABLE ISLAND NATIONAL PARK RESERVE OF CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Canada National Parks Act</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Consequential Amendments to the <cite class="XRefExternalAct">Canada Shipping Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="page-1.html#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">OTHER AMENDMENTS TO THE <cite class="XRefExternalAct">CANADA NATIONAL PARKS ACT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Amendments</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

