<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Courts Administration Service Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">PURPOSES OF ACT</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">COURTS ADMINISTRATION SERVICE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">CHIEF ADMINISTRATOR</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">POWERS, DUTIES AND FUNCTIONS OF CHIEF ADMINISTRATOR</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText1">CHIEF JUSTICES</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">STAFF OF THE SERVICE</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText1">CONTRACTING FOR SERVICES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText1">REPORT TO PARLIAMENT</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText1">AMENDMENTS TO THE FEDERAL COURT ACT</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-11"><span class="HTitleText1">AMENDMENTS TO THE TAX COURT OF CANADA ACT</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-12"><span class="HTitleText1">AMENDMENTS TO THE JUDGES ACT</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-13"><span class="HTitleText1">RELATED AND CONSEQUENTIAL AMENDMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-14"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-15"><span class="HTitleText2">Anti-Personnel Mines Convention Implementation Act</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-16"><span class="HTitleText2">Army Benevolent Fund Act</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-17"><span class="HTitleText2">Canada Elections Act</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-18"><span class="HTitleText2">Canada Evidence Act</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-19"><span class="HTitleText2">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-20"><span class="HTitleText2">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-21"><span class="HTitleText2">Canada Transportation Act</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-22"><span class="HTitleText2">Canadian Ownership and Control Determination Act</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-23"><span class="HTitleText2">Civil International Space Station Agreement Implementation Act</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-24"><span class="HTitleText2">Commercial Arbitration Act</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-25"><span class="HTitleText2">Competition Act</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-26"><span class="HTitleText2">Competition Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-27"><span class="HTitleText2">Copyright Act</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-28"><span class="HTitleText2">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-29"><span class="HTitleText2">Cree-Naskapi (of Quebec) Act</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-30"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-31"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-32"><span class="HTitleText2">Energy Supplies Emergency Act</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-33"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-34"><span class="HTitleText2">Extradition Act</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-35"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-36"><span class="HTitleText2">Immigration Act</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-37"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-38"><span class="HTitleText2">International Sale of Goods Contracts Convention Act</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-39"><span class="HTitleText2">Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-40"><span class="HTitleText2">Investment Canada Act</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-41"><span class="HTitleText2">National Defence Act</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-42"><span class="HTitleText2">Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-43"><span class="HTitleText2">Plant Breeders’ Rights Act</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-44"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-45"><span class="HTitleText2">Proceeds of Crime (Money Laundering) Act</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-46"><span class="HTitleText2">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-47"><span class="HTitleText2">Public Service Employment Act</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-48"><span class="HTitleText2">Public Service Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-49"><span class="HTitleText2">Railway Safety Act</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-50"><span class="HTitleText2">Special Import Measures Act</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-51"><span class="HTitleText2">Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-52"><span class="HTitleText2">Supreme Court Act</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-53"><span class="HTitleText2">Trade-marks Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-54"><span class="HTitleText2">United Nations Foreign Arbitral Awards Convention Act</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-55"><span class="HTitleText2">Veterans Review and Appeal Board Act</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-56"><span class="HTitleText2">Yukon First Nations Self-Government Act</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-57"><span class="HTitleText2">Yukon Surface Rights Board Act</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-58"><span class="HTitleText2">References</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-59"><span class="HTitleText1">TRANSITIONAL PROVISIONS</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-60"><span class="HTitleText1">COORDINATING AMENDMENTS</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-61"><span class="HTitleText1">COMING INTO FORCE</span></a>
</li>
<li><a href="#h-62"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

