<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Economic Action Plan 2015 Act, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">SHORT TITLE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">AMENDMENTS TO THE <cite class="XRefExternalAct">INCOME TAX ACT</cite> AND TO RELATED LEGISLATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-4"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-4.html#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Canada Pension Plan Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-5.html#h-6"><span class="HTitleText2"><cite class="XRefExternalRegulation">Insurable Earnings and Collection of Premiums Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="page-5.html#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">SUPPORT FOR FAMILIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="page-5.html#h-8"><span class="HLabel2">Division 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-6.html#h-9"><span class="HLabel2">Division 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Universal Child Care Benefit Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="page-6.html#h-10"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-6.html#h-11"><span class="HTitleText3">Related Amendments to the <cite class="XRefExternalAct">Children’s Special Allowances Act</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-6.html#h-12"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-6.html#h-13"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">VARIOUS MEASURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-6.html#h-14"><span class="HLabel2">Division 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Federal Balanced Budget Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-6.html#h-15"><span class="HTitleText3">Enactment of Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="page-7.html#h-16"><span class="HLabel2">Division 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Prevention of Terrorist Travel Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-7.html#h-17"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-7.html#h-18"><span class="HTitleText3">Related Amendment to the <cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="page-7.html#h-19"><span class="HLabel2">Division 3</span> - <span class="HTitleText2">Intellectual Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-7.html#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Industrial Design Act</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-8.html#h-21"><span class="HTitleText3"><cite class="XRefExternalAct">Patent Act</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-9.html#h-22"><span class="HTitleText3"><cite class="XRefExternalAct">Trade-marks Act</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-9.html#h-23"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-10.html#h-24"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="page-10.html#h-25"><span class="HLabel2">Division 4</span> - <span class="HTitleText2">Compassionate Care Leave and Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="page-10.html#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-10.html#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-10.html#h-28"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-10.html#h-29"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>81 - </span><a href="page-11.html#h-30"><span class="HLabel2">Division 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Copyright Act</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-11.html#h-31"><span class="HLabel2">Division 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Export Development Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83 - </span><a href="page-11.html#h-32"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-11.html#h-33"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="page-11.html#h-34"><span class="HLabel2">Division 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-11.html#h-35"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-12.html#h-36"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="page-12.html#h-37"><span class="HLabel2">Division 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Members of Parliament Retiring Allowances Act</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-12.html#h-38"><span class="HLabel2">Division 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">National Energy Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-12.html#h-39"><span class="HLabel2">Division 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-12.html#h-40"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-12.html#h-41"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-14.html#h-42"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="page-14.html#h-43"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Post Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-14.html#h-44"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-14.html#h-45"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-14.html#h-46"><span class="HTitleText4"><cite class="XRefExternalAct">Garnishment, Attachment and Pension Diversion Act</cite></span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-15.html#h-47"><span class="HTitleText4"><cite class="XRefExternalAct">Government Employees Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-15.html#h-48"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-15.html#h-49"><span class="HTitleText4"><cite class="XRefExternalAct">Radiocommunication Act</cite></span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-15.html#h-50"><span class="HTitleText4"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-16.html#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Non-smokers’ Health Act</cite></span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="page-16.html#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Official Languages Act</cite></span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-16.html#h-53"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-16.html#h-54"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-16.html#h-55"><span class="HTitleText4"><cite class="XRefExternalAct">Expenditure Restraint Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="page-16.html#h-56"><span class="HLabel2">Division 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="page-16.html#h-57"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-16.html#h-58"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-16.html#h-59"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="page-16.html#h-60"><span class="HTitleText4"><cite class="XRefExternalAct">Modernization of Benefits and Obligations Act</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-16.html#h-61"><span class="HTitleText4"><cite class="XRefExternalAct">Budget Implementation Act, 2000</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>161 - </span><a href="page-16.html#h-62"><span class="HLabel2">Division 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Small Business Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-17.html#h-63"><span class="HLabel2">Division 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Personal Information Protection and Electronic Documents Act</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-17.html#h-64"><span class="HLabel2">Division 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-17.html#h-65"><span class="HLabel2">Division 15</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="page-17.html#h-66"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-18.html#h-67"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>177 - </span><a href="page-18.html#h-68"><span class="HLabel2">Division 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">First Nations Fiscal Management Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="page-18.html#h-69"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="page-20.html#h-70"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="page-20.html#h-71"><span class="HLabel2">Division 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Forces Members and Veterans Re-establishment and Compensation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="page-20.html#h-72"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="page-22.html#h-73"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">Veterans Review and Appeal Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-22.html#h-74"><span class="HTitleText3">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="page-22.html#h-75"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>230 - </span><a href="page-22.html#h-76"><span class="HLabel2">Division 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Ending the Long-gun Registry Act</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="page-22.html#h-77"><span class="HLabel2">Division 19</span> - <span class="HTitleText2">Privilege for Supervisory Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>232 - </span><a href="page-22.html#h-78"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-23.html#h-79"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="page-23.html#h-80"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="page-24.html#h-81"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="page-24.html#h-82"><span class="HTitleText3">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>253 - </span><a href="page-24.html#h-83"><span class="HLabel2">Division 20</span> - <span class="HTitleText2">Sick Leave and Disability Programs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>253 - </span><a href="page-24.html#h-84"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="page-25.html#h-85"><span class="HTitleText3">Sick Leave</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="page-25.html#h-86"><span class="HTitleText3">Short-term Disability Program</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="page-25.html#h-87"><span class="HTitleText3">Long-term Disability Programs</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="page-26.html#h-88"><span class="HTitleText3">General</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-27.html#h-89"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-28.html#h-90"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

